PingCAP-QE/ci

- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
upgrade go version to go1.20.1
> chore(pingcap/tidb-test): upgrade to go1.20

- pipelines/pingcap/tidb/latest/ghpr_build.groovy
> feat(pipelines/pingcap/tidb/latest): add plugin test step for build job

- jenkins/jobs/ci/tidb-test/ghpr_build.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
disbe tidb-test build on jenkins
> chore: disable trigger on master

- pipelines/pingcap/tidb/latest/ghpr_build.groovy
> Revert "feat(pipelines/pingcap/tidb/latest): add plugin test step for build job"

- jobs/pingcap/tidb-test/release-6.2/ghpr_build.groovy
> fix: correct scripts path

- pipelines/pingcap/tidb-test/latest/pod-ghpr_build.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_jdbc_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_mysql_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_mysql_test.yaml
upgrade go version on master to 1.20
> chore(pingcap/tidb-test): upgrade go version to 1.20

- jenkins/pipelines/cd/multibranch/build_binlog_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_br_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_dm_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_dumpling_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_enterprise_tools_master.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tikv_multi_branch.groovy
For all golang project's multi-branch pipelines, need support go1.20.
Tested: https://cd.pingcap.net/view/Dev-build-master/job/build_pd_multi_branch/job/master/765/console
> chore(build): multi branch pipeline upgrade goversion

- jenkins/pipelines/cd/dev-build.groovy
Why:
- sometimes we need failpoint
How:
- add a features fields, it can contains failpoint option
> feat: support failpoint in devbuild

- jobs/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
* Test all groups
* shallow clone ci.git with depth 1
> fix: fix cdc kafka ci on staging

- jobs/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
> fix: correct cdc jobdsl

- libraries/tipipeline/vars/component.groovy
- scripts/ops/get-artifacts-of-pull-request.sh
- `comonent.checkout`
- `comonent.fetchAndExtractArtifact`
> also make the checkout timeout as optional param.
> refactor(libraries/tipipeline): refactor global component functions to support hotfix pull requests

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
> feat: use binPath env rather than bash

- jenkins/Dockerfile/release/linux-arm64/br
- jenkins/Dockerfile/release/linux-arm64/dumpling
- jenkins/Dockerfile/release/linux-arm64/enterprise/tidb
- jenkins/Dockerfile/release/linux-arm64/ng-monitoring
- jenkins/Dockerfile/release/linux-arm64/tidb
- jenkins/Dockerfile/release/linux-arm64/tidb-backup-manager
- jenkins/Dockerfile/release/linux-arm64/tidb-lightning
- jenkins/Dockerfile/release/linux-arm64/tidb-monitor-reloader
- jenkins/Dockerfile/release/linux-arm64/tidb-tools
- jenkins/Dockerfile/release/linux-arm64/tikv
pingcap/centos-stream:8 is just centos:8 updated some packages
> fix(security): use fix centos to repleace centos:8

- jobs/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/latest/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/latest/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
* Add dm compatibility test to test on staging
* Fix wait for mysql ready script
> feat: test pull-dm-compatibility test on staging

- jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
dm integration test ci support hotfix branch: download the tikv/pd of the corresponding release-x.x branch
> fix(pingcap/tiflow): support hotfix branch

- jobs/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
- jobs/pingcap/tidb-test/latest/prow-presubmits.yaml
- pipelines/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_common_test.yaml
* Add integration common test on tidb-test.
* Skip report currentlly
> feat: add it common test to test

- scripts/plugins/analyze-go-test-from-bazel-output.sh
> fix(scripts/plugins): fix regex with posix

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
> feat(pipelines/pingcap/tidb/latest): analyze bazel output when failed

- jobs/pingcap/tidb-test/latest/prow-presubmits.yaml
- pipelines/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
* Correct s3 cache path 
* Enable report fot integration-common-test
> fix(pingcap/tidb-test): tidb test add common ci fix

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
Enable WITH_RACE when build pd failpont binary.
> feat: enable WITH_RACE when build pd failpoint

- scripts/plugins/report-flaky-cases.ts
> feat(scripts/plugins): add report flaky test tool

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
Update golang minor version
* go1.20: from 1.20.1 to 1.20.2
* go1.19: from 1.19.5 to 1.19.7
> feat(build): update go1.20 and go1.19 minor version

- pipelines/pingcap/tidb/latest/ghpr_build.groovy
> chore(pippeliens/pingcap/tidb/latest): temp increase timeout to 1 hour for tidb build

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
- scripts/ops/get-topn-longest-cases.ts
- scripts/plugins/analyze-go-test-from-bazel-output.sh
Report unstable cases which are parsed from bazel test result.
> feat(pipelines/pingcap/tidb/latest): add report for flaky tests

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
Adjust pd download url to fix download error
> fix(pingcap/br): adjust pd download url

- pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
> fix: remove useless env

- jenkins/pipelines/ci/tidb/tidb_integration_test_ci_shadow_debug.groovy
> chore: shadow debug not notify

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
br integration test pipeline support go1.20
> fxi: fix br make build error

- jobs/pingcap/tidb/release-7.0/aa_folder.groovy
- jobs/pingcap/tidb/release-7.0/ghpr_build.groovy
- jobs/pingcap/tidb/release-7.0/ghpr_check.groovy
- jobs/pingcap/tidb/release-7.0/ghpr_check2.groovy
- jobs/pingcap/tidb/release-7.0/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-7.0/prow-presubmits.yaml
- pipelines/pingcap/tidb/release-7.0/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_check.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.0/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.0/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-7.0/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-7.0/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-7.0/pod-ghpr_unit_test.yaml
Splite pipelines for new branch release-7.0
> feat(pingcap/tidb): splite pipelines for new branch release-7.0

- jenkins/jobs/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
- jenkins/jobs/ci/tidb/ghpr_build.groovy
- jenkins/jobs/ci/tidb/ghpr_check.groovy
- jenkins/jobs/ci/tidb/ghpr_check2.groovy
- jenkins/jobs/ci/tidb/ghpr_mysql_test.groovy
- jenkins/jobs/ci/tidb/ghpr_unit_test.groovy
- jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
disable trigger on release-7.x for old pipelines
> fix: disable trigger on release-7.x for old pipelines

- jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
> fix(jobdsl): correct trigger phrase

- jobs/pingcap/tidb/release-6.5/README.md
> docs(jobs/pingcap/tidb/release-6.5): update env for ut

- README.md
- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
- scripts/plugins/report-flaky-cases.ts
- enable report in release-6.5 branch
- fix report time col NULL problem.
> fix(scrpts/plugins): fix report-flaky-cases about report time

- jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
- jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
- jenkins/pipelines/ci/tidb/goversion-select-lib.groovy
- jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_readonly_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
- jenkins/pipelines/ci/tikv/pd/pd_ghpr_build.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
- jenkins/pipelines/goversion-select-lib.groovy
> chore: adjust some go version lib

- jenkins/jobs/ci/tikv/tikv/ghpr_build.groovy
- jenkins/jobs/ci/tikv/tikv/ghpr_build_release.groovy
Adjuest build & build-release trigger regex.
> fix(tikv/tikv): correct build-release trigger

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
> fix(build-comom): support go1.20

- jobs/tikv/pd/latest/prow-presubmits.yaml
- jobs/tikv/pd/latest/pull_integration_copr_test.groovy
- pipelines/tikv/pd/latest/pod-pull_integration_copr_test.yaml
- pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
Add integration-copr-test to pd
> feat(tikv/pd): add integration-copr-test to pd

- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
> fix: correct missing env

- jenkins/pipelines/qa_release_test.groovy
upload binary.tar.gz to be compatible with integration testing.
> chore(qa-release-test): upload binary.tar.gz to be compatible with integration testing

- jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_br_test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_cdc_test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
maintain compatibility issues with old pipelines
> fix(tikv): maintain compatibility issues with old pipelines

- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
> fix: remove duplicate

- jenkins/pipelines/qa_release_test.groovy
> fix(qa-release-test): correct third bin path

- pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
> fix: correct dm it cache bin

- jobs/tikv/pd/latest/prow-presubmits.yaml
> fix: correct job name

- jenkins/pipelines/qa_release_test.groovy
upload tikv-server binary for compatibility integration Test
> fix(qa-release-test): upload tikv-server binary for compatibility integration Test

- pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
- scripts/artifacts/download_pingcap_artifact.sh
> fix: add download artifact script

- pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
- scripts/artifacts/download_pingcap_artifact.sh
- scripts/pingcap/tidb-test/download_pingcap_artifact.sh
fix pr copr-test not found script.
> fix: to fix pr copr-test not found script

- pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
Adjust timeout from 10min to 20min
> chore: increase cdc it build timeout

- jobs/pingcap/tiflow/latest/prow-presubmits.yaml
- jobs/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
- jobs/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/latest/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/latest/pull_engine_integration_test.groovy
tiflow ci refactor to prow style
> feat: tiflow ci refactor to prow style

- jobs/pingcap/tiflow/latest/prow-presubmits.yaml
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
refactor tiflow ci to prow style
> feat: refactor tiflow ci to prow style

- jobs/tikv/pd/latest/README.md
- jobs/tikv/pd/latest/prow-presubmits.yaml
Enable ci report on pd copr-test.
> chore(tikv/pd): enable ci report on pd copr-test

- jenkins/pipelines/ci/tiflash-scripts/tiflash_scripts_ghpr_build.groovy
- jenkins/pipelines/ci/tiflash-scripts/tiflash_scripts_ghpr_test.groovy
- jenkins/pipelines/ci/tiflash/tiflash_regression_test_daily.groovy
- jenkins/pipelines/ci/tiflash/tiflash_schrodinger_test.groovy
Adjust org for tiflash_scripts repo.
> feat: adjust org for tiflash_scripts repo

- scripts/plugins/report-flaky-cases.ts
> fix(scripts/plugins): fix parallel sql inserting issue

- jenkins/jobs/ci/tidb/ghpr_integration_br_test.groovy
* Add trigger for releease-6.1 
* Add trigger for release-7.x
> feat: add trigger for release-6.1

- pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
> chore: add some skip stage

- jobs/pingcap/tiflow/latest/prow-presubmits.yaml
support comment `/test all` to trigger all integration test jobs.
> feat(tiflow): /test all to trigger all

- jobs/pingcap/tiflow/latest/ghpr_verify.groovy
- jobs/pingcap/tiflow/latest/prow-presubmits.yaml
- jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-5.3/prow-presubmits.yaml
- jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-6.0/prow-presubmits.yaml
- jobs/pingcap/tiflow/release-6.1/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-6.1/prow-presubmits.yaml
- jobs/pingcap/tiflow/release-6.2/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-6.2/prow-presubmits.yaml
- pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-6.2/ghpr_verify.groovy
Refactor tiflow verify pipeline to prow style.
> feat(tiflow): tiflow verify pipeline refactor to  prow style

- jobs/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb-test/release-6.0/ghpr_integration_mysql_test.groovy
- pipelines/pingcap/tidb-test/release-6.0/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb-test/release-6.1/ghpr_integration_mysql_test.groovy
- pipelines/pingcap/tidb-test/release-6.1/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb-test/release-6.2/ghpr_integration_mysql_test.groovy
- pipelines/pingcap/tidb-test/release-6.2/ghpr_mysql_test.groovy
fix https://github.com/PingCAP-QE/ci/issues/1951.
> fix(tidb-test): fix timeout options exception

- pipelines/pingcap/tidb/latest/ghpr_check2.groovy
makefile target add in https://github.com/pingcap/tidb/pull/42762/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
> add bazel_loaddatatest for tidb test

- jobs/tikv/pd/latest/README.md
- jobs/tikv/pd/release-6.5/README.md
> docs(jobs/tikv/pd): add job documents for relase-6.5 and master branches

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
* go1.19 update to 1.19.8
* go1.20 update to 1.20.3
> feat: update go version to 1.20.3

- pipelines/pingcap/tiflow/latest/pod-pull_engine_integration_test.yaml
update docker container image.
> fix(tiflow/engine): update docker container image

- pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
remove dockerignore file for ticdc.
> fix(tiflow/engine): remove dockerignore file for ticdc

- README.md
- gitee/OWNERS
- gitee/jobs/pingcap_enterprise/aa_folder.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/aa_folder.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/aa_folder.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/aa_folder.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/aa_folder.groovy
> feat(jobs/pingcap_enterprise): init folders for repos

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pod-pr-verify.yaml
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
> feat(gitee/jobs):  add jobs for tidb-enterprise-manager

- jenkins/pipelines/cd/tiproxy-docker.groovy
1. default branch name is main
2. use make docker
> tiproxy: fix build

- libraries/tipipeline/vars/prow.groovy
> Revert "refactor(libraries/tipipeline/vars): refactor prow.checkoutRefs"

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pod-pr-verify.yaml
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- using nodejs v14.
- archive the build dist tarball.
> ref #1968 
> feat(jobs/pingcap_enterprise/tidb-enterprise-manager-ui): init jobs for nodejs project

- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pod-pr-verify.yaml
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pod-pr-verify.yaml
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
- libraries/tipipeline/vars/prow.groovy
> feat(jobs/pingcap_enterprise): init jobs for `tidb-enterprise-utilities` and `tidb-security-advanced`

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
> fix(gitee/jobs/pingcap_enterprise):  fix job triggers

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
> fix(gitee/jobs/pingcap_enterprise):  fix job triggers regexp

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
> fix(gitee/jobs/pingcap_enterprise):  fix job triggers for pr updating

- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
- libraries/tipipeline/vars/prow.groovy
- refactor `prow.checkoutPrivateRefs` to support other git hosts.
- refactor checkout steps with `prow.checkoutPrivateRefs` function.
> fix(gitee/pipelines/pingcap_enterprise):  fix checkouts

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pod-pr-verify.yaml
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pod-pr-verify.yaml
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pod-pr-verify.yaml
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
- libraries/tipipeline/vars/gitee.groovy
> fix(gitee/pipelines/pingcap_enterprise):  update images

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
> fix(gitee/jobs/pingcap_enterprise):  fix trigger webhook secrets

- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
> fix(gitee/pipelines/pingcap_enterprise):  add comment status in pr

- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
> Revert "fix(gitee/pipelines/pingcap_enterprise):  add comment status in pr"

- jobs/pingcap/tiflow/latest/prow-presubmits.yaml
Update the tiflow master CI status to match the triggered command.
> feat(tiflow): update tiflow ci status

- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager-ui/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-manager/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- gitee/pipelines/pingcap_enterprise/tidb-security-advanced/pr-verify.groovy
> feat(gitee/pipelines/pingcap_enterprise):  add notify when started.

- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
- libraries/tipipeline/vars/git.groovy
> fix(gitee/pipelines/pingcap_enterprise):  add debug steps for checkout ssh

- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager-ui/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-manager/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-enterprise-utilities/pr_verify.groovy
- gitee/jobs/pingcap_enterprise/tidb-security-advanced/pr_verify.groovy
> fix(gitee/jobs/pingcap_enterprise):  delete useless job params

- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
> feat(gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities): add mysql tests

- jobs/tikv/tikv/release-6.5/README.md
> docs(jobs/tikv/tikv/release-6.5): add doc for unit test job

- gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities/pr-verify.groovy
> fix(gitee/pipelines/pingcap_enterprise/tidb-enterprise-utilities): fix mysql tests

- pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
- cpu from 4 to 16
- memory from 8 to 32 GiB
> feat(pipelines/pingcap/tidb): increase `resources.requests`

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
* tikv cache image add release-7.1
* remove build image for dmr version
> feat: tikv cache image add release-7.1

- jobs/pingcap/tiflow/release-7.1/README.md
- jobs/pingcap/tiflow/release-7.1/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-7.1/prow-presubmits.yaml
- jobs/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
- jobs/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.1/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.1/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-7.1/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-7.1/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-7.1/pod-pull_cdc_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.1/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-7.1/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.1/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
* Add tiflow dsl jobs for release-7.1
* Add tiflow pipelines for release-7.1
> feat: tiflow split release 7.1 jobs

- jobs/pingcap/tidb/release-7.1/aa_folder.groovy
- jobs/pingcap/tidb/release-7.1/ghpr_build.groovy
- jobs/pingcap/tidb/release-7.1/ghpr_check.groovy
- jobs/pingcap/tidb/release-7.1/ghpr_check2.groovy
- jobs/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-7.1/prow-presubmits.yaml
- pipelines/pingcap/tidb/release-7.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_check.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_unit_test.yaml
* Add tidb release-7.1 jobs.
* Add tidb release-7.1 pipelines.
> feat:  tidb split release-7.1 jobs

- jobs/pingcap/tiflow/release-7.1/aa_folder.groovy
add tiflow relase-7.1 job folder
> fix: add tiflow relase-7.1 job folder

- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
> chore: build release 7.1 nightly

- jobs/pingcap/tiflow/latest/prow-presubmits.yaml
- jobs/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
tiflow add cdc storage sink job
> feat: tiflow add cdc storage sink job

- jobs/pingcap/tidb/latest/prow-presubmits.yaml
master jobs not response to release-7.x
> fix(tidb): master jobs not response to release-7.x

- jenkins/pipelines/cd/tidb-operator.groovy
ref: https://github.com/pingcap/tidb-operator/issues/4984
> cd: fix tidb-operator helm chart repo schema

- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
some build failed but we can't see any error message
> fix: will print exception

- scripts/plugins/security-scan.ts
> feat(scripts/plugins): add security scan script

- scripts/plugins/security-scan-prow.ts
> feat(scripts/plugins): add security scan script to connect with prow jobs

- jobs/tikv/tikv/release-6.5/README.md
> docs(jobs/tikv/tikv/release-6.5): add unit test doc for current using container info

- prow-jobs/pingcap-tiflow-latest-presubmits.yaml
Enable cdc integration storage test on master branch.
> feat(tiflow): enable cdc integration storage test

- pipelines/pingcap/tidb-engine-ext/latest/ghpr_unit_test.groovy
fix git status due to .git on parent dir
> fix(tidb-engine-ext): fix git status due to .git on parent dir

- jobs/pingcap/tidb/latest/canary_scan_security.groovy
- pipelines/pingcap/tidb/latest/canary-scan-security.groovy
- pipelines/pingcap/tidb/latest/pod-canary-scan-security.yaml
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
- scripts/plugins/security-scan-prow.ts
- scripts/plugins/security-scan.ts
- Adjust deno scripts with new backend implements.
- add canary type job, it will triggered by comments
> feat(jobs/pingcap/tidb/latest): add canary job for security scan

- pipelines/pingcap/tidb/latest/pod-canary-scan-security.yaml
> fix(jobs/pingcap/tidb/latest): fix image for security scan job

- pipelines/pingcap/tidb/latest/pod-canary-scan-security.yaml
> fix(jobs/pingcap/tidb/latest): increase pod resources for security scan job

- pipelines/pingcap/tidb/latest/canary-scan-security.groovy
> fix(jobs/pingcap/tidb/latest): fix security scan pipeline

- pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
correct checkout  branch error
> fix(tiflow): correct checkout  branch error

- pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
> fix(tiflow): use correct image tag 

- jobs/pingcap-inc/aa_folder.groovy
- jobs/pingcap-inc/exterprise-extension/aa_folder.groovy
- jobs/pingcap-inc/exterprise-extension/latest/pr_verify.groovy
- pipelines/pingcap-inc/exterprise-extension/latest/pod-pr-verify.yaml
- pipelines/pingcap-inc/exterprise-extension/latest/pr-verify.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-inc-exterprise-extension-presubmits.yaml
> feat(jobs/pingcap-inc/enterprise-extension): add plugin job

- pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
> fix(pipelines/pingcap-inc/enterprise-extensions): fix unit test steps

- pipelines/pingcap/tidb/latest/canary-scan-security.groovy
- scripts/plugins/security-scan-prow.ts
- scripts/plugins/security-scan.ts
> fix(scripts/plugins): save report with decode content

- scripts/plugins/security-scan-prow.ts
- scripts/plugins/security-scan.ts
make changes to files: `security-scan*.ts`.
> fix(scripts/plugins): save html report with decode content

- pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
changes made to branches:
- master
- release-7.1
> feat(pipelines/pingcap/tidb): increase memory limit to 32GiB for build jobs

- jenkins/pipelines/ci/ticdc/cdc_ghpr_downstream_coverage.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/engine_ghpr_integration_test.groovy
> chore(tilflow): use another cluster to run pipeline

- libraries/tipipeline/vars/prow.groovy
- pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
- pipelines/pingcap/tidb/latest/ghpr_build.groovy
- pipelines/pingcap/tidb/latest/ghpr_check.groovy
- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Changes:
- support update submodule for global prow checkout functions.
- refactor build steps for extension.
- fetch submodule to make test include the extension pkgs.
/hold
Depend on pingcap/tidb#43681
> refactor(pipelines/pingcap/tidb): refactor build and UT pipelines to include new extensions

- jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
update golang image to use tini
> chore(tiflow): update golang image to use tini

- pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
tmp fix cache contains untraced submodule files
> fix: tmp fix cache contains untraced files

- libraries/tipipeline/vars/prow.groovy
> fix(libraries/tipipeline/vars): clean untracked submodule's dirs

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_downstream_coverage.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/engine_ghpr_integration_test.groovy
* Increase cpu request to avoid 5000ms timeout error
* temp adjust use cluster kubernetes-ng
* use tini image in dm ci pipelines
> fix: fix ticdc pod 5000 timeout

- pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
- pipelines/pingcap/tidb/latest/pull_integration_mysql_test.groovy
Correct to use matrix env TEST_PART
> fix: fix env part

- jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
Remove extra character "/" from the URL
ci link https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/34628/pipeline/
> fix(download): fix download file from fileserver

- jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Adjust timeout period to avoid timing out when downloading large files.
> fix(tiflow): fix wget timeout

- jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
> fix(tikv): remove '/' from download url

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
1. Logic rewrite for downloading third-party products.
2. cached builds from `make build_for_integration_test`
test pass https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/15877/pipeline/109/
> fix: tidb br it refactor

- jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
Why:
new fileserver do not return status field
> fix: adapt new fileserver

- jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
- jenkins/pipelines/ci/ticdc/integration_test_common.groovy
Reduce the download pressure on the fileserver
> fix: ticdc it fileserver download adjust

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_downstream_coverage.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/engine_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/integration_test_common.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
use high performance disk to run tests
* br tests
* cdc tests
* dm tests
* tikv ut
Test pipeline
1. cdc https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/19822/pipeline/146/
2. cdc  https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/18951/pipeline/151/
3. br  https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/15881/pipeline
4. tikv ut   https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/34708/pipeline/51/
> feat: use high performance disk to run some heavy tests

- jenkins/pipelines/cd/multibranch/build_tidb_enterprise_tools_master.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
- jenkins/pipelines/cd/release-GA-v5-extra-packages.groovy
- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0-hotfix.groovy
- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-atom.groovy
- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy
adjust fileserver upload success check
> chore: adjust fileserver upload success check

- jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
revert nfs change conf on tiflash-build-common
> fix: revert nfs conf

- jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
> Revert "fix: revert nfs conf"

- pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.1/ghpr_verify.groovy
> Revert "fix(tiflow): fix ut get wrong repo dir"

- prow-jobs/kustomization.yaml
Update kustomization.yaml: add tiflow release-6.5
> fix: Update kustomization.yaml

- pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_kafka_test.yaml
* update image, add tini as pid 1, add openjdk
> chore(tiflow): update go image with tini & java

- pipelines/pingcap/tiflow/release-6.1/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-6.1/pull_dm_compatibility_test.groovy
- scripts/pingcap/tiflow/release-6.1/dm_download_integration_test_binaries.sh
- scripts/pingcap/tiflow/release-6.1/dm_run_group.sh
*  remove some cases
*  let container hostname shorter (< 60)
> fix(tiflow/dm): remove some cases

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/merged_unit_test.groovy
- pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.6/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
> feat(pipelines/pingcap/tidb): update codecov uploader and add flags option

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-community-postsubmits.yaml
- scripts/pingcap/community/update-prow-owners.ts
> feat(scripts/pingcap/community): add script `update-prow-oweners.ts`

- jobs/pingcap/tidb/latest/canary_ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/canary-ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
> chore(pingcap/tidb): add a new ut canary job

- jobs/pingcap/tidb-test/latest/ghpr_common_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_common_test.groovy
- pipelines/pingcap/tidb-test/latest/pod-ghpr_common_test.yaml
- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
> feat(tidb-test): tidb test add pipeline common test

- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
> chore(pingcap/tidb): update a new ut canary job pod yaml

- pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
disable failfast on release-6.1 it pipelines.
> debug(tiflow): temp disable failfast

- scripts/pingcap/tiflow/release-6.1/dm_run_group.sh
> fix(tiflow): adjust dm test case order

- pipelines/OWNERS
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
> refactor(pipelines/pingcap/tiflow): fix cache key for binary

- pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
- scripts/pingcap/tiflow/release-6.1/dm_run_group.sh
set path to use correct gh-ost version
> fix(tiflow): set path to use correct gh-ost version

- jobs/pingcap/tiflow/release-5.4/aa_folder.groovy
- jobs/pingcap/tiflow/release-5.4/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-5.4/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-5.4/pull_cdc_integration_test.groovy
- jobs/pingcap/tiflow/release-5.4/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-5.4/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-5.4/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-5.4/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-5.4/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-5.4/pod-pull_cdc_integration_test.yaml
- pipelines/pingcap/tiflow/release-5.4/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-5.4/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-5.4/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-5.4/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-5.4/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-5.4/pull_dm_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
- scripts/pingcap/tiflow/release-5.4/cdc_run_group.sh
- scripts/pingcap/tiflow/release-5.4/dm_download_compatibility_test_binaries.sh
- scripts/pingcap/tiflow/release-5.4/dm_download_integration_test_binaries.sh
- scripts/pingcap/tiflow/release-5.4/dm_run_group.sh
- scripts/pingcap/tiflow/release-5.4/ticdc_download_integration_test_binaries.sh
tiflow split release 5.4 jobs.
> feat(tiflow): tiflow split release 5.4 jobs

- pipelines/pingcap-inc/enterprise-extensions/latest/pod-pr-verify.yaml
- pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
> feat(pipelines/pingap-inc/enterprise-extensions): add git safe dir and update with new images

- jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
- jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
- pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
disable old pipelines trigger on release-5.3.
> feat(tiflow): disable old pipelines trigger on release-5.3

- pipelines/pingcap/tiflow/release-6.1/pod-pull_cdc_integration_kafka_test.yaml
- prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
update pod template to use memory volume in cdc kafka test.
> chore(tiflow): update pod template to use memory volume in cdc kafka test

- prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
Enable refactor pipelines on tiflow release-5.3.
> feat(tiflow): enable refactor pipelines on tiflow release-5.3

- prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
enable tiflow refactor pipelines on release-6.5.
> feat(tiflow): enable tiflow refactor pipelines on release-6.5

- prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
Enable refactor pipelines on tiflow release-5.4.
> feat(tiflow): enable refactor pipelines on tiflow release-5.4

- pipelines/pingcap/tidb/latest/pod-ghpr_check2_debug.yaml
add new test podtemplate for debug verify.
> debug: add new test podtemplate for verify

- jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
- jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
- jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
- jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
disable old jobs trigger on some LTS branch
* release-6.5
* release-6.1
* release-5.4
* release-5.3
> feat(tiflow): disable old jobs trigger on lts branch

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
bump version of go1.20 & go1.19.
> feat(build-common): bump version of go1.20 & go1.19

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
tikv cache image add release-7.2
> feat: tikv cache image add release-7.2

- scripts/pingcap/tidb/br-lightning_run_group.sh
> fix: update br run_group

- jobs/pingcap/tidb/release-7.2/aa_folder.groovy
- jobs/pingcap/tidb/release-7.2/ghpr_build.groovy
- jobs/pingcap/tidb/release-7.2/ghpr_check.groovy
- jobs/pingcap/tidb/release-7.2/ghpr_check2.groovy
- jobs/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_check.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.2/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.2/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-7.2/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-7.2/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-7.2/pod-ghpr_unit_test.yaml
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-release-7.2-presubmits.yaml
> feat: tidb split release-7.2 jobs

- jobs/pingcap/tiflow/release-7.2/README.md
- jobs/pingcap/tiflow/release-7.2/aa_folder.groovy
- jobs/pingcap/tiflow/release-7.2/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-7.2/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-7.2/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-7.2/pull_cdc_integration_test.groovy
- jobs/pingcap/tiflow/release-7.2/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-7.2/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-7.2/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.2/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.2/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-7.2/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-7.2/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-7.2/pod-pull_cdc_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.2/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-7.2/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.2/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.2/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-7.2/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.2/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.2/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.2/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.2/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
Tiflow split release 7.2 jobs.
> feat: tiflow split release 7.2 jobs

- prow-jobs/pingcap-tidb-latest-postsubmits.yaml
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Branches:
- trunk branch
- feature branches
- latest release branch
Depended on: https://github.com/ti-community-infra/configs/pull/812
> feat(jobs/pingcap/tidb): enable condition triggering on trunk branches

- prow-jobs/pingcap-qe-ci-presubmits.yaml
> feat(prow-jobs): add jobs to verify ci's prow jobs

- jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
- jenkins/pipelines/ci/ticdc/integration_test_common.groovy
add schema_registry binary to cdc kafka integration tests
test passed
> fix: add schema_registry binary

- libraries/tipipeline/vars/prow.groovy
- pipelines/pingcap/tidb/latest/ghpr_check2.groovy
- pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
Ref:
- #2171 
- pingcap/tidb#44796
> feat(pipelines/pingcap/tidb/latest): enable coverage upload in `check_dev2` job

- pipelines/pingcap/tidb/latest/pull_integration_br_test.groovy
Use test scripts in repo br/tests/ to run tests.
> fix: update br lightning it test

- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
- jenkins/pipelines/cd/pre-release-check.groovy
- jenkins/pipelines/cd/pre-release-enterprise-docker.groovy
- jenkins/pipelines/cd/release-check.groovy
- jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
- jenkins/pipelines/cd/tiup/pre-release-build.groovy
- jenkins/pipelines/cd/tiup/pre-release-tiup.groovy
- jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
Add nodeSelector to use linux/amd64 node.
> chore(build): add nodeselector to use linux/amd64 node

- pipelines/pingcap/tidb/latest/ghpr_check2.groovy
> Revert "fix: run importintotest at the first"

- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
disable auto trigger on wip job.
> fix: disable auto trigger on wip job

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-binlog-latest-presubmits-wip.yaml
Currently it's working in progress.
> feat(prow-jobs): add presubmit job for `pingcap/tidb-binlog`

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
remove wip on br-integration-test.
> chore: remove wip on br-integration-test

- prow-jobs/pingcap-tiflow-latest-presubmits-wip.yaml
> feat(prow-jobs): fix presubmit job for `pingcap/tiflow`

- pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
Add debug info to find abnormal node.
> fix: add debug info to find abnormal node

- prow-jobs/pingcap-tiflow-latest-presubmits-wip.yaml
> fix(prowjobs): fix tiflow wip jobs

- prow-jobs/pingcap-tiflow-latest-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.0-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.2-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
Ref: https://github.com/PingCAP-QE/ci/issues/2129
> perf(prow-jobs): update trigger condition for jobs of pingcap/tiflow

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-latest-postsubmits.yaml
- prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.1-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.2-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.3-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.4-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.6-presubmits.yaml
- prow-jobs/pingcap-tidb-release-7.0-presubmits.yaml
- prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml
- prow-jobs/pingcap-tidb-release-7.2-presubmits.yaml
Ref: https://github.com/PingCAP-QE/ci/issues/2129
> perf(prow-jobs): update trigger condition for CI jobs of pingcap/tidb

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Trigger br&lighting integration tests against diff files. Only changes made in the "br/" directory will be automatically triggered.
> feat(br): trigger br against diff files

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
* AlwaysRun is mutually exclusive with SkipIfOnlyChanged
* AlwaysRun is mutually exclusive with RunIfChanged
> fix: remove AlwaysRun because mutually exclusive

- jobs/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_mysql_test.yaml
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Ref: https://github.com/PingCAP-QE/ci/issues/2234
> feat: tidb test add  new pipeline for mysql test with tiproxy

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
> Revert "feat(br): trigger br against diff files"

- prow-jobs/pingcap-tiflow-latest-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.0-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.2-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
> Revert "perf(prow-jobs): update trigger condition for jobs of pingcap/tiflow"

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
temp disable report for br-integration-test.
> fix: temp disable report for br-integration-test

- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
enable integration-sequelize-test report.
> chore: enable integration-sequelize-test report

- jobs/pingcap/tidb/latest/pull_common_test.groovy
- jobs/pingcap/tidb/latest/pull_integration_common_test.groovy
- jobs/pingcap/tidb/latest/pull_integration_ddl_test.groovy
- jobs/pingcap/tidb/latest/pull_sqllogic_test.groovy
- jobs/pingcap/tidb/latest/pull_tiflash_test.groovy
- pipelines/pingcap/tidb/latest/pod-pull_common_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_integration_common_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_integration_ddl_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_sqllogic_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_tiflash_test.yaml
- pipelines/pingcap/tidb/latest/pull_common_test.groovy
- pipelines/pingcap/tidb/latest/pull_integration_common_test.groovy
- pipelines/pingcap/tidb/latest/pull_integration_ddl_test.groovy
- pipelines/pingcap/tidb/latest/pull_integration_jdbc_test.groovy
- pipelines/pingcap/tidb/latest/pull_integration_mysql_test.groovy
- pipelines/pingcap/tidb/latest/pull_sqllogic_test.groovy
- pipelines/pingcap/tidb/latest/pull_tiflash_test.groovy
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Ref: https://github.com/PingCAP-QE/ci/issues/2233
> feat: add presubmit for some integration-test

- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
> fix(tiproxy): repo name is case-sensitive

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
bump version to go1.20.6 & go1.19.11.
> feat(build-common): bump version to go1.20.6 & go1.19.11

- jobs/pingcap/tiproxy/latest/pull_integration_common_test.groovy
- jobs/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_common_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_jdbc_test.yaml
- pipelines/pingcap/tiproxy/latest/pull_integration_common_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy
- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Add two integration orm test.
Notice:
1. remove `wip/` from context after pipeline test passed
> feat(tiproxy): add two integration orm test

- prow-jobs/pingcap-qe-ci-presubmits.yaml
> feat(prow-jobs): add presubmit job to verify prow jobs

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
- scripts/plugins/notify-by-lark.ts
only notify when the monitor files changed.
Ref: #2277
> feat(tidb): add notify presubmit job for tidb

- jobs/pingcap/tiproxy/latest/pull_integration_ruby_orm_test.groovy
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_ruby_orm_test.yaml
- pipelines/pingcap/tiproxy/latest/pull_integration_common_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_ruby_orm_test.groovy
- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Notice:
remove wip/ from context after pipeline test passed.
> feat(tiproxy):  add ruby orm pipeline

- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
only auto trigger before merge for mysql-connector-test.
> feat(tiproxy): only auto trigger before merge for mysql-connector-test

- pipelines/pingcap/tidb/latest/ghpr_check2.groovy
- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
> fix(pipelines/pingcap/tidb): fix coverage data path and refactor unit job

- pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
- pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
- pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
- pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
Optimize pipeline cache logic.
> fix(tidb): adjust pipeline dependency cache

- jobs/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
- jobs/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
- jobs/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
- jobs/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_common_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_jdbc_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_ruby_orm_test.yaml
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Add more tiproxy releated ci on tidb-test
> feat(tiproxy): tidb test add more tiproxy ci

- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_mysql_connector_test.yaml
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
Add pod yamls of tiproxy pipeline.
> fix(tidb-test): tidb test add pod yamls of tiproxy

- jobs/pingcap/tidb/latest/merged_mysql_connector_test.groovy
- jobs/pingcap/tidb/latest/pull_mysql_connector_test.groovy
- pipelines/pingcap/tidb/latest/merged_mysql_connector_test.groovy
- pipelines/pingcap/tidb/latest/pod-merged_mysql_connector_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_mysql_connector_test.yaml
- pipelines/pingcap/tidb/latest/pull_mysql_connector_test.groovy
- prow-jobs/pingcap-tidb-latest-postsubmits.yaml
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Add mysql connector-c test pipeline.
Notice: 
Temporarily disable status reporting, enable configuration after stable testing.
> feat(tidb): Add mysql connector-c test pipeline

- pipelines/pingcap/tiproxy/latest/pull_integration_common_test.groovy
- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Remove `wip` on some ci context.
> feat(tiproxy): update ci context to remove wip

- jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
- jenkins/pipelines/ci/tiflash/tiflash-ghpr-build.groovy
- jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
- jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy
To reduce the probability of 5000 timeout issues
> chore(tiflash): Reduce the probability of 5000 timeout issues

- jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
use specify node to reduce the probability of 5000 timeout issues
> chore(tiflash): use specify node to reduce the probability of 5000 timeout issues

- jenkins/pipelines/cd/dev-build.groovy
Why:
- fix PipelineStartAt unintended removed introduced by [#2317](https://github.com/PingCAP-QE/ci/pull/2317)
> fix: recover pipeline start at

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
enable report for some test passed presubmit
> feat: enable report for some test passed presubmit

- pipelines/pingcap/tidb-test/latest/ghpr_build.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_common_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_prisma_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_sequelize_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
> fix(tidb-test): fix s3 cache src code error

- prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml
Ref https://github.com/PingCAP-QE/ci/issues/2129.
update trigger condition for jobs of tidb release-7.1.
> feat(tidb): update trigger condition for jobs of tidb release-7.1

- jobs/pingcap/tidb/release-7.3/aa_folder.groovy
- jobs/pingcap/tidb/release-7.3/ghpr_build.groovy
- jobs/pingcap/tidb/release-7.3/ghpr_check.groovy
- jobs/pingcap/tidb/release-7.3/ghpr_check2.groovy
- jobs/pingcap/tidb/release-7.3/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-7.3/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_check.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.3/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.3/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-7.3/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-7.3/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-7.3/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.3/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/release-7.3/pull_br_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-release-7.3-presubmits.yaml
> feat: tidb split release-7.3 jobs

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
* tikv cache image add release-7.3
* remove the last dmr version cache image(7.2)
> feat: tikv cache image add release-7.3

- jobs/pingcap/tiflow/release-7.3/aa_folder.groovy
- jobs/pingcap/tiflow/release-7.3/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-7.3/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-7.3/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-7.3/pull_cdc_integration_test.groovy
- jobs/pingcap/tiflow/release-7.3/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-7.3/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-7.3/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.3/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.3/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-7.3/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-7.3/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-7.3/pod-pull_cdc_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.3/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-7.3/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.3/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.3/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-7.3/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.3/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.3/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.3/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.3/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-7.3-presubmits.yaml
Tiflow split release 7.3 jobs.
> feat: tiflow split release 7.3 jobs

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
bump go vesion to 1.20.7 & 1.19.11.
> feat(build): bump go vesion to 1.20.7 & 1.19.11

- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
- jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
- jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
update nightly version to v7.4.0
> chore: update nightly version to v7.4.0-alpha

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
> fix(pingcap/tidb): make flaky and timecost reporting always

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
> chore(pingcap/tidb): add notify receivers when congfiguration changed in PR

- pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
use the go1.21 image in mysql-test.
> feat(tidb): update go image

- pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
- pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy
Upload br integration test coverage data to codecov.io.
> feat(tidb/br): upload br integration test coverage data

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
> feat(build): support go1.21 from v7.4

- pipelines/pingcap/tidb-test/latest/pod-ghpr_build.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_common_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_common_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_jdbc_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_mysql_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_prisma_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_python_orm_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_sequelize_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_common_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_jdbc_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_mysql_connector_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_mysql_test.yaml
- pipelines/pingcap/tidb-test/latest/pod-pull_tiproxy_ruby_orm_test.yaml
> feat: tidb-test master use go1.21

- pipelines/pingcap/tidb/latest/merged_integration_python_orm_test.groovy
- pipelines/pingcap/tidb/latest/merged_integration_sequelize_test.groovy
- pipelines/pingcap/tidb/latest/merged_mysql_connector_test.groovy
- pipelines/pingcap/tidb/latest/pod-merged_integration_python_orm_test.yaml
add a go image in python-orm test pod template.
> feat: add a go image in python-orm test pod template

- jobs/tikv/pd/release-7.1/aa_folder.groovy
- jobs/tikv/pd/release-7.1/ghpr_build.groovy
- jobs/tikv/pd/release-7.1/pull_integration_copr_test.groovy
- pipelines/tikv/pd/release-7.1/ghpr_build.groovy
- pipelines/tikv/pd/release-7.1/pod-ghpr_build.yaml
- pipelines/tikv/pd/release-7.1/pod-pull_integration_copr_test.yaml
- pipelines/tikv/pd/release-7.1/pull_integration_copr_test.groovy
- prow-jobs/tikv-pd-release-7.1-presubmits.yaml
split pd release-7.1 jobs.(support v7.0 ~ v7.3)
> feat(pd): split pd release-7.1 jobs

- pipelines/tikv/pd/latest/pod-ghpr_build.yaml
- pipelines/tikv/pd/latest/pod-pull_integration_copr_test.yaml
pd master update go version to 1.21.
Ref  https://github.com/tikv/pd/issues/6923
> feat(pd): update go version to 1.21

- jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
From v7.4, we update to go1.21 for build.
> feat(build): multi branch build support go1.21

- jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
- jenkins/pipelines/ci/tikv/pd/pd_ghpr_build.groovy
- pipelines/tikv/pd/latest/ghpr_build.groovy
- pipelines/tikv/pd/release-6.5/ghpr_build.groovy
- pipelines/tikv/pd/release-7.1/ghpr_build.groovy
> fix(tikv/pd): should not tar all files for pd-server.tar.gz

- prow-jobs/pingcap-tidb-release-6.2-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.3-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.4-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.6-presubmits.yaml
- prow-jobs/pingcap-tidb-release-7.0-presubmits.yaml
- prow-jobs/pingcap-tidb-release-7.2-presubmits.yaml
Ref  https://github.com/PingCAP-QE/ci/issues/2129
update trigger condition for jobs of tidb release branch.
> feat: update trigger condition for jobs of tidb

- jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_check.groovy
Set resource limit to avoid excessive resource usage of golangci-lint.
Ref  https://github.com/PingCAP-QE/ci/issues/2146
> fix: set limit to avoid excessive resource usage of golangci-lint

- jenkins/pipelines/cd/tiflow-operator-docker.groovy
> fix: node selector for tiflow operator

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
disable failfst on br integration test.
> chore(br): disable failfst on br integration test

- jenkins/pipelines/cd/dev-build.groovy
- jenkins/pipelines/cd/release-GA.groovy
> feat: change GA/Hotfix GCR tag by plan

- pipelines/pingcap/tiflow/latest/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/latest/pod-pull_dm_integration_test.yaml
dm upgrade go version to 1.21.
> feat(tiflow): dm upgrade go version to 1.21

- pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_test.yaml
- pipelines/pingcap/tiflow/latest/pod-pull_engine_integration_test.yaml
cdc upgrade go version to 1.21.
> feat(tiflow): cdc upgrade go version to 1.21

- jenkins/pipelines/cd/tiflow-docker.groovy
- jenkins/pipelines/cd/tiflow-operator-docker.groovy
- jenkins/pipelines/cd/tiproxy-docker.groovy
add nodeselector to avoid accidental scheduling to arm64 nodes.
> fix(build): add nodeselector

- jobs/pingcap/tiflow/release-7.1.0/aa_folder.groovy
- jobs/pingcap/tiflow/release-7.1.0/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.1.0/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-7.1.0/pull_cdc_integration_storage_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.1.0-presubmits.yaml
split tiflow storage test on v7.1.0.
> feat(tiflow): split tiflow storage test on v7.1.0

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
- scripts/plugins/report-flaky-cases.ts
Fixes #2370
We need the build url to deep dialog the failure or slow problem of test cases.
> feat(pingcap/tidb) report build url info for flaky and case time report records

- pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
> chore(tiflow): adjust timeout for dm test

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
- jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_build_new3.groovy
- jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_check.groovy
- jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
- jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_unit_test.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
- jenkins/pipelines/goversion-select-lib.groovy
update br old integration test pipeline to support go1.21.
> feat(br): br old it pipeline support go1.21

- jobs/pingcap/tiproxy/latest/pull_integration_prisma_test.groovy
- jobs/pingcap/tiproxy/latest/pull_integration_python_orm.groovy
- jobs/pingcap/tiproxy/latest/pull_integration_sequelize.groovy
- jobs/pingcap/tiproxy/latest/pull_sqllogic_test.groovy
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_sequelize_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_prisma_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_python_orm_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_sequelize_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_sqllogic_test.yaml
- pipelines/pingcap/tiproxy/latest/pull_integration_prisma_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_python_orm_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_sequelize_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_mysql_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_sqllogic_test.groovy
- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
add more presubmit jobs on tiproxy
> feat(tiproxy): add more presubmit on tiproxy

- pipelines/pingcap/tiproxy/latest/pull_sqllogic_test.groovy
> fix(tiproxy): escape error

- jobs/pingcap/tidb/latest/pull_integration_prisma_test.groovy
- pipelines/pingcap/tidb/latest/pod-pull_integration_prisma_test.yaml
- pipelines/pingcap/tidb/latest/pull_integration_prisma_test.groovy
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Add more presubmit pieline on tidb
* pull_integration_prisma_test
> feat(tidb): support prisma-test in presubmit

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Enable report status of pull-integration-prisma-test.
> chore(tidb): enable report status of pull-integration-prisma-test

- pipelines/pingcap/tidb-test/latest/ghpr_integration_prisma_test.groovy
- pipelines/pingcap/tidb-test/latest/ghpr_integration_sequelize_test.groovy
correct code cache key mismatch.
> fix(tidb-test): correct code cache key mismatch

- jobs/pingcap/tiproxy/latest/merged_integration_prisma_test.groovy
- jobs/pingcap/tiproxy/latest/merged_integration_python_orm_test.groovy
- jobs/pingcap/tiproxy/latest/merged_integration_sequelize_test.groovy
- jobs/pingcap/tiproxy/latest/merged_sqllogic_test.groovy
- pipelines/pingcap/tiproxy/latest/merged_integration_prisma_test.groovy
- pipelines/pingcap/tiproxy/latest/merged_integration_python_orm_test.groovy
- pipelines/pingcap/tiproxy/latest/merged_integration_sequelize_test.groovy
- pipelines/pingcap/tiproxy/latest/merged_sqllogic_test.groovy
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_prisma_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_python_orm_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_sequelize_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_sqllogic_test.yaml
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml
Add more tiproxy tests:
- merged_integration_prisma_test
- merged_integration_python_orm_test
- merged_integration_sequelize_test
- merged_sqllogic_test
> feat(tiproxy): add more tiproxy tests

- jobs/pingcap/tidb/release-6.1/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-6.1/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/release-6.1/pull_br_integration_test.groovy
- prow-jobs/pingcap-tidb-release-6.1-presubmits.yaml
- scripts/pingcap/tidb/br-lightning_run_group.sh
- scripts/pingcap/tidb/br_integration_test_download_dependency.sh
support refactor br-integration-test ci on lts branch  release-6.1
> feat(br): support refactor br-integration-test ci on lts branch

- pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.6/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_mysql_test.groovy
Correct the log path for mysql test log archive.
> fix(tidb): archive the mysql test fail log

- jenkins/pipelines/cd/tiup/tiproxy-tiup-mirror.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_common_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_jdbc_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_connector_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_mysql_test.groovy
- pipelines/pingcap/tidb-test/latest/pull_tiproxy_ruby_orm_test.groovy
- prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml
- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
repo TiProxy already renamed to tiproxy.
> fix: repo TiProxy rename to tiproxy

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- jenkins/pipelines/cd/atom-jobs/docker-common.groovy
- jenkins/pipelines/cd/dev-build.groovy
Why:
- pod is more reliable and reproducible
- we are migrating IDC, in order to keep service
> feat: arm use pod rather than bare machine

- jobs/pingcap/tiproxy/latest/merged_integration_common_test.groovy
- jobs/pingcap/tiproxy/latest/merged_integration_jdbc_test.groovy
- jobs/pingcap/tiproxy/latest/merged_integration_ruby_orm_test.groovy
- pipelines/pingcap/tiproxy/latest/merged_integration_common_test.groovy
- pipelines/pingcap/tiproxy/latest/merged_integration_jdbc_test.groovy
- pipelines/pingcap/tiproxy/latest/merged_integration_ruby_orm_test.groovy
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_common_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_jdbc_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_ruby_orm_test.yaml
- prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml
Add more tiproxy tests:
* merged-integration-ruby-orm-test
* merged-integration-jdbc-test
* merged-integration-common-test
> feat: add more merged pipeline on tiproxy

- tools/list-go-dependencies/README.md
- tools/list-go-dependencies/main.go
Add features:
- Get the count of the imported modules.
- Get the count of the imported by modules.
- Get the line of module code (exclude blank and comment lines).
> feat(tools/list-go-dependencies): support get imports and imported by count and lines of code

- scripts/pingcap/tidb/integrationtest.sh
for https://github.com/pingcap/tidb/pull/46712
> feat: add a new scprit named `integrationtest.sh`

- pipelines/pingcap/tidb/latest/pod-ghpr_check2_v2.yaml
add new pod template file for debug ceph pvc
> chore: add new pod template file

- pipelines/pingcap/tidb/latest/pod-ghpr_check2_v2.yaml
> Revert "chore: update debug pod template"

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
fix build enterprise plugin error after using arm pod
remove inner container directive
> fix: enterprise plugin build

- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
> chore(pipelines/pingcap/tidb/latest): update image and add repo cache mount for job canary unit test job

- pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.6/ghpr_build.groovy
> chore(tidb): add build timeout to 60 min

- pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
cache  bazel repo cache on build pipeline.
> chore: cache  bazel repo cache

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_unit_test.yaml
cache bazel repo cache for ut pipeline
> chore(tidb): cache bazel repo cache

- pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
use high performance disk for ut pipeline
> chore: use high performance disk for ut pipeline

- pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-6.5/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-6.5/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_check2.yaml
> chore(tidb): use disk with better io

- jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
fix ci mysql-test, the problem comes from the changes in this PR https://github.com/PingCAP-QE/ci/pull/2431.
> fix(tidb): fix ci mysql-test

- scripts/ops/create-issues-for-tidb-flaky-tests.ts
- scripts/ops/create-issues-for-tidb-slow-tests.ts
Add scripts:
- `scripts/ops/create-issues-for-tidb-flaky-tests.ts`
- `scripts/ops/create-issues-for-tidb-slow-tests.ts`
> Currently only support `pingcap/tidb` repo at `master` branch, so I hard coded it.
> feat(scripts/ops): add scripts to create issues for tidb

- jenkins/pipelines/cd/tiflow-docker.groovy
> fix: use ksyun k8s cluster

- jenkins/jobs/cd/tiflow_docker.groovy
- jenkins/jobs/cd/tiflow_operator_docker.groovy
- jenkins/jobs/cd/tiproxy_docker.groovy
- jenkins/pipelines/cd/tiflow-docker.groovy
- jenkins/pipelines/cd/tiflow-operator-docker.groovy
- jenkins/pipelines/cd/tiproxy-docker.groovy
- old arm k8s cluster can not allocate pod(debuging)
- add timeout
- add job dsl
- migrate from arm k8s cluster to default ksyun cluster
- add node selector for arm
> feat: use ksyun rather than old arm cluster

- jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
Correct pipelines affected by tidb-test org adjusted.
> fix: correct pipelines affected by tidb-test org adjusted

- scripts/ops/create-issues-for-tidb-flaky-tests.ts
- scripts/ops/create-issues-for-tidb-slow-tests.ts
the regex is bad in deno, currently I do not know why.
> fix(scripts/ops): fix topN issue creating scripts

- .ci/verify-jenkins-pipelines.sh
- jenkins/pipelines/cd/release-GA.groovy
- fix syntax
- add jenkins/pipelines to ci validate
> fix: release-ga syntax

- jenkins/jobs/ci/tidb/ghpr_integration_br_test.groovy
disable trigger by pr comment on master and lts branch
> fix(br): disable trigger on master and lts branch

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_ingration_enterprise_plugin_test.groovy
- jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy
- pipelines/pingcap/tidb/latest/merged_build.groovy
- pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.4/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.6/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_build.groovy
- staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
- staging/pipelines/pingcap/tidb/latest/merged_build.groovy
from `pingcap` ORG to `pingcap-inc` ORG.
> refactor: migrate `enterprise-plugin` repo

- jobs/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy
- pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_pulsar_test.yaml
- pipelines/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy
- prow-jobs/pingcap-tiflow-latest-presubmits.yaml
as title. 
Note: Temporarily disable the status reporting of pipeline. After the new pipeline passes the test, enable the status reporting again.
> ticdc: add pulsar sink integration test pipeline for ticdc

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
* tikv cache image add release-7.4
* remove the last dmr version cache image(7.3)
> feat(tikv): support 7.4 cache image

- jobs/pingcap/tiflow/release-7.3/pull_cdc_integration_pulsar_test.groovy
- jobs/pingcap/tiflow/release-7.4/aa_folder.groovy
- jobs/pingcap/tiflow/release-7.4/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_mysql_test.groovy
- jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_pulsar_test.groovy
- jobs/pingcap/tiflow/release-7.4/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-7.4/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-7.4/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-7.4/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.4/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.4/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_mysql_test.yaml
- pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_pulsar_test.yaml
- pipelines/pingcap/tiflow/release-7.4/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-7.4/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-7.4/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.4/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_mysql_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_pulsar_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-7.4-presubmits.yaml
> feat(tiflow): add tiflow release-7.4 jobs

- pipelines/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
> fix(tidb): remove post report step

- jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
- tiup has release stable version to solve timeout problem
this PR will close: #2465
> chore: use tiup stable version

- jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
- jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
- jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
- jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
- jenkins/pipelines/goversion-select-lib-v2.groovy
support go1.21 on 7.4 in those qa test pipelines.
> fix(qatest): fix issue of pipieline used by qatest

- prow-jobs/ti-community-infra-test-infra-presubmits.yaml
> chore(prow-jobs): bump image gcr.io/k8s-staging-test-infra/kubekins-e2e to `v20230926-f045ae1296-test-infra`

- jenkins/pipelines/qa_release_test.groovy
not force upload tar package to fileserver to avoid affect ci.
> fix(qa-test): not force upload tar package to fileserver

- jobs/pingcap-qe/tidb-test/latest/ghpr_integration_typeorm_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_typeorm_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_typeorm_test.yaml
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Add new pipelines for integration-typeorm-test on tidb-test.
> config: add typeorm pipeline to tidb test repo

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
add typeorm_test job on tidb-test repo
> feat(tidb-test): add typeorm_test job on tidb-test repo

- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_prisma_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_sequelize_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_typeorm_test.yaml
add node affinity on some pipelines podtemplte.
> feat(tidb-test): add node affinity

- jenkins/jobs/ci/qa/archive-image-binary-to-minio.groovy
- jenkins/pipelines/qa/archive-image-binary-to-minio.groovy
add archive-image-binary-to-minio
> feat(qa): add archive-image-binary-to-minio

- jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
Why:
- fix the nightly tiflash path
> fix: nightly tiflash path

- pipelines/tikv/tikv/latest/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/latest/pull_unit_test.groovy
> feat(tikv): refactor tikv ut

- pipelines/pingcap/tidb/latest/merged_integration_nodejs_test.groovy
* fix cache path and cache key
* only run with tikv store so we remove axis name TEST_STORE
> fix(tidb): fix cache path and cache key

- jobs/pingcap-inc/enterprise-extensions/le-release-7.4/aa_folder.groovy
- jobs/pingcap-inc/enterprise-extensions/le-release-7.4/pr_verify.groovy
- pipelines/pingcap-inc/enterprise-extensions/le-release-7.4/pod-pr-verify.yaml
- pipelines/pingcap-inc/enterprise-extensions/le-release-7.4/pr-verify.groovy
- prow-jobs/pingcap-inc-enterprise-extensions-presubmits.yaml
> fix(pingcap-inc/enterprise-extensions): fix checkout step

- jenkins/pipelines/ci/rust-rocksdb/rust_rocksdb_ghpr_test.groovy
update rust_rocksdb image in test
* need perl-IPC-Cmd
> feat: updaste rust_rocksdb image in test

- pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
> fix(pingcap-inc/enterprise-extensions): fix unit test step

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
- jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Why:
- remove mydumper and tikv-importer since v7.5.0
> feat: remove mydumper and tikv-importer since v7.5.0

- jobs/pingcap/tiflow/release-7.5/aa_folder.groovy
- jobs/pingcap/tiflow/release-7.5/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-7.5/pull_cdc_integration_mysql_test.groovy
- jobs/pingcap/tiflow/release-7.5/pull_cdc_integration_pulsar_test.groovy
- jobs/pingcap/tiflow/release-7.5/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-7.5/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-7.5/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-7.5/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.5/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.5/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-7.5/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-7.5/pod-pull_cdc_integration_mysql_test.yaml
- pipelines/pingcap/tiflow/release-7.5/pod-pull_cdc_integration_pulsar_test.yaml
- pipelines/pingcap/tiflow/release-7.5/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-7.5/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-7.5/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.5/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_mysql_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_pulsar_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-7.5-presubmits.yaml
tiflow split release-7.5 branch jobs.
> feat(tiflow): tiflow split release-7.5 branch jobs

- jobs/pingcap/tidb/release-7.5/aa_folder.groovy
- jobs/pingcap/tidb/release-7.5/ghpr_build.groovy
- jobs/pingcap/tidb/release-7.5/ghpr_check.groovy
- jobs/pingcap/tidb/release-7.5/ghpr_check2.groovy
- jobs/pingcap/tidb/release-7.5/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-7.5/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-7.5/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_check.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.5/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.5/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-7.5/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-7.5/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-7.5/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.5/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/release-7.5/pull_br_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-release-7.5-presubmits.yaml
> feat(tidb): tidb split release 7.5 jobs

- pipelines/pingcap/tidb/release-7.5/ghpr_mysql_test.groovy
correct build tidb-server cmd.
> fix(tidb): correct build tidb-server cmd

- pipelines/pingcap/tidb/release-7.5/ghpr_check2.groovy
update integrationtest cmd on 7.5
> fix(tidb): update integrationtest cmd on 7.5

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
> chore: set pull-e2e-test optional

- jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
Why:
- deleteDir will fail on root workspace while retry
> fix: deleteDir  retry will fail at root workspace

- jenkins/pipelines/cd/tiup/prometheus-tiup-mirror-update.groovy
- tidb repo layout changed
- branch logic by version
- remove ` || true`, let error exposed
- https://github.com/PingCAP-QE/ci/issues/2533
> fix: tidb repo layout change

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
- jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
support qa-release-test trigger pipeline
> fix: support qa-release-test trigger pipeline

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
ref https://github.com/tikv/pd/pull/6946/files
> fix the pd failpoint build

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
* remove wip label on some pull-test pipelines.
* set those pull-test pipelines to optional because these are optional triggers.
> feat(tidb): remove wip and set those optional

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-latest-presubmits-wip.yaml
- prow-jobs/tikv-pd-release-6.1-presubmits.yaml
> feat(tikv/pd): add wip job `build` for release-6.1

- jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
- remove 7.4 nightly
- add 7.5 nightly
> chore: build nightly for 7.5

- prow-jobs/pingcap-tidb-latest-postsubmits.yaml
Enable ci report of nodejs test pipeline.
> chore: enable report of nodejs test

- jenkins/jobs/cd/grafana_tiup_mirror_update.groovy
- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update.groovy
- jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
- jenkins/pipelines/cd/tiup/prometheus-tiup-mirror-update.groovy
- jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
- jenkins/pipelines/cd/tiup/tiup-online-mirror-tidb.groovy
> fix(jenkins): deprecate `tiup package` usages

- jobs/pingcap/tidb/latest/periodics_integration_test.groovy
- pipelines/pingcap/tidb/latest/periodics_integration_test.groovy
- pipelines/pingcap/tidb/latest/pod-periodics_integration_test.yaml
Add periodics integration test to test end-to-end correctness.
> feat: add periodics integration test to check

- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
> fix(pipelines/pingcap/tidb/latest): fix pod of canary unit test job

- pipelines/pingcap/tidb/latest/periodics_integration_test.groovy
fix periodics integration test
> fix: fix periodics integration test

- pipelines/pingcap/tidb/latest/periodics_integration_test.groovy
> fix: fix refs file upload path

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
Currently we report with private scripts downloaded from internal servers, them may contains some credentials to access the backend database, it's not security and extendable.
We mirror the reports to  event server to encapsulate the logic and not need to expose the credentials in scripts.
- cloudevents server implementation: https://github.com/PingCAP-QE/ee-apps/tree/main/cloudevents-server
- cdevents spec: https://cdevents.dev/
- cloudevents spec: https://github.com/cloudevents/spec
> feat(pipeliens/pingcap/tidb/latest): mirror report to event server

- jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
Close https://github.com/PingCAP-QE/ci/issues/2021
Fix archive log failed after some integration test failed due to missing file read and write permission in containers. 
The default user in image hub.pingcap.net/jenkins/docker:build-essential-java is `root`, but the jenkins try to archive log using `UID 1000`  within `archiveArtifacts(artifacts: "${name}-logs.tar.gz", allowEmptyArchive: true)`
We change the ownship of log file to user jenkins (its UID is 1000)  before  archive logs.
> fix(tiflash): fix archive log failed 

- prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
currently it will not report to github and will not affect any pull requests.
> chore(pingcap/tidb): auto run canary unit test job

- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
> chore(canary): update ut image

- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
> Revert "chore(canary): update ut image"

- pipelines/PingCAP-QE/tidb-test/latest/pull_tiproxy_common_test.groovy
- prow-jobs/pingcap-tidb-test-latest-presubmits.yaml
* Update some tiproxy test ci context: remove`wip/`
* mysql connector test already covered in another pipeline `pull_tiproxy_mysql_connector_test`.
> chore(tidb-test): update some tiproxy test ci context

- libraries/tipipeline/vars/component.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
support check tidb pr then merge base
> feat(tidb-test): support check tidb pr then merge base

- pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_mysql_test.groovy
Checkout tidb pr then merge base-branch in `pull_integration_mysql_test`
> feat(tidb-teest): checkout tidb pr then merge base-branch

- pipelines/PingCAP-QE/tidb-test/latest/ghpr_build.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_common_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_common_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_jdbc_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_mysql_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_nodejs_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_python_orm_test.groovy
- pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_build.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_integration_mysql_test.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_mysql_test.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_build.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_integration_mysql_test.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_mysql_test.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_build.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_integration_mysql_test.groovy
- pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_mysql_test.groovy
Support check tidb pr then merge base on release branch pipelines.
> feat: checkout tidb pr then merge base

- jenkins/pipelines/cd/build-tidb-dashboard.groovy
> feat: add perl to tidb-dashboard

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- tar file path changed, which cause trouble when extracting
> fix: tar path

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- nfs maintenance cost time
- just  not use nfs, because we have fileserver s3
> feat: no nfs code cache

- pipelines/pingcap/tidb/latest/ghpr_check2.groovy
> fix(tidb): correct archive path

- jenkins/pipelines/cd/tiup/br-tiup-mirror-update.groovy
- jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test-hotfix.groovy
- jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test.groovy
- jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update.groovy
- jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update.groovy
- jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
> chore(jenkins/pipelines/cd/tiup): delete useless vars

- jenkins/pipelines/cd/dev-build.groovy
- artifact repo pr has been merged
> chore: change dockerfile path

- pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
fix download error on hotfix branch
> fix: fix download error on hotfix branch

- jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
Add tiflash code cache at the first checkout step. After adding the code cache, the time it takes to checkout the code decreased from 30s to 8s.
In case of special circumstances, such as GitHub's speed limit, due to the presence of code cache, it will be less likely to encounter checkout timeout issues.
> feat(tiflash): add tiflash code cache

- jobs/pingcap/tidb/latest/pull_lightning_integration_test.groovy
- pipelines/pingcap/tidb/latest/pod-pull_lightning_integration_test.yaml
- pipelines/pingcap/tidb/latest/pull_lightning_integration_test.groovy
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Add new pipeline for lightning test, support split lightning test from current pull_br_integration_test.
> feat(tidb/lightning): add pull lightning tests pipeline

- jenkins/pipelines/cd/tidb-operator.groovy
ref https://github.com/PingCAP-QE/ci/pull/2635/files#diff-d46d28381dc8458d1a51170268d8d360a769db99a5136b6896cacd5739563e14L165
> fix mkdir for charts in TiDB Operator CD

- pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
- pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy
split br and lightning test in pipeline
> feat(tidb/br): split br and lightning test in pipeline

- scripts/pingcap-inc/enterprise-extensions/update-submodule-in-tidb.ts
> opt(scripts/pingcap-inc/enterprise-extensions): add descriptioin for PR

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
> ci: v5.3 is EOS

- pipelines/tikv/migration/latest/pod-pull_integration_test.yaml
- pipelines/tikv/migration/latest/pod-pull_unit_test.yaml
> feat(tikv/migration): upgrade to go1.21

- prow-jobs/pingcap-inc-enterprise-extensions-postsubmits.yaml
the submodule path is changed from v7.5.0: from `extensions` to `pkg/extensions`.
> fix(pingcap-inc/enterprise-extensioins): fix post-submit job

- pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
- pipelines/pingcap-inc/enterprise-extensions/le-release-7.4/pr-verify.groovy
Currently it will failure with cache in checkout stage.
> fix(pingcap-inc/enterprise-extensions): not use git repo cache for private repo

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.0/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.2/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.3/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.4/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.5/pod-ghpr_unit_test.yaml
- scripts/plugins/analyze-go-test-from-bazel-output.sh
> currently it's implemented with go race analyzing.
```bash
> ./analyze-go-test-from-bazel-output.sh bazel-test.log
Parse from local file: bazel-test.log
race detected case: TestAddIndexIngestGeneratedColumns
new flaky case: TestCursorFetchErrorInFetch
new flaky case: TestCursorFetchShouldSpill
Output files:
bazel-flaky-summaries.log                       bazel-go-test-problem-cases.json                bazel-target-output-L4631-5414.fail.log
bazel-go-test-index.log                         bazel-target-output-L3857-4621.fail.log         bazel-target-output-L520-3195.fail.race.log
```
file `bazel-go-test-index.log`:
```log
520:==================== Test output for //pkg/ddl/ingest:ingest_test (shard 5 of 15):
521:=== RUN   TestAddIndexIngestGeneratedColumns
1790:WARNING: DATA RACE …
```
> feat(script/plugins): support analyze fail reason of test case

- jenkins/pipelines/cd/tidb-operator.groovy
- support fips for tidb-operator
- fips require cgo, which disables cross compiling
- build arm binary with arm pod
> feat: support fips for operator

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- jenkins/pipelines/cd/atom-jobs/docker-common.groovy
- jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
Why:
- ks3util usually stall
How:
- add debug log
> chore: add debug log for ks3util

- jenkins/jobs/cd/devbuild.groovy
- jenkins/pipelines/cd/dev-build.groovy
- support drainer and pump as requested
- support docker image name differ from tiup
- re-run  for existing devbuild
> feat(devbuild): support drainer and pump

- prow-jobs/tikv-pd-latest-presubmits.yaml
enable pd pull-integration-realcluster-test for test.
> feat(pd): enable pd pull-integration-realcluster-test

- jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tikv_multi_branch.groovy
> chore(build): update multi-branch build

- jobs/pingcap/tidb/release-6.5-fips/aa_folder.groovy
- jobs/pingcap/tidb/release-6.5-fips/ghpr_build.groovy
- jobs/pingcap/tidb/release-6.5-fips/ghpr_check.groovy
- jobs/pingcap/tidb/release-6.5-fips/ghpr_check2.groovy
- jobs/pingcap/tidb/release-6.5-fips/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-6.5-fips/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-6.5-fips/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_check.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pull_br_integration_test.groovy
- prow-jobs/pingcap-tidb-latest-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.5-fips-presubmits.yaml
- scripts/pingcap/tidb/release-6.5-fips/br_integration_test_download_dependency.sh
support pipelines on branch feature/release-6.5-fips.
> feat: tidb support fips branch pipelines

- jobs/pingcap/tiflow/release-6.5-fips/aa_folder.groovy
- jobs/pingcap/tiflow/release-6.5-fips/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-6.5-fips/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-6.5-fips/pull_cdc_integration_test.groovy
- jobs/pingcap/tiflow/release-6.5-fips/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-6.5-fips/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-6.5-fips/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-6.5-fips/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-6.5-fips/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-6.5-fips/pod-pull_cdc_integration_test.yaml
- pipelines/pingcap/tiflow/release-6.5-fips/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-6.5-fips/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-6.5-fips/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-6.5-fips/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-6.5-fips/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-6.5-fips/pull_dm_integration_test.groovy
- prow-jobs/pingcap-tiflow-latest-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.5-fips-presubmits.yaml
- scripts/pingcap/tiflow/release-6.5-fips/cdc_run_group.sh
- scripts/pingcap/tiflow/release-6.5-fips/dm_download_compatibility_test_binaries.sh
- scripts/pingcap/tiflow/release-6.5-fips/dm_download_integration_test_binaries.sh
- scripts/pingcap/tiflow/release-6.5-fips/dm_run_group.sh
- scripts/pingcap/tiflow/release-6.5-fips/ticdc_download_integration_test_binaries.sh
tiflow support fips branch pipelines
> feat: tiflow support fips branch pipelines

- prow-jobs/kustomization.yaml
> feat: add two presubmit yaml

- pipelines/pingcap/tidb/release-6.5-fips/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5-fips/pull_br_integration_test.groovy
relate to https://github.com/PingCAP-QE/ci/issues/2606.
> feat: build with enable fips

- jobs/tikv/pd/release-6.5-fips/aa_folder.groovy
- jobs/tikv/pd/release-6.5-fips/ghpr_build.groovy
- pipelines/tikv/pd/release-6.5-fips/ghpr_build.groovy
- pipelines/tikv/pd/release-6.5-fips/pod-ghpr_build.yaml
- prow-jobs/kustomization.yaml
- prow-jobs/tikv-pd-latest-presubmits.yaml
- prow-jobs/tikv-pd-release-6.5-fips-presubmits.yaml
> feat: pd support fips pipeline

- jenkins/pipelines/cd/build-tidb-dashboard.groovy
Why:
- bypass dockerhub rate limit
> fix: bypass dockerhub rate-limit

- pipelines/pingcap/tidb/release-6.5-fips/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-6.5-fips/pod-ghpr_unit_test.yaml
> fix: fix tidb support on release 6.5 fips

- scripts/pingcap/tiflow/release-6.5-fips/dm_download_integration_test_binaries.sh
update dm download scripts on fips branch
> fix: update dm download scripts

- pipelines/pingcap/tidb/release-6.5-fips/ghpr_mysql_test.groovy
> chore: use the fips-branch tidb-test

- prow-jobs/pingcap-tidb-latest-periodics.yaml
* use shallow clone to reduce clone time.
* add affinity to schedule pod to x86 node.
> feat: optimize job clone params

- prow-jobs/pingcap-tidb-latest-periodics.yaml
update cron to run every 6 hours.
> chore: update cron

- pipelines/pingcap/tidb/latest/ghpr_check.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_check.groovy
> feat: archive logs if check failed

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Set pull-integration-ddl-test as required label on master branch.  After this PR is merged, each PR in the tidb master branch will be required to pass this test before merging.
> feat(tidb): set pull-integration-ddl-test as reuired on master branch

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
Set `pull-mysql-client-tes`t as required label on master branch. After this PR is merged, each PR in the tidb master branch will be required to pass this test before merging.
> feat(tidb): set pull-mysql-client-test as required lable on master branch

- prow-jobs/pingcap-qe-ci-presubmits.yaml
Reverts PingCAP-QE/ci#2692(this is a debug pr for param `optional`)
> Revert "debug: test optional"

- jobs/tikv/migration/latest/pull_integration_test.groovy
- jobs/tikv/migration/latest/pull_unit_test.groovy
- pipelines/tikv/migration/latest/pull_integration_test.groovy
- pipelines/tikv/migration/latest/pull_unit_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/tikv-migration-latest-presubmits.yaml
> feat(tikv/migration): support prow trigger job

- jenkins/pipelines/cd/pre-release-check.groovy
- jenkins/pipelines/cd/release-check.groovy
Why:
- dockerhub dind image is not stable
> fix: use internal dind image

- pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
> feat(tidb): add plugin test on build job for v6.1.x and v6.5.x

- pipelines/pingcap/tidb/latest/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5-with-kv-timeout-feature/ghpr_build.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_build.groovy
- v7.1.x
- v7.5.x
- trunk branch
> fix(pingcap/tidb): add plugin test stage

- jobs/pingcap/tiproxy/latest/merged_mysql_test.groovy
`merged_mysql_test` is missing.
> tiproxy: add merged_mysql_test

- pipelines/pingcap/tidb/release-6.5-fips/ghpr_check2.groovy
- scripts/pingcap/tidb/release-6.5-fips/br_integration_test_download_dependency.sh
- scripts/pingcap/tidb/release-6.5-fips/pingcap_download_artifacts.sh
- scripts/pingcap/tiflow/release-6.5-fips/dm_download_compatibility_test_binaries.sh
- scripts/pingcap/tiflow/release-6.5-fips/dm_download_integration_test_binaries.sh
- scripts/pingcap/tiflow/release-6.5-fips/ticdc_download_integration_test_binaries.sh
update fips-branch ci download script.
> feat(fips-branch): update fips-branch ci download script

- pipelines/pingcap/tidb/release-6.5-fips/ghpr_check2.groovy
- scripts/pingcap/tidb/release-6.5-fips/br_integration_test_download_dependency.sh
- scripts/pingcap/tidb/release-6.5-fips/pingcap_download_artifacts.sh
- scripts/pingcap/tiflow/release-6.5-fips/dm_download_integration_test_binaries.sh
- scripts/pingcap/tiflow/release-6.5-fips/ticdc_download_integration_test_binaries.sh
need download pd-ctl and pd-recover.
> fix: need download pd-ctl and pd-recover

- pipelines/pingcap/tidb/release-6.5-fips/ghpr_check2.groovy
> fix: update binary path

- pipelines/pingcap/tidb/release-6.5-fips/ghpr_build.groovy
- Remove Build plugins stage from ghpr_build.groovy file
- Remove Test plugin stage from ghpr_build.groovy file
> chore: Remove unnecessary build and test stages

- pipelines/pingcap/tiflash/latest/pull_build_and_integration_test.groovy
- pipelines/pingcap/tiflash/latest/pull_unit_test.groovy
- Remove unnecessary line from `pull_unit_test.groovy`
- Update file copying and exclusion in `pull_unit_test.groovy`
- Set git configuration and display git information in `pull_unit_test.groovy`
- Change ownership and extract files in `pull_unit_test.groovy`
- Modify file and remove unnecessary line in `pull_build_and_integration_test.groovy`
> fix:  update build and test pipeline for TiFlash

- scripts/ops/statics-repo-code-lines.ts
> feat(scripts/ops): add script to statics code line for repo

- scripts/ops/cherry_pick_pull.sh
This script is used to create a cherry pick pull request.
Usage:
```bash
./scripts/ops/cherry_pick_pull.sh upstream/release-7.5 98765
```
Thanks:
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md
- https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh
> feature(scripts/ops): add script `cherry_pick_pull.sh`

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
Update release-7.6 tikv cache image build.
> feat: update release-7.6 tikv cache image build

- pipelines/tikv/migration/latest/pod-pull_integration_kafka_test.yaml
* fix missing volume
* Use image with tini to avoid the problem of lsof getting stuck.
> fix(tikv/migration): fix missing volume

- jenkins/pipelines/cd/tiup-package-offline-mirror-dm.groovy
- jenkins/pipelines/cd/tiup/tiup_utils.groovy
- tiup 1.14 has bug, so we fix verison to avoid that
- 1.14.1 should publish its bug-fix on Jan.4th, but it delays
> fix: fix tiup verison to 1.13

- pipelines/pingcap/tidb/latest/ghpr_build.groovy
> chore: adjust timeout for build

- pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
> chore: increase cpu request on build

- jobs/pingcap/tidb/release-7.6/aa_folder.groovy
- jobs/pingcap/tidb/release-7.6/ghpr_build.groovy
- jobs/pingcap/tidb/release-7.6/ghpr_check.groovy
- jobs/pingcap/tidb/release-7.6/ghpr_check2.groovy
- jobs/pingcap/tidb/release-7.6/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-7.6/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-7.6/pull_br_integration_test.groovy
- jobs/pingcap/tidb/release-7.6/pull_lightning_integration_test.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_check.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.6/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.6/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-7.6/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-7.6/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-7.6/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-7.6/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/release-7.6/pod-pull_lightning_integration_test.yaml
- pipelines/pingcap/tidb/release-7.6/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-7.6/pull_lightning_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-release-7.6-presubmits.yaml
> feat(tidb): tidb split release 7.6 jobs

- jobs/pingcap/tiflow/release-7.6/aa_folder.groovy
- jobs/pingcap/tiflow/release-7.6/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-7.6/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-7.6/pull_cdc_integration_mysql_test.groovy
- jobs/pingcap/tiflow/release-7.6/pull_cdc_integration_pulsar_test.groovy
- jobs/pingcap/tiflow/release-7.6/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-7.6/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-7.6/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-7.6/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.6/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.6/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-7.6/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-7.6/pod-pull_cdc_integration_mysql_test.yaml
- pipelines/pingcap/tiflow/release-7.6/pod-pull_cdc_integration_pulsar_test.yaml
- pipelines/pingcap/tiflow/release-7.6/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-7.6/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-7.6/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.6/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-7.6/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_cdc_integration_mysql_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_cdc_integration_pulsar_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-7.6-presubmits.yaml
tiflow split release 7.6 jobs.
> feat(tiflow): tiflow split release 7.6 jobs

- pipelines/pingcap/tidb/release-7.6/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-7.6/pull_lightning_integration_test.groovy
* correct podtemplate file path
* correct test script name
> fix: correct podtemplate file path

- jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
download dumpling for inregration-tests instead of mydumper.
> fix(tidb-tools): download dumpling for inregration-tests instead of mydumper

- pipelines/pingcap/tiflow/release-7.1/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-7.5/ghpr_verify.groovy
Not upload to codecov on lts release branch.
> fix(tiflow): not upload to codecov on release branch

- jenkins/pipelines/cd/tiup-package-offline-mirror-dm.groovy
- jenkins/pipelines/cd/tiup/tiup_utils.groovy
> chore: upgrade tiup version

- pipelines/pingcap/tiproxy/latest/merged_mysql_test.groovy
`merged_mysql_test` in tiproxy is never run, I've updated the pipeline to be the same as others.
https://prow.tidb.net/log?job=pingcap/tiproxy/merged_mysql_test&id=1746725158531371013
> tiproxy: fix merged_mysql_test

- prow-jobs/pingcap-monitoring-periodics.yaml
> fix(monitoring): fix job step on fetch

- pipelines/pingcap/tiflash/latest/merged_unit_test.groovy
- pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
- pipelines/pingcap/tiflash/latest/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/latest/pull_unit_test.groovy
* Fix set CPU affinity failed in ut.
* Adjust cpu request from 12 to 16, the execution time of Ut has decreased from 27 minutes to 17 minutes.
> fix(tiflash): fix set CPU affinity failed in ut

- prow-jobs/pingcap-tidb-latest-periodics.yaml
Upload codecoverage to codecov in periodic ut task.
> feat(tidb): upload codecoverage to codecov in ut

- prow-jobs/pingcap-monitoring-periodics.yaml
> fix(pingcap/monitoring): fix step in update content jobs

- pipelines/pingcap/tiflash/release-7.5/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-7.5/pull_unit_test.groovy
- Fix environment variable `currentBuild.description`
> fix(tiflash ): correct env  currentBuild.description

- jobs/pingcap/tiflash/release-6.1/aa_folder.groovy
- jobs/pingcap/tiflash/release-6.1/pull_build_and_integration_test.groovy
- jobs/pingcap/tiflash/release-6.1/pull_unit_test.groovy
- jobs/pingcap/tiflash/release-6.5/aa_folder.groovy
- jobs/pingcap/tiflash/release-6.5/pull_build_and_integration_test.groovy
- jobs/pingcap/tiflash/release-6.5/pull_unit_test.groovy
- jobs/pingcap/tiflash/release-7.1/aa_folder.groovy
- jobs/pingcap/tiflash/release-7.1/pull_build_and_integration_test.groovy
- jobs/pingcap/tiflash/release-7.1/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-6.1/pod-pull_build.yaml
- pipelines/pingcap/tiflash/release-6.1/pod-pull_integration_test.yaml
- pipelines/pingcap/tiflash/release-6.1/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/release-6.1/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-6.1/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-6.5/pod-pull_build.yaml
- pipelines/pingcap/tiflash/release-6.5/pod-pull_integration_test.yaml
- pipelines/pingcap/tiflash/release-6.5/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/release-6.5/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-6.5/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-7.1/pod-pull_build.yaml
- pipelines/pingcap/tiflash/release-7.1/pod-pull_integration_test.yaml
- pipelines/pingcap/tiflash/release-7.1/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/release-7.1/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-7.1/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-7.5/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-7.5/pull_unit_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflash-release-6.1-presubmits.yaml
- prow-jobs/pingcap-tiflash-release-6.5-presubmits.yaml
- prow-jobs/pingcap-tiflash-release-7.1-presubmits.yaml
Add  tiflash other lts new pipelines
> feat(tiflash): tiflash add other lts new pipelines

- prow-jobs/pingcap-docs-cn-latest-presubmits.yaml
- prow-jobs/pingcap-docs-latest-presubmits.yaml
Correct job name to match jobdsl.
> fix(docs): correct job name to match jobdsl

- pipelines/tikv/migration/latest/pull_integration_kafka_test.groovy
- Wait Kafka ready before running tests
- Collect logs after test failed.
> tikv-migration: wait Kafka ready before test

- prow-jobs/pingcap-tiflow-latest-presubmits.yaml
skip ci on no-code pr for tiflow master  branch
> feat(tiflow): skip ci on no-code pr for tiflow master  branch

- prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.0-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.2-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.5-fips-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.1.0-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.3-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.4-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.5-presubmits.yaml
- prow-jobs/pingcap-tiflow-release-7.6-presubmits.yaml
skip ci on no-code pr for  toflow release branch.
> feat(tiflow): skip ci on no-code pr for  toflow release branch

- prow-jobs/pingcap-tiflow-latest-presubmits.yaml
skip ci on svg files for tiflow master branch
> feat(tiflow): skip ci on svg files for tiflow master branch

- pipelines/tikv/migration/latest/pull_integration_kafka_test.groovy
- pipelines/tikv/migration/latest/pull_integration_test.groovy
- pipelines/tikv/migration/latest/pull_unit_test.groovy
> debug(tikv/migration): print node info for debug

- pipelines/pingcap-inc/enterprise-extensions/latest/pod-pr-verify.yaml
- pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
- pipelines/pingcap-inc/enterprise-extensions/le-release-7.4/pod-pr-verify.yaml
- pipelines/pingcap-inc/enterprise-extensions/le-release-7.4/pr-verify.groovy
* update pod image
* print pr info in descrtion
> chore(enterprise-extension): update pod and add pr info in description

- pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy
- pipelines/pingcap-inc/enterprise-extensions/le-release-7.4/pod-pr-verify.yaml
- pipelines/pingcap-inc/enterprise-extensions/le-release-7.4/pr-verify.groovy
> fix(enterprise-extension): fix checkout not clean

- prow-jobs/pingcap-docs-cn-latest-presubmits.yaml
- prow-jobs/pingcap-docs-latest-presubmits.yaml
enable docs & docs-cn presubmit
> feat: enable docs & docs-cn presubmit

- jenkins/jobs/cd/release_tidb_master_tiup_nightly.groovy
> feat: disable nightly pipeline

- scripts/ops/create-issues-for-tidb-flaky-tests.ts
- scripts/ops/create-issues-for-tidb-slow-tests.ts
- scripts/ops/insight-the-pr.ts
currently just tested for `pingcap/tidb`
> feat(scripts/ops): add insight script for pull requests

- prow-jobs/pingcap-tidb-release-7.6-presubmits.yaml
branch: `feature/release-7.6-20240125`
it just need the build job.
> feat(prow-jbos): support for feature branch

- pipelines/pingcap/tidb/latest/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_build.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_build.groovy
changed for feature branches that based on trunk or release-7.1+ branches.
> opt(pingcap/tidb): skip test plugins for feature branches

- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
- no pcc and package for arm64
> fix: skip pcc and package for arm64

- scripts/ops/insight-the-pr.ts
> feat(scripts/ops): update insight script for PR

- prow-jobs/pingcap-tidb-release-6.1-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.5-fips-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml
- prow-jobs/pingcap-tidb-release-6.5-with-kv-timeout-feature-presubmits.yaml
skip ci on some images file change on  tidb lts 6.1 & 6.5
> feat(tidb): skip ci on some images file change on  tidb lts 6.1 & 6.5

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
skip ci on some images file change on tidb master.
> feat(tidb): skip ci on some images file change on tidb master

- pipelines/pingcap/tidb/latest/merged_build.groovy
- pipelines/pingcap/tidb/latest/merged_unit_test.groovy
update checkout param to ensure submodule update correctly
> fix: update checkout param to ensure submodule update correctly

- pipelines/pingcap/tidb/release-6.1/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-6.5/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.1/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-7.5/pod-ghpr_build.yaml
double build request resource to reduce build time.
> feat: double build request resource to reduce build time

- pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-5.3/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-5.4/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-6.1/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-6.5-fips/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-6.5/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.2/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.3/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_dm_compatibility_test.groovy
> fix(tiflow): fix archvie log file

- pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
> Revert "fix(tiflow): update pull_dm_compatibility_test.groovy"

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5-fips/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5-with-kv-timeout-feature/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_unit_test.groovy
> fix(pingcap/tidb): add timeout for event sending

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-community-postsubmits.yaml
- prow-jobs/pingcap-ng-monitoring-postsubmits.yaml
- prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml
- scripts/plugins/update-submodule.ts
> feat(pingcap/ng-monitoring): auto update submodule in monitoring

- prow-jobs/pingcap-inc-enterprise-extensions-postsubmits.yaml
- prow-jobs/pingcap-ng-monitoring-postsubmits.yaml
- scripts/plugins/update-submodule.ts
> fix(pingcap/monitoring): no need human approve for the submodule updating PR

- jobs/pingcap/tidb/latest/merged_integration_lightning_test.groovy
- pipelines/pingcap/tidb/latest/merged_integration_lightning_test.groovy
- pipelines/pingcap/tidb/latest/pod-merged_integration_lightning_test.yaml
- prow-jobs/pingcap-tidb-latest-postsubmits.yaml
add merged lightning pipeline.
> feat: add merged lightning pipeline

- prow-jobs/pingcap-tidb-latest-presubmits.yaml
If br ci is triggered, prevent pr merge if failure.
> feat: if br ci started, block pr merge if it failed

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
Using domestic sources to solve the failure of unstable network.
> fix: Using domestic sources to solve the failure of unstable network.

- jenkins/pipelines/cd/release-GA-v5-extra-packages.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0-hotfix.groovy
- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Fix CVE issues to enhance security
> fix(cd): bump etcd version from v3.4.21 to v3.4.30

- pipelines/tikv/tikv/latest/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/latest/pull_unit_test.groovy
- scripts/tikv/tikv/gen_test_binary_json.py
update tikv refactor ut to test.
> fix: update tikv refactor ut

- jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
Why:
- we've add PCC for all platform
> feat: add PCC for all platform

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-common-postsubmits.yaml
- scripts/pingcap/tidb/auto-handle-tidb-test-pr.py
Add postsubmit to auto merge tidb test pr.
When a TiDB PR is merged, if the TiDB-Test PR is specified in the title of this PR, automatically merge the dependent TiDB-Test PR.
> feat(tidb): add postsubmit to auto merge tidb test pr

- prow-jobs/pingcap-tidb-common-postsubmits.yaml
- scripts/pingcap/tidb/auto-handle-tidb-test-pr.py
Fix run scripts error on postsubmit job auto-handle-tidb-test-pr.
> fix: fix run scripts error

- pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-6.5/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_mysql_test.groovy
- prow-jobs/pingcap-tidb-common-postsubmits.yaml
* batch merge support specify tidb-test pr in  tidb pr title on lts branch
* auto merge dependent tidb-test pr after tidb pr merged on lts branch
> feat: batch merge support specify tidb-test pr in title

- prow-jobs/pingcap-tidb-latest-periodics.yaml
set randon timezone before run ut.
> feat: set randon timezone before run ut

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
*  add 8.0 tikv cache image build
*  remove 7.6 tikv cache image build
> feat: add 8.0 tikv cache image build

- jobs/pingcap/tidb/release-8.0/aa_folder.groovy
- jobs/pingcap/tidb/release-8.0/ghpr_build.groovy
- jobs/pingcap/tidb/release-8.0/ghpr_check.groovy
- jobs/pingcap/tidb/release-8.0/ghpr_check2.groovy
- jobs/pingcap/tidb/release-8.0/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-8.0/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-8.0/pull_br_integration_test.groovy
- jobs/pingcap/tidb/release-8.0/pull_lightning_integration_test.groovy
- pipelines/pingcap/tidb/release-8.0/ghpr_build.groovy
- pipelines/pingcap/tidb/release-8.0/ghpr_check.groovy
- pipelines/pingcap/tidb/release-8.0/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-8.0/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-8.0/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-8.0/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-8.0/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-8.0/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-8.0/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-8.0/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-8.0/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/release-8.0/pod-pull_lightning_integration_test.yaml
- pipelines/pingcap/tidb/release-8.0/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-8.0/pull_lightning_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-release-8.0-presubmits.yaml
> feat(tidb): tidb split release 8.0 jobs

- jobs/pingcap/tiflow/release-8.0/aa_folder.groovy
- jobs/pingcap/tiflow/release-8.0/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_mysql_test.groovy
- jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_pulsar_test.groovy
- jobs/pingcap/tiflow/release-8.0/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-8.0/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-8.0/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-8.0/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.0/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-8.0/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_pulsar_test.yaml
- pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-8.0/pod-pull_cdc_integration_test.yaml
- pipelines/pingcap/tiflow/release-8.0/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-8.0/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-8.0/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_pulsar_test.groovy
- pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-8.0/pull_cdc_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.0/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-8.0/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.0/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-8.0-presubmits.yaml
split tiflow release-8.0 jobs.
> feat(tiflow): tiflow split release 8.0 jobs

- jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
* daily internal build add release-8.0
* remove dmr 7.6 build
> feat: daily internal build add release-8.0

- prow-jobs/pingcap-monitoring-periodics.yaml
> feat(pingcap/monitoring): add update job

- jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
- jenkins/pipelines/qa_release_test.groovy
update qa test reupload tar-file path
> fix: update qa test reupload tar file path

- jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
update old cdc pipeline for qa-release-test.
> fix: update old pipeline for qa-release-test

- jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
> fix: disable old pd pipelines

- jenkins/jobs/ci/tikv/tikv/ghpr_integration_cdc_test.groovy
Fix jobdsl config on job tikv_ghpr_integration_cdc_test.
> fix: fix jobdsl config

- tools/check_artifact/check_artifact.sh
> feature(tools/check_artifacts): support  gather and check result for RC

- pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
- pipelines/pingcap/docs-cn/latest/pod-merged_update_docs_cn.yaml
- pipelines/pingcap/docs/latest/merged_update_docs.groovy
- pipelines/pingcap/docs/latest/pod-merged_update_docs.yaml
fix git checkout fail due to git version on docs postsubmit.
> fix: fix git checkout fail due to git version

- jenkins/pipelines/cd/multibranch/build_tiflash_multi_branch.groovy
remove useless webhook for notify on tiflash multi-branch.
> chore: remove useless webhook for notify

- jenkins/jobs/ci/qa/archive_image_binary_to_minio.groovy
> fix: update pipeline groovy path

- tools/check_artifact/check_artifact.sh
> fix(tools/check_artifacts): limit the version grep

- scripts/artifacts/delete_qiniu.py
- scripts/artifacts/list_qiniu.py
- scripts/artifacts/upload_qiniu.py
> feat(scripts/artifacts): add qiniu object list and delete scripts

- scripts/artifacts/check-tiup.sh
- it will validate with origin oci artifacts' git sha.
- it will validate the publish time and platforms.
> feat(scripts/artifacts): add check tiup script

- pipelines/pingcap/tidb/latest/pod-merged_integration_python_orm_test.yaml
Update docker image to avoid accidental cleaning of temporary paths.
> fix: update python orm image

- scripts/artifacts/check-tiup.sh
- scripts/artifacts/tag-rc2ga-on-repos.sh
> fix(scripts/artifacts): add taging for oci artifacts

- pipelines/pingcap/tidb/latest/merged_integration_lightning_test.groovy
releate to https://github.com/pingcap/tidb/pull/52289
> chore: change lightning ci dir

- pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
- pipelines/pingcap/tiflash/latest/pod-pull_integration_test.yaml
- pipelines/pingcap/tiflash/latest/pod-pull_unit-test.yaml
update tiflash image in master to use clang17
> chore: update tiflash refactor ci  image in master branch

- scripts/pingcap/add-placeholder-version-in-readme.ts
Usage:
```bash
deno run --allow-all scripts/pingcap/add-version-placeholder-readme.ts --owner <owner> --github_private_token <token> --repo <repo> --branch master --placeholder 8.2.0-alpha --draft
```
> feat(scripts/pingcap): add deno script `add-placeholder-version-in-readme.ts`

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
* add 8.1 tikv cache image build
* remove 8.0 tikv cache image build
> feat: add 8.1 tikv cache image build

- prow-jobs/pingcap-monitoring-periodics.yaml
> chore(prow-jobs): update periodic job for monitoring

- jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
* daily internal build add release-8.1
* remove dmr 8.0 build
> feat: daily internal build add release-8.1

- jobs/pingcap/tidb/release-8.1/aa_folder.groovy
- jobs/pingcap/tidb/release-8.1/ghpr_build.groovy
- jobs/pingcap/tidb/release-8.1/ghpr_check.groovy
- jobs/pingcap/tidb/release-8.1/ghpr_check2.groovy
- jobs/pingcap/tidb/release-8.1/ghpr_mysql_test.groovy
- jobs/pingcap/tidb/release-8.1/ghpr_unit_test.groovy
- jobs/pingcap/tidb/release-8.1/pull_br_integration_test.groovy
- jobs/pingcap/tidb/release-8.1/pull_lightning_integration_test.groovy
- pipelines/pingcap/tidb/release-8.1/ghpr_build.groovy
- pipelines/pingcap/tidb/release-8.1/ghpr_check.groovy
- pipelines/pingcap/tidb/release-8.1/ghpr_check2.groovy
- pipelines/pingcap/tidb/release-8.1/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-8.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-8.1/pod-ghpr_build.yaml
- pipelines/pingcap/tidb/release-8.1/pod-ghpr_check.yaml
- pipelines/pingcap/tidb/release-8.1/pod-ghpr_check2.yaml
- pipelines/pingcap/tidb/release-8.1/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/release-8.1/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tidb/release-8.1/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/release-8.1/pod-pull_lightning_integration_test.yaml
- pipelines/pingcap/tidb/release-8.1/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/release-8.1/pull_lightning_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tidb-release-8.1-presubmits.yaml
> feat(tidb): tidb split release 8.1 jobs

- jobs/pingcap/tiflow/release-8.1/aa_folder.groovy
- jobs/pingcap/tiflow/release-8.1/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-8.1/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-8.1/pull_cdc_integration_mysql_test.groovy
- jobs/pingcap/tiflow/release-8.1/pull_cdc_integration_pulsar_test.groovy
- jobs/pingcap/tiflow/release-8.1/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-8.1/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-8.1/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-8.1/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.1/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-8.1/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-8.1/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-8.1/pod-pull_cdc_integration_mysql_test.yaml
- pipelines/pingcap/tiflow/release-8.1/pod-pull_cdc_integration_pulsar_test.yaml
- pipelines/pingcap/tiflow/release-8.1/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-8.1/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-8.1/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-8.1/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_mysql_test.groovy
- pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_pulsar_test.groovy
- pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-8.1/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-8.1/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.1/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-tiflow-release-8.1-presubmits.yaml
Split tiflow release-8.1 jobs.
> feat(tiflow): tiflow split release 8.1 jobs

- pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
- pipelines/pingcap/tiflash/latest/pull_unit_test.groovy
- pipelines/tikv/tikv/latest/pull_unit_test.groovy
> chore: print pr info in pipelinerun

- jobs/tikv/tikv/release-6.1/aa_folder.groovy
- jobs/tikv/tikv/release-6.1/pull_unit_test.groovy
- jobs/tikv/tikv/release-6.5/aa_folder.groovy
- jobs/tikv/tikv/release-6.5/pull_unit_test.groovy
- jobs/tikv/tikv/release-7.1/aa_folder.groovy
- jobs/tikv/tikv/release-7.1/pull_unit_test.groovy
- jobs/tikv/tikv/release-7.5/aa_folder.groovy
- jobs/tikv/tikv/release-7.5/pull_unit_test.groovy
- jobs/tikv/tikv/release-8.1/aa_folder.groovy
- jobs/tikv/tikv/release-8.1/pull_unit_test.groovy
- pipelines/tikv/tikv/release-6.1/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-6.1/pull_unit_test.groovy
- pipelines/tikv/tikv/release-6.5/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-6.5/pull_unit_test.groovy
- pipelines/tikv/tikv/release-7.1/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-7.1/pull_unit_test.groovy
- pipelines/tikv/tikv/release-7.5/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-7.5/pull_unit_test.groovy
- pipelines/tikv/tikv/release-8.1/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-8.1/pull_unit_test.groovy
add pipeline for tikv refactor ut  in lts branch.
> feat: add pipeline for tikv refactor ut  in lts branch

- jenkins/jobs/ci/qa/qa_release_br_integration_test.groovy
- jenkins/jobs/ci/qa/qa_release_lightning_integration_test.groovy
- jenkins/pipelines/qa/qa-release-br-integration-test.groovy
- jenkins/pipelines/qa/qa-release-lightning-integration-test.groovy
add two qa-release-test pipeline.
support br and lightning integration tests in release-8.1 branch.
> feat: add two qa-release-test pipeline

- pipelines/qa/qa-release-br-integration-test.groovy
- pipelines/qa/qa-release-lightning-integration-test.groovy
checkout code with tags in qa-release-test pipelines.
> fix: checkout with tags

- prow-jobs/tikv-tikv-latest-presubmits.yaml
Make tikv ut on master ready:
* enable pipeline status report
* enable always_run
> feat(tikv): make tikv ut on master ready

- pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
- pipelines/pingcap/docs/latest/merged_update_docs.groovy
- prow-jobs/pingcap-docs-cn-postsubmits.yaml
- prow-jobs/pingcap-docs-postsubmits.yaml
enable upload pdf and context report.
> feat(docs&docs-cn): enable upload pdf and context report

- pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
- pipelines/pingcap/docs/latest/merged_update_docs.groovy
print branch info in docs merged pipeline.
> chore(docs&docs-cn): print branch info in docs merged pipeline

- jobs/pingcap/docs-tidb-operator/aa_folder.groovy
- jobs/pingcap/docs-tidb-operator/latest/merged_update.groovy
- pipelines/pingcap/docs-tidb-operator/latest/merged_update.groovy
- pipelines/pingcap/docs-tidb-operator/latest/pod-merged_update.yaml
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-docs-tidb-operator-postsubmits.yaml
add docs tidb operator merged pipeline.
> feat(docs-tidb-operator): add docs tidb operator merged pipeline

- jenkins/pipelines/ci/tikv/tikv_ghpr_coverage.groovy
NOTE: This pr uses a patched grcov version(https://github.com/glorv/grcov/tree/patched) to allow grcov to ignore some corrupted raw profile files. 
Replay result is: https://ci.pingcap.net/blue/organizations/jenkins/cron_tikv_ghpr_coverage/detail/cron_tikv_ghpr_coverage/631/pipeline
> tikv: run coverage test with nextest and ignore corrupted profile files

- pipelines/tikv/tikv/release-6.5/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-7.1/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-7.5/pod-pull_unit_test.yaml
- pipelines/tikv/tikv/release-8.1/pod-pull_unit_test.yaml
reduce cpu request to 6 core on tikv new ut
> chore(tikv): reduce cpu request to 6 core on tikv ut

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
Ref: https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
> fix(old-cd): workaround cargo fetching failure for git type crates

- scripts/ops/statics-repo-code-lines.ts
- scripts/pingcap/add-placeholder-version-in-readme.ts
> fix(scripts/pingcap): fix regexp in file add-placeholder-version-in-readme.ts

- pipelines/pingcap/docs-tidb-operator/latest/merged_update.groovy
- prow-jobs/pingcap-docs-tidb-operator-postsubmits.yaml
enable pdf upload and pipeline context report.
> chore(docs-tidb-operator): enable pdf upload and pipeline context report

- scripts/ops/parse-jenkins-build-log/main.py
- scripts/ops/parse-jenkins-build-log/requirements.txt
add scripts parse jenkins build log.
> feat(scripts): add scripts parse jenkins build log

- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
- jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
- jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
bump nightly version to v8.2.0-alpha.
> chore: bump nightly version to v8.2.0-alpha

- jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
use tidb server failpoint in old ci
> fix(br): use failpoint tidb-server instead

- scripts/pingcap/add-placeholder-version-in-readme.ts
> fix(scripts/pingcap): fix script of adding version placeholder

- scripts/artifacts/check-images-internal.sh
It can not check the delivery results for external registries.
> feat(scripts/aritfacts): add scripts to check internal images

- prow-jobs/pingcap-tiflash-latest-presubmits.yaml
Enable report and trigger on tiflash master new pipeline.
> feat: enable report and trigger on tiflash master new pipeline

- prow-jobs/pingcap-ng-monitoring-postsubmits.yaml
> fix(pingcap/ng-monitoring): fix the base_ref arg for create pull request on pingcap/monitoring

- jenkins/jobs/ci/tiflash/ghpr_build.groovy
- jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
- jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
disable old pipeline trigger on tiflash master.
> feat: disable old pipeline trigger on tiflash master

- pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-6.1/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-6.5/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-7.1/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-7.5/pull_integration_test.groovy
correct the dir to collect log.
> fix(tiflash): correct the dir to collect log

- prow-jobs/kustomization.yaml
- prow-jobs/tikv-community-postsubmits.yaml
> feat(tikv/*): add job to sync prow OWNERS files

- prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml
- prow-jobs/pingcap-tiproxy-latest-presubmits.yaml
Apply pre-submit and post-submit prow-jobs all to all branches of TiProxy.
> chore(tiproxy): apply prow-jobs to all branches

- scripts/pingcap/community/update-prow-owners.ts
> fix(scripts/pingcap/community): add sign-off in commit message

- jenkins/pipelines/cd/atom-jobs/products/tiflash/master.groovy
- jenkins/pipelines/cd/dev-build.groovy
- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
- jenkins/pipelines/cd/pre-release-community-docker-rocky.groovy
- jenkins/pipelines/cd/pre-release-enterprise-docker-rocky.groovy
- pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
- pipelines/pingcap/tidb/latest/pull_tiflash_test.groovy
They are compatible with the old locations.
> refactor(jenkins/pipelines,pipelines): use the new dockerfile url location

- pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
- pipelines/pingcap/docs-tidb-operator/latest/merged_update.groovy
- pipelines/pingcap/docs/latest/merged_update_docs.groovy
Maybe company firewall has forbidden the hosts.
Ref: https://jhooq.com/pip-install-connection-error/#1-root-cause-of-the-problem
> fix(pingcap/*docs*): fix pip3 install issue

- jenkins/pipelines/cd/atom-jobs/docker-common.groovy
- jenkins/pipelines/cd/atom-jobs/products/tiflash/master.groovy
- jenkins/pipelines/cd/dev-build.groovy
- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
- jenkins/pipelines/cd/pre-release-community-docker-rocky.groovy
- jenkins/pipelines/cd/pre-release-enterprise-docker-rocky.groovy
- pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
- pipelines/pingcap/tidb/latest/pull_tiflash_test.groovy
> Revert "refactor(jenkins/pipelines,pipelines): use the new dockerfile url location"

- pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
- pipelines/pingcap/docs-cn/latest/pod-merged_update_docs_cn.yaml
- pipelines/pingcap/docs/latest/merged_update_docs.groovy
- pipelines/pingcap/docs/latest/pod-merged_update_docs.yaml
update to image with pre install python3 packages
> fix(docs&docs-cn): update to image with pre install python3 packages

- jenkins/pipelines/ci/ticdc/engine_ghpr_integration_test.groovy
- jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
> chore: update deprecated domain name

- jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
- prow-jobs/tikv/pd/release-6.1-presubmits.yaml
> feat(tikv-pd): use prow style job in 6.1

- pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy
- pipelines/pingcap/tidb/latest/pull_lightning_integration_test.groovy
ignore file changed when collect log file
> chore: ignore file changed when collect log file

- prow-jobs/ti-community-infra/prow/postsubmits.yaml
- prow-jobs/ti-community-infra/prow/presubmits.yaml
to gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-test-infra
> fix(ti-community-infra/prow): bump job images

- prow-jobs/pingcap/tidb-tools/presubmits.yaml
fix tidb-tools presubmit config
> fix: fix tidb-tools presubmit config

- jenkins/jobs/ci/tidb-tools/ghpr_integration_test.groovy
- jenkins/jobs/ci/tidb-tools/ghpr_unit_test.groovy
add jobdsl for old tidb-tools pipeline
> feat: add jobdsl for old tidb-tools pipeline

- jenkins/jobs/ci/tidb-tools/ghpr_integration_test.groovy
- jenkins/jobs/ci/tidb-tools/ghpr_unit_test.groovy
> fix: add missing conf on joddsl

- jenkins/jobs/ci/tidb-tools/ghpr_integration_test.groovy
- jenkins/jobs/ci/tidb-tools/ghpr_unit_test.groovy
- pipelines/pingcap/tidb-tools/latest/pull_verify.groovy
- prow-jobs/pingcap/tidb-tools/presubmits.yaml
enable new tidb-tools pipelines
> feat(pingcap/tidb-tools): enable new tidb-tools pipelines

- jobs/pingcap/tidb/release-8.2/pull_common_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_e2e_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_br_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_common_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_copr_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_ddl_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_jdbc_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_lightning_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_mysql_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_nodejs_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_integration_python_orm_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_mysql_client_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_sqllogic_test.groovy
- jobs/pingcap/tidb/release-8.2/pull_tiflash_test.groovy
fix jobdsl error
___
Bug fix
___
- Fixed incorrect closing quote in `scriptPath` string across multiple Groovy files.
- Ensured consistency and correctness in pipeline job definitions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><details><summary>14 files</summary><table>
<tr>
<td>
<details>
<summary><strong>pull_common_test.groovy</strong><dd><code>Fix incorrect closing quote in scriptPath</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
jobs/pingcap/tidb/release-8.2/pull_common_test.groovy
- Fixed incorrect closing quote in `scriptPath` string.
</details>
</td>
<td><a …
> fix: fix jobdsl error

- scripts/artifacts/check-tiup.sh
> Revert "fix(scripts/artifacts): workaround tikv amd64 building hang problem"

- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
Build tiflash with rust cargo cache in nightly build.
> chore: build tiflash with rust cargo cache

- tools/list-rust-dependencies/list.ts
> feat(tools/list-rust-dependencies): add script to list rust dependencies to csv

- pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy
do not cache the third party bin in prepare stage.
> fix(pingcap/tidb): fix the cache too large problem

- pipelines/pingcap/tidb/release-6.6/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.0/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.4/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-8.0/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/release-8.1/ghpr_mysql_test.groovy
mysql-test support batch merge if some pr title specify tidb-test PR number.
> fix(pingcap/tidb): mysql-test support batch merge in 8.1

- prow-jobs/pingcap/tidb/common-postsubmits.yaml
support auto-handle tidb-test merge in more branches.
> chore: support auto-handle in more branches

- jobs/pingcap/tidb/release-7.1/pull_common_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_e2e_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_integration_common_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_integration_copr_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_integration_ddl_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_integration_jdbc_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_integration_mysql_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_sqllogic_test.groovy
- jobs/pingcap/tidb/release-7.1/pull_tiflash_test.groovy
- jobs/pingcap/tidb/release-8.1/pull_common_test.groovy
- pipelines/pingcap/tidb/release-7.1/pod-pull_common_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_e2e_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_integration_common_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_integration_copr_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_integration_ddl_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_integration_jdbc_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_integration_mysql_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_sqllogic_test.yaml
- pipelines/pingcap/tidb/release-7.1/pod-pull_tiflash_test.yaml
- pipelines/pingcap/tidb/release-7.1/pull_common_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_e2e_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_integration_common_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_integration_copr_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_integration_ddl_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_integration_jdbc_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_integration_mysql_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_sqllogic_test.groovy
- pipelines/pingcap/tidb/release-7.1/pull_tiflash_test.groovy
- prow-jobs/pingcap/tidb/release-7.1-presubmits.yaml
add presubmit pipelines on 7.1
> feat: add presubmit pipelines on 7.1

- pipelines/pingcap/tidb/release-8.1/pull_integration_nodejs_test.groovy
- pipelines/pingcap/tidb/release-8.2/pull_integration_nodejs_test.groovy
- pipelines/pingcap/tidb/release-8.3/pull_integration_ddl_test.groovy
- pipelines/pingcap/tidb/release-8.3/pull_integration_jdbc_test.groovy
- pipelines/pingcap/tidb/release-8.3/pull_integration_nodejs_test.groovy
increase timeout for nodejs test
> chore: increase timeout for nodejs test

- pipelines/pingcap/tiflash/release-6.1/pod-pull_build.yaml
- pipelines/pingcap/tiflash/release-6.1/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/release-6.1/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-6.1/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-6.5/pod-pull_build.yaml
- pipelines/pingcap/tiflash/release-6.5/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/release-6.5/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-6.5/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-7.1/pod-pull_build.yaml
- pipelines/pingcap/tiflash/release-7.1/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/release-7.1/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-7.1/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-7.5/pod-pull_build.yaml
- pipelines/pingcap/tiflash/release-7.5/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/release-7.5/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-7.5/pull_unit_test.groovy
update image and fix pod yaml path of tiflash lts branches.
> chore: update image of tiflash new pipelines

- scripts/artifacts/check-images-internal.ts
> fix(scripts/artifacts): add checks for enterprise images

- jenkins/jobs/ci/tidb-tools/ghpr_integration_test.groovy
- jenkins/jobs/ci/tidb-tools/ghpr_unit_test.groovy
> chore: enable pipeline of tidb-tools

- pipelines/pingcap/tiflash/latest/pod-pull_build.yaml
- pipelines/pingcap/tiflash/latest/pod-pull_integration_test.yaml
- pipelines/pingcap/tiflash/latest/pod-pull_unit-test.yaml
- pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
- pipelines/pingcap/tiflash/latest/pull_unit_test.groovy
> Revert "fix: not to set jnlp conf in pod file"

- pipelines/pingcap/tiproxy/latest/ghpr_build.groovy
- pipelines/pingcap/tiproxy/latest/ghpr_check.groovy
- pipelines/pingcap/tiproxy/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_common_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_nodejs_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_python_orm_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_integration_ruby_orm_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_mysql_connector_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_mysql_test.groovy
- pipelines/pingcap/tiproxy/latest/pull_sqllogic_test.groovy
Print PR info in pipeline details
> feat(tiproxy): print pr info in pipeline details

- jenkins/jobs/ci/tiflash/ghpr_build.groovy
- jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
- jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
- jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy
- prow-jobs/pingcap/tiflash/release-7.1-presubmits.yaml
- prow-jobs/tikv/tikv/release-7.1-presubmits.yaml
Swtich to use new pipeline trigger by prow in tikv & tiflash branch release-7.1
> feat: switch to use new pipeline trigger by prow in branch 7.1

- jenkins/jobs/ci/tiflash/ghpr_build.groovy
- jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
- jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
- jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy
disable old jobs trigger on feature branch
> fix(tiflash&tikv): disable old jobs trigger on feature branch

- pipelines/pingcap/tidb/latest/canary-ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
- prow-jobs/pingcap/tidb/latest-presubmits-canary.yaml
> refactor(canary): use new base ci image

- jobs/pingcap/tidb/latest/merged_unit_test_ddlv1.groovy
- pipelines/pingcap/tidb/latest/merged_unit_test_ddlv1.groovy
- prow-jobs/pingcap/tidb/latest-postsubmits.yaml
Add another merged ddlv1 ut pipeline, Currently in the testing phase, we need to observe the stability of the test.
> feat(tidb): add another merged ddlv1 ut pipeline

- pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml
> opt: use mirror to download bazel

- pipelines/tikv/pd/latest/pod-ghpr_build.yaml
- pipelines/tikv/pd/latest/pod-pull_integration_copr_test.yaml
- pipelines/tikv/pd/latest/pod-pull_integration_realcluster_test.yaml
- pipelines/tikv/pd/latest/pod-pull_unit_test.yaml
pd master bump go version to 1.23
> feat(pd): pd master bump go version to 1.23

- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_build.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_common_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_common_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_jdbc_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_mysql_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_nodejs_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_python_orm_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_mysql_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_common_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_jdbc_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_mysql_connector_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_mysql_test.yaml
- pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_ruby_orm_test.yaml
tidb-test master bump go version to 1.23
> feat(tidb-test): tidb-test master bump go version to 1.23

- jenkins/pipelines/cd/atom-jobs/build-common.groovy
- jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
- jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy
multi-branch build on  master bump go version to 1.23
> feat(build): multi-branch build on  master bump go version to 1.23

- pipelines/pingcap/tiproxy/latest/pod-ghpr_build.yaml
- pipelines/pingcap/tiproxy/latest/pod-ghpr_check.yaml
- pipelines/pingcap/tiproxy/latest/pod-ghpr_unit_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_common_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_jdbc_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_nodejs_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_python_orm_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_integration_ruby_orm_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_mysql_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-merged_sqllogic_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_common_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_jdbc_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_nodejs_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_python_orm_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_integration_ruby_orm_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_mysql_connector_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_mysql_test.yaml
- pipelines/pingcap/tiproxy/latest/pod-pull_sqllogic_test.yaml
tiproxy master bump go version to 1.23
> feat(tiproxy): tiproxy master bump go version to 1.23

- jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
* add 8.4 tikv cache image build
* remove 8.3 tikv cache image buildv
> feat: add cache image build for 8.4

- prow-jobs/pingcap/monitoring/periodics.yaml
switch cron job to next release branch
> chore(pingcap/monitoring): update periodics.yaml

- jenkins/jobs/cd/release_all_images_by_branch_for_internal.groovy
- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
- jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
- jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
- jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy
> feat: support build for v8.4

- jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
fix for nighlty build on tidb-binlog
> chore: fix for nighlty build  on tidb-binlog

- scripts/pingcap/community/update-prow-owners.ts
Also add `cherry-pick-approved` label when the pull request is created for release branch.
> fix(scripts/pingcap/community): fix /update-prow-owners.ts

- jenkins/jobs/ci/tiflash/ghpr_build.groovy
- jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
- jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
- jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy
- prow-jobs/pingcap/tiflash/release-6.5-presubmits.yaml
- prow-jobs/tikv/tikv/release-6.5-presubmits.yaml
Swtich to use new pipeline trigger by prow in  tiflash & tikv branch release-6.5
> feat(tiflash & tikv): switch to use new pipeline trigger by prow in branch 7.1

- pipelines/pingcap/tiflash/latest/pod-merged_build.yaml
- pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
set readyonly to false to update cache in nfs.
> fix(tiflash): set readonly to false to update cache in nfs

- pipelines/pingcap/tiflash/latest/merged_build.groovy
- pipelines/pingcap/tiflash/latest/merged_unit_test.groovy
enable ccache save in merged pipelines
> fix(tiflash): enable ccache save in merged pipelines

- jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
Remove building bench_dbms in debug mode by design.
> chore(tiflash): remove building bench_dbms in master

- jobs/pingcap/tiflow/release-8.5/aa_folder.groovy
- jobs/pingcap/tiflow/release-8.5/ghpr_verify.groovy
- jobs/pingcap/tiflow/release-8.5/pull_cdc_integration_kafka_test.groovy
- jobs/pingcap/tiflow/release-8.5/pull_cdc_integration_mysql_test.groovy
- jobs/pingcap/tiflow/release-8.5/pull_cdc_integration_pulsar_test.groovy
- jobs/pingcap/tiflow/release-8.5/pull_cdc_integration_storage_test.groovy
- jobs/pingcap/tiflow/release-8.5/pull_dm_compatibility_test.groovy
- jobs/pingcap/tiflow/release-8.5/pull_dm_integration_test.groovy
- jobs/pingcap/tiflow/release-8.5/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.5/ghpr_verify.groovy
- pipelines/pingcap/tiflow/release-8.5/pod-ghpr_verify.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-merged_unit_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-pull_cdc_integration_kafka_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-pull_cdc_integration_mysql_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-pull_cdc_integration_pulsar_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-pull_cdc_integration_storage_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-pull_dm_integration_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pod-pull_engine_integration_test.yaml
- pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_mysql_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_pulsar_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_storage_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_dm_compatibility_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_dm_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_engine_integration_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap/tiflow/release-8.5-presubmits.yaml
split release 8.5 jobs for tiflow.
> feat(tiflow): split release 8.5 jobs for tiflow

- OWNERS_ALIASES
- prow-jobs/tikv/raft-engine/OWNERS
- prow-jobs/tikv/raft-engine/presubmits.yaml
> feat(tikv/raft-engine): enable ci for raft-engine

- scripts/ops/release-check-version/main.py
Disable fail fast for image check, support exiting after error summarization
> feat: disable fail fast for image check

- prow-jobs/pingcap/tidb/latest-presubmits.yaml
Enable trigger for tidb pull-integration-e2e-test.
> feat(tidb): enable trigger for tidb pull-integration-e2e-test

- pipelines/pingcap/tiflow/release-6.5-20241101-v6.5.7/pod-pull_dm_compatibility_test.yaml
- pipelines/pingcap/tiflow/release-6.5-20241101-v6.5.7/pull_dm_compatibility_test.groovy
Compatible with the Go version requirements on the base branch.
> fix(tiflow): compatible with the Go version requirements on the base branch.

- scripts/flow/ga/create-patch-release-branches.ts
Create release branche `release-X.Y.Z` when released vX.Y.Z TiDB version for these repos:
- `tidb-test`
- `enterprise-plugin`
> feat(scripts/flow/ga): add GA flow script for create patch release branches on some repos

- jobs/pingcap/tidb/release-8.1/pull_integration_tidb_tools_test.groovy
- pipelines/pingcap/tidb/release-8.1/pod-pull_integration_tidb_tools_test.yaml
- pipelines/pingcap/tidb/release-8.1/pull_integration_tidb_tools_test.groovy
- prow-jobs/pingcap/tidb/release-8.1-presubmits.yaml
add tidb-tools integration test for qa-release-test.
> feat(qa-release-test): add tidb-tools integration test for qa-release-test

- jobs/pingcap/tidb/latest/pull_integration_python_orm_test.groovy
- pipelines/pingcap/tidb/latest/pod-pull_integration_python_orm_test.yaml
- pipelines/pingcap/tidb/latest/pull_integration_python_orm_test.groovy
add python orm test pipeline in master verify
> feat: add python orm test in master verify

- scripts/flow/ga/create_github_release.ts
- scripts/flow/rc/check-images-internal.ts
- scripts/flow/rc/check-tiup.ts
Solve the github api limit problem by passing github private token
> fix(scripts/flow/rc): fix artifacts check scripts

- jenkins/jobs/ci/tiflash/ghpr_build.groovy
- jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
- jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
- jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy
disable trigger for all lts and hotfix branch
> chore: disable trigger for all lts and hotfix branch

- scripts/pingcap/community/update-prow-owners.ts
> fix(scripts): fix script to sync OWNERS file

- prow-jobs/pingcap/tidb/latest-presubmits-canary.yaml
> fix(pingcap/tidb): fix canary job triggers

- libraries/tipipeline/vars/component.groovy
Support the hotfix branches and release feature branches for peer components:
- Expect return regular release branches:
- release-X.Y             => release-X.Y
- feature/release-X.Y-abc => release-X.Y
- feature_release-X.Y-abc => release-X.Y
- Expect return patch release branches for special components:
- release-6.1-20230101-v6.1.2 => release-6.1.2
- feature/release-8.1.1-abcdefg => release-8.1.1
- feature_release-8.1.1-abcdefg => release-8.1.1
- Expect return trunk branch for regular feature branches:
- feature/abcd => `<trunk branch>`
- feature_abcd => `<trunk branch>`
> fix(libraries): enhance the base global method `computeBranchFromPR`

- pipelines/pingcap/tiflash/release-6.1/pod-pull_integration_test.yaml
- pipelines/pingcap/tiflash/release-6.5/pod-pull_integration_test.yaml
bump docker dind versin to 20.10.24.
> fix: bump docker dind versin to 20.10.24

- libraries/tipipeline/vars/component.groovy
> chore(libraries): rename params and local vars

- prow-jobs/tikv/tikv/latest-presubmits.yaml
- prow-jobs/tikv/tikv/release-6.1-presubmits.yaml
- prow-jobs/tikv/tikv/release-6.5-presubmits.yaml
- prow-jobs/tikv/tikv/release-7.1-presubmits.yaml
- prow-jobs/tikv/tikv/release-7.5-presubmits.yaml
- prow-jobs/tikv/tikv/release-8.1-presubmits.yaml
- prow-jobs/tikv/tikv/release-8.2-presubmits.yaml
- prow-jobs/tikv/tikv/release-8.3-presubmits.yaml
- prow-jobs/tikv/tikv/release-8.4-presubmits.yaml
- prow-jobs/tikv/tikv/release-8.5-presubmits.yaml
> opt(tikv/tikv): save CI resources for none-code changes

- prow-jobs/pingcap/tidb/release-8.5-presubmits.yaml
> feat(pingcap/tidb): support run ci tasks on release feature branches for v8.5

- jobs/pingcap/tiflow/latest/periodics_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/latest/periodics_cdc_integration_kafka_test.groovy
- pipelines/pingcap/tiflow/latest/pod-periodics_cdc_integration_kafka_test.yaml
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap/tiflow/latest-periodics.yaml
Add periodics pipeline for cdc kafka test
> feat(tiflow): add periodics pipeline for cdc kafka test

- pipelines/pingcap/tiflow/latest/periodics_cdc_integration_kafka_test.groovy
- prow-jobs/pingcap/tiflow/latest-periodics.yaml
* Correct periodics pipeline  job name of cdc test.
> fix(tiflow): tiflow periodics pipeline fix

- pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
- pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
- pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_br_integration_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_integration_ddl_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_lightning_integration_test.yaml
- pipelines/pingcap/tidb/latest/pod-pull_mysql_client_test.yaml
upgrade ci base image from centos7 to rocky linux 8 because centos7 end of life.
> feat(tidb): update base image to rocky linux8

- prow-jobs/pingcap/tidb/common-postsubmits.yaml
Auto handle tidb-test pr support feature branch like `feature/release-X.Y-xxxxxx`
> chore: auto handle tidb-test pr support feature branch

- pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
- pipelines/pingcap/tidb/latest/pull_integration_mysql_test.groovy
Correct script parameter passing in rocky8.
> fix(tidb): correct script parameter passing

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap-qe/ee-apps/presubmits.yaml
> feat(pingcap-qe/ee-apps): add a scan job `pull-scan-deps`

- prow-jobs/pingcap-qe/ee-apps/presubmits.yaml
> fix(pingcap-ee-apps): fix the limits and requests for scan job

- OWNERS
- OWNERS_ALIASES
- prow-jobs/pingcap-qe/ee-apps/presubmits.yaml
also update OWNERS_ALIASES and OWNERS files
> chore: update scan dep job

- prow-jobs/pingcap-qe/ee-apps/presubmits.yaml
> refactor(pingcap-qe/ee-apps): concurrently run the scan jobs

- scripts/artifacts/tag-rc2ga-on-repos.sh
- scripts/flow/ga/check-image-delivery.ts
> feat(scripts/flow/ga): add script check-image-delivery.ts

- pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.2/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.3/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.4/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.5/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-7.6/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.0/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.1/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.2/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.3/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.4/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_engine_integration_test.groovy
- pipelines/pingcap/tiflow/release-8.5/pull_engine_integration_test_centos.groovy
Engine image set go env GOTOOLCHAIN=auto to auto download latest go toolchain.
> fix(tiflow): engine image set go env GOTOOLCHAIN=auto

- scripts/flow/rc/check-images-internal.ts
- scripts/flow/rc/check-tiup.ts
- add a timeout with 5 seconds for github api request, and fallback to "" to result.
- update the check order for repos, the most problem repo is `pingcap/monitoring`.
> fix(scripts/flow/rc): fix rc scripts for github api request quota

- scripts/flow/sprint/create_github_alpha_tags.ts
The building trigger will be implemented in the next PR.
> feat(script/flow/sprint): add create_github_alpha_tags.ts

- pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/latest/merged_unit_test.groovy
- pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.5/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-7.6/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-8.0/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-8.1/ghpr_unit_test.groovy
- pipelines/pingcap/tidb/release-8.2/pull_unit_test.groovy
- pipelines/pingcap/tidb/release-8.3/pull_unit_test.groovy
- pipelines/pingcap/tidb/release-8.4/pull_unit_test.groovy
- pipelines/pingcap/tidb/release-8.5/pull_unit_test.groovy
> fix(pipelines/pingcap/tidb): fix when conditions for pulls size

- prow-jobs/pingcap/tidb/latest-periodics.yaml
Executed daily pipeline every night at 10 PM UTC.
> chore(tidb): executed every night at 10 PM UTC

- prow-jobs/kustomization.yaml
- prow-jobs/pingcap/ticdc/latest-presubmits.yaml
Add build and unit-test task to prow job.
> feat(ticdc): add new ticdc presubmit config

- prow-jobs/pingcap/ticdc/latest-presubmits.yaml
> feat(ticdc): add check pipeline

- prow-jobs/pingcap/ticdc/latest-presubmits.yaml
Set these pipelines as required checks before merging Pull Requests.
> feat(ticdc): make ut and check required

- jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/tikv/pd/release-5.4-presubmits.yaml
> refactor(tikv/pd): move build job to prow style job

- prow-jobs/tikv/tikv/latest-presubmits.yaml
> fix(prow-jobs/tikv/tikv): fix the shell step

- pipelines/pingcap/tiflow/release-8.1/pod-pull_cdc_integration_kafka_test.yaml
ref https://github.com/PingCAP-QE/ci/pull/3208
> fix(ticdc): update env for debezium test

- jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_build.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml
> refactor(pingcap/tidb-binlog): refactor build job to prow style

- prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml
> refactor(pingcap/tidb-binlog): refactor unit-test job to prow style

- prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml
> Revert "refactor(pingcap/tidb-binlog): refactor integration-test job to prow style"

- prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml
currently it has no test steps, but we implemented the sidecar containers for it.
ref #3342
> feat(pingcap/tidb-binlog): add integration test job

- scripts/pingcap/tiflow/download_test_binaries_by_tag.sh
Add script support download binary by tag, this is a preparation PR to support the Hotfix branch with precise version dependencies.
> feat(tiflow): script support download binary by tag

- prow-jobs/pingcap/tidb/release-6.1-presubmits.yaml
- prow-jobs/pingcap/tidb/release-6.5-presubmits.yaml
- prow-jobs/pingcap/tidb/release-7.1-presubmits.yaml
- prow-jobs/pingcap/tidb/release-8.1-presubmits.yaml
- prow-jobs/pingcap/tidb/release-8.5-presubmits.yaml
Support trigger on branch like feature/release-8.1-xxx
> feat(tidb): presubmit branch trigger match feature branch on 8.1 

- jenkins/jobs/cd/devbuild.groovy
build job add ticdc-newarch choice
> feat(dev-build): build job add ticdc-newarch choice

- pipelines/pingcap/ticdc/latest/pull_cdc_mysql_integration_heavy.groovy
- pipelines/pingcap/ticdc/latest/pull_cdc_mysql_integration_light.groovy
Remove unnecessary test build in cdc mysql integration
> chore(ticdc): remove unnecessary test build

- pipelines/pingcap/ticdc/latest/pull_cdc_mysql_integration_heavy.groovy
- pipelines/pingcap/ticdc/latest/pull_cdc_mysql_integration_light.groovy
Disable failfast for new ticdc wip pipeline
> chore(ticdc): disable failfast for new ticdc  wip pipeline

- scripts/ops/release-check-version/check_offline_package.py
support for differences in tidb-dashboard across different branches.
> chore(check-release-version):  support for differences in tidb-dashboard across different branches

- prow-jobs/pingcap/tidb/release-6.1-presubmits.yaml
- prow-jobs/pingcap/tidb/release-6.5-presubmits.yaml
- prow-jobs/pingcap/tidb/release-7.1-presubmits.yaml
- prow-jobs/pingcap/tidb/release-8.1-presubmits.yaml
- prow-jobs/pingcap/tidb/release-8.5-presubmits.yaml
- prow-jobs/pingcap/tiflash/release-6.1-presubmits.yaml
- prow-jobs/pingcap/tiflash/release-6.5-presubmits.yaml
- prow-jobs/pingcap/tiflash/release-7.1-presubmits.yaml
- prow-jobs/pingcap/tiflash/release-7.5-presubmits.yaml
- prow-jobs/pingcap/tiflash/release-8.1-presubmits.yaml
- prow-jobs/pingcap/tiflash/release-8.5-presubmits.yaml
- prow-jobs/pingcap/tiflow/release-6.1-presubmits.yaml
- prow-jobs/pingcap/tiflow/release-6.5-presubmits.yaml
- prow-jobs/pingcap/tiflow/release-7.1-presubmits.yaml
- prow-jobs/pingcap/tiflow/release-7.5-presubmits.yaml
- prow-jobs/pingcap/tiflow/release-8.1-presubmits.yaml
- prow-jobs/pingcap/tiflow/release-8.5-presubmits.yaml
- prow-jobs/tikv/tikv/release-6.1-presubmits.yaml
- prow-jobs/tikv/tikv/release-6.5-presubmits.yaml
- prow-jobs/tikv/tikv/release-7.1-presubmits.yaml
- prow-jobs/tikv/tikv/release-7.5-presubmits.yaml
- prow-jobs/tikv/tikv/release-8.1-presubmits.yaml
- prow-jobs/tikv/tikv/release-8.5-presubmits.yaml
Update trigger to match two hotfix with same tag in same day,
branch examples:
1. release-7.1-20250117-v7.1.3
2. release-7.1-20250117-v7.1.3-1
> feat(prow-trigger):  update trigger to match two hotfix with same tag in same day

- jobs/tikv/pd/release-7.5/aa_folder.groovy
- jobs/tikv/pd/release-7.5/ghpr_build.groovy
- jobs/tikv/pd/release-7.5/pull_integration_copr_test.groovy
- jobs/tikv/pd/release-8.5/aa_folder.groovy
- jobs/tikv/pd/release-8.5/ghpr_build.groovy
- jobs/tikv/pd/release-8.5/pull_integration_copr_test.groovy
- pipelines/tikv/pd/release-7.5/ghpr_build.groovy
- pipelines/tikv/pd/release-7.5/pod-ghpr_build.yaml
- pipelines/tikv/pd/release-7.5/pod-pull_integration_copr_test.yaml
- pipelines/tikv/pd/release-7.5/pull_integration_copr_test.groovy
- pipelines/tikv/pd/release-8.5/ghpr_build.groovy
- pipelines/tikv/pd/release-8.5/pod-ghpr_build.yaml
- pipelines/tikv/pd/release-8.5/pod-pull_integration_copr_test.yaml
- pipelines/tikv/pd/release-8.5/pull_integration_copr_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/tikv/pd/latest-presubmits.yaml
- prow-jobs/tikv/pd/release-6.5-presubmits.yaml
- prow-jobs/tikv/pd/release-7.1-presubmits.yaml
- prow-jobs/tikv/pd/release-7.5-presubmits.yaml
- prow-jobs/tikv/pd/release-8.5-presubmits.yaml
To facilitate better maintenance and updates in the future, separate pipelines will be used for the two LTS branches.
> refactor(pd): split 7.5 and 8.5 lts jobs

- libraries/tipipeline/vars/component.groovy
Update the function to support the new beta release branches. The beta release branch style is "release-X.Y-beta.M".
> feat(libraries/tipipeline): update function `component.computeBranchFromPR

- scripts/flow/build/versioning-strategy.md
- scripts/flow/build/versioning-strategy.test.ts
- scripts/flow/build/versioning-strategy.ts
> refactor(scripts/flow/build): update the versioin strategy about pre logics

- prow-jobs/pingcap-inc/enterprise-extensions/postsubmits.yaml
- prow-jobs/pingcap/community/postsubmits.yaml
- prow-jobs/pingcap/monitoring/periodics.yaml
- prow-jobs/pingcap/ng-monitoring/postsubmits.yaml
- prow-jobs/pingcap/tidb/common-postsubmits.yaml
- prow-jobs/tikv/community/postsubmits.yaml
This pull request includes several updates across multiple `postsubmits.yaml` and `periodics.yaml` files. The changes primarily focus on updating the Deno image versions, modifying the command formatting, and adjusting branch regex patterns for better compatibility.
* Updated the Deno image version from `1.45.5` to `2.2.2` and reformatted the command structure in `prow-jobs/pingcap-inc/enterprise-extensions/postsubmits.yaml`.
* Applied the same Deno image version update and command reformatting in `prow-jobs/pingcap/community/postsubmits.yaml`.
* Similarly updated the Deno image version and command structure in `prow-jobs/pingcap/ng-monitoring/postsubmits.yaml`. [[1]](diffhunk://#diff-9df894993d59fb9e4cd03fbfeebbac188222f962cfd57dfefcad718f7d832c51L15-R20) …
> feat: update auto flow jobs for release 9.x

- jobs/pingcap/ticdc/release-9.0-beta/aa_folder.groovy
- jobs/pingcap/ticdc/release-9.0-beta/pull_cdc_mysql_integration_heavy.groovy
- jobs/pingcap/ticdc/release-9.0-beta/pull_cdc_mysql_integration_light.groovy
- pipelines/pingcap/ticdc/release-9.0-beta/pod-pull_cdc_mysql_integration_heavy.yaml
- pipelines/pingcap/ticdc/release-9.0-beta/pod-pull_cdc_mysql_integration_light.yaml
- pipelines/pingcap/ticdc/release-9.0-beta/pull_cdc_mysql_integration_heavy.groovy
- pipelines/pingcap/ticdc/release-9.0-beta/pull_cdc_mysql_integration_light.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap/ticdc/release-9.0-beta-presubmits.yaml
Add ticdc jobs on branch release-9.0-beta.1, support branch like release-9.0-beta.x
> feat(ticdc): add ticdc jobs on branch release-9.0-beta.1

- prow-jobs/pingcap/ticdc/latest-presubmits.yaml
Remove wip on context of mysql it pipeline.
> chore(tiflow): remove wip on context of mysql it pipeline

- prow-jobs/pingcap/docs/docs-latest-presubmits.yaml
add trigger for release-cloud branch in presubmits configuration.
> feat(prow-jobs/docs): add trigger for release-cloud branch in presubmits configuration

- README.md
- Updated the introduction to provide a comprehensive overview of the repository's purpose.
- Enhanced the organization of CI pipeline components and repository structure with detailed descriptions and diagrams.
- Added sections on modifying and testing pipelines, including a step-by-step guide and workflow diagram.
- Clarified the file structure and naming conventions for Prow jobs, Jenkins jobs, and pipelines.
- Included links to relevant directories for easier navigation.
> docs(README): Revise and expand CI/CD documentation for clarity and structure

- scripts/ops/release-check-version/check_info.py
Support beta & rc version check for new branch name(example release-9.0-beta.1).
> feat(release-check-version): support beta & rc version check

- prow-jobs/tikv/copr-test/latest-presubmits.yaml
Enable test pipeline trigger and report
> feat(tikv/copr-test): enable test pipeline trigger and report

- prow-jobs/pingcap-qe/ci/periodics.yaml
> Revert "refactor(prow-jobs/pingcap-qe/ci): switch from Ubuntu/pixi to Alpine/uv for crawl jobs"

- pipelines/pingcap/tidb/latest/pull_integration_e2e_test.groovy
> fix(pingcap/tidb): update binary download script to use computed branch name

- libraries/tipipeline/vars/component.groovy
Ignore the inherited params for cherry-picked pull requests.
> fix(libraries): enhance the `computeBranchFromPR` method

- pipelines/pingcap/tidb/latest/pull_lightning_integration_test.groovy
update to support feature branch
> fix(tidb/lightning): update to support feature branch

- jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy
> fix(pingcap/tiflash): update TiFlash builder image for old daily job

- jobs/pingcap/tidb/latest/periodics_tidb_next_gen_smoke_test.groovy
- pipelines/pingcap/tidb/latest/periodics_tidb_next_gen_smoke_test.groovy
- pipelines/pingcap/tidb/latest/pod-periodics_tidb_next_gen_smoke_test.yaml
- prow-jobs/pingcap/tidb/latest-periodics.yaml
add smoke test prow job for tidb next gen
> feat(tidb/next-gen): add smoke test prow job for tidb next gen

- pipelines/pingcap/tidb/latest/pod-periodics_tidb_next_gen_smoke_test.yaml
increase resource limits for smoke test job
> chore(pipelines/pingcap/tidb): increase resource limits for smoke test job

- pipelines/pingcap/tidb/latest/periodics_tidb_next_gen_smoke_test.groovy
update tidb next gen smoke test pipeline
> fix(tidb/next-gen): update tidb next gen smoke test pipeline

- prow-jobs/pingcap-inc/tici/presubmits.yaml
And increase resource limits to 2 CPU + 8Gi RAW
> fix(prow-jobs/pingcap-inc/tici): enable devtoolset-10 

- jobs/pingcap/tidb/latest/pull_next_gen_real_tikv_test.groovy
- pipelines/pingcap/tidb/latest/pod-pull_next_gen_real_tikv_test.yaml
- pipelines/pingcap/tidb/latest/pull_next_gen_real_tikv_test.groovy
- prow-jobs/kustomization.yaml
- prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml
add new pipeline for  next gen real tikv test
> feat(pingcap/tidb): add new pipeline for  next gen real tikv test

- scripts/flow/rc/check-images-internal.ts
Remove checks of syncing images to 'qa' project in registry.
> refactor(scripts/flow/rc): simplify image validation and mapping structure

- scripts/flow/ga/collect-info-for-release-issue.sh
- scripts/ops/analysis-approvals-for-changes-of-files.ts
This pull request introduces two significant changes: the addition of a script to automate the collection of release issue information and a script to analyze approvals for changes to specific files in repositories. These changes aim to streamline release management and approval tracking processes.
* Added `collect-info-for-release-issue.sh` to generate release-related information, including repository tags, release links, and diffs between the current and previous releases. This script simplifies the process of preparing release issues by automating the collection of relevant data.
* Added `analysis-approvals-for-changes-of-files.ts` to analyze file changes in repositories and identify associated pull requests and their approvers. It uses the Octokit library to interact with GitHub APIs …
> chore(scripts): add release ref script and analyze approvals script

- prow-jobs/pingcap/docs/docs-cn-latest-presubmits.yaml
- prow-jobs/pingcap/docs/docs-latest-presubmits.yaml
* Add support for temp branch  https://github.com/pingcap/docs/tree/support-azure
> feat(prow-jobs): add support-azure branch to presubmit configuration

- prow-jobs/pingcap-inc/tici/presubmits.yaml
Relate to PR https://github.com/PingCAP-QE/artifacts/pull/623.
Update test image.
> chore(tici): update test image

- pipelines/pingcap/tiflash/latest/pull_integration_next_gen.groovy
Related PR on tiflash repo: https://github.com/pingcap/tiflash/pull/10189
> chore(pipelines/pingcap/tiflash): Update the integration tests of next-gen tiflash

- prow-jobs/tikv/pd/latest-presubmits.yaml
- prow-jobs/tikv/pd/release-6.1-presubmits.yaml
Also refactor anchors in release-6.1 build job for clarity.
Ref #3541
> feat(tikv/pd): add next-gen build and unit test presubmits for pd master

- prow-jobs/tikv/pd/latest-presubmits.yaml
- Add pull-build and pull-unit-test jobs using Kubernetes agent
- Update resource requests and limits for build and test jobs
- Remove deprecated Jenkins pull_unit_test job
> feat(prow-jobs/tikv/pd): add Kubernetes jobs for build and unit test

- jobs/pingcap/tidb/latest/pull_integration_e2e_test_next_gen.groovy
- pipelines/pingcap/tidb/latest/pull_integration_e2e_test_next_gen/pipeline.groovy
- pipelines/pingcap/tidb/latest/pull_integration_e2e_test_next_gen/pod.yaml
- prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml
- prow-jobs/pingcap/tidb/latest-presubmits.yaml
- scripts/artifacts/download_pingcap_oci_artifact.sh
> feat(pingcap/tidb): add tidb next gen job `pull_integration_e2e_test_next_gen`

- pipelines/pingcap/ticdc/release-9.0-beta/pull_cdc_mysql_integration_light.groovy
Updated the branch reference in the MySQL integration pipeline script to ensure proper handling of the base reference for component branches.
> fix(pingcap/ticdc): correct branch reference in MySQL integration test

- pipelines/pingcap/tidb/latest/pull_integration_e2e_test_next_gen/pipeline.groovy
- prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml
remove debug info stage and update artifact download logic
- Remove the 'Debug info' stage to streamline the pipeline
- Update artifact download to include tikv-worker and move version checks to the test stage
> fix(pingcap/tidb): fix job `pull_integration_e2e_test_next_gen` job

- prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml
fix go -race in tidb operator e2e test
> fix go -race in tidb operator e2e test

- prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml
- change timeout from 45m to 2h
- use `--proc` to run make e2e
> change timeout to 2h and use --proc to run tidb operator e2e

- prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml
- pull-check-next-gen
- pull-mysql-test-next-gen
- pull-mysql-client-test-next-gen
- pull_integration_e2e_test_next_gen
> chore(pingcap/tidb): comment out skip_if_only_changed for unready presubmits jobs

- prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml
> Remove memory limit for operator e2e

- jenkins/pipelines/cd/dev-build.groovy
This pull request introduces a semantic version comparison function to the `dev-build.groovy` pipeline script, improving the accuracy of version checks when selecting Dockerfiles. The main change replaces a simple string comparison with a proper semantic version comparator, ensuring correct ordering for versions with pre-release and patch information.
Version comparison improvements:
* Added a `semverCompare` closure to accurately compare semantic version strings, including handling of pre-release and patch metadata.
* Updated the Dockerfile selection logic to use `semverCompare` instead of a string comparison, ensuring correct behavior for versions such as `v6.5.12` and above.
> fix(jenkins/pipelines/cd): use new base images since v6.5.12

- pipelines/pingcap/tidb/latest/pull_unit_test_next_gen/pipeline.groovy
This pull request makes two main changes to the TiDB unit test pipeline configuration. First, it removes the "Debug info" stage to streamline the pipeline and reduce unnecessary output. Second, it introduces a temporary hack to modify test configuration files, disabling the "fail fast" behavior in unit tests to allow tests to continue running after failures.
Pipeline simplification:
* Removed the `Debug info` stage, which previously printed environment information and performed network checks, to streamline the pipeline and reduce noise.
Test configuration adjustments:
* Added a step to temporarily modify `.bazelrc` and `Makefile` to disable "fail fast" for unit tests by setting `--flaky_test_attempts=1` and replacing `--test_keep_going=false` with `-k`, allowing more tests to run even if …
> chore(pingcap/tidb): add temporary UT fail fast hacks for next-gen

- prow-jobs/pingcap/ticdc/latest-presubmits.yaml
- prow-jobs/pingcap/tidb/latest-presubmits.yaml
- prow-jobs/pingcap/tiflow/latest-presubmits.yaml
- prow-jobs/tikv/pd/latest-presubmits.yaml
Officially effective error log review check in go based repos: pingcap/tidb , pingcap/tiflow , pingcap/ticdc, tikv/pd. 
For PRs with error changes, approval from any member of the error log approvers is required to proceed with the PR merge.
> chore(presubmits): officially effective error log review check in go based repos

- prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml
for job `pull-integration-realcluster-test-next-gen`
> fix(pingcap/tidb): make integration test optional and update context

- prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml
Reverts PingCAP-QE/ci#3720
prow pcm and check config have been updated: 
* pcm upadte https://github.com/PingCAP-QE/ee-ops/pull/1638
* checkconfig update https://github.com/PingCAP-QE/ci/pull/3722
> fix(operator): fix e2e ci job of tidb operator

- prow-jobs/pingcap/ticdc/latest-presubmits.yaml
For jobs:
- pull-build
- pull-check
> refactor(prow-jobs/pingcap/ticdc): migrate the run cluster to default gcp cluster

- prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml
> Revert "feat(prow-jobs/pingcap/tidb-operator): update pull-e2e job"

- prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml
update pull-e2e job to make job required.
> feat(pingcap/tidb-operator): update pull-e2e job to make job required

- pipelines/pingcap/tidb/latest/pull_br_integration_test_next_gen/pipeline.groovy
- pipelines/pingcap/tidb/latest/pull_integration_e2e_test_next_gen/pipeline.groovy
- Add `FILE_SERVER_URL` env and pass to download_tools.sh
> feat(pingcap/tidb): update ci job `pull_br_intergration_test_next_gen`

- prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml
> chore:  "Revert "Remove dind-daemon initContainer configuration""

- pipelines/pingcap/tidb/latest/pull_integration_realcluster_test_next_gen/pipeline.groovy
- pipelines/pingcap/tiflash/latest/pull_integration_next_gen.groovy
- pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
- pipelines/pingcap/tiflash/latest/pull_unit_next_gen.groovy
- pipelines/pingcap/tiflash/latest/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-8.5/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-8.5/pull_unit_test.groovy
- pipelines/pingcap/tiflash/release-9.0-beta/pull_integration_test.groovy
- pipelines/pingcap/tiflash/release-9.0-beta/pull_unit_test.groovy
This pull request standardizes and updates the cache key naming conventions across multiple pipeline Groovy files for TiFlash and TiDB projects. The changes primarily aim to unify cache key prefixes (e.g., replacing `tiflash` and `tiflash-next-gen` with `binary` or `ng-binary`) to improve cache management and consistency across different pipelines and environments.
**Cache key naming standardization:**
* Updated TiFlash integration and unit test pipelines to use the `binary` prefix for cache keys instead of `tiflash`, across release branches `release-8.5`, `release-9.0-beta`, and `latest`. This affects both build and test cache steps. [[1]](diffhunk://#diff-68854d1a3b7109cd070fd473690ed2404d1d96c64cb969c04801076f0ec81c4bL61-R64) [[2]](diffhunk://#diff-68854d1a3b7109cd070fd473690ed2404d1d96 …
> chore(pipelines): update cache keys for TiFlash and TiDB pipelines

- prow-jobs/pingcap-inc/enterprise-plugin/presubmits.yaml
remove backticks from loading-test.log in echo message
> fix(prow-jobs/pingcap-inc/enterprise-plugin): fix pull-build job
