jenkins/pipelines/tikv_ghpr_test.groovy

update tikv pipeline

---

jenkins/pipelines/tikv_ghpr_test.groovy

remove prost test from PR, will do it in nightly

remove prost

---

jenkins/pipelines/tikv_ghpr_integration_ddl_test.groovy

Add tikv_ghpr_integraion_ddl_test

Add tikv_ghpr_integraion_ddl_test

---

sync_ci/pkg/parser/regex_rules.json
sync_ci/pkg/parser/regex_rules_test.go

According to 2020-12-10's failure jobs, modify this two rules.

refine: two rules

---

sync_ci/pkg/command/sync_ci.go
sync_ci/pkg/detect/detect.go
sync_ci/pkg/server/server.go
sync_ci/pkg/util/connections.go
sync_ci/pkg/util/log.go

1. add util package
2. modify zone to Asia/Shanghai

Refine org and time

---

sync_ci/pkg/parser/regex_rules.json
sync_ci/pkg/parser/regex_rules_test.go
sync_ci/pkg/parser/rules_test/pd_build_failed.log

add: new rule

---

sync_ci/SQLs/views.sql

fix: bug in dashboard that caused one rerun job displayed multiple times.

fix: view bug

---

sync_ci/pkg/parser/envrules.json
sync_ci/pkg/parser/regex_rules.json
sync_ci/pkg/parser/regex_rules_test.go
sync_ci/pkg/parser/rules.go
sync_ci/pkg/parser/rules_test.go

[[fatal] run test [type_time] err: sql:SELECT TIME('1000009:10:10.1999999999999');: failed to run query](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/29979/pipeline/)

add ci rules

---

sync_ci/pkg/parser/regex_rules.json
sync_ci/pkg/parser/regex_rules_test.go
sync_ci/pkg/parser/rules_test/tidb_ghpr_check_2.log
sync_ci/pkg/parser/rules_test/tidb_ghpr_mybatis_case_error.log
sync_ci/pkg/parser/rules_test/tidb_ghpr_unit_test_build_error.log
sync_ci/pkg/parser/rules_test/tidb_ghpr_unit_test_build_error2.log

Namely
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/64465/pipeline/
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/64472/pipeline/
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/73449/pipeline
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_mybatis/detail/tidb_ghpr_mybatis/29332

Add rules for unknown failure before 2021.2.3

---

sync_ci/Jenkinsfile

Require a native go installed in `/usr/local/go/`
Plugin Credential Binding have to be available.
Update: Ok, it is fully tested and successfully deployed. Ready to merge.

Add Jenkinsfile for CI

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy

Migrate lightning grafana dashboard and alert rules to br repo.

tiup: migrate lightning grafana dashboard and alert rules to br repo

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

Enable to using branch in build

Enable to using branch or tag when build in `optimization release tidb`

---

jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup_utils.groovy

extarct download tiup and qshell function to an util file

extract some util function

---

jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy

Using common install tiup pipeline

Extract common install TiUP

---

jenkins/Dockerfile/centos7_golang-1.13_cached
jenkins/Dockerfile/centos7_golang-1.13_java_cached
jenkins/Dockerfile/centos7_golang-1.13_rust_cached

Remove image download lightning

remove image download lightning

---

jenkins/pipelines/cd/build-arm-image.groovy

In old days, some line was comment, now bring it back

make arm image online

---

jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

add throw exception

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
jenkins/pipelines/tikv_ghpr_test.groovy

Signed-off-by: Andy Lok <andylokandy@hotmail.com>
Fix ci error in https://github.com/tikv/tikv/pull/9802

Upload .so of dylib crate during testing

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
jenkins/pipelines/tikv_ghpr_test.groovy

Revert "Upload .so of dylib crate during testing"

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
jenkins/pipelines/tikv_ghpr_test.groovy

Signed-off-by: Andy Lok <andylokandy@hotmail.com>
Refer: https://github.com/PingCAP-QE/ci/pull/105

Upload .so in dylib crate during testing (take 2)

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
jenkins/pipelines/tikv_ghpr_test.groovy

Revert "Upload .so in dylib crate during testing (take 2)"

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

今天这两个 PR 可千万不能像 4.0.12 那样给自己合了哦[捂脸][捂脸][捂脸]
好
以后是不是都不要自己合并
嗯嗯，都不自动合并吧
好的
还是周老师或其他老师通知可以合并 + 我手动合并吧
嗯嗯
这样比较保险一点
10:20
好，我看以前还专门做了这种任务哈哈

remove tigger merge docs

---

jenkins/pipelines/ci/tics/tics_ghpr_test.groovy

默认点开链接（或者直接从github的状态跳转的链接），显示的是有问题的；
需要再重新点一下 Parallel， 才能显示正常。
有问题的 job：https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tics_ghpr_test/detail/tics_ghpr_test/4343/pipeline

refine-tics-test

---

jenkins/pipelines/cd/tiup/tiup_utils.groovy

fix util function

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Remove race test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Add race test to run on new jenkins ci.

Add race test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

This reverts commit f5ec4b8cd9794ad8f43fd3bb76804073895348e0.

Revert "Add race test (#135)"

---

jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy

Make tidb linux amd all build job run in parallel , reduce build time

Make tidb linux amd all build job run in parallel

---

jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy

Fix a bug: when build tidb and tidb plugins, remove deleteDir when start build plugins.

Fix bug when build tidb & plugins, tidb src not exist

---

jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy

Fix bug, surround the deleteDir with node is necessary.

surround the deleteDir with node

---

jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy

Get tidb code from nfs cache, fix tiflash clone error

 Tidb get code from nfs-cache, fix tiflash clone error

---

jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy

Make arm64 build job in parallel to save time.

Make arm64 build in parallel

---

jenkins/pipelines/cache-go-module.groovy
jenkins/pipelines/update-code.groovy

Cache code and go module to reduce ci time.

Cache code and go module

---

jenkins/pipelines/ci/br/br_check_release_note.groovy
jenkins/pipelines/ci/br/br_ghpr_build.groovy
jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

add br ghpr pipeline

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
sync_ci/api/swagger.yaml

The machine deployed by sync-ci has been changed from 172.16.5.13 to 172.16.5.25, so the job upload information address needs to be changed

fix sync-ci analysis-res is null

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-amd.groovy

let tikv / importer / tiflash and other repo build in parallel. some job build in mac-i7.

Make all build in mac to parallel

---

jenkins/Dockerfile/centos7_golang-1.16

image: cadmusjiang/centos7_golang-1.16
run cmd:docker run -d  --privileged=true cadmusjiang/centos7_golang-1.16 /usr/sbin/init
exec cmd:docker exec -it ${containerID} /bin/bash

add centos7_golang-1.16 Dockerfile

---

jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy

Correct logic error, skip build if build cache existed

fix bug: logic error, skip build if build cache existed

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

Let tikv test use memory volume.

tikv use test-slave-with-memvolume

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

set `export CARGO_INCREMENTAL=0` to disable incremental build

Disable  incremental build

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

Patch tikv fix slave

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-amd.groovy

Correct login error, if build cache exist then skip build. 
Build tiflash on mac with i5.

Patch2 darwin build parallel

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_build.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_check.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Add ticdc ci pipeline, migration from cdc repo.

Add ticdc ci pipeline

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tikv/tikv_master_test_coverage.groovy

add tikv coverage pipeline, hide credential for codecov

add tikv coverage pipeline, hide credential

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Make "Race Test Chunk 7 DDL-Other" about 1 minute faster.

pipelines/ci/tidb: speed up ddl test with race

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Make running "Race Test Chunk 7 DDL-Other" about 1 minute faster.
related to #190

pipelines/ci/tidb: speed up ddl test with race in main

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

master and 5.x use go1.16, other use go1.13

---

jenkins/Dockerfile/centos7_golang-1.16

add git tool to golang image

---

jenkins/Dockerfile/centos7_golang-1.16

change git version from v1.8 to v2.22

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

release-5.x use go1.13 now

---

jenkins/pipelines/ci/importer/importer_ghpr_build.groovy
jenkins/pipelines/ci/importer/importer_ghpr_test.groovy

Add importer ci pipeline

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Signed-off-by: guo-shaoge <shaoge1994@163.com>

split executor cases into 2 jobs

---

jenkins/pipelines/ci/tidb/tidb_check_release_note.groovy
jenkins/pipelines/ci/tidb/tidb_check_title.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

upgrade node go version: from 1.13 to 1.16

upgrade node go version: from 1.13 to 1.16

---

jenkins/Dockerfile/centos7_golang-1.16

add sqllogic repo cache

---

jenkins/pipelines/cd/nightly/release_br_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_cdc_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_dm_ansible_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_dm_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_mydumper_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_tidb-operator-nightly.groovy
jenkins/pipelines/cd/nightly/release_tidb-tools_docker_nightly.groovy
jenkins/pipelines/cd/nightly/release_tidb_binlog_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_tidb_enterprise_nightly.groovy
jenkins/pipelines/cd/nightly/release_tidb_enterprise_tools_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_tidb_tools_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_tispark_master-nightly.groovy

Migrate pipeline script from jenkins to github

add release nightly pipeline

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy
jenkins/pipelines/cd/optimization-release-tidb.groovy

- Build importer before real tag was set.
- Build tikv using PR before real tag was set.
- Fix jenkins bool prameter issues.

optimization release workflow

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy
jenkins/pipelines/cd/optimization-release-tidb.groovy

Revert "optimization release workflow"

---

jenkins/pipelines/ci/tidb/tidb_check_release_note.groovy
jenkins/pipelines/ci/tidb/tidb_check_title.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Remove shard library for github quota limit， all tidb ci block for quota limit

Remove shard library for github quota limit

---

jenkins/pipelines/ci/pd/pd_check_release_note.groovy
jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
jenkins/pipelines/ci/pd/pd_ghpr_integration_compatibility_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_integration_lightning_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_intergration_common_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_intergration_ddl_test.groovy
jenkins/pipelines/ci/pd/pd_test.groovy

upgrade pd ci go version: from 1.13 to 1.16.4

patch pd upgrade go

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

select the specific test script for upstream

BR: add upstream(tikv/tidb/pd) support

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

- add dm ci pipeine
- dm ci upgrade go version from 1.13 to 1.16.4, branch master only

add dm ci pipeline, upgrade go version

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

Correct pod go docker image for go1.16.4

correct go docker image

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy
jenkins/pipelines/cd/optimization-release-tidb.groovy

Revert "Revert "optimization release workflow""

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_build_new3.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_check.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_unit_test.groovy

binlog ci upgrade go version from 1.13 to 1.16.4, branch master only

binlog ci upgrade go version from 1.13 to 1.16.4, branch master only

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_build.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_check.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy

ticdc ci upgrade go version from 1.13 to 1.16.4, branch master only

ticdc ci upgrade go version from 1.13 to 1.16.4, branch master only

---

jenkins/pipelines/ci/br/br_ghpr_build.groovy
jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

br ci upgrade go version from 1.13 to 1.16.4, branch master only

br ci upgrade go version from 1.13 to 1.16.4, branch master only

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_build.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_check.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy

Reverts PingCAP-QE/ci#230
- go1.16 image need to install pip

Revert "ticdc ci upgrade go version from 1.13 to 1.16.4, branch master only"

---

jenkins/Dockerfile/centos7_golang-1.16

patch go1160 image

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_build.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_check.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy

Reverts PingCAP-QE/ci#233
- go1160 image already add python-pip

Revert "Revert "ticdc ci upgrade go version from 1.13 to 1.16.4, branch master only""

---

jenkins/pipelines/cd/qa/build-binlog.groovy
jenkins/pipelines/cd/qa/build-br.groovy
jenkins/pipelines/cd/qa/build-dm.groovy
jenkins/pipelines/cd/qa/build-image.groovy
jenkins/pipelines/cd/qa/build-monitor.groovy
jenkins/pipelines/cd/qa/build-pd.groovy
jenkins/pipelines/cd/qa/build-ticdc.groovy
jenkins/pipelines/cd/qa/build-tidb.groovy
jenkins/pipelines/cd/qa/build-tiflash.groovy
jenkins/pipelines/cd/qa/build-tikv-client-c-builder.groovy
jenkins/pipelines/cd/qa/build-tikv.groovy
jenkins/pipelines/cd/qa/task-build-nightly.groovy

Signed-off-by: mahjonp <junpeng.man@gmail.com>
merge from https://github.com/zyguan/qa/tree/jenkins and make a little update

add qa_build scripts

---

jenkins/pipelines/ci/importer/importer_ghpr_build.groovy
jenkins/pipelines/ci/importer/importer_ghpr_test.groovy

importer upgrade gcc from 4.8.5 to 8.3.1

importer upgrade gcc: 4.8.5 to 8.3.1

---

jenkins/pipelines/nightly/tidb/tidb_nightly_unit_test.groovy

add race/leek unit tests run on nightly

add nightly unit tests

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy

add tidb br test pipeline

---

jenkins/pipelines/qa_release_test.groovy

qa-release-test supports pr on tikv

qa-release-test supports pr on tikv

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

dm release-2.0 upgrade go version from 1.13 to 1.16.4

dm release-2.0 upgrade go version from 1.13 to 1.16.4

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

- always dump stack
- check whether library exists

tiny refinement

---

jenkins/pipelines/cd/multibranch/build_binlog_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_br_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_dm_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_dumpling_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_lightning_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_ctl_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy
jenkins/pipelines/cd/nightly/build-darwin-amd64-4.0.groovy
jenkins/pipelines/cd/nightly/build-linux-arm64-4.0.groovy
jenkins/pipelines/cd/nightly/release_br_docker_nightly.groovy

release-5.1 use go1.16.4 for cd

release-5.1 use go1.16.4 for cd

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Revert "[on tidb_unit_test] grep fail info of previous failed test"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Revert "[tidb_ghpr_unit_test] grep fail info after race test"

---

jenkins/pipelines/nightly/tidb/tidb_nightly_unit_test.groovy

Revert "[add] grep fail info after tests of tidb nightly fail"

---

jenkins/pipelines/nightly/tidb/tidb_nightly_unit_test.groovy

Revert "Revert "[add] grep fail info after tests of tidb nightly fail""

---

jenkins/pipelines/nightly/tidb/tidb_nightly_unit_test.groovy

Revert "Revert "Revert "[add] grep fail info after tests of tidb nightly fail"""

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

let a ci job trigger all tidb integration test ci

ci to trigger all tidb integration test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
jenkins/pipelines/ci/tidb/tidb_update_commit_status.groovy

update commit status if triggered by upstream ci job

update commit status

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

pr merged commit trigger tidb build ci, binary is required by other integration test

tidb build trigger by upstream ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

integration test ci trigger another ci to update commit status when current job triggered by a merged pr

trigger ci to update commit status

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy
jenkins/pipelines/ci/tidb/tidb_update_commit_status.groovy

- add tidb update commit status ci
- merge pr not trigger unit test ci, only trigger all integration tests

add update commit status ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

`store/tikv` is going to remove.
releated PR: https://github.com/pingcap/tidb/pull/25488

Compatible with `store/tikv` directory does not exist

---

jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy

branch release-5.x also need run tidb tics test

release-5.x need run test logic

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

longer log info

---

jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

dm: remove useless log print

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

update image with go1.16.4 in podtemplate

pod image use go1.16.4 on branch master & release-5.1

---

jenkins/pipelines/build-linux-amd64-enterprise.groovy
jenkins/pipelines/build-linux-arm64-enterprise.groovy

- update enterprise build go version

update enterprise build go version

---

jenkins/pipelines/cd/optimization-release-tidb.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-hotfix.groovy

- tidb tools always use master branch

tidb tools always use master branch

---

jenkins/pipelines/nightly/tidb/tidb_nightly_unit_test.groovy

Revert "Temp fix nightly"

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

This will add build-arm-image pipeline to main release pipeline.

Add build and push arm64 docker image to release pipeline

---

jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

* remove pod tempfs set, pod use memory volume may cause dm ci encounter etcd wal error [dm issue 1790](https://github.com/pingcap/dm/issues/1790)
* remove pod idletime

fix: dm debug etcdwal err due to memvolume

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

- Add docker registry mirror to aviod exceed rate limit

Add docker registry mirror to aviod exceed rate limit

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

- master branch should use go 1.16

master branch should use go 1.16

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy

- fix tidb ddl test go version

fix tidb ddl test go version

---

jenkins/Dockerfile/centos7_golang-1.13_rust-arm64

This PR will add `hub.pingcap.net/jenkins/centos7_golang-1.13_rust-arm64:latest`

Add rust arm64 image

---

jenkins/pipelines/cd/nightly/release_br_docker_nightly.groovy
jenkins/pipelines/cd/nightly/release_cdc_docker_nightly.groovy

- upgrade nightly docker build go version

upgrade nightly docker build go version

---

jenkins/Dockerfile/release/linux-amd64/br
jenkins/Dockerfile/release/linux-amd64/dumpling
jenkins/Dockerfile/release/linux-amd64/lightning
jenkins/Dockerfile/release/linux-amd64/pd
jenkins/Dockerfile/release/linux-amd64/ticdc
jenkins/Dockerfile/release/linux-amd64/tidb
jenkins/Dockerfile/release/linux-amd64/tidb-binlog
jenkins/Dockerfile/release/linux-amd64/tikv

- add linux-amd64 build dockerfile

add linux-amd64 build dockerfile

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy

Revert "tidb: update golangci-lint version on master / release-5.x"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy

Revert "Revert "tidb: update golangci-lint version on master / release-5.x""

---

jenkins/Dockerfile/release/linux-amd64/lightning

- remove importer from lightning docker

remove importer from lightning docker

---

jenkins/pipelines/ci/tidb/tidb_check_release_note.groovy
jenkins/pipelines/ci/tidb/tidb_check_title.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

* hz-poc branch need go 1.16.4

branch hz-poc use go1164

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy

* use memory volume in tidb integration test, releate issue [tidb #26458](https://github.com/pingcap/tidb/issues/26458)

tidb: use memory volume in tidb_ghpr_integration_common_test

---

jenkins/pipelines/ci/rocksdb/rocksdb_ghpr_test.groovy
jenkins/pipelines/ci/rust-rocksdb/rust_rocksdb_ghpr_test.groovy
jenkins/pipelines/ci/titan/titan_ghpr_test.groovy

And jenkins github PR CI scripts for tikv/rocksdb, tikv/rust-rocksdb and tikv/titan repos.
Signed-off-by: Yi Wu <yiwu@pingcap.com>

Add rocksdb CI

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy

* tidb_ghpr_integration_test and tidb_ghpr_mybatis use memory volume

mybatis & ddl_test use memory volume

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

TiCDC tests are run in groups, two tests per group.

TiCDC tests are run in groups, two tests per group

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

- Move buildng arm docker images to the end of pipeline.

Move buildng arm docker images to the end of pipeline.

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-arm.groovy
jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/pre-release-tiup.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

- Surpport darwin arm64 build.

Surpport darwin arm64 build

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy

binlog integration test to use latest tidb-tools
* binlog releated pr : binlog #[1062](https://github.com/pingcap/tidb-binlog/pull/1062), already merged
* get binlogctl from binlog make build
* get sync_diff_inspectors from tidb-tools (build from multibranch)

binlog: integration test use latest tidb-tools

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

- grep tidb check 2 fail error info

grep tidb check 2 fail error info

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

Revert "grep tidb check 2 fail error info"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy

* build tidb on pod with memory volume, sometimes start tidb-server failed on the hdd disk

tidb: build on pod with memory volume

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

grep tidb dev 2 fail info

---

jenkins/pipelines/cd/nightly/build-darwin-arm64-4.0.groovy
jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

Add m1 nightly build

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy

Use the correct name of br integration job in tidb test.

Fix br integration test job 

---

jenkins/pipelines/cd/qa/build-pd.groovy
jenkins/pipelines/cd/qa/build-tidb.groovy

fix qa build BUILD_METHOD parameter

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

* correct nfs cache dir path
* adjust git clone timeout from 2 min to 10 min

br: fix br clone timeout error

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy

* use customized pod 4c8g for cdc leak test. pod before is 2c4g

cdc: leak test use 4c8g pod to run

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy

Revert "cdc: leak test use 4c8g pod to run"

---

jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test-hotfix.groovy

fix br hotfix tag

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

* tikv cached image add release-5.2

tikv: cached image add release-5.2

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy

- use diferent node label for cdc build

use diferent node label for cdc build

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

* split load plugin test from ci tidb_ghpr_build
* add ci tidb_merged_pr_build, this ci will set commit status: idc-jenkins-ci-tidb/plugin-test
* trigger coverage ci after pr merged

tidb: split tidb plugin test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

*  remove token
*  update commit status with idc-jenkins-ci-tidb/code-coverage after merged pr
Currently this ci will always failed due to this issue https://github.com/pingcap/tidb/issues/27328

fix tidb coverage

---

jenkins/pipelines/cd/release-monitor.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy

- change br metrics config dir

change br metrics config dir

---

jenkins/pipelines/ci/tidb/tidb_check_release_note.groovy
jenkins/pipelines/ci/tidb/tidb_check_title.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

* feature branch ft-data-inconsistency use go1.16.4

tidb: branch ft-data-inconsistency use go1.16.4

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

adjust fail info to grep

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

* install s3cmd in image
* two image has added s3cmd hub.pingcap.net/jenkins/centos7_golang-1.13:latest & -t hub.pingcap.net/jenkins/centos7_golang-1.16:latest

cdc: adjust pod image for lack of s3cmd

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

Ingore unit test run in pr

---

jenkins/Dockerfile/release/linux-amd64/tiem

add Dockerfile for tiem project

[Dockerfile]add for tiem

---

jenkins/pipelines/cd/build-arm-image.groovy
jenkins/pipelines/cd/release-enterprise-docker.groovy
jenkins/pipelines/cd/release_cdc_docker.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-hotfix.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy

- fix cd script for release v5.2.0

fix cd script for release v5.2.0

---

jenkins/pipelines/qa_release_test.groovy

add tikv tests to qa-release-test

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Release-5.1 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/17/pipeline/110
Release-5.2 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/19/pipeline/109 
Release-5.0 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/20/pipeline/101
Release-4.0 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/22/pipeline/101
Master https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/23/pipeline/101

ticdc: Use the corresponding version

---

jenkins/pipelines/cd/optimization-release-tidb.groovy
jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

- build m1 only version lt 5.1.0

build m1 only version lt 5.1.0

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

tikv: fix chache image harbor credential id

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

* correct default git refspec instead of checkout all pull request code

br: fix default git refspec

---

jenkins/pipelines/cd/release-check.groovy
release-checker/checker/pkg/image.py
release-checker/checker/pkg/pingcap.py

- remove importer from release checker

remove importer from release checker

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

dm: correct image project

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

dm: fix dm image

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

tidb: fix upload coverage cmd

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

tidb: fix tidb coverage patch

---

jenkins/pipelines/cd/build-arm-image.groovy
jenkins/pipelines/cd/optimization-release-tidb.groovy
jenkins/pipelines/cd/release-monitor.groovy

- change pingcap/monitor build base branch

change pingcap/monitor build base branch

---

jenkins/pipelines/ci/pd/pd_check_release_note.groovy
jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
jenkins/pipelines/ci/pd/pd_ghpr_integration_compatibility_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_intergration_common_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_intergration_ddl_test.groovy
jenkins/pipelines/ci/pd/pd_test.groovy

* feature branch auto-scaling-improvement use golang 1.16

pd: branch auto-scaling-improvement use golang 1.16

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy

* adjuest request memory to improve integration test stability

cdc: adjuest request memory

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

* cdc kafka test need more resource to improve stability

cdc: kafka test need more resource

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy

* ajust cdc test to another k8s cluster

cdc: adjuest k8s cluster

---

jenkins/pipelines/build-linux-amd64-enterprise.groovy
jenkins/pipelines/build-linux-arm64-enterprise.groovy

fix tidb enterprise build

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy

releate to https://github.com/pingcap/tidb/pull/28043
* modify `make dev` to avoid  https://github.com/pingcap/tidb/pull/28043 affecting the ci

tidb: correct make test cmds

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

Signed-off-by: xhe <xw897002528@gmail.com>
For #28644, which is blocked by this test.

tidb: remove parser replace check for migration

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

Signed-off-by: joccau <zak.zhao@pingcap.com>
br: CI: Send msg to feishu when br-integratino failed

br: CI: Send msg to feishu when br-integratino failed

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

* add cache image for release-5.3

tikv: add cache image for release-5.3

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

as title
related to https://github.com/pingcap/ticdc/pull/3247
replayed CI success in [here](https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/232/pipeline/)

dm: use old version of sync_diff

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_cdc_test.groovy

add ticdc integration test for tikv

test(tikv): add ticdc integration test for tikv

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

use new sync_diff

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* mask coverage tokens
TODO: update releated tokens

cdc: mask ticdc coverage token

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Stop installing s3cmd Use the built-in s3cmd.

test(ticdc): Stop installing s3cmd Use the built-in s3cmd

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

update nightly version

---

jenkins/Dockerfile/release/debug-image/br
jenkins/Dockerfile/release/debug-image/dumpling
jenkins/Dockerfile/release/debug-image/lightning
jenkins/Dockerfile/release/debug-image/pd
jenkins/Dockerfile/release/debug-image/ticdc
jenkins/Dockerfile/release/debug-image/tidb
jenkins/Dockerfile/release/debug-image/tidb-binlog
jenkins/Dockerfile/release/debug-image/tiem
jenkins/Dockerfile/release/debug-image/tikv

* add debug dockerfile for qa test, use centos7.9.2009 as base image

dockerfile: add debug dockerfile for qa test

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

* add cdc integration test when merge pr

tidb: add cdc it to merge master ci

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

close https://github.com/pingcap/ticdc/issues/3569

test(ticdc): separate statistics for unit tests and integration tests

---

jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test-hotfix.groovy

Add pre dm tiup

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

- final release tidb to ensure tiup release complete

final release tidb to ensure tiup release complete

---

jenkins/Dockerfile/release/linux-amd64-updated-base-image/br
jenkins/Dockerfile/release/linux-amd64-updated-base-image/dumpling
jenkins/Dockerfile/release/linux-amd64-updated-base-image/lightning
jenkins/Dockerfile/release/linux-amd64-updated-base-image/pd
jenkins/Dockerfile/release/linux-amd64-updated-base-image/ticdc
jenkins/Dockerfile/release/linux-amd64-updated-base-image/tidb
jenkins/Dockerfile/release/linux-amd64-updated-base-image/tidb-binlog
jenkins/Dockerfile/release/linux-amd64-updated-base-image/tiem
jenkins/Dockerfile/release/linux-amd64-updated-base-image/tikv

* add dockerfile with updated base image (amd64 image)

update base image

---

jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test.groovy

fix dm tiup release

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

test(ticdc): fix the integration tests dir

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

* tikv ci in feature branch to user default cached ci image

tikv ci feature branch use default image

---

jenkins/pipelines/qa_release_test.groovy

add version parameter to qa-release-test

---

jenkins/pipelines/cd/optimization-release-tidb.groovy
jenkins/pipelines/cd/release-enterprise-docker.groovy

fix download release binary

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

* fix codecov uploader post api param error

fix codecov upload error

---

jenkins/pipelines/ci/tidb/tidb_check_release_note.groovy
jenkins/pipelines/ci/tidb/tidb_check_title.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

* feature branch br-stream use go 1.16.4

ci tidb: feature branch br-stream use go1.16

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

- reserve tidb check 2 pod for debug

reserve tidb check 2 pod for debug

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

* upload ut coverage to codecov

tidb ut upload coverage file

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy

ci: disable upload coverage

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

tidb ci: disable ut nfs volume

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy

* get failed integration test result, save result to currentBuild.description

get tidb integration test failed task summary

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy

* get br and ticdc integration test ci details

get br&cdc integration test ci details

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy

Revert "get br&cdc integration test ci details"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

* comment ut coverage link on pr

tidb ci: comment coverage link on pr

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

- change release base dockerfile

change release base dockerfile

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

tidb mergeci notify

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

* write each it test result to json file

feat: write json to file

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

Update jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy for metrics.

Update jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy for metrics

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

* adjust successful integration test result info

feat: adjust successful it result summary info

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

* Reduce resource requests
before: 36 * (4+1+1) = 216 core 
after: 36 * (3+0.5+0.5) = 144 core
* modify namespace: jenkins-tidb --> jenkins-dm
test pipeline https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/1962/pipeline/

dm: adjust dm it test pod request resource

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy

tidb: fix jdbc test error

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

* some integration test use unique pod label to count resource usage

tidb ci unique pod lable

---

jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

* adjust go1.13 image for sqllogic test /git/sqllogictest path

fix: correct go1.13 image for sqllogic test path error

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

feat: ticdc readd it coverage

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

- Collect tidb check dev 2 test report

Collect tidb check dev 2 test report

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

fix check2

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

- add junit report for tidb ut

add junit report for tidb ut

---

jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy

enhance ticdc tiup patch & docker image

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

- fix tidb check 2 lack of .git dir

fix tidb check 2 lack of .git dir

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* archive failed it tests logs for debug

ticdc: archive it test logs

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

* update KAFKA_MESSAGE_MAX_BYTES to 11 MiB
* create big message test topic

kafka(ticdc): update KAFKA_MESSAGE_MAX_BYTES and create big message topic

---

jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tikv_multi_branch.groovy

remove tikv/pd multi branch trigger always fail docker image build

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy

* tiup nightly build ci add notify

tiup nightly notify

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

- fix tidb check dev 2 fail occasionally

fix tidb check dev 2 fail occasionally

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

* get coverage rate from codecov

tidb: get coverage from codecov

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

upload prid to tipipeline

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

add cache image for release-5.4

tikv: add cache image for release-5.4

---

jenkins/pipelines/cd/optimization-libs.groovy

* build-common add param NEED_SOURCE_CODE

fix: build-common add param NEED_SOURCE_CODE

---

jenkins/pipelines/qa_release_test.groovy

* update some build package name

qa-release-test: udpate some package name

---

jenkins/pipelines/ci/tidb-and-tools/tidb_and_tools_e2e_test.groovy

ci: add tidb and tools test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

* for mysql-tester param --all

fix: Compatible parameter settings for --all

---

jenkins/pipelines/cd/optimization-libs.groovy

temp remove plugin

---

jenkins/pipelines/cd/optimization-libs.groovy

Revert "temp remove plugin"

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy

disable foce rebuild for nightly 

---

jenkins/pipelines/cd/optimization-libs.groovy

hotfix filepath

---

jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy

fix tiflash error

---

jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test-hotfix.groovy

fix tiflash

---

jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy

unify tarball name

---

jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

fix nightly build

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test.groovy

fix hash error

---

jenkins/pipelines/cd/tiup/br-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/cdc-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/dumpling-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/lightning-tiup-mirror-update-test.groovy

fix package dir error

---

jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy

try to fix tiflash error

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-darwin-arm.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/tiflash-tiup-mirror-update-test.groovy

fix tiflash build

---

jenkins/pipelines/ci/tispark/build.groovy
jenkins/pipelines/ci/tispark/integration_test.groovy
jenkins/pipelines/ci/tispark/log4j-ci.properties
jenkins/pipelines/ci/tispark/tidb_config-for-tiflash-test.properties

ADD:add tispark ci

---

jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy

fix prometheus

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

fix tiup mirror update

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

temp update tidb resource usage

temp update tidb resource usage

---

jenkins/pipelines/ci/tispark/integration_test.groovy

update tispark ci

---

jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

add arch on prometheus

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

reset tidb ut resource

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy

add new hotfix

---

jenkins/Dockerfile/release/linux-amd64/tiflash
jenkins/Dockerfile/release/linux-arm64/tiflash

Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>
We may still want to adjust some parameters in this dockerfile

cache tiflash dockerfile

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy

* remove nfs cache volume for hand forever
* set timeout 20min for leak test

fix: remove nfs cache volume and set timeout for leak test

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy

* fix wrong go version when running ut coverage

tispark: fix wrong go version

---

jenkins/pipelines/ci/tispark/daily.groovy

tispark:add daily

---

jenkins/pipelines/cd/tiup/pre-release-tiup.groovy

temp using master for tools

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* waiting for Kafka alive then start test
* reduce some CPU request

ticdc: waitting kafka to alive

---

jenkins/pipelines/ci/tispark/daily.groovy

tispark:fix daily

---

jenkins/pipelines/ci/tispark/daily.groovy

tispark:fix daily println

---

jenkins/pipelines/ci/tics/tics_ghpr_build.groovy
jenkins/pipelines/ci/tics/tics_ghpr_test.groovy

update tics token

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

Signed-off-by: guo-shaoge <shaoge1994@163.com>

Purelind/fix tidb test mysql test param error: add some index_merge cases

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

1. Remove Build Stage
2. Remove TIDB_TAG/TIKV_TAG/..etc
3. Remove MINOR_TELEASE_TAG/FORCE_REBUILD/SKIP_TIFLASH

remove build since no build on optimization release

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

remove useless code

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy

refine tiup-release-tidb-master-nightly

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

add dm job back

---

jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test.groovy

fix dm hash

---

jenkins/pipelines/ci/tispark/integration_test.groovy

ADD: mvn package use profile

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy

add from github hash

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy

print hash

---

jenkins/pipelines/ci/tispark/integration_test.groovy

add tispark memory

---

jenkins/pipelines/ci/tispark/integration_test.groovy

add multi-profile by using regex group

ADD: muti profile

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/optimization-build-tidb.groovy

try to all in one optimization build job

---

jenkins/pipelines/cd/multibranch/build_tiflash_multi_branch.groovy

wait on https://cd.pingcap.net/blue/organizations/jenkins/build_tiflash_multi_branch/detail/master/768

Archive new tiflash multibranch script

---

jenkins/pipelines/cd/build-operator-arm-image.groovy

fix arm path

---

jenkins/pipelines/ci/tispark/daily.groovy
jenkins/pipelines/ci/tispark/integration_test.groovy

tispark-allversion

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

fix tidb stash file failed

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy

fix offline package

---

jenkins/pipelines/cd/release-tikv-java-client.groovy

background: tikv java client build task;
content:
- add cd pipeline of maven to build 
- upload nexus
test passed!

Release tikv java client

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

record ci pr author

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

dm: add minio for s3 test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

* release-5.1 are fewer cases than the master branch

 mysql test release 5.1 some tests not exist

---

jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

as title. the same as https://github.com/PingCAP-QE/ci/pull/683

cdc-dm: add minio for s3 test

---

jenkins/pipelines/ci/tispark/integration_test.groovy

add timeout

---

jenkins/pipelines/ci/tispark/daily.groovy

TiSpark new version

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

* check_dev2 : destroy pod when ci task finished

tidb: destroy pod when ci task finished

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

* skip cdc integration test for dm's pr

ci: skip cdc ci for dm's pr

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

* skip dm integration it if pr diff files not related to dm 
* file matches `/(^dm\/|^pkg\/).*$/` is treated as related to dm

ci: skip dm ci if pr not related 

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

add tidb ut timeout

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

* trigger tidb_ghpr_mysql_test by upstream pipeline (from repo tidb-test)

tidb: mysql-test support uptream pipeline trigger

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

add tidb-test ci

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

fix download x86 error

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

remove server on path

---

jenkins/pipelines/cd/optimization-build-tidb-darwin-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-darwin-arm.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy

add importer hash

---

jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy

fix ng monitoring version

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy

fix optimization

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

fix tidb_ctl cp

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

fix br hash

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

* failed this ci if merge_pr_build failed

fix tidb merge it trigger

---

jenkins/pipelines/cd/optimization-libs.groovy

fix lightning

---

jenkins/pipelines/cd/build-linux-enterprise.groovy

fix tiflash hash

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy

delete hash on path

---

jenkins/pipelines/cd/release-enterprise-docker.groovy

fix enterprise docker

---

jenkins/pipelines/cd/optimization-libs.groovy
jenkins/pipelines/cd/release-enterprise-docker.groovy

add docker socket

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

* add a parallel step to run all tests

update tidb test mysql test ci

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

fix tidb-ctl

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_cdc_test.groovy

make cdc it  compatible with upstream trigger

make cdc it  compatible with upstream trigger

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

* update ut cmds
* improve wait time to ensure successful coverge uploads

update tidb coverage ci

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy

add performance overview

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

tidb: add some info if unit test failed

---

jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy

Revert "delete tidb master nightly"

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/3551/pipeline/67/

DM CI can download TiDB of release version rather than nightly

---

jenkins/Dockerfile/release/linux-amd64/enterprise/tidb

add tidb enterprise

---

jenkins/pipelines/cd/tiup/importer-tiup-mirror-update-test.groovy

add importer

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

fix tidb ctl

---

jenkins/pipelines/ci/tidb/tidb_ghpr_readonly_test.groovy

- add tidb readonly test pipeline

add tidb readonly test pipeline

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy

* feature branch release-multi-source need use go1.16

tiflow: support feature branch release-multi-source

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* update sync_diff_inspector url: commit hash is  00998a9a4bfd08eb63449186d147b0e6bb1fea5d

ticdc: update sync_diff_inspector url

---

jenkins/pipelines/ci/tics/tiflash-sanitizer-daily.groovy

see https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/activity

Cache TiFlash sanitizer script

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy

remove importer

---

jenkins/pipelines/cd/optimization-release-tidb.groovy

refine lightning image

---

jenkins/pipelines/cd/build-linux-enterprise.groovy

build amd & arm the in para

---

jenkins/pipelines/cd/optimization-libs.groovy

add enterprise build

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy

fix hotfix

---

jenkins/pipelines/ci/tispark/daily.groovy

update tispark daily

---

jenkins/pipelines/cd/build-linux-enterprise.groovy

fix arm build

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

update to v6.0.0

---

jenkins/Dockerfile/release/debug-image/dm
jenkins/Dockerfile/release/linux-amd64/dm
jenkins/Dockerfile/release/linux-arm64/dm

* add dm dockerfile for release: arm64 / amd64 / debug

add dm image

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

correct explain test log name
ci link: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/67971/pipeline/64/

correct explain test log name

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

fix tidb explaintest log name

---

jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy

fix ng monitoring

---

jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test.groovy

- fix tiup dm pipeline did not fail

fix tiup dm pipeline did not fail

---

jenkins/pipelines/goversion-select-lib.groovy

* add lib for go version select
* select by tag or branch

add lib for go version select

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* all feature branch use master branch depency to test

any branch other then release-xxx use master branch depency

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Revert "[WIP] tiflow master upgrade go version to go1.18"

---

jenkins/pipelines/ci/pd/pd_ghpr_build.groovy

* master branch ci upgrade go version from go1.16 to go1.18

pd master ci use go1.18

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_build_new3.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_check.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_unit_test.groovy

* master branch ci upgrade go version from go1.16 to go1.18
related to https://github.com/pingcap/tidb-binlog/pull/1142

binlog ci use go1.18

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

branch master upgrade go version from go1.16 to go1.18

tiflow ci use go1.18

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_readonly_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

* tidb ci in master branch need upgrade go version to go1.18

 tidb master upgrade golang version to go1.18

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy

tidb: fix integration test pod lable

---

jenkins/pipelines/cd/multibranch/build_binlog_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_br_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_dumpling_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_enterprise_tools_master.groovy
jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy

- support go 1.18 for cd pipeline

support go 1.18 for cd pipeline

---

jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
jenkins/pipelines/ci/tidb-tools/tools_ghpr_unit_test.groovy

* add tidb-tool ci pipeline
* ci on master branch use go1.18

add tidb-tools master branch

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

- add tikv cache for release-6.0

add tikv cache for release-6.0

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

change docker credential

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy

suppurt release 6.0

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

fix sync diff version

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

fix tikv push image failed

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

* make some task in tidb_ghpr_check parallel
* run it in tidb_ghpr_unit_test even on release-xxx

make check dev faster

---

jenkins/Dockerfile/release/linux-arm64/pd

Revert "fix pd for arm"

---

jenkins/pipelines/cd/build-linux-enterprise.groovy

fix enterprise tikv build

---

jenkins/pipelines/cd/release-enterprise-docker.groovy

fix pre docker synax error

---

jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy

update tikv copr test go version

update tikv copr test go version

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

generate core dump file

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

archieve tidb ut core dump file

archieve tidb ut core dump file

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

archieve ut test.bin file

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy

currently tiup update take too long

speed up tiup update

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-hotfix.groovy

Revert "speed up tiup update"

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

fix tikv/pd br tests not use the lasted br

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

* only update commit status if triggered by merge-ci upstream pipeline
* not update if triggered in daily-ci

only update commit status if triggered in merge-ci

---

jenkins/pipelines/ci/tiflash/tiflash_ghpr_build_release.groovy

add pipeline to build tiflash release binary

add pipeline to build tiflash release binary

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy

* fix cdc integration test triggered by upstream pr not use tidb latest branch binary

fix cdc use wrong version binary

---

jenkins/pipelines/cd/build-linux-enterprise.groovy

support tikv build by bump version pr

support tikv build by bump version pr

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy

fix tiup failed on mac m1

---

jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_intergration_ddl_test.groovy
jenkins/pipelines/ci/pd/pd_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy

* ci has default internal goproxy, not override default

ci has default internal goproxy

---

jenkins/pipelines/ci/tispark/m2_cache_daily.groovy

tispark:add m2 cache

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

* some makefile target is missing in some release-branch, make ci compatible with those branches

support diff makefile in diff release-branch

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

ci triggered on master branch use tidb release-6.0 cached binary

use tidb latest release-branch cache for integration test

---

jenkins/pipelines/ci/tispark/daily.groovy
jenkins/pipelines/ci/tispark/integration_test.groovy

tispark:support tiflash

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/optimization-libs.groovy

* need build params for debug covenience

print build params

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

Revert "run 3 times mysql-test in ci"

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

Revert "Revert "run 3 times mysql-test in ci""

---

jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy

* tidb e2e test need been triggered by upstream pipeline

tidb e2e support triggered

---

jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy

* remove slack notify
* support update commit status

tidb  e2e support update comit status

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy

* feature branch `planner_refactory` use tidb master build for integration tests

use tidb master build for it

---

jenkins/Dockerfile/release/linux-amd64/dm
jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy

* dm release step has merge in release pipeline, not use this multi-branch pipeline for release any more
* remove mydumper for myumper is deprecated from dm v2.0.0

do not publish image in this multi-branch pipeline

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* set unique pod lable to fix some cdc test user wrong go version

fix cdc use wrong go version

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

fix pod label

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_downstream_coverage.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy

* run cdc ci in a new k8s cluster

use new k8s cluster for cdc ci

---

jenkins/pipelines/cd/release-monitor.groovy

* fix push image to dockerhub timeout
* not auto create pr

fix release monitor2

---

jenkins/pipelines/cd/optimization-libs.groovy
jenkins/pipelines/cd/pre-release-docker.groovy
jenkins/pipelines/cd/pre-release-enterprise-docker.groovy

* support build multi-arch image
* sync image from harbor to dockerhub

[WIP] pre release support multi arch

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy

* some docker container open file limit is 65535, it is too small

use old cluster for now

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
jenkins/pipelines/ci/tidb/tidb_integration_test_ci_shadow_debug.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

Revert "change tidb it default cluster"

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy
jenkins/pipelines/ci/tidb/tidb_integration_test_ci_shadow_debug.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

Revert "Revert "change tidb it default cluster""

---

jenkins/pipelines/ci/tispark/daily.groovy

- add test for spark3.2.1
- only run tiflash on sunday

tispark:fix tiflash

---

jenkins/Dockerfile/release/debug-image/br
jenkins/Dockerfile/release/debug-image/dm
jenkins/Dockerfile/release/debug-image/dumpling
jenkins/Dockerfile/release/debug-image/pd
jenkins/Dockerfile/release/debug-image/ticdc
jenkins/Dockerfile/release/debug-image/tidb
jenkins/Dockerfile/release/debug-image/tidb-binlog
jenkins/Dockerfile/release/debug-image/tidb-lightning
jenkins/Dockerfile/release/debug-image/tikv
jenkins/Dockerfile/release/linux-amd64/br
jenkins/Dockerfile/release/linux-amd64/dm
jenkins/Dockerfile/release/linux-amd64/dm-monitor-initializer
jenkins/Dockerfile/release/linux-amd64/dumpling
jenkins/Dockerfile/release/linux-amd64/enterprise/tidb
jenkins/Dockerfile/release/linux-amd64/ng-monitoring
jenkins/Dockerfile/release/linux-amd64/pd
jenkins/Dockerfile/release/linux-amd64/ticdc
jenkins/Dockerfile/release/linux-amd64/tidb
jenkins/Dockerfile/release/linux-amd64/tidb-binlog
jenkins/Dockerfile/release/linux-amd64/tidb-lightning
jenkins/Dockerfile/release/linux-amd64/tidb-tools
jenkins/Dockerfile/release/linux-amd64/tiem
jenkins/Dockerfile/release/linux-amd64/tikv
jenkins/Dockerfile/release/linux-arm64/pd
jenkins/pipelines/cd/optimization-libs.groovy
jenkins/pipelines/cd/pre-release-community-docker.groovy

Revert "update dockerfile and update pre-release-community-docker to dockerhub"

---

jenkins/pipelines/cd/multibranch/build_binlog_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_br_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_dm_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_dumpling_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_enterprise_tools_master.groovy
jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_test_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_tools_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tiflash_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tikv_multi_branch.groovy
jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/optimization-libs.groovy
jenkins/pipelines/cd/optimization-release-tidb.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0-hotfix.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-atom.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror.groovy

curl default always exit with zero code.
add `--fail` option to `curl` cmd for file uploading.

jenkins/pipeline/cd: make curl exit with err code

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_build_new3.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_check.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_unit_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy

binlog ci use new cluster

---

jenkins/pipelines/ci/rocksdb/rocksdb_ghpr_test.groovy
jenkins/pipelines/ci/rust-rocksdb/rust_rocksdb_ghpr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/titan/titan_ghpr_test.groovy

* br ci use new cluster
* some repo in org tikv use new cluster

br use new cluster

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

use new cluster

---

jenkins/pipelines/ci/tispark/build.groovy
jenkins/pipelines/ci/tispark/m2_cache_daily.groovy

adjsut cluster

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

* part 20 failed in the new k8s cluster for unknown reason. adust this to use the old cluster.

chunk 20 use the old  cluster

---

jenkins/pipelines/qa_release_test.groovy

jenkins/pipeline: migrate qa-release to new kubernetes cluster

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

* some test case in tikv need run pod in privileged mode
* ut will consume about 13G memory

fix tikv ut unstable

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

fix tidb cache url

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

adjust tidb cache path

---

jenkins/pipelines/cd/multibranch/build_tiflash_multi_branch.groovy
jenkins/pipelines/cd/nightly/release_tidb_enterprise_tools_master-nightly.groovy
jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
jenkins/pipelines/cd/optimization-libs.groovy
jenkins/pipelines/cd/optimization-release-tidb.groovy
jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test.groovy
jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/dm/dm_compatibility_test.groovy
jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/ci/tidb-and-tools/tidb_and_tools_e2e_test.groovy
jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy
jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
jenkins/pipelines/ci/tispark/integration_test.groovy
jenkins/pipelines/qa_release_test.groovy
jenkins/pipelines/release_tiflash_by_tag.groovy

added options:
- `-C -`: to make it continue where it dropped of (if you run the command again). The dash afterwards tells it to figure out where to resume from.
- `--retry 3`: to retry 3 times.

feat(jenkins/pipelines): enhance tarball download with curl retry and continue options

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy

* currently too many PRs in tidb-test repo waiting to be merged, temporarily run the msyql test in whitelist

run msyql-test on master in whitelist mode

---

jenkins/pipelines/qa_release_test.groovy

I'm not familiar with groovy, please help check it

Add DM release CI

---

jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

* qa-release-test will trigger dm ci from v5.3.0

dm: dm ci support qa-release-test trigger

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

Signed-off-by: crazycs520 <crazycs520@gmail.com>
https://github.com/pingcap/tidb-test/pull/1722

add beego orm test in ci

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

Signed-off-by: crazycs520 <crazycs520@gmail.com>
https://github.com/pingcap/tidb-test/pull/1766

add upper db orm test in ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

1. Fix some groovy array bug introduced by  https://github.com/PingCAP-QE/ci/pull/1078 
2. support new branch [pingcap:6.1.0-pitr-dev](https://github.com/pingcap/tidb/tree/6.1.0-pitr-dev)

support tidb branch 6.1.0 pitr dev

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

Signed-off-by: crazycs520 <crazycs520@gmail.com>
https://github.com/pingcap/tidb-test/pull/1728

add xorm test in ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

*: update tidb_image:20220614

---

jenkins/pipelines/ci/tispark/daily.groovy

update tispark daily ci
- add tispark 3.0
- add tidb 6.0

update tispark daily ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

update image and exit 1 when to fail to build

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

Hibernate 6.1 integration test

Hibernate 6.1 integration test

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

Signed-off-by: tabokie <xy.tao@outlook.com>

install cargo-nextest in tikv image

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

*  resolve git.io in ci node  is likely to fail

ticdc: fix download file from git.io failed

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

* currently those tests run on [github action](https://github.com/pingcap/tidb/blob/master/.github/workflows/integration-test-with-real-tikv.yml) . github action free quota is limited, tasks often encounter queues

add some real tikv tests

---

.gitignore
jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy

Add a notify receiver

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy

* support trigger params: ghprbCommentBody

ticdc ci support trigger comment body

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

*: update image

---

jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy

Reverts sanitizer modify in PingCAP-QE/ci#1142 for [TiFlash sanitizer CI failure](https://ci.pingcap.net/job/tiflash-sanitizer-daily/350/console).

revert sanitizer modify in #1142

---

jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy

add TSAN_OPTIONS suppressions

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-build-arm64.groovy

* add pipeline for build tiflash arm64 binary: comment /run-build-arm64 on tiflash pr will trigger pipeline

tiflash: add build linux arm64 ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

update tidb image

---

jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy

fix(jenkins/pipelines/ci/tidb): fix retring for test coverage getting

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

using the minor release dependencies

fix(ci/ticdc): support for pr to hotfix branch

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

Test Case: https://github.com/pingcap/tidb-test/pull/1893

[Update] add mysql-connector-c integration test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

ci: skip race check for explain test

---

jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy

* mysql test on release-6.2 user -blacklist param

tikv it comon fix

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

* upload tidb verify ci pipeline run data for each run

tidb pipeline upload data

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

https://ci.pingcap.net/blue/organizations/jenkins/tidb_test_ghpr_integration_test/detail/tidb_test_ghpr_integration_test/1460/pipeline/112

[Update] add TiDB JDBC Unique Test

---

jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy

https://cd.pingcap.net/job/build-common/128007/console
to align with https://github.com/pingcap/tiflow/pull/6384

Update CD because DM has changed the folder

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

update bazel image

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

ci: fix check_dev_2 to use real tikv

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

Revert "ci: fix check_dev_2 to use real tikv"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

* tidb_ghpr_mysql_test. for master and release-6.2 branch, split the tests to 4 parts, run them in parallel
* tidb_ghpr_integration_common_test  split test to 4 parts, run test in parallel
* tidb_ghpr_common_test  remove duplicate mysql-test that already run in verifyci tidb_ghpr_mysql_test

tidb split mysql test

---

jobs/pingcap-qe/ci/trunk/self_test.groovy
jobs/pingcap/tidb/latest/ghpr_build.groovy
jobs/pingcap/tidb/latest/ghpr_unit_test.groovy

chore(jobs): disable jobs and switch pipeline to main branch

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

update bazel 20220801

---

pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

Revert "feat(pipelines/pingcap/tidb): set pipeline agent cloud to `kubernetes…"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

Revert "Revert "ci: fix check_dev_2 to use real tikv""

---

jenkins/pipelines/cd/multibranch/build_dm_from_cdc_multi_branch.groovy

ref https://github.com/PingCAP-QE/ci/pull/1202

Fix forget to modify ARM build script

---

jobs/pingcap/tidb/latest/ghpr_build.groovy
jobs/pingcap/tidb/latest/ghpr_check.groovy
jobs/pingcap/tidb/latest/ghpr_check2.groovy
jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
jobs/pingcap/tidb/latest/ghpr_unit_test.groovy

test(jobs/pingcap/tidb/latest): limit trigger only by debug phrase

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

*: bazel update 20220802

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy

use bazel for lint

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

upgrade bazel image 20220805

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_ingration_enterprise_plugin_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy

Revert "feat: make integration tests run on ksyun cluster"

---

pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
scripts/pingcap/tidb/run_real_tikv_tests.sh

*: add bezel realtikvtest

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

*: change check-2 to bazel

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

*: fix check-2 to bazel

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/tiup-check-online-version.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy

add test for nightly version exist after tiup nightly build

add test tiup nightly component exist

---

jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy

* tiflash is public repo now,  download rules.yml directly

feat(build): download tiflash.rules.yml directly

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

update bazel 20220816

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy

* upload different os-arch tiup packages in parallel

feat(build): upload tiup multi os-arch package parallel

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy

update master verison to v6.3.0-alpha

---

jenkins/pipelines/cd/check-images-with-basic-sql.groovy

fix token environment variable

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

*: add feature branch CI for distribute-reorg

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

support feature branch and release branch for `mysql test`

feat(jenkins/pipelines/ci/tidb): support feature and release branch

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy

* for lts versin (currently mean v6.1.x), need upload enterprise package(server and toolkit) to s3

feat(build): only upload enterprise package for lts version

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

*: upgrade bazel cache

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

Test passed: https://github.com/pingcap/tidb-test/pull/1925
CI Link: https://ci.pingcap.net/blue/organizations/jenkins/tidb_test_ghpr_integration_test/detail/tidb_test_ghpr_integration_test/1488/pipeline/114

[Update] integration test for Ruby ActiveRecord framework

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy

- write in shell instead of groovy

feat(pipelines/pingcap/tidb): add third component branch setting in pr comment

---

jenkins/pipelines/cd/tiup/dm-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_downstream_coverage.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/ci/tidb-and-tools/tidb_and_tools_e2e_test.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy
jenkins/pipelines/ci/tispark/build.groovy
jenkins/pipelines/ci/tispark/daily.groovy
jenkins/pipelines/ci/tispark/integration_test.groovy
jenkins/pipelines/ci/tispark/m2_cache_daily.groovy

- `--retry` retry
- `-C` continue
- `-f` or `--fail` fail with non-zero exit code

fix: curl cli retry and continue args

---

.gitignore
jenkins/pipelines/ci/ticdc/dfe_ghpr_integration_test.groovy

Add dataflow engine integration test to `jenkins/pipelines/ci/ticdc`

ci: add dataflow engine integration test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

*: add addindexlittest

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

Revert "*: add addindexlittest"

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy

optimize time to checkout 
original: 6m32s
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-unit-tests/detail/tiflash-ghpr-unit-tests/5352/pipeline/18
optimized: 13s
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-unit-tests/detail/tiflash-ghpr-unit-tests/5371/pipeline/18
----
original: 4m50s
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-integration-tests/detail/tiflash-ghpr-integration-tests/8329/pipeline/92
optimized: 33s
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-integration-tests/detail/tiflash-ghpr-integration-tests/8337/pipeline/26

Optimize tiflash-ghpr-unit-tests & tiflash-ghpr-integration-tests

---

jenkins/pipelines/ci/tispark/daily.groovy

Signed-off-by: qidi1 <1083369179@qq.com>
After this [pr](https://github.com/pingcap/tispark/pull/2492) merge, we need to change TiSpark Daily CI.

change tispark daily ci version

---

jobs/pingcap/tidb/latest/ghpr_build.groovy
jobs/pingcap/tidb/latest/ghpr_check.groovy
jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
jobs/pingcap/tidb/latest/ghpr_unit_test.groovy

new pipelines
- build
- check
- mysql_test
- unit_test

feat(jobs/pingcap/tidb/latest): fast with pipeline scm lightweight checkout

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

upgrade bazel image

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

* integration-ddl-test and integration-sqllogic-test have been tested for a week. Not find 5000 timeout error anymore. it is time to move on

tidb-it: make some it task run on ksyun

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

* currently codecov report link is invalid, so remove it.

fix: remove tidb ut codecov report

---

jenkins/pipelines/ci/tidb/goversion-select-lib.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy

* tidb common and integration-test master use go1.19 for mysql-test case failed in go1.18

tidb it use go1.19

---

jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy

- it will fail when target branch is release hotfix branch
replay links:
https://ci.pingcap.net/blue/organizations/jenkins/tidb_e2e_tests/detail/tidb_e2e_tests/3903/pipeline/31

fix(tidb): fix checkout for e2e_test

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy

Revert "parallel builds tiup package among arch"

---

jobs/pingcap-qe/ci/trunk/self_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
scripts/plugins/report_job_result.sh

replay link: https://prow-ee.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_build/1459/console
new:

fat(pipelines/pingcap/tidb): add report for `ghpr_build`

---

jenkins/pipelines/cd/optimization-build-tidb.groovy
jenkins/pipelines/cd/optimization-libs.groovy

* not build enterprise-plugin for community binary
* enterprise-plugin already build on build-linux-enterprise task

fix: not build plugin for comunity binary

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy

* get tidb-test code directly from git instead of fileserver

feat: download tidb-test from git instead of fileserver

---

jenkins/pipelines/ci/rust-rocksdb/rust_rocksdb_ghpr_test.groovy

Signed-off-by: tabokie <xy.tao@outlook.com>

fix rust-rocksdb ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

*: update ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy

- build result should not be ignored.

fix(jenkins/pipelines/ci/tidb): fix failure step display in `ghpr_build`

---

pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

fix(pipelines/pingcap/tidb): add fs group to pod security context

---

jenkins/jobs/ci/tidb/ghpr_build.groovy
jobs/pingcap/tidb/latest/ghpr_build.groovy

`branch` not support multi items, but `ghprbBranch` supported

fix(jobs/pingcap/tidb,jenkins/jobs/ci/tidb): switch trigger to new server for `tidb_ghpr_build`

---

libraries/tipipeline/vars/control.groovy

ref: https://gist.github.com/sturman/ce445c13a741fb3a0d4c0bf9bb940580

feat(libraries/tipipeline/vars): add build control function `cancelPreviousBuilds`

---

jenkins/jobs/ci/tidb/ghpr_check.groovy
jenkins/jobs/ci/tidb/ghpr_check2.groovy
jenkins/jobs/ci/tidb/ghpr_mysql_test.groovy
jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
jobs/pingcap/tidb/latest/ghpr_build.groovy
jobs/pingcap/tidb/latest/ghpr_check.groovy
jobs/pingcap/tidb/latest/ghpr_check2.groovy
jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml

- add job dsl for `ghpr_check`, `ghpr_check2` and `ghpr_mysql_test`
- add report step in new refactored pipelines: `ghpr_check`, `ghpr_check2` and `ghpr_mysql_test`

feat(jenkins/jobs/ci/tidb): prepare to switch tidb verify pipelines

---

jenkins/pipelines/goversion-select-lib.groovy

* add go1.19 (master use go1.19)

feat: govesion lib script add go1.19

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/goversion-select-lib.groovy

* some ci pipeline in tidb need support  release-6.3

ci(tidb): support release-6.3

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_integration_test.groovy

Related PR in tidb-test repo: https://github.com/pingcap/tidb-test/pull/1972

Add TLS Test in tidb_jdbc8_tls_test

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* default tidb use latest release: release-6.3

cdc: default tidb use release-6.3

---

jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
jenkins/pipelines/ci/tidb-tools/tools_ghpr_unit_test.groovy

Signed-off-by: Leavrth <jianjun.liao@outlook.com>

sync-diff-inspector: update mysql version

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

upgrade image 20220921

---

pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

remove limit for tidb test

---

pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy

Why: only build the plugins is not enough to find plugin loading error
replayed link:
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_build/detail/ghpr_build/1548/pipeline/81/
it will not increase build time

feat(tidb): test plugin with tidb

---

pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy

Revert "feat(tidb): test plugin with tidb"

---

jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy

* The affinity policy is already in effect under namespace

tidb mergeci: remove nodeselector

---

jobs/pingcap/tidb-engine-ext/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb-engine-ext/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb-engine-ext/latest/pod-ghpr_unit_test.yaml

* add ut pipeline for tidb-engine-ext

tidb-engine-ext: add ut pipeline

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

update image 20220922

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy

tidb it mysql-test: add > release-6.2 support

---

pipelines/pingcap/tidb-engine-ext/latest/ghpr_unit_test.groovy

Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

fix(tiflash): Enable gcc 8 for TiFlash Proxy

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy
scripts/pingcap/tidb/run_real_tikv_tests.sh

fix(tiflash): add timeout for unit test pipeline

---

jenkins/jobs/ci/tidb/ghpr_mysql_test.groovy
jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
jobs/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy

for target branches:
- master
- release-6.2+

feat(jobs/pingcap/tidb): switch `mysql_test` to refactored ones

---

jenkins/jobs/ci/tidb/ghpr_check2.groovy
jobs/pingcap/tidb/latest/ghpr_check2.groovy
jobs/pingcap/tidb/release-6.2/ghpr_check2.groovy

- current brand is low,so disable it(switch it to idc)

chore(pipielines/pingcap/tidb): disable ghpr_check2

---

pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

tidb_build set cpu 16

---

staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy

current should merge it for staging testing

refactor(staging/pipelines/pingcap/tidb/latest): using share library to simpfy components repo checkout

---

pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

Revert "refactor(pipelines/pingcap/tidb): explict set resource limits for bazel container"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

upgrade cache image 20221010

---

staging/jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
staging/pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
staging/pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml

* add env CACHE_ENABLED on mysql-test, test this on staging

staging: add an env CACHE_ENABLED for mysql-test

---

pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

the args added before build image updated, now updated.

revert(pipelines/pingcap/tidb): ram limit and other args for bazel build

---

pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

Revert "revert(pipelines/pingcap/tidb): ram limit and other args for bazel build"

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

Signed-off-by: tabokie <xy.tao@outlook.com>

use cargo sort in tikv format

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

update ci image 20221013

---

jenkins/pipelines/cd/tiup/pre-release-tiup.groovy

check artifact after rc

---

jenkins/pipelines/cd/tiflow-docker.groovy
jenkins/pipelines/cd/tiflow-operator-docker.groovy

Support to get commit hash before parallel build

refine tiflow build script, get git commit hash auto

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy
jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy

Install `gtests_dbms` by cmake install rule.

install gtests_dbms by cmake

---

libraries/tipipeline/vars/component.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy

replayed link: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/2006/pipeline/49/
`passed`

feat(pipelines/pingcap/tidb): make artifact fetching simple with share library function

---

scripts/pingcap/br/integration_test_download_dependency.sh
staging/jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
staging/pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
staging/pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml

* test merged pipeline (br integration test) on staging

feat(staging): simplify tidb br integration test

---

pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy

- prefer to top level timeout option in pipeline

feat(pipglines/pingcap/tidb): adjust build timeout setting

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

update image 20221101

---

jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy

Verified in https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/638/pipeline

Update tiflash-sanitizer-daily.groovy to add rust code cache

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

because DM will embed lightning, lightning need to test the TiDB cluster with PD/TiKV

download pd/tikv for DM integration test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

chore(*/pipelines/tidb): bump bazel build image to `go11920221103`

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

broken build: https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/10625/pipeline
broken image: https://hub.pingcap.net/harbor/projects/2/repositories/centos7_golang-1.19:latest
> sha256:b5f727ba

fix(jenkins/pipelines/ci/ticdc/dm): fix pip installing failure

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

qa release test need use specify commit hash of binary(tidb / pd / tikv), make this work in dm_ghpr_integration_test
replay test link: https://ci.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/81/pipeline/

feat(dm): support qa release test trigger

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy

replay test link
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/12030/pipeline/71

fix(tidb): fix shell syntax error

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy
staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

update image 20221108

---

jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy

this PR update nightly version to 6.5.0-alpha from 6.4.0-alpha after release-6.4 has been check-out

update nightly version to v6.5.0-alpha

---

jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy

* need use correct go version to run integration tests
replay link
1. https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_integration_ddl_test/detail/tikv_ghpr_integration_ddl_test/2564/pipeline/
2. https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_integration_compatibility_test/detail/tikv_ghpr_integration_compatibility_test/2549/pipeline
3. https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_integration_common_test/detail/tikv_ghpr_integration_common_test/4484/pipeline/

feat(tikv): select correct go version in tikv integration tests

---

staging/jobs/pingcap-qe/ee-ops/prow_debug.groovy
staging/jobs/pingcap/tidb/latest/ghpr_build.groovy
staging/jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
staging/jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
staging/jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
staging/jobs/pingcap/tidb/latest/merged_mysql_test.groovy
staging/jobs/prow_debug.groovy
staging/pipelines/pingcap-qe/ee-ops/prow_debug.groovy
staging/pipelines/pingcap/tidb/latest/ghpr_build.groovy

We should skip the needless cloning when we have none dependences files in CI repo.

chore(staging/pipelines): try to skip default checkout of ci repo

---

jobs/tikv/aa_folder.groovy
jobs/tikv/migration/aa_folder.groovy
jobs/tikv/migration/latest/pull_integration_test.groovy
jobs/tikv/migration/latest/pull_unit_test.groovy
pipelines/tikv/migration/latest/pod-pull_integration_test.yaml
pipelines/tikv/migration/latest/pod-pull_unit_test.yaml
pipelines/tikv/migration/latest/pull_integration_test.groovy
pipelines/tikv/migration/latest/pull_unit_test.groovy

* add unit-test and integration-test ci pipeline for tikv/migration
Already test those pipelines on staging env
1. https://prow-ee.pingcap.net/jenkins/job/tikv/job/migration/job/pull_unit_test/7/
2. https://prow-ee.pingcap.net/jenkins/job/tikv/job/migration/job/pull_integration_test/6/

feat(tikv/migration): add ut and it ci

---

jobs/tikv/migration/latest/pull_integration_test.groovy
jobs/tikv/migration/latest/pull_unit_test.groovy
pipelines/tikv/migration/latest/pull_integration_test.groovy

fix(tikv/migration): fix jobdsl path

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy

tidb-tools not create release-branch from 5.3(include 5.3), so use master tidb-tools to run test

fix(tidb-binlog): integration-test use mster tidb-tools

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

Upload coverage to codecov, currently missing ut coverage data on https://app.codecov.io/github/pingcap/tidb
test link:
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/5997/pipeline

feat(tidb/ut): add tidb pull codecov coverage data

---

pipelines/tikv/migration/latest/pull_integration_test.groovy

add more integration test cases
replay link:
https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Fmigration%2Fpull_integration_test/detail/pull_integration_test/10/pipeline/314

feat(tikv/migration): add more test case tikvcdc

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy

Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

add tikv-cdc metric

---

pipelines/tikv/migration/latest/pull_integration_test.groovy

run tests in group, case grouping via shell scripts to avoid frequent modification of ci scripts
test link  https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Fmigration%2Fpull_integration_test/detail/pull_integration_test/18/pipeline/46

feat: run test in group

---

pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/release-6.4/pod-ghpr_build.yaml
pipelines/pingcap/tidb/release-6.4/pod-ghpr_unit_test.yaml

- add option in `$HOME/.bazelrc`

feat(pipglines/pingcap/tidb/latest): enable bazel repo cache

---

jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy

run compatibility tests only when some dm path files change.
replay test link
https://ci2.pingcap.net/job/dm_ghpr_compatibility_test/8802/console
https://ci2.pingcap.net/job/dm_ghpr_compatibility_test/8803/console

feat(dm): only run test when match some files changed

---

pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml

adjust pod resource limit from 12G to 16G

fix(tidb): adjust pod resource limit

---

jenkins/pipelines/goversion-select-lib.groovy

relase branch >= release-6.1 need use go1.19

feat: release-6.1 use go1.19

---

jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

releate to https://github.com/pingcap/tidb/pull/39267

fix: adjust timeout for sqllogic index test

---

jenkins/pipelines/ci/pd/pd_ghpr_build.groovy

replay ci with go1.19 link
https://ci2.pingcap.net/job/pd_ghpr_build/9349/console

feat: pd release-6.1 use go1.19

---

pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy

remove some real tikv test that not exist on release-6.1 and release-6.2

fix(tidb): remove realtikv tests

---

pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy

mysql test on release-6.1 not output junit xml report

fix: 6.1 not output any junit report

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy

replay test 
https://ci.pingcap.net/job/tidb_ghpr_mybatis/11674/console

fix: fix mybatis test

---

jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy
jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy

feat: mergeci 6.1 use go1.19

---

jobs/pingcap/tiflow/aa_folder.groovy
jobs/pingcap/tiflow/latest/ghpr_verify.groovy
jobs/pingcap/tiflow/release-5.3/aa_folder.groovy
jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
jobs/pingcap/tiflow/release-6.0/aa_folder.groovy
jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
jobs/pingcap/tiflow/release-6.1/aa_folder.groovy
jobs/pingcap/tiflow/release-6.1/ghpr_verify.groovy
pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-5.3/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.0/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.1/pod-ghpr_verify.yaml
staging/jobs/pingcap/tiflow/latest/ghpr_verify.groovy
staging/jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
staging/jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
staging/pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
staging/pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy

migration tiflow verifyci from idc to ksyun

feat: migrate tiflow verifyci to ksyun

---

jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy

curl not fail even 404, this will puzzle when debuging
add --fail option for curl

fix: add --fail for curl when not exist

---

pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy

correct pod template file path

fix: correct pod file path

---

pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-5.3/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-6.0/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-6.1/pod-ghpr_verify.yaml

feat: add GOPATH and GOCACHE

---

jobs/pingcap/tiflow/latest/ghpr_verify.groovy
jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
jobs/pingcap/tiflow/release-6.1/ghpr_verify.groovy

Temporarily disable tiflow ci on ksyun. revert this after ksyun adds machine resources

feat: tmp disable tiflow ci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

* add retry to fix unexpected error when download file from fileserver

feat: make download file from fileserver more stable

---

pipelines/pingcap/tidb-engine-ext/latest/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/release-6.1/pod-ghpr_build.yaml
pipelines/pingcap/tidb/release-6.1/pod-ghpr_check.yaml
pipelines/pingcap/tidb/release-6.1/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/release-6.1/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/release-6.1/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/release-6.2/pod-ghpr_build.yaml
pipelines/pingcap/tidb/release-6.2/pod-ghpr_check.yaml
pipelines/pingcap/tidb/release-6.2/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/release-6.2/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/release-6.2/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/release-6.3/pod-ghpr_build.yaml
pipelines/pingcap/tidb/release-6.3/pod-ghpr_check.yaml
pipelines/pingcap/tidb/release-6.3/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/release-6.3/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/release-6.3/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/release-6.4/pod-ghpr_build.yaml
pipelines/pingcap/tidb/release-6.4/pod-ghpr_check.yaml
pipelines/pingcap/tidb/release-6.4/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/release-6.4/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/release-6.4/pod-ghpr_unit_test.yaml
pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-5.3/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-6.0/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/release-6.1/pod-ghpr_verify.yaml

fix(pipelines/pingcap/tidb): current ceph-fs is slow

---

jobs/pingcap-qe/aa_folder.groovy
jobs/pingcap/aa_folder.groovy
jobs/tikv/aa_folder.groovy

unauthenticated api rate limit is 60/hour.

perfer to git url to avoid github api rate limit

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

* build image for 6.5
* remove dmr version cache image

feat: add build cache image fot 6.5

---

jobs/pingcap/tiflow/latest/ghpr_verify.groovy
jobs/pingcap/tiflow/release-5.3/ghpr_verify.groovy
jobs/pingcap/tiflow/release-6.0/ghpr_verify.groovy
jobs/pingcap/tiflow/release-6.1/ghpr_verify.groovy

Revert "feat: tmp disable tiflow ci"

---

jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy

fix: adjust timeout for integration mysql test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

adjust goproxy to avoid go mod download timeouts caused by the two network

feat: adjust internal goproxy

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy

feat(tidb):  print trigger job link

---

jenkins/pipelines/qa_release_test.groovy

Revert "Update qa_release_test.groovy"

---

jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_integration_cdc_test.yaml

Gray scale test on prod, not update commit status actually

feat(tidb): test tidb merged-cdc pipeline on prod

---

jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml

Gray scale test on prod, not update commit status actually

feat: test merged-br on prod

---

staging/jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
staging/jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
staging/jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
staging/jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
staging/jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
staging/jobs/pingcap/tidb/latest/merged_mysql_test.groovy
staging/jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
staging/pipelines/pingcap/tidb/latest/merged_common_test.groovy

* disable test pipeline on staging
* fix default container to java for merged-common-test

fix(staging): fix merged-common default container

---

jobs/ti-community-infra/aa_folder.groovy
jobs/ti-community-infra/test-prod/aa_folder.groovy
jobs/ti-community-infra/test-prod/prow_debug.groovy
pipelines/ti-community-infra/test-prod/pod-prow_debug.yaml
pipelines/ti-community-infra/test-prod/prow_debug.groovy

test on repo: ti-community-infra/test-prod (controlled under prow.tidb.net)

chore(test-prod): add test prow-jenkins job in prod jenkins server

---

pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
scripts/pingcap/br/integration_test_download_dependency.sh

* add more cdc integration tests
* add more br integration tests

feat(tidb/merged): merged add more tests

---

jobs/pingcap/tidb/latest-prow/aa_folder.groovy
jobs/pingcap/tidb/latest-prow/ghpr_build.groovy
jobs/pingcap/tidb/latest-prow/ghpr_check.groovy
jobs/pingcap/tidb/latest-prow/ghpr_check2.groovy
jobs/pingcap/tidb/latest-prow/ghpr_mysql_test.groovy
jobs/pingcap/tidb/latest-prow/ghpr_unit_test.groovy
libraries/tipipeline/vars/prow.groovy
pipelines/pingcap/tidb/latest-prow/ghpr_build.groovy
pipelines/pingcap/tidb/latest-prow/ghpr_check.groovy
pipelines/pingcap/tidb/latest-prow/ghpr_check2.groovy
pipelines/pingcap/tidb/latest-prow/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest-prow/ghpr_unit_test.groovy

current it will not be triggered.

feat(jobs/pingcap/tidb): add prow's jenkins jobs to debug

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy

test link https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_mybatis/detail/tidb_ghpr_mybatis/12083/pipeline/

feat: add retry for mybatis test

---

jobs/pingcap/tidb/latest/merged_e2e_test.groovy
jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
jobs/pingcap/tidb/latest/merged_integration_ddl_test.groovy
jobs/pingcap/tidb/latest/merged_integration_mysql_test.groovy
pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_ddl_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_mysql_test.yaml

add 4 merged pipeline to test stablity on prod, not update commit status currently.
* integration-mysql-test
* integration-copr-test
* integration-ddl-test
* e2e-test

feat(tidb): add 4 merged pipeline prod

---

jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy

* br merged into tidb repo since v5.2.0
* dumpling merged into tidb repo since v5.3.0

fix(build): correct hash for old version of br and dumpling

---

jenkins/pipelines/cd/multi-arch-sync-docker.groovy

fix(build): publish dm image since v5.3.0

---

jenkins/jobs/ci2/tikv/pd/ghpr_build.groovy
jobs/tikv/pd/aa_folder.groovy
jobs/tikv/pd/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/tikv/pd/latest/ghpr_build.groovy
pipelines/tikv/pd/latest/pod-ghpr_build.yaml

current will it will be triggered manually

refactor(jobs/tikv/pd): refactor job pd_ghpr_build

---

staging/jobs/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
staging/pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
staging/pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml

test new pipeline : integration-jdbc-test
test link  https://prow-ee.pingcap.net/jenkins/job/pingcap/job/tidb/job/merged_integration_jdbc_test/4/

feat(staging): add jdbc tests

---

pipelines/tikv/pd/latest/ghpr_build.groovy

Revert "fix(pipelines/tikv/pd): using other goproxy to avoid branch version issue"

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy

feat: add 6.5 to lts versions and sha256

---

jobs/pingcap/tidb/latest/merged_common_test.groovy
jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
jobs/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
pipelines/pingcap/tidb/latest/merged_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml

add 4 refactor merged pipeline to test stablity on prod
* common_test
* sqllogic_test
* integration_common_test
* integrationi_jdbc_test

feat(prod/pingcap/tidb): test merged pipeline stablity on prod

---

jobs/pingcap/tidb/latest/merged_common_test.groovy
jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
jobs/pingcap/tidb/latest/merged_integration_ddl_test.groovy
jobs/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
jobs/pingcap/tidb/latest/merged_integration_mysql_test.groovy
jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
pipelines/pingcap/tidb/latest/merged_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_ddl_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml

refactor some merged-pipelines to prow style
* merged_common_test
* merged_integration_common_test
* merged_integration_ddl_test
* merged_integration_jdbc_test
* merged_integration_mysql_test
* merged_sqllogic_test

refactor(pingcap/tidb): refactor some merged tests to prow style

---

jobs/pingcap/tidb/latest/merged_tiflash_test.groovy
pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_tiflash_test.yaml

add merged_tiflash_test to test stablity on prod

feat(prod/pingcap/tidb): test merged-tiflash-test on prod

---

jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
jobs/pingcap/tidb/latest/merged_tiflash_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_tiflash_test.yaml

refactor some merged-pipelines to prow style
* merged_integration_copr_test
* merged_tiflash_test

refactor(pingcap/tidb): refactor two merged tests to prow sytle

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

related to https://github.com/ti-community-infra/configs/pull/759

chore(pingcap/tidb): disable some mergeCI on master on idc-jenkins

---

pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
scripts/pingcap/br/integration_test_download_dependency.sh
scripts/pingcap/tiflow/ticdc_integration_test_download_dependency.sh

* update merged_integration_cdc_test cases name
* update dependency download shell scripts to use explicit params

fix(pingcap/tidb): merge cdc update cases

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_build.yaml
pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
staging/pipelines/pingcap/tidb/latest/pod-merged_build.yaml
staging/pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml

upgrade go1.19.5 for tidb

---

jenkins/pipelines/cd/tidb-operator.groovy

docker limit pull rate
use pingcap internal registry mirror

fix: operator use docker mirror

---

pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy

tested  https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fmerged_integration_mysql_test/detail/merged_integration_mysql_test/166/pipeline/332

fix: fix missing env TEST_PART

---

pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/merged_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
pipelines/pingcap/tiflow/latest/ghpr_verify.groovy

fix(pipelines/pingcap): increase timeout for checkout with multi repos

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy

fix(pipelines/pingcap/tidb): fix codecov uploading to pull requests

---

pipelines/pingcap/tidb/latest/ghpr_check.groovy

migrate license check from github action to ksyun jenkinis.
original github action workflow https://github.com/pingcap/tidb/blob/master/.github/workflows/misc.yml
tested  https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check/detail/ghpr_check/11108/pipeline

feat: add misc check task

---

pipelines/pingcap/tidb/latest/ghpr_check.groovy

Reverts PingCAP-QE/ci#1718
it has been in the tidb's makefile.

Revert "feat: add misc check task"

---

jobs/pingcap-qe/ci/prow-presubmits.yaml
jobs/pingcap/tidb/latest/prow-postsubmits.yaml
jobs/pingcap/tidb/latest/prow-presubmits.yaml
jobs/pingcap/tidb/release-6.1/prow-presubmits.yaml
jobs/pingcap/tidb/release-6.2/prow-presubmits.yaml
jobs/pingcap/tidb/release-6.3/prow-presubmits.yaml
jobs/pingcap/tidb/release-6.4/prow-presubmits.yaml
jobs/tikv/pd/latest/prow-presubmits.yaml

fix(jobs): update prow jobs

---

jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy

feat: nightly use rocky

---

jenkins/pipelines/cd/pre-release-docker-rocky-sync.groovy
jenkins/pipelines/cd/tiup/pre-release-tiup.groovy

feat: v6.6.0 will use rocky

---

jenkins/pipelines/cd/tidb-operator.groovy

feat(operator): add resource request for builder pod

---

jenkins/pipelines/cd/tidb-operator.groovy

From 12min to 1min
add go proxy in china

feat: speed up go mod download

---

libraries/tipipeline/vars/prow.groovy

fix(libraries/tipipeline/vars): enable tag fetching in `prow.checkoutRefs`

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_build.yaml
pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
staging/pipelines/pingcap/tidb/latest/pod-merged_build.yaml
staging/pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml

update bazel to 6.0 LTS

---

staging/pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
staging/pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy

* adjust timeout
* fix tidb-test code cache

fix: fix tidb-test pipeline on staging

---

jobs/pingcap/tidb-test/aa_folder.groovy
jobs/pingcap/tidb-test/latest/ghpr_build.groovy
jobs/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
jobs/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
jobs/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
jobs/pingcap/tidb-test/latest/prow-presubmits.yaml
pipelines/pingcap/tidb-test/latest/ghpr_build.groovy
pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb-test/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_jdbc_test.yaml
pipelines/pingcap/tidb-test/latest/pod-ghpr_integration_mysql_test.yaml
pipelines/pingcap/tidb-test/latest/pod-ghpr_mysql_test.yaml

* refactor tidb-test pipelines and migrate to ksyun
* refactor to prow style pipelines

feat(pingcap/tidb-test): prod refactor tidb-test pipeline

---

pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

request == limit = 32 core + 64GB

feat(pipelines/pingcap/tidb/latest): limit resource for unit test

---

pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml

request == limit = 8 core + 24 GB

feat(pipelines/pingcap/tidb/latest): make the pod of build job be guaranteed

---

libraries/tipipeline/vars/prow.groovy

feat(libraries/tipipeline/vars): batch checkput pulls

---

pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

Revert "feat(pipelines/pingcap/tidb/latest): limit resource for unit test"

---

jenkins/pipelines/cd/tidb-operator.groovy

fix: correct goproxy

---

jenkins/pipelines/cd/pre-release-check.groovy
jenkins/pipelines/cd/pre-release-docker-rocky-sync.groovy

6.6.0 RC problem
- release check only main image, no need to check rocky
- sync more image for rokcy

fix: v6.6.0 use rocky

---

jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy

feat: bump nightly to v6.7.0 alpha

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_mysql_test.groovy

fix(pipelines/pingcap/tidb): fix binary cache for binary in pre merge mode

---

jobs/pingcap/tidb-test/latest/prow-presubmits.yaml

Add conditional trigger and skip report to perform a few days of grayscale testing.

chore(jobs/pingcap/tidb-test): add conditional triggers

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-sanitizer.groovy
jenkins/pipelines/ci/tiflash/tiflash_regression_test_daily.groovy
jenkins/pipelines/ci/tiflash/tiflash_schrodinger_test.groovy

mange tiflash pipeline with git
* tiflash-ghpr-sanitizer
* tiflash_regression_test_daily
* tiflash_schrodinger_test

feat: mange tiflash pipeline with git

---

scripts/ops/get-artifacts-of-pull-request.sh

in file `get-artifacts-of-pull-request.sh`.

feat(scripts/ops): add step to instll github client

---

jenkins/pipelines/ci/tikv/tikv_ghpr_build_arm64.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_build_release.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_darwin_amd64.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_darwin_arm64.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_linux_arm64.groovy

* Manage 3 clippy pipelines groovy with git
* Remove some unnecessary logic

feat: add 3 tikv clippy pipelines

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/merged_unit_test.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
staging/pipelines/pingcap/tidb/latest/merged_unit_test.groovy

chore(pipelines/pingcap/tidb): no need to upload test report files to fileserver

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/merged_unit_test.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy
staging/pipelines/pingcap/tidb/latest/merged_unit_test.groovy

Revert "chore(pipelines/pingcap/tidb): no need to upload test report files to fileserver"

---

jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_downstream_coverage.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/engine_ghpr_integration_test.groovy

manage tiflow pipelines with jobdsl

feat(pingcap/tiflow): manage tiflow with jobdsl

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

fix: add credentials env

---

jobs/pingcap/tidb-test/latest/prow-presubmits.yaml

Enable ci report on tidb-test master.

chore: enable report

---

jenkins/pipelines/cd/release-check.groovy
release-checker/checker/pkg/image.py

- rocky will use docker >= 20
- rocky lightning remove br

fix: 6.6.0 rocky check

---

jenkins/pipelines/goversion-select-lib-upgrade-temporary.groovy

add temp lib.groovy for upgrade to go1.20

chore: add temp lib.groovy for upgrade to go1.20

---

jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy

Add timeout, set 3 hours.
Tested: https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/898/

chore: set sanitizer daily timeout to 6 hours

---

jenkins/jobs/ci/tidb-test/ghpr_build.groovy
jenkins/jobs/ci/tidb-test/tidb_test_ghpr_integration_test.groovy
jenkins/jobs/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

manage tidb-test pipeline with jobdsl.

chore: manage tidb-test pipeline with jobdsl

---

jenkins/pipelines/ci/tidb/tidb_merged_pr_build.groovy
jenkins/pipelines/goversion-select-lib-upgrade-temporary.groovy

chore: support go1.20

---

jobs/OWNERS
jobs/pingcap/tidb/latest/prow-postsubmits.yaml
pipelines/OWNERS

chore(jobs/pingcap/tidb/latest): limit max_concurrency to 1 for merged ci jobs

---

jobs/pingcap/tidb/release-6.6/aa_folder.groovy

fix: add folder release-6.6

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy
jenkins/pipelines/cd/atom-jobs/docker-common.groovy

chore: add retry on build pipeline

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
jobs/pingcap/tiflow/release-6.2/aa_folder.groovy
jobs/pingcap/tiflow/release-6.2/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.2/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.2/pod-ghpr_verify.yaml

tiflow ci on master upgrade to go1.20.
* add go1.20 on old pipelines
* split pipelines for latest branch because goversion diverse from v7.0.0

chore(pingcap/tiflow): tiflow upgrade to go1.20

---

jenkins/pipelines/ci/tidb-tools/tools_ghpr_integration_test.groovy
jenkins/pipelines/ci/tidb-tools/tools_ghpr_unit_test.groovy

tidb-tools ci on master upgrade to go1.20.
releated to https://github.com/pingcap/tidb-tools/issues/701.

chore(pingcap/tidb-tools): tidb-tools master upgrade to go1.20
