sync_ci/pkg/parser/ci_log.go
sync_ci/pkg/parser/regex_rules.json

only use the first case when multiple case failed.

modify: use the first case only.

---

sync_ci/pkg/parser/regex_rules_test.go
sync_ci/pkg/parser/rules_test.go

Pls check this before #39 
The tests in **parser** package now use path relative to /sync_ci, which make it have to be compiled and run manually from /sync_ci, rather than be processed along with other tests (although there's none for now) by `go test ./...`.
Change path to be relative to the /sync_ci/pkg/parser folder, namely to the test file it self.

Update test path in parser

---

jenkins/pipelines/build-linux-amd64-enterprise.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-arm.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_build_release.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy
jenkins/pipelines/copr-test-old.groovy
jenkins/pipelines/tikv_ghpr_integration_common_test.groovy
jenkins/pipelines/tikv_ghpr_test.groovy

We can't use scl_enable before
https://github.com/sclorg/scl-utils/pull/35 is released.

*: use source directly to enable devtoolset-8

---

jenkins/pipelines/ci/tidb/tidb_check_title.groovy

Disallow terrible titles like `foo:do something` or `: do something`

make tidb_title_check more strict

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_mybatis.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

Put go1.16 logic code after release test params setting in case of job failed when triggered by qa_release.

Put go1.16 logic code after release test params setting

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy

fix error when some ci test case not use go1.16, set test-slave node

fix some miss go1.16 node setting on some test step

---

jenkins/pipelines/ci/tikv/tikv_check_release_note.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_build_release.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_compatibility_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

-  tikv ci upgrade go version from 1.13 to 1.16.4, only for branch master
-  tikv test use agent pod with memory volume

upgrade tikv ci go version from 1.13 to 1.16.4, only for branch master

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_build.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

to fix error `go: modules disabled by GO111MODULE=off; see 'go help modules'`
gomodule is enabled by default in ticdc

ci: remove GO111MODULE=off in ticdc pipelines

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

fix the failure of Lightning's integration test.

tikv importer: use release-5.0 branch instead of master as default

---

jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy

We move `unit test` and `leak test` to [nightly test](https://github.com/PingCAP-QE/ci/blob/main/jenkins/pipelines/nightly/tidb/tidb_nightly_unit_test.groovy) because of:
1. Leak test rarely failed.
2. Unit test is almost the same as what `check_dev_2` does. (Unit test sets `config.checkBeforeDropLDFlag=1`.)

mv unit-test and leak-test to nightly-test

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

The idea is from travis CI, which will skip testing when commit message or title contain "[ci skip]".

allow skip CI

---

jenkins/Dockerfile/release/tidb-backup-manager-arm64
jenkins/Dockerfile/release/tidb-operator-arm64
jenkins/pipelines/cd/build-operator-arm-image.groovy

This PR will:
* Add TiDB-Operator related Dockerfile and Jenkins pipeline.
* tidb-backup-manager-arm64 Dockerfile is switched to `centos:8` to avoid libc related problems.
Before Merge, we should:
1. Change `baseUrl` in `jenkins/pipelines/cd/build-operator-arm-image.groovy` to use the right branch(instead of `operator-arm64`).
2. Make sure those images are working.

Add TiDB-Operator related Dockerfile and Jenkins pipeline.

---

jenkins/pipelines/ci/pd/pd_ghpr_build.groovy
jenkins/pipelines/ci/pd/pd_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_integration_compatibility_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_intergration_common_test.groovy
jenkins/pipelines/ci/pd/pd_ghpr_intergration_ddl_test.groovy
jenkins/pipelines/ci/pd/pd_integration_test_ci.groovy
jenkins/pipelines/ci/pd/pd_update_commit_status.groovy

decoupling pd integration test from pr merge:
* all pd integration test required contexts will be removed when try to merge pr
* trigger all pd integration test after pr merged
* update commit status then send feishu report to group
* /run-integration-tests trigger all integration test ci,  /run-all-tests will not trigger any integration test ci anymore

decoupling pd integration test from pr merge

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

BR needs [TDE feature](https://github.com/pingcap/br/pull/1273) be tested, which needs tikv-ctl tools

Add tikv-ctl support

---

jenkins/Dockerfile/centos7_golang-1.13-arm64
jenkins/Dockerfile/centos7_golang-1.16-arm64
jenkins/Dockerfile/centos7_jenkins_arm64
jenkins/Dockerfile/jnlp-slave-arm64

This PR has added three docker images, names are:
* hub.pingcap.net/jenkins/centos7_golang-1.13-arm64:latest
* hub.pingcap.net/jenkins/centos7_golang-1.16-arm64:latest
* hub.pingcap.net/jenkins/centos7_jenkins-arm64:latest
Those are modified from amd64 Dockerfiles from:
* jenkins/Dockerfile/centos7_golang-1.13
* jenkins/Dockerfile/centos7_golang-1.16
* jenkins/Dockerfile/centos7_jenkins
However, `hub.pingcap.net/jenkins/centos7_jenkins-arm64` has some modifications, as follows:
* Removed `gdb`, `jq` as they does not present on centos7-arm64
* Compiled Git 2.18
Note: `hub.pingcap.net/jenkins/centos7-arm64:latest` is the same as `arm64v8/centos:7`

Add centos7_jenkins along with golang images

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

BR TDE test need KMS service, KES binary had been upload to CDN, ci script should be modified to download kes binary.
This pr has been tested in ci debug env.

br: Upload kes

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

1. use fileserver instead stash. The compress step cannot be omitted so fileserver only speed up file transfer.
2. merge shell scripts. Each `sh` keyword in groovy will trigger master send `scripts` to slaver, which is a heavy workload. So merge these `download shell scripts` into one `sh` keyword in groovy and parallel downloading will reduce much CI time.
3. split little slow cases. Now it has much parallel nodes to do tests and some nodes finish tests much more quickly. In the best case, all nodes finish tests at the same time. So the PR try to reduce the granularity of way to split tests in order to be  more closer to the best case and reduce the number of nodes besides.

BR: use fileserver instead stash, merge shell scripts to speed up, split little slow cases

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy

golangci-lint version need upgrade from v1.21.0 to v1.29.0 on master&release-5.x

tidb: update golangci-lint version on master / release-5.x

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* To reduece ticdc integration test time, adjust concurrent test number from 8 to 20

adjust concurrent test number from 8 to 20, reduce integration test time

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Reverts PingCAP-QE/ci#347 due to out of index error

Revert "adjust concurrent test number from 8 to 20, reduce integration test time"

---

jenkins/pipelines/ci/pd/pd_ghpr_build_arm64.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_build_arm64.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_build_arm64.groovy

* add thress ci pipeline for tidb & tikv & pd
* `/run-build-arm64` will trigger jenkins ci to build arm64 binary.(default sre-bot will comment binary download url on pr)
* `/run-build-arm64 comment=false` only build arm64 binary (sre-bot will not comment binary download url)

arm64 ci: add build arm64 for tidb&tikv&pd

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy

close #353
refine TiDB CI after BR merged into TiDB
1. add `tidb-br` upstream for br_integration_test.
2. skip gcs tests due to https://github.com/googleapis/google-cloud-go/pull/3509

refine TiDB's ci for BR merged into TiDB

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy

* example hotfix branch release-4.0-20210727, build enterprise plugin use branch release-4.0 (remove date suffix because hotfix branch with date not been created  on plugin repo)

fix: hotfix branch build plugin by remove date suffix

---

jenkins/pipelines/ci/dm/dm_ghpr_new_test.groovy

* split other test
* support setup mysql ssl certs

chore: update dm ci

---

jenkins/pipelines/ci/tikv/tikv_ghpr_build.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

* remove useless job data report api
* hotfix branch test use correct image, example release-4.0-20210724 use image hub.pingcap.net/jenkins/tikv-cached-release-4.0:latest

tikv: hotfix branch use correct image

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Currently integration test stage name is `integration test step_12`, we can't find the running case directly (have to click the stage name and expand details).

ticdc: use case name in integration step

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Reverts PingCAP-QE/ci#419
Coverage step uses hard coded step name, ref:
https://github.com/PingCAP-QE/ci/blob/09643537687a5d956bb3543095595fe51fa739bf/jenkins/pipelines/ci/ticdc/integration_test_common.groovy#L286-L289

Revert "ticdc: use case name in integration step"

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy

* use a new k8s cluster to run test
* a more detailed monitor dashboard is available on this new cluster

ticdc: use another k8s cluster run test

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* pod lable diff against go version to avoid pod mixing

ticdc: fix pod version

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy

after br merged into tidb, we had two different integration tests in br groovy.
we distinguish by ghprbTargetBranch, but sometimes we had hot fix branch like `release-5.1-20210926`, so we need trimPrefix for these branch to run the correct br groovy.

br: trigger the correct branch ci

---

jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

Migrate DM CI to TiCDC so that dm-integration-test and dm-compatibility-test are ok to run in TiCDC repo.

ticdc: migrate dm ci to ticdc

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

as https://github.com/pingcap/ticdc/pull/3228 was merged, we can revert this change now

dm: revert comment

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

* test_tikv_go1130_memvolume own a memory dir /home/jenkins/agent/memvolume

tikv: use a node with memory dir

---

jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

when running dm-it test, pod use almost 4G memory, so i add some resources request/limit config in pod template
see the metrics here
btw, because all dm-ci was moved into ticdc folder, i just delete the whole dm folder

add resource request in dm ci

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

ticdc repo can not run intergration test with tidb PR
command
```
/run-integration-tests /tidb=pr/30008 
```
```
[2021-11-25T06:43:52.238Z] + tidb_url=http://fileserver.pingcap.net/download/builds/pingcap/tidb/pr/b786f429e46104fcbdab1d4880f99812b443036d/centos7/tidb-server.tar.gz
[2021-11-25T06:43:52.238Z] + tidb_archive_path=bin/tidb-server
[2021-11-25T06:43:52.238Z] + tikv_url=http://fileserver.pingcap.net/download/builds/pingcap/tikv/f6ec493e8f0a5af7b4ea5652c7073af81d15d22d/centos7/tikv-server.tar.gz
[2021-11-25T06:43:52.238Z] + pd_url=http://fileserver.pingcap.net/download/builds/pingcap/pd/ca16d8d99e94fd6fab230089df23139381431387/centos7/pd-server.tar.gz
[2021-11-25T06:43:52.238Z] + tiflash_url=http://fileserver.pingcap.net/download/builds/pingcap/tiflash/master/e655a42735301dde42e733 …
```

fix  bin/tidb-server: Not found in archive issue

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Ignore upload coverage error so that we don't need to rerun tests.

cdc: ignore upload coverage error

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

[This PR](https://github.com/pingcap/tidb/pull/30692) makes the test run in serial. We should increase the timeout for the go test.

jenkins/ci/tidb: increase check_2 timeout for gotest

---

jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy
jenkins/pipelines/cd/nightly/build-darwin-amd64-4.0.groovy
jenkins/pipelines/cd/nightly/build-darwin-arm64-4.0.groovy
jenkins/pipelines/cd/nightly/build-linux-arm64-4.0.groovy
jenkins/pipelines/cd/nightly/release_cdc_docker_nightly.groovy
jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/optimization-build-tidb-linux-amd.groovy
jenkins/pipelines/cd/release-enterprise-docker.groovy
jenkins/pipelines/cd/release_cdc_docker.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test-hotfix.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirrior-update-test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/qa_release_test.groovy
misc_tools/create_branch.sh
misc_tools/create_tag.py
misc_tools/get_hash.sh

Part of step-4 in https://github.com/pingcap/ticdc/issues/3749
Change with following scripts
```bash
sed -i "s/github.com\/pingcap\/ticdc/github.com\/pingcap\/tiflow/g" $(find . -type f)
sed -i "s/github.com:pingcap\/ticdc/github.com:pingcap\/tiflow/g" $(find . -type f)
sed -i "s/githubusercontent.com\/pingcap\/ticdc/githubusercontent.com\/pingcap\/tiflow/g" $(find . -type f)
```
Besides several `pingcap/ticdc` are changed to `pingcap/tiflow` manually, since not all `pingcap/ticdc` should be changed.
Unchanged contents include
- fileserver build path
- docker image name

ci/cd: rename pingcap/ticdc to pingcap/tiflow

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

This is a temporary workaround for flaky test https://github.com/pingcap/tidb/issues/30470

Disable pipelined pessimistic lock in TiDB CI

---

jenkins/Dockerfile/release/linux-amd64/tiflash

Docker with older versions does not support default args syntax iwth whitespace.
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>

compat w/ jenkins docker

---

jenkins/Dockerfile/release/debug-image/ticdc

```
[2022-01-13T09:19:32.842Z] Installing for dependencies:
[2022-01-13T09:19:32.842Z]  tcp_wrappers-libs      x86_64      7.6-77.el7               base          66 k
[2022-01-13T09:19:32.842Z] Updating for dependencies:
[2022-01-13T09:19:32.842Z]  libcurl                x86_64      7.29.0-59.el7_9.1        updates      223 k
[2022-01-13T09:19:32.842Z] 
[2022-01-13T09:19:32.842Z] Transaction Summary
[2022-01-13T09:19:32.842Z] ================================================================================
[2022-01-13T09:19:32.842Z] Install  1 Package  (+1 Dependent package)
[2022-01-13T09:19:32.842Z] Upgrade  3 Packages (+1 Dependent package)
[2022-01-13T09:19:32.842Z] 
[2022-01-13T09:19:32.842Z] Total download size: 2.3 M
[2022-01-13T09:19:32.842Z] Is this ok [y/d/N]: Exiting on user …
```

cdc debug image fail

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

Reverts PingCAP-QE/ci#554
download file https://download.pingcap.org/tidb-enterprise-tools-nightly-linux-amd64.tar.gz  often fails due to network problems

Revert "update ticdc ci: use the nightly sync_diff_inspector"

---

jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

replay (running): https://ci2.pingcap.net/job/dm_ghpr_integration_test/3692/
currently the CI uses nightly version of sync-diff and it has some problem. In order to cope with the urgent release, I hardcoded a version of sync-diff. We will revert it later

DM CI use a pinned version of sync-diff

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_downstream_coverage.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* skip binary build if found cache binary in fileserver
* move coverall upload coverage file step to downstream pipeline (parse and upload file currently taken more than 20min, it is suffering)

ticdc some improve

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* release branch and master branch use the different sync_diff version

release branch use diff sync_diff version

---

jenkins/pipelines/cd/multibranch/build_tikv_multi_branch.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_build.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_coverage.groovy
jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

We use to check grpcio version and decide to choose what gcc is used.
But now gcc 8 has been used for v5.x for more than almost a year now
without any issues, and the only versions remain using legacy gcc are
v4.0.x.
grpcio 0.10.0 is released, the old check rule doesn't work anymore.
Writing new rules for only one version seems overkilled to me, hence
this PR switches to use gcc 8 all the time

*: always use gcc 8

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_build.groovy
jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

* master branch upgrade go version to go1.18
we need merge this now for this block  https://github.com/PingCAP-QE/ci/pull/803
https://ci.pingcap.net/blue/organizations/jenkins/tidb_test_ghpr_build/detail/tidb_test_ghpr_build/1124/pipeline

tidb test upgrade go version to 1.18

---

jenkins/pipelines/goversion-select-lib.groovy

`br-stream` uses go 118 after merging master at https://github.com/pingcap/tidb/commit/a32b7f8ff911cca17f4febf6d11517f5624da4fc

Update feature branch golang version information for `br-stream`

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy

We have internal GOPROXY, no need for this as it may introduce weird problems like:
```
dial tcp: lookup goproxy.cn on <DNS_SERVER>:53: server misbehaving
```

Remove explicit GOPROXY define

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_br_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_cdc_test.groovy

* daily ci or merge ci trigger br/cdc integration test, we want get all test case results

make integration test fail fast Optional

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

* currently copr-test is unstable, we disable this ci on tidb mergeCI.

tmp disable copr-test in tidb mergeci

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

ref: task-5 in https://github.com/pingcap/tiflow/issues/5352
Skip ticdc integration test/kafka integration test if only changes engine code.

ci: skip ticdc integration tests if matching engine dir

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

After https://github.com/pingcap/tiflash/pull/5003, the target `page_ctl` is deprecated, need to remove it from CI.

Remove the deprecated target page_ctl

---

jenkins/pipelines/qa_release_test.groovy

This PR fixes issue introduced by #1048. There is a task.py(i.e. `/home/jenkins/task.py`) in `hub.pingcap.net/qa/ci-toolkit:lates` image, so we must not override the folder.

jenkins/pipeline: fix pod template to not override python script

---

jenkins/pipelines/ci/tikv/tikv_ghpr_integration-copr-test.groovy

Signed-off-by: yibin <huyibin@pingcap.com>
Previously, copr-test doesn't maintain different branches for different TiDB/TiKV releases. However, the copr-test is version sensitive, due to its functions.txt which maintains push-down-function-white-name-list. In release-6.0, TiKV supports new push down function 'mod', which adds a new entry in the white-name-list. But when we test older versions, like TiDB release 5.4 and before, we would encounter not-support error when push down 'mod' to TiKV of related versions.
This PR will ensure that we use correct copr-test branch for test.

Use copr-test related version instead of using latest master

---

jenkins/pipelines/ci/tispark/integration_test.groovy

**What**: Disable tikv-client unit test in TiSpark integration_test.
**Why**: Because tikv-client unit test has been already done in GitHub Action, we need not add it to the integration test again.

Disable tikv-client unit test in TiSpark integration_test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_copr_test.groovy

* support to trigger copr-test in tidb pr, comment /run-integration-copr-test copr-test=pr/xxx
* also support specify copr-test branch, comment  comment /run-integration-copr-test copr-test=branch-name

copr test support specify pr

---

jenkins/pipelines/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

Using `-part` to split mysql-test to 4 parts
Update `test3_result` file name.

tidb-test: split mysql-test to 4 parts

---

jenkins/pipelines/ci/tidb/tidb_integration_test_ci.groovy

* tidb_e2e_test has been fixed, currently is stable for tidb master.
https://ci.pingcap.net/blue/organizations/jenkins/tidb_e2e_tests/activity

tidb(merge-ci): add tidb_e2e_tests to mergeci

---

jenkins/pipelines/ci/tidb/tidb_ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy

What: revert: refactor `if` expression with `==~` instead of `=~`
Wny: `==~` is strict mode.

tidb: fix tidb-test branch from pr comment

---

pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

- mount empty dir volume at /home/jenkins/.tidb

feat(pipelines/pingcap/tidb): add standalone volume for bazel output

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy

Fix `/tidb-tools=xxx` doesn't work
```
[2022-08-26T09:54:29.914Z] [Pipeline] Start of Pipeline
[2022-08-26T09:54:29.929Z] [Pipeline] echo
[2022-08-26T09:54:29.932Z] TIKV_BRANCH=release-4.0
[2022-08-26T09:54:29.934Z] [Pipeline] echo
[2022-08-26T09:54:29.935Z] PD_BRANCH=release-4.0
[2022-08-26T09:54:29.937Z] [Pipeline] echo
[2022-08-26T09:54:29.937Z] TIDB_BRANCH=release-4.0
[2022-08-26T09:54:29.941Z] [Pipeline] End of Pipeline
[2022-08-26T09:54:29.946Z] java.lang.NullPointerException: Cannot invoke method getAt() on null object
[2022-08-26T09:54:29.946Z] 	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
```
ref: https://github.com/pingcap/tidb-binlog/pull/1202#issuecomment-1228296628

ci: fix tidb-tools branch in binlog ci

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy

Use `${TIDB_TOOLS_BRANCH}` variable instead of `master`

ci: fix tidb-tools sha1 branch

---

jenkins/jobs/ci/tidb/ghpr_build.groovy

Why: current the context is required in github branch protection.

revert(jenkins/jobs): not set  excluded regions in tidb build job dsl

---

jenkins/jobs/ci/tidb/ghpr_build.groovy
jobs/pingcap/tidb/latest/ghpr_build.groovy

to switch target branches:
- master
- feature branches: `feautre_*` or `feature/*`
- release branches for `6.2+`

feat(jobs/pingcap/tidb,jenkins/jobs/ci/tidb): switch trigger to new server for `tidb_ghpr_build`

---

jenkins/jobs/ci/tidb/ghpr_build.groovy
jenkins/jobs/ci/tidb/ghpr_check.groovy
jenkins/jobs/ci/tidb/ghpr_check2.groovy
jenkins/jobs/ci/tidb/ghpr_mysql_test.groovy
jenkins/jobs/ci/tidb/ghpr_unit_test.groovy
jobs/pingcap/tidb/latest/ghpr_build.groovy
jobs/pingcap/tidb/latest/ghpr_check.groovy
jobs/pingcap/tidb/latest/ghpr_check2.groovy
jobs/pingcap/tidb/latest/ghpr_mysql_test.groovy
jobs/pingcap/tidb/latest/ghpr_unit_test.groovy

* currently tidb ci generates 1500 build histories per week, we need to keep history for 1 month.

tidb(ci): adjust keep days to 30, remove keep nums

---

jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy

* tics test fail due to cpu nums diff between node and pod, so we adjust cluster back to original

tidb mergeci: tics test failed on ksyun due to cpu num logic

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-build.groovy

As we upgrade the compiler version, the static lints checks and format could be changed after the compile toolchain is upgraded.
Only apply lints and format check on the master branch.
Changing `TiFlashTestBasic.cpp` in master don't raise any lint errors, but the cherry-pick to release-5.4 raise errors.
https://github.com/pingcap/tiflash/pull/5924

tiflash: Only apply lint and format on master branch

---

pipelines/pingcap/tidb-engine-ext/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy

some builds will failed on write on `/dev/null`, maybe the file permission and type was changed.

chore(pipelines/pingap): add ls command for `/dev/null` file

---

jenkins/pipelines/ci/ticdc/engine_ghpr_integration_test.groovy

Related to https://github.com/pingcap/tiflow/pull/7240

engine_ghpr_integration_test: Use Go 1.19

---

pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy

ref issue: https://github.com/pingcap/tidb-test/issues/1987

feat(pipelines/pingcap/tidb): restore `ghpr_mysql_test` with binary compiled with `-race`

---

pipelines/pingcap/tidb-engine-ext/latest/pod-ghpr_unit_test.yaml

* correct image name : hub.pingcap.net/tiflash/tiflash-llvm-base:latest is not exist

ci: fix wrong pod image

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy
jenkins/pipelines/ci/tiflash/tiflash-cache-update-multibranch.groovy
jenkins/pipelines/ci/tiflash/tiflash-ghpr-build.groovy
jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy

1. When build failed, will show a link pointing the build URL inline. Sometimes BlueOcean does not show the Trigger Build, and this could be helpful.
2. Fixed idents for some scripts. (If you want to view diff, please diff without whitespace)
3. Disable coverage in the unit test phase, as currently it does not work well. We can enable it later when the efficiency can be improved by running it in the post PR stage and providing more detailed coverages.
4. Adjusted unit test CPU request from 10c to 12c, since our test concurrency is set to 12. Also changed the limit from 20c to 12c, because 12c should be enough. (this limit change may be reverted later, if we really incur some problems)

tiflash: improve error notice and fix idents

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy

* fix trigger downstream pipeline with error 
```shell
Cannot invoke method getResult() on null object
```

tiflash: fix trigger tiflash-build-common error

---

jenkins/pipelines/ci/ticdc/engine_ghpr_integration_test.groovy

ref: https://github.com/pingcap/tiflow/pull/7377
Tiflow will simplify binaries that are built from `make engine`.
Replace `make engine` with `make tiflow tiflow-demo`

ci(tiflow): update make engine script

---

libraries/tipipeline/vars/component.groovy

- default trunk branch set to `master`, but caller can give custom value, as:
```groovy
component.checkout('xxx.git', 'depA', 'feature/abc', '', "", "custom-trunk-branch")
```

fix(libraries/tipipeline/vars): add support for feature branch PRs in component checkout

---

pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml

why:
occued bazel build OOM in `ghpr_check2` builds for https://github.com/pingcap/tidb/pull/38497
what:
same as pod of `ghpr_build`, add ram limit args to the bazel RC file.

fix(pipelines/pingcap/tidb): ram limit and other args for bazel build

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy

The nfs service is not stable enough and can affect Pipeline tasks

ticdc: remove nfs go module cache

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy
jenkins/pipelines/ci/tiflash/tiflash-ghpr-unit-tests.groovy

https://github.com/pingcap/tiflash/pull/6147 allows us to specify a directory for runtime immediate files.
This PR mounts tmpfs for the runtime directory.
Actually the overall test time is not greatly reduced (from 8min -> 7min), but the stability is improved.
Replay using this PR: https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-unit-tests/detail/tiflash-ghpr-unit-tests/6590/pipeline/73/
When memfs is not mounted: https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-unit-tests/detail/tiflash-ghpr-unit-tests/6589/pipeline
Signed-off-by: Wish <breezewish@outlook.com>

tiflash: use memory as test runtime dir

---

jenkins/pipelines/cd/tiflow-docker.groovy
jenkins/pipelines/cd/tiflow-operator-docker.groovy

Also sync `branch` or `git tag` as image tag to gcr, such as
- Revision = master, will sync `master`, `latest` and `git commit hash` as image tag.
- Revision = v20221019, will sync `v20221019` and `git commit hash` as image tag.
- Revision = git commit hash, will sync `git commit hash` as image tag only.

also sync branch/tag as image tag if possible

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

releated to https://github.com/pingcap/tiflow/issues/7409
tidb pr https://github.com/pingcap/tidb/pull/38243 introduced an incompatible change which may be fixed by https://github.com/pingcap/tiflow/pull/7410.  So we need temporarily lock the tidb version to a commit (master branch)
replay test link
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/16257/pipeline/131/

ticdc: use specific tidb master commit hash for integration tests

---

jenkins/pipelines/nightly/tidb/tidb_nightly_unit_test.groovy
jenkins/pipelines/utf-ci/utf-go-test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_unit_test.groovy

why: should perfer to `|| true` rather than `| true`

fix(pipelines/pingcap/tidb): fix report steps

---

scripts/pingcap/tiflow/ticdc_integration_test_download_dependency.sh
staging/jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
staging/pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
staging/pipelines/pingcap/tidb/latest/pod-merged_integration_cdc_test.yaml

The current pipeline has the following problems, making it very difficult to maintain and carefully adjust the pipeline
* Some Groovy handles a lot of test-related logic that has nothing to do with ci orchestration
* One script is compatible with multiple branches
* A lot of versioning logic has been added to the script
A newcomer has difficulty modifying the assembly line on his own, So let's refactor these complex historical pipelines and use cdc's pipeline for a refactoring demonstration.
* Make the pipeline jobdsl
* Make the groovy simple and less
* Different branches maintain different pipelines
* Some dependency logic needs to be migrated from groovy to the shell script

ci: refactor tidb_ghpr_integration_cdc_test pipeline

---

jenkins/pipelines/ci/tidb/tidb_e2e_tests.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_campatibility_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_1.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_sqllogic_test_2.groovy

* add retry to download file, avoid errors caused by interrupted downloads
* increase request CPU for sqllogic test, avoid 5000 timeout error
replay test link
1. https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/13558/pipeline/176/
2. https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_ddl_test/detail/tidb_ghpr_integration_ddl_test/12060/pipeline/
3. https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_campatibility_test/detail/tidb_ghpr_integration_campatibility_test/12695/pipeline/

fix(tidb): make mergeci more stable

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_leak_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy
jenkins/pipelines/ci/ticdc/dm_ghpr_integration_test.groovy

branch equals and greater than release-6.1 use go1.19
replay with go1.19 image test link
1. https://ci2.pingcap.net/job/dm_ghpr_compatibility_test/8882/console

feat(tiflow): cdc and dm 6.1 use go1.19

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy

1. go mod vendor should not or with `true`, delete the `true`.
2. enhance copy logic.

fix(tidb): fix tidb_ghpr_integration_ddl_test

---

pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy

remove useless archive to avoid wasting disk space

fix: remove useless archive

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

example:
/run-integration-test pd=commit-id tikv=commit-id

feat(tiflow): support passing commit id for `pd`, `tikv`, `tidb` components

---

jenkins/pipelines/cd/tidb-operator.groovy

```
TKCTL_CLI_PACKAGE = tkctl-linux-amd64-v1.4.0-alpha.3
[2022-11-30T11:04:14.445Z] /home/jenkins/agent/workspace/release-tidb-operator@tmp/durable-c70c2321/script.sh: line 2: TKCTL_CLI_PACKAGE: command not found
```
fix shell script syntax

fix: shell syntax var define

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy

Use wget instead of curl to avoid file download failures
replay test link: 
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_ddl_test/detail/tidb_ghpr_integration_ddl_test/12373/pipeline/

fix(tidb): fix tidb ddl-test ci curl error

---

jenkins/pipelines/cd/optimization-libs.groovy
jenkins/pipelines/cd/pre-release-community-docker.groovy

dm migrate from pincap/dm into pingcap/tiflow from v5.3.0, so only build dm for version v5.3.0+

fix(build): only build dm for version v5.3.0+

---

jenkins/pipelines/cd/tiflow-docker.groovy

build tiflow usually report connection reset when connectting to goproxy
Add GOPROXY in Dockerfile

fix: add GOPROXY for tiflow docker build

---

scripts/ops/get-topn-longest-cases.ts

get top100 longest cases in a build
```shell
deno run --allow-all scripts/ops/get-topn-longest-cases.ts --buildUrl=https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/11588 --topN=100
```
output:
```log
total count: 7961
P50: <=2.31
P80: <=5.55
P90: <=29.18
P95: <=40
P99: <=190
-------------------
expression TestDoubleRow2Vec 960
mathutil TestStrLenOfUint64Fast 930
mathutil TestStrLenOfUint64Fast/RandomInput 930
gcworker TestGCWithPendingTxn 860
cpuprofile TestParallelCPUProfiler 830
sessionstates TestVerifyToken 810
streamhelper_test TestRegionIterator/case#2 770
copr TestConsistentHash 730
gcworker TestGCLabelRules 730
tikv TestScanSampleStep 730
expression TestDoubleVec2Row 720
gcworker TestSetServiceSafePoint 700
owner TestCluster 680
streamhelper_test …
```

feat(scripts/ops): add ut duration statics script

---

jenkins/pipelines/ci/tidb/tidb_ghpr_tics_test.groovy

Use a complete image to avoid constant downloads from external networks.
test link  https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_tics_test/detail/tidb_ghpr_tics_test/11821/pipeline/

fix(tidb/tiflash-test): avoid constant downloads from external networks

---

pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy

current jobs of tidb repo are Prow job style
before refactored, we can trigger them with comment, such as `/run-mysql-test tidb-test=pr/1234`
now, we should append ` | tidb-test=pr/1234` in PR title, and then comment with `/retest`, then the bot will rerun the failed jobs with the PR codes of `/pulls/1234` of `tidb-test` repo.
examples:
- `<scope>: the PR main title | tidb-test=pr/1234`
- `<scope>: the PR main title | plugin=pr/456`

fix(pipelines/pingcap/tidb/latest): support set peer repos in PR title

---

pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy

fix upload file error on release-6.1 ut pipeline

fix(jobs/pingcap/tidb): release-6.1 not use bazel

---

jenkins/pipelines/cd/tidb-operator.groovy

tidb-operator commit hash use ci jenkins script commit hash, becuase GIT_COMMIT environment has been pre-set
set environment variable explicitly

fix: git commit hash environment variable

---

jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
scripts/pingcap/br/integration_test_download_dependency.sh
scripts/pingcap/tidb-test/download_pingcap_artifact.sh
scripts/pingcap/tiflow/ticdc_integration_test_download_dependency.sh
staging/pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy

To avoid abnormal interruptions during download, use `wget` instead of `curl` to download file from fileserver.

fix(staging/tidb): fix curl download unstable

---

staging/pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
staging/pipelines/pingcap/tidb/latest/pod-merged_tiflash_test.yaml

update docker version to fix error  (releated https://github.com/containers/skopeo/issues/1501)
```shell
+ docker run --rm hub.pingcap.net/qa/tidb:master -V
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f188db9342c m=0 sigcode=18446744073709551610
goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7f188db9342c
stack: frame={sp:0x7ffd3d98fdc0, fp:0x0} stack=[0x7ffd3d191340,0x7ffd3d990350)
0x00007ffd3d98fcc0:  0x000000000174bbf9 <runtime.sysMapOS+0x0000000000000039>  0x0000000000000000 
0x00007ffd3d98fcd0:  0x00007f1866779000  0x000000000174bb85 <runtime.sysHugePageOS+0x0000000000000065> 
0x00007ffd3d98fce0:  0x00007f1868a00000  0x0000000000200000 
0x00007ffd3d98fcf0:  0x000000000000000e  0x00007f1800000000 
0x00007ffd3d98fd00:  0x00007ffd3d98fd30 …
```

fix(staging/tidb): update pod docker daemon version

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-build.groovy

Add a timeout limit to prevent pipeline from getting stuck.
tested: https://ci.pingcap.net/view/tiflash/job/tiflash-ghpr-build/20420/

chore(pingcap/tiflash): ghpr_build set timeout to 60min

---

jenkins/pipelines/ci/ticdc/integration_test_common.groovy

To avoid abnormal interruptions during download, use wget instead of curl to download file from fileserver.
tested
1. https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/17774/pipeline/173/
2. https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/16910/pipeline/
3. https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/16904/pipeline/

fix(ticdc): fix curl download unstable

---

pipelines/pingcap/tiflow/latest/ghpr_verify.groovy

Explicitly set the variable GOPROXY to avoid checksum errors. This error can be caused by the introduction of the upstream goproxy.io.
Revert this after internal goproxy back to normal.

chore(pingcap/tiflow): set goproxy to proxy.golang.org

---

pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy

Explicitly set the variable GOPROXY to avoid checksum errors. This error can be caused by the introduction of the upstream goproxy.io.
Revert this after internal goproxy back to normal.

chore(pingcap/tiflow): set goproxy to proxy.golang.org 

---

pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy

Reverts PingCAP-QE/ci#1699
The internal goproxy has been back to normal.

Revert "chore(pingcap/tiflow): set goproxy to proxy.golang.org "

---

pipelines/pingcap/tidb/latest/merged_build.groovy

Build without parallelism to avoid errors 
```shell
cp bazel-out/k8-fastbuild/bin/tidb-server/tidb-server_/tidb-server ./bin
cp: cannot create regular file './bin/tidb-server': Text file busy
make: *** [bazel_build] Error 1
script returned exit code 2
```

fix(pingcap/tidb): merged_build build tidb-server without parallelism

---

pipelines/tikv/pd/latest/ghpr_build.groovy

Reverts PingCAP-QE/ci#1668
Internal goproxy upstream has been back to normal.

Revert "fix(pipelines/tikv/pd): using other goproxy to avoid branch version issue"

---

scripts/ops/statics-repo-branch-green-rate.ts

Usage example:
```bash
deno run --allow-all scripts/ops/statics-repo-branch-green-rate.ts \
--token=<github-oauth-token> \
--repo=pd --owner=tikv \
--since=2023-01-01T08:00:00
```

feat(scripts/ops): add script to statics green rate of repo branch

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

migrate github action workflow
when it's merged, we should modify the repo branch protect rule: delete the required context:

feat(jenkins/pipelines/ci/tiflash): merge license header checking in build-common

---

pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml

request == limit = 8 core + 32 GB(from 16GB)

feat(pipelines/pingcap/tidb/latest): make pod in check2 job be a guaranteed pod

---

scripts/ops/get-artifacts-of-pull-request.sh

usage:
found the artifacts build with the merged commit:
```bash
scripts/ops/get-artifacts-of-pull-requests.sh <pull-request-url>
```
found the artifacts builded with latest commits inthe pull request:
```bash
scripts/ops/get-artifacts-of-pull-requests.sh <pull-request-url> open
```

feat(scripts/ops): add script to index artifacts by github pull requests

---

jenkins/pipelines/cd/multi-arch-sync-docker.groovy

Why:
- from Hongliang Wang(添加者）: 现在是不需要了吧？ 现在initializer都有多架构版了
- from operator team: 这个是手动发布就可以了, 不用跟随发版

feat: remove monitor reloader and initializer at releasing

---

jobs/pingcap/tidb/release-6.6/ghpr_build.groovy
jobs/pingcap/tidb/release-6.6/ghpr_check.groovy
jobs/pingcap/tidb/release-6.6/ghpr_check2.groovy
jobs/pingcap/tidb/release-6.6/ghpr_mysql_test.groovy
jobs/pingcap/tidb/release-6.6/ghpr_unit_test.groovy
jobs/pingcap/tidb/release-6.6/prow-presubmits.yaml
pipelines/pingcap/tidb/release-6.6/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.6/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.6/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.6/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.6/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.6/pod-ghpr_build.yaml
pipelines/pingcap/tidb/release-6.6/pod-ghpr_check.yaml
pipelines/pingcap/tidb/release-6.6/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/release-6.6/pod-ghpr_mysql_test.yaml
pipelines/pingcap/tidb/release-6.6/pod-ghpr_unit_test.yaml

tidb ci on master upgrade go version go go1.20, so we splite pipelines for release-6.6.

chore(pingcap/tidb): master use go1.20, split release-6.6

---

jobs/tikv/pd/latest/prow-presubmits.yaml
jobs/tikv/pd/release-6.5/aa_folder.groovy
jobs/tikv/pd/release-6.5/ghpr_build.groovy
jobs/tikv/pd/release-6.5/prow-presubmits.yaml
pipelines/tikv/pd/release-6.5/ghpr_build.groovy
pipelines/tikv/pd/release-6.5/pod-ghpr_build.yaml

pd master go version will upgrade to go1.20, so we split pipelines from master.

chore(tikv/pd): split pd jobs for go1.20

---

pipelines/pingcap/tidb/latest/pod-merged_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_br_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_cdc_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_ddl_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_tiflash_test.yaml

merged pipeline on tidb master upgrade to go1.20.1.

chore: tidb pipelines on master use go1.20

---

pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml

tidb msyql-test on master upgrade go version to 1.20.

chore(pingcap/tidb): tidb mysql-test use go1.20 on master

---

jenkins/jobs/ci/tidb-test/tidb_test_ghpr_mysql_test.groovy

Mysql-test ci on master has been refactored to prow style on ksyun, so we disable trigger this on idc jenkins.

chore: disable trigger mysql-test on master branch

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy
jenkins/pipelines/cd/dev-build.groovy

Why:
- to support forked repo
- for enterprise-plugin TIDB_HASH can accept repo name before sha1 to accomplish plugin with forked repo

feat: support forked repo

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy

- curl fileserver often fail with: curl: (18) transfer closed with 557466155 bytes remaining to read

fix: use wget instead of curl

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

Fix https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/20767/pipeline/
Verified in https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/20776/pipeline

update `tiflash-build-common.groovy` to fix ccache process

---

jenkins/pipelines/cd/release-enterprise-plugin.groovy

Why:
- old-path is very long and complex
- jenkinsfile is not git managed

feat: upload enterprise plugin to fixed path

---

scripts/plugins/analyze-go-test-from-bazel-output.sh

```bash
./scripts/plugins/analyze-go-test-from-bazel-output.sh bazel-test.log
```
> Those files also will be archived in CI server.
- `bazel-go-test-index.log` // bazel test sumary index file, you should check it first.
```log
828:==================== Test output for //session:session_test (shard 23 of 50):
829:=== RUN   TestIndexMergeUpgradeFrom300To540
3096:--- PASS: TestIndexMergeUpgradeFrom300To540 (206.04s)
3097:=== RUN   TestValidationRecursion
4085:-- Test timed out at 2023-03-07 15:37:05 CST --
4086:================================================================================
4104:==================== Test output for //session:session_test (shard 24 of 50):
4105:=== RUN   TestIndexMergeUpgradeFrom400To540
7413:-- Test timed out at 2023-03-07 15:37:05 CST -- …
```

feat(pipelines/pingcap/tidb/latest): analyze bazel output when failed.

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

Skip license check if config not exist.
Test pass  https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/21309/pipeline/174

fix(pingcap/tiflash): skip license check if not config

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
scripts/plugins/analyze-go-test-from-bazel-output.sh
scripts/plugins/report_job_result.sh

output a new file: `bazel-go-test-problem-cases.json`
```json
{
"//ddl/tiflashtest:tiflashtest_test": {
"new_flaky": [
"TestTiFlashProgressCache",
"TestTiFlashTruncatePartition"
]
},
"//executor:executor_test": {
"new_flaky": [
"TestStaleReadNoExtraTSORequest"
]
},
"//ddl:ddl_test": {
"new_flaky": [
"TestCancel"
],
"long_time": {
"TestCancel": -1
}
},
"//session:session_test": {
"new_flaky": [
"TestClusteredIndexSplitAndAddIndex2",
"TestClusteredIndexSyntax",
"TestCommitWhenSchemaChanged",
"TestDeleteExecChunk",
"TestGlobalAndLocalTxn",
"TestIndexLookUpReaderChunk",
"TestIndexMergeUpgradeFrom400To540",
"TestIndexUsageSyncLease",
"TestInitializeSQLFile",
"TestPartitionTable",
"TestPrefixClusteredIndexAddIndexAndRecover",
"TestRetrySchemaChange",
"TestRetrySchemaChangeForEmptyChange", …
```

feat(scripts/plugins): extract flaky tests from bazel output

---

jobs/pingcap/tidb/latest/merged_build.groovy
jobs/pingcap/tidb/latest/merged_common_test.groovy
jobs/pingcap/tidb/latest/merged_e2e_test.groovy
jobs/pingcap/tidb/latest/merged_integration_br_test.groovy
jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy
jobs/pingcap/tidb/latest/merged_integration_common_test.groovy
jobs/pingcap/tidb/latest/merged_integration_copr_test.groovy
jobs/pingcap/tidb/latest/merged_integration_ddl_test.groovy
jobs/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
jobs/pingcap/tidb/latest/merged_integration_mysql_test.groovy
jobs/pingcap/tidb/latest/merged_sqllogic_test.groovy
jobs/pingcap/tidb/latest/merged_tiflash_test.groovy
jobs/pingcap/tidb/latest/merged_unit_test.groovy

Reduce the network bandwidth consumption of downloading ci.git.
Complate git clone 20M, shallow git clone 6.4M.

chore(pingcap/tidb): reduce the network bandwidth consumption

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test-new.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy

- old pipeline embed logic, which is different with that in operator, we need to unify them
- pannel now managed within `monitoring` repo
- use script in `pingcap/monitoring` repo
- when the script not exist in repo, we just fallback to old pipeline , and then cherry-pick build script to that branch. 
- without this fallback, a lot of pipeline would fail immediately, when most branch has been migrated, we can remove fallback

feat: add new grafana tiup pipeline

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

tikv cache image add release-7.0

chore: tikv cache image add release-7.0

---

jobs/pingcap/tiflow/latest/README.md
jobs/pingcap/tiflow/latest/prow-presubmits.yaml

Enable status reporting for the following pipelines.
* pull_cdc_integration_kafka_test
* pull_cdc_integration_test
* pull_dm_compatibility_test
* pull_dm_integration_test
* pull_engine_integration_test

feat: tiflow ci enable report

---

jobs/pingcap/tiflow/latest/prow-presubmits.yaml

Use `run_before_merge` instead of `always`.

fix: use run_before_merge to control integration test

---

pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy

dm integration test need shorter pod hostname (Less than 60).
test pass: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_dm_integration_test/detail/pull_dm_integration_test/126/pipeline

chore: use shorter pod hostname for dm it test

---

libraries/tipipeline/vars/git.groovy

why: some repo's script will using git to clone or update, but we only set it in default container.

fix(gitee/pipelines/pingcap_enterprise):  add git ssh key in go build containers

---

jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_build.groovy
jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_check.groovy
jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_integration.groovy
jenkins/jobs/ci2/pingcap/tidb-binlog/ghpr_unit_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_downstream_coverage.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_leak_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/engine_ghpr_integration_test.groovy
jenkins/jobs/ci2/pingcap/tispark/ghpr_integration_test.groovy
jenkins/jobs/ci2/tikv/importer/ghpr_build.groovy
jenkins/jobs/ci2/tikv/importer/ghpr_test.groovy

Only save log during 30days to reduce the consumption of disk space by logs.

feat: only save log during 30days

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy

- in release-6.1+ the script has lines `set -ex` and had the shell shaban line.

fix(jenkins/pipelines/ci/tiflash): no need add `base -ex` to run the test shell

---

jenkins/pipelines/ci/tiflash/tiflash-ghpr-integration-tests.groovy

Archive will failed, but we need the core log info, so reorder it.

fix(jenkins/pipelines/ci/tiflash): reorder the steps in catch block

---

jobs/pingcap/tidb/latest/prow-postsubmits.yaml

The following MergeCI pipeline has been running stably and the status report is enabled.
* ci/integration-copr-test
* ci/sqllogic-test
* ci/integration-jdbc-test
* ci/e2e-test

feat: enable mergeci report on some ci

---

prow-jobs/kustomization.yaml
prow-jobs/ti-community-infra-configs-periodics.yaml
prow-jobs/ti-community-infra-configs-postsubmits.yaml
prow-jobs/ti-community-infra-configs-presubmits.yaml
prow-jobs/ti-community-infra-periodics.yaml
prow-jobs/ti-community-infra-test-infra-postsubmits.yaml
prow-jobs/ti-community-infra-test-infra-presubmits.yaml

I have tested with command:
```shell
flux build kustomization prow-post-ci-jobs --path prow-jobs/ --kustomization-file ../ee-ops/apps/gcp/prow/post/ci-jobs.yaml -n apps
```

feat(prow-jobs): migrate in job files from configs repo

---

pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-7.1/ghpr_verify.groovy

run `make unit_test_in_verify_ci ` will encounter error below: 
"""
=== Failed
=== FAIL: pkg/tcpserver TestTCPServerTLSHTTP1 (0.01s)
tcp_server_test.go:77: 
Error Trace:	/home/jenkins/agent/workspace/pingcap/tiflow/release-7.1/ghpr_verify/tiflow/pkg/tcpserver/tcp_server_test.go:77
Error:      	Received unexpected error:
[CDC:ErrToTLSConfigFailed]generate tls config failed: could not read ca certificate: open /home/jenkins/agent/workspace/pingcap/tiflow/release-7.1/ghpr_verify/tests/integration_tests/_certificates/ca.pem: no such file or directory
github.com/pingcap/errors.AddStack
/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174
github.com/pingcap/errors.(*Error).GenWithStackByArgs
/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cd …

fix(tiflow): fix ut get wrong repo dir

---

jenkins/pipelines/ci/ticdc/cdc_ghpr_integration_test.groovy
jenkins/pipelines/ci/ticdc/cdc_ghpr_kafka_integration_test.groovy

Use the default tini as the first process to avoid zombie processes.

fix(tiflow): use default command

---

pipelines/pingcap/tidb/release-6.1/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_build.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_unit_test.groovy

when restore src code caceh from s3 cache,  we might unexpected code cache contains untrack files like `extension/enterprise/` that only existed on branch master as submodule.
so we need clean this dir to make sure current git tree is clean.

fix(tidb): clean possible untrack git files

---

prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml

Enable pull-cdc-integration-storage-test when merge tiflow pr on release-7.1
* Supports responding to /test all
* Auto run before pr ready to merge

feat(tiflow): enable run_before_merge

---

jenkins/pipelines/cd/dev-build.groovy

Why:
- devbuild is actually for endpoint user
- https is enabled

feat: use https rather than http

---

pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
scripts/pingcap/tiflow/release-6.1/cdc_run_group.sh

split cdc tests to 16 group to speed up the execution of CI.

chore(tiflow): split to 16 group to decrease ci time

---

pipelines/pingcap/tiflow/latest/ghpr_verify.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
pipelines/pingcap/tiflow/release-5.3/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.0/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.1/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-6.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-6.2/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-7.1/ghpr_verify.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy

more extracting for multi PRs cases.
It's already used in tidb's pipelines.

refactor(pipelines/pingcap/tiflow): simplfy git repo cache keys

---

pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy

Replace jenkins checkout with `prow.checkoutRef` to avoid the wrong checkouts for batch triggered runs.
Close issue #2112

fix(pipelines/pingcap/tiflow): fix checkout for prow style jobs

---

jobs/pingcap/tidb/latest/merged_integration_cdc_test.groovy

disable merged cdc test pipeline, this pipelines not finished yet.

ci: disable merged cdc test pipeline

---

jenkins/pipelines/cd/release-enterprise-plugin.groovy

old non-LTS internal plugin path is ugly
add an option to specify whether it is LTS, non LTS will not push to public, but still push to internal

feat: will upload plugin to proper file-server path for non LTS

---

pipelines/tikv/pd/latest/ghpr_build.groovy
pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
pipelines/tikv/pd/release-6.5/ghpr_build.groovy

Just copy the refactoring to all prow style pipelines
- Ref:  #2113

refactor(pipelines/tikv/pd): simplfy git repo cache keys and checkout peer repos with `component.checkout`

---

prow-jobs/ti-community-infra-configs-postsubmits.yaml

Why: currently we use GitOps to deploy and update prow instance and configuration for persistent.

fix(prow-jobs): delete job `post-configs-deploy-prow` for `ti-community-infra/configs` repo

---

prow-jobs/ti-community-infra-test-infra-presubmits.yaml

It's a presubmits job of `ti-community-infra/test-infra` repo.

fix(prow-jobs): change job `pull-test-infra-prow-image-build-test` to manually triggered

---

pipelines/pingcap/tiflow/release-5.3/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-5.3/pull_cdc_integration_test.groovy

set LD_LIBRARY_PATH to fix errors when run `tiflash --version`
```
error while loading shared libraries: libtiflash_proxy.so: cannot open shared object file: No such file or directory
```

fix(tiflow): to set LD_LIBRARY_PATH

---

jenkins/pipelines/ci/tikv/tikv_ghpr_test.groovy

Fix the uncorrect tikv test cache file url: remove redundant slash on url.
Test pass  https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/35484/pipeline/88/

fix(tikv): fix download url error

---

pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy

Hotfix branch on 7.1 will be like release-7.1-20220101-v7.1.0. To download the corresponding branch's dependency binary, we should specify the branch to release-7.1

feat(tiflow): to specify release-7.1 to download third party binarys

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy

see https://github.com/pingcap/tidb/pull/44602, we plan to rename bazel_loaddatatest to bazel_importintotest to avoid mixing with load data

using bazel_importintotest to replace loaddatatest

---

pipelines/pingcap/tidb/latest/merged_integration_django_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_integration_django_test.yaml

This PR will add Django unit test cases based on Django-TiDB to the TiDB CI pipeline, the tests should run after every PR merged into TiDB repo.
related PR: https://github.com/pingcap/tidb-test/pull/2151

feat: integrate django test cases into ci pipeline

---

jobs/pingcap/tidb/latest/merged_integration_django_test.groovy
prow-jobs/pingcap-tidb-latest-postsubmits.yaml

* Add job integration-django-test to postsubmit jobs on master.
* Currently, the task is in debug mode, so the status update has been disabled.

feat: add job integration-django-test

---

pipelines/pingcap/tidb/latest/merged_integration_django_test.groovy

do not print go env in django test pipeline as it uses a python image

fix: go binary does not exists in the django test pipeline

---

scripts/pingcap/community/update-prow-owners.ts

The pull requests that only make changes on prow `OWNERS` should not trigger CI jobs.
1. Add some CI skip words in head commit of the PR created, this may be worked for Github workflows.
2. Other type CI jobs be implement in another way.
Ref: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

feat(scripts/pingcap/community): add skip ci words in commit message to avoid unnecessary ci builds

---

libraries/tipipeline/vars/component.groovy

- use wget continue option with saving file to path.
- limit retry times to 3.
- add tiny info outputs lines.

fix(libraries/tipipeline/vars): fix `component.fetchAndExtractArtifact`

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy

Use the default release-5.0 branch as tikv/importer is no longer being updated.

fix(br): default importer use release-5.0

---

scripts/pingcap/community/update-prow-owners.ts

example:
```bash
deno run --allow-all scripts/pingcap/community/update-prow-owners.ts \
--owner pingcap \
--github_private_token <github-private-token> \
--only_repo.repo=tidb \
--only_repo.branch=<target-branch> \
--force \
--inputs=teams/diagnostic/membership.json \
--inputs=teams/docs/membership.json \
--inputs=teams/tiunimanager/membership.json \
--inputs=teams/tidb/membership.json \
--inputs=teams/tiflash/membership.json \
--inputs=teams/tiup/membership.json \
--inputs=teams/kubernetes/membership.json \
--inputs=teams/migration/membership.json \
--inputs=teams/bigdata/membership.json
```

feat(scripts/pingcap/community): add only repo support to manually sync owners to repo

---

prow-jobs/pingcap-qe-ci-presubmits.yaml
prow-jobs/ti-community-infra-configs-presubmits.yaml

- add presubmit to verify GitOps for configMaps for prow.
- add presubmit to verify GitOps for cronJobs for prow.
Ref: https://github.com/PingCAP-QE/ee-ops/issues/627

feat(prow-jobs): Add presubmit jobs for verifying GitOps for prow configMaps and cronJobs

---

jenkins/pipelines/cd/multibranch/build_cdc_multi_branch.groovy

In order to be compatible with the BR integration test pipeline, we need to upload the CDC binary to path like `builds/pingcap/ticdc/${githash}/centos7/ticdc-linux-amd64.tar.gz`.
download cdc binary in [br pipeline](https://github.com/PingCAP-QE/ci/blob/main/jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy#L424-L426)

build: add cdc binary upload path on multi-branch build

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy

Relate https://github.com/PingCAP-QE/ci/issues/2186
Temporary workaround for inconsistent status between prow job and job build.

fix: run importintotest at the first

---

prow-jobs/pingcap-tidb-latest-postsubmits.yaml

Enable django_test report.
The pipeline has been running smoothly for a while.

chore: enable django_test report

---

jobs/pingcap/tidb/latest/merged_integration_prisma_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_prisma_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_integration_prisma_test.yaml
prow-jobs/pingcap-tidb-latest-postsubmits.yaml

This PR will add Prisma integration testes to TiDB merged CI pipeline. After this PR be merged, the Prisma integration testes will be execute after every PR be merged in TiDB repo.
Related PR: https://github.com/pingcap/tidb-test/pull/2163
Notice: The `skip_report` option of the trigger is set to `true`, which means skip report the test status on Github checks status. After verifying the test working on the prod, `skip_report` option will be set to `false`.

feat: add prisma integration test to tidb merged ci

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy

Currently it has no coverage data collected, let's print them.
Ref: #2171 

chore(pipelines/pingcap/tidb/latest): print the coverage files

---

libraries/tipipeline/vars/component.groovy

Only checkout code of the current PR instead of all PRs, reducing unnecessary consumption of download bandwidth.
Add a checkoutV2 method to avoid unexpected errors affecting all related pipelines.When running for a period of time without any unexpected situations, replace the existing logic that uses checkout.
Notice: please clean lib cache in do jenkins after pr merged.

feat: add lib checkout to only pull current pr

---

pipelines/pingcap/tidb-test/latest/ghpr_common_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_integration_common_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_integration_jdbc_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_integration_mysql_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_integration_prisma_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_integration_sequelize_test.groovy
pipelines/pingcap/tidb-test/latest/ghpr_mysql_test.groovy

The existing checkout method has a flaw where specifying the tidb pr causes a timeout due to checking out all PRs.

fix(tidb-test): fix checkout tidb pr timeout

---

prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml

update trigger condition for CI jobs of pingcap/tidb release-6.5.
An existing issue with the tide.
Due to the defect of tide, modifying any condition triggering related configurations will retrigger CI for all existing PRs, which may put tremendous pressure on prow and cause issues with the refresh status of prow components.
So, after merging this PR, please continue to observe whether Prow is running normally.

perf(prow-jobs): update trigger condition for CI jobs of pingcap/tidb release-6.5

---

pipelines/pingcap/tiproxy/latest/pull_integration_jdbc_test.groovy

- Remove `'make deploy-hibernatetest ARGS="-x"'` because it's unstable
- Add `'make deploy-tidbjdbctest ARGS="-x -m unique"'`

remote hibernate test from TiProxy pipeline

---

prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml

Why:
deno official image have not arm64 container images currlently.

fix(prow-jobs): fix node selector for job `pull-notify-when-compatibility-sections-changed`

---

prow-jobs/pingcap-tiflow-latest-presubmits.yaml
prow-jobs/pingcap-tiflow-release-5.3-presubmits.yaml
prow-jobs/pingcap-tiflow-release-5.4-presubmits.yaml
prow-jobs/pingcap-tiflow-release-6.1-presubmits.yaml
prow-jobs/pingcap-tiflow-release-6.5-presubmits.yaml
prow-jobs/pingcap-tiflow-release-7.1-presubmits.yaml
prow-jobs/pingcap-tiflow-release-7.2-presubmits.yaml

For integration testing, it supports conditional triggering but does not require automatic triggering.
Refer to  https://docs.prow.k8s.io/docs/jobs/#trigger-types.

fix(tiflow): not run integrations test automatically

---

jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy

- get github sha1 failed when many concurrent builds
- disperse the trigger time

fix: avoid build multi-branch at the same time to avoid github limit

---

jenkins/pipelines/cd/update-all-image-to-latest-on-dockerhub.groovy
jenkins/pipelines/cd/update-base-images-on-dockerhub.groovy

Why:
- update dockerhub image latest tag
- sync base image to dockerhub

feat: add image sync to dockerhub pipeline

---

jenkins/pipelines/cd/dev-build.groovy

fix [#2314](https://github.com/PingCAP-QE/ci/issues/2314)
according to `GCR 镜像命名RFC `

feat: update GCR tag by plan

---

jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy

Disable trigger old pipeline on release 5.3 & 5.4, those two dm pipeline have been  replaced by a pipeline.

chore(tiflow): disable trigger old pipeline on release 5.3 & 5.4

---

prow-jobs/pingcap-tidb-release-7.3-presubmits.yaml

Only run pull-br-integration-test brfore merge other then trigger when push every new commit. This integration test consumes a lot of resources and does not need to be automatically triggered every time.

chore(tidb/br): only run pull-br it before merge

---

prow-jobs/pingcap-tidb-release-7.3-presubmits.yaml

There are currently some failed lightning cases in the upstream.  To ensure the smooth merging of other PRs, temporarily remove this configuration.

chore(tidb/br): remove run_before_merge on release-7.3

---

pipelines/pingcap/tidb/latest/canary-ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/ghpr_build.groovy
pipelines/pingcap/tidb/latest/ghpr_check.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/merged_build.groovy
pipelines/pingcap/tidb/latest/merged_common_test.groovy
pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_cdc_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_ddl_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_prisma_test.groovy
pipelines/pingcap/tidb/latest/merged_sqllogic_test.groovy
pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
pipelines/pingcap/tidb/latest/pull_integration_mysql_test.groovy

Reverts PingCAP-QE/ci#2167
`CI=true` is  a default environment variable in jenkins. So it is unnecessary to set CI=1.

Revert "fix: use CI=1 for tidb make command"

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_coverage.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_check2_debug.yaml
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_build.yaml
pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml
staging/pipelines/pingcap/tidb/latest/pod-ghpr_build.yaml
staging/pipelines/pingcap/tidb/latest/pod-merged_build.yaml
staging/pipelines/pingcap/tidb/latest/pod-merged_unit_test.yaml

Go v1.21.0 was release, we need to upgrade the CI/CD container image to adjust for `pingcap/tidb` repo.

chore(pingcap/tidb): bump go version to `v1.21.0`

---

pipelines/pingcap/tidb/latest/pod-ghpr_mysql_test.yaml

use go1.21 in image of mysql-test ci.

feat(tidb): update go image

---

pipelines/pingcap/tidb/latest/ghpr_check.groovy

ref https://github.com/pingcap/tidb/pull/45930

feat(pipelines/pingcap/tidb/latest): enable coverage upload in  job

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

Run format-check first to avoid git file lock error. Ref https://github.com/PingCAP-QE/ci/issues/2361

fix(tiflash): run format check first to avoid git lock error

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy

see https://github.com/pingcap/tidb/pull/46299
currently, test in real-tikv-test is run in serial, if there're too many test in one directory, test will run slow and delay pr merge, or even timeout
so we add 3 importintotestX into real tikv test, we will split the test later, to avoid test timeout as we will add more test later.

split importinto real-tikv test into multiple directory

---

jenkins/pipelines/ci/titan/titan_ghpr_test.groovy

Do not pass rocksdb dir by CI, titan itself would download the rocksdb branch corresponding to Titan CMakeList.txt

Update titan CI to not pass rocksdb dir

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

Install clang-format-15 if not exist, releated to https://github.com/pingcap/tiflash/pull/7927/files#diff-a847e281c62ad2738f1616a96cd3174ca1fa5eba8134bf6f5d802a425c92c8b2.
After the change, the CI of the tiflash master branch will prioritize using clang-format-15.

feat(tiflash): install clang-format-15 if not exist

---

scripts/pingcap/community/update-prow-owners.ts

Fixes #2377
Ref https://github.com/octokit/oauth-app.js/issues/424
Also make it faster by reducing needless sleep.

fix(pingcap/community): fix sync owners deno script

---

jenkins/Dockerfile/release/linux-amd64/pd

Why:
- according to the add component plan
How:
- arm64 already has  pd-recover, no need to change
- add jq to amd64 pd image, and for arm64 to base image  because yum is not reliable and slow, refer https://github.com/PingCAP-QE/ci-dockerfile/pull/67.
- if `apk add` is not acceptable for amd64, we will add jq to base image. Because tidb alse use apk add, it seems to be acceptable

feat: add jq and pd-recover according to plan

---

prow-jobs/pingcap-tiproxy-latest-presubmits.yaml

Make some integration test  ci status optional to avoid impacting the tide check of whether the PR can be merged.

chore(tiproxy): make some it test ci optional

---

prow-jobs/pingcap-tidb-release-6.1-presubmits.yaml
prow-jobs/pingcap-tidb-release-6.5-presubmits.yaml
prow-jobs/pingcap-tidb-release-7.1-presubmits.yaml

Enable ci context report of pull-br-integration-test because those pipeline test passed. 
test link
1. https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Frelease-7.1%2Fpull_br_integration_test/detail/pull_br_integration_test/6/pipeline/
2. https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Frelease-6.5%2Fpull_br_integration_test/detail/pull_br_integration_test/3/pipeline/

chore(br): enable ci context report of pull-br-it-test

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy

- jemalloc in tikv use host pagesize, but 4k page binary can not run 64k kernel
- larger page size is compatible with lower page size: https://github.com/jemalloc/jemalloc/issues/467
- there is no any pitfall if builder is 64k. https://github.com/jemalloc/jemalloc/blob/b71da25b8a12c2c3f0c10b0811d15a61980186e8/configure.ac#L1805
- force tikv on linux/arm64 use 64k page size

fix: force tikv linux/arm64 use 64k pagesize

---

pipelines/pingcap/tidb/release-6.5/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.5/pod-ghpr_check2.yaml
pipelines/pingcap/tidb/release-7.1/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.1/pod-ghpr_check2.yaml

cache bazel repo cache with pvc avoid downloading a large number of dependency packages from external networks.

chore(tidb): cache bazel repo cache with pvc

---

jenkins/pipelines/cd/dev-build.groovy

- someone just give failpoint image as hotfix to customer
- just fail to avoid this situation before I have better solution

fix: hotfix will fail if it contains special features

---

jenkins/pipelines/ci/tidb/tidb_ghpr_check.groovy
jenkins/pipelines/ci/tidb/tidb_ghpr_check_2.groovy

revert related changes  from https://github.com/PingCAP-QE/ci/pull/2410 to fix ci on branch release-5.4

fix(tidb): correct ci on old branch release-5.4

---

prow-jobs/pingcap-tiflow-latest-presubmits.yaml

chore(prow-jobs): comment for why the prow context and job name is not same

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/pod-ghpr_unit_test.yaml

Fixes #2441
- no need the `report` step anymore, also remove the container, we will send the data by cloud events in global CI server.
- currently hardcode the threshold value.
- fail in build when long time case found, contributors should fix it, make it run fast.

feat(pingcap/tidb): fail the CI build when found long time cost test cases

---

pipelines/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy

currently we encounter some issue when using pulsar container to run shell script.
```shell
process apparently never started in /home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_pulsar_test/tiflow@tmp/durable-0f4d238f
(running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
script returned exit code -2
```

fix(tiflow): comment some check ready code

---

jenkins/jobs/cd/tiup_mirror_online_rc.groovy

Why:
- the staging tiup address is changed, but it does not matter for this situation, because parent pipeline will pass the right address

fix: change default staging mirror address

---

prow-jobs/pingcap-tiflow-latest-presubmits.yaml

enable report cdc-integration-pulsar-test.
test passed https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_cdc_integration_pulsar_test/detail/pull_cdc_integration_pulsar_test/9/pipeline/495/
Wait for https://github.com/pingcap/tiflow/pull/9766 to be merged first.

chore(tiflow): enable report cdc-integration-pulsar-test

---

jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy
jenkins/pipelines/ci/ticdc/integration_test_common.groovy

* The save path for test coverage has changed, so create the directory in advance.
*  sync_diff that used in cdc test need updated since 7.4, ref https://github.com/pingcap/tiflow/pull/9781

fix(qatest): fix issue of pipeline used by qatest

---

pipelines/pingcap/tidb/release-7.4/ghpr_check2.groovy
scripts/pingcap/tidb/integrationtest_v2.sh

fix script start cluster fail on 7.4. 
I'm not sure why the master branch didn't encounter this issue, and I will continue to investigate.

fix(tidb): fix script start cluster fail on 7.4

---

pipelines/pingcap/tidb/release-7.4/ghpr_check2.groovy

fix issue of pipeline check2 of release-7.4: tidb-server start failed because binary path not correct.

fix: correct move dest binary name

---

pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.2/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.6/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.0/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.1/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.2/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.3/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.4/ghpr_check2.groovy

In the coming pull requests of `pingcap/tidb` repo, the folder layout will be changed, but will keep make tasks persistent.
we need use make to build rather than native go build commands to make CI jobs be compatible.

chore(pingcap/tidb): compatible with the coming package refactor contribution

---

pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_typeorm_test.yaml

As @wuhuizuo suggestion, I updated the docker image of typeorm test https://github.com/PingCAP-QE/ci-dockerfile/pull/70#issuecomment-1752099006

feat: using ci base image for typeorm test

---

jenkins/pipelines/ci/tidb/tidb_ghpr_integration_common_test.groovy

`cmd/explaintest` has been rename to `tests/integrationtest`

feat: support pipeline used by qa-test

---

pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_typeorm_test.groovy

The bash interpreter in the `hub.pingcap.net/ee/ci/base` image doesn't support the array feature, and @purelind provides a way to work around it.
cc: @wuhuizuo

fix: fix the typeorm scripts

---

jenkins/pipelines/ci/tidb/tidb_ghpr_build.groovy

go.mod in enterprise-plugin used relative path.
test passed  https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_build/detail/tidb_ghpr_build/81578/pipeline/84/

fix(enterprise-plugin): correct enterprise-plugin path

---

jenkins/pipelines/ci/tikv/tikv_ghpr_coverage.groovy

fix error when run `cargo install grcov`
```
11:54:09  error: failed to compile `grcov v0.8.19`, intermediate artifacts can be found at `/tmp/cargo-install7uDpjN`
11:54:09  
11:54:09  Caused by:
11:54:09    package `anstyle-parse v0.2.2` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.0-nightly
11:54:09    Try re-running cargo install with `--locked`
```

fix(tikv): cargo install with --locked to fix error

---

pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_nodejs_test.groovy

Error:
> + [[ tikv == tikv ]]
> /home/jenkins/agent/workspace/pingcap-qe/tidb-test/ghpr_integration_nodejs_test/tidb-test@tmp/durable-17bcd1ba/script.sh: 5: [[: not found
https://superuser.com/questions/374406/why-do-i-get-not-found-when-running-a-script

fix: using bash with abs path

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

* update release-7.5 tikv cache image build.
* remove dmr version 7.4 image build.

feat: tikv_ghpr_cache image build update

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy
scripts/pingcap/tidb/integrationtest.sh
scripts/pingcap/tidb/integrationtest_with_tikv.sh

* Correct start pd cmd params.
* Specify using store tikv for testing.

fix(tidb): fix script integrationtest.sh

---

prow-jobs/kustomization.yaml
prow-jobs/pingcap-community-postsubmits.yaml
prow-jobs/pingcap-inc-enterprise-extensions-postsubmits.yaml
scripts/pingcap-inc/enterprise-extensions/update-submodule-in-tidb.ts

Close #2495
- Bot will create pull requests to update submodule in `pingcap/tidb` repo when any pull request merged in `pingcap-inc/enterprise-extensions` repo.
- Avoid checkout any repositories to save time and bandwidth.
- Currently we use the free public service,it can not update private submodule, and it's not recommend for security.
- It is designed on pulling, so may be minutes or hours delay.
- Ref:  https://github.com/wuhuizuo/tidb/pull/56

feat(tidb): auto create pull requests to bump enterprise extension submodule folders

---

prow-jobs/pingcap-tidb-latest-presubmits-canary.yaml

Set two canary job as optional
* pingcap/tidb/canary-scan-security
* pingcap/tidb/canary_ghpr_unit_test
In order to make the trigger command prompts of the bot clearer:

chore(tidb): set two canary job as optional

---

scripts/pingcap/community/update-prow-owners.ts

why: the bot will add blocking lables when the pull request description is not meet specifications.

fix(scripts/pingcap/community): fix update-prow-owners.ts

---

libraries/tipipeline/vars/component.groovy
pipelines/pingcap/tidb/latest/ghpr_check2.groovy

Currently, we obtain the latest compiled binary for the corresponding branch. This approach has a hidden risk as dependencies can cause issues that affect the current pipeline.
This PR support fetch artifact binary that already passed some e2e tests to avoid the above-mentioned problems.

feat(tidb): support fetch verify artifact

---

jenkins/pipelines/cd/atom-jobs/manifest-multiarch-common.groovy

- there is a file manifest-tool not managed by git
- docker is enough
- communicated with @purelind , remove manifest.yaml is ok
related issue: https://github.com/PingCAP-QE/ci/issues/2445

feat: remove manifest tool

---

pipelines/pingcap/tidb/latest/periodics_integration_test.groovy

Always archive log to debug probabilistic stuck test case in `https://github.com/pingcap/tidb/tree/master/tests/integrationtest`

chore(tidb): archive log to check stuck test case

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

The previous PR enables the bench_dbms https://github.com/PingCAP-QE/ci/pull/2515 to ensure the new code changes do not break building the bench binary.
But in the old branches, the bench binary have been broken for a long days and it brings trouble for cherry-pick to LTS branches and hotfix branches.
This PR only build the bench_dbms on the master branch. Ignore it for the LTS branches and hotfix branches.

Only build bench for the master branch

---

prow-jobs/pingcap-community-postsubmits.yaml

Currently most community members of `tiup` is not active. We need stop the auto syncing for this repository.

chore(pingcap/tiup): disable auto sync OWNERS files

---

jenkins/jobs/cd/community_docker_multi_products.groovy
jenkins/jobs/cd/pre_release_community_docker_rocky.groovy
jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/pre-release-community-docker-rocky.groovy

- build nightly image usually get file 404, because binary has not been build yet
- CI do not has this problem
- cd only product single arch image for a few products
- reuse the rc sub pipeline to produce multiple products with multi-arch

feat: build images after binary

---

jenkins/pipelines/cd/nightly/release_tidb_master-nightly.groovy
jenkins/pipelines/cd/release-GA-v5-extra-packages.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0-hotfix.groovy
jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy

Why:
- 3.3.10 is too old, even tidb 5.x use 3.4.3
- from tidb 6.5, use 3.4.21
- 3.4.21 copatible 3.4.3 by semantic versioning
How:
- use official etcd release package for linux, darwin/amd64
- build for darwin/arm64 with dockerfile:
```Dockerfile
FROM golang:1.19
ENV GOOS=darwin\
GOARCH=arm64
ADD . /go/src/github.com/coreos/etcd
WORKDIR /go/src/github.com/coreos/etcd
RUN  ./build
```

chore: update etcd from 3.3.10 to 3.4.21(since 6.5)

---

pipelines/tikv/migration/latest/pull_unit_test.groovy

* check git dir clean after checkout
* not use cache code because restored code The code recovered from the backup will lose the .git directory.
TODO
1. We will refactor this pipeline, using Prow for triggering and simultaneously using Lib functions for checking out code.
replay link
https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Fmigration%2Fpull_unit_test/detail/pull_unit_test/104/pipeline/

fix: check git dir clean after checkout in ut ci 

---

jenkins/pipelines/ci/tidb-binlog/binlog_ghpr_integration.groovy

Close https://github.com/PingCAP-QE/ci/issues/2591.
Use the corrent release-branch download binary on hotfix branch.

fix(tidb-binlog): hotfix branch it use the corrent release-branch download binary

---

scripts/pingcap/community/update-prow-owners.ts

5 seconds is not enough, we need to increase it to 60 seconds.
Ref #2582

fix(scripts/pingcap/community): add delay to add label for sync owners pr

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy

Why:
- remove spark and tispark since v7.5

chore: remove tispark and spark since v7.5

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy
jenkins/pipelines/cd/atom-jobs/products/tiflash/master.groovy

checkout tiflash unclean, use newer image for git
- new builder image, ref: https://github.com/pingcap/tiflash/pull/8325
- edited cd jenkins pod template
- change the default container from tiflash(old, gcc) to tiflash-llvm(upgraded) while checkout

fix: checkout tiflash unclean

---

jenkins/pipelines/cd/build-tidb-dashboard.groovy

- docker buildkit will now push attestation manifest by default, which will cause docker manifest fail. ref: https://docs.docker.com/build/attestations/
- disable attestation with commandline option

fix: docker attestation manifest

---

pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_integration_copr_test.yaml
pipelines/pingcap/tidb/latest/pull_integration_copr_test.groovy

*  Increase container cpu  limit to 16 core
* Optimize the checkout of copr-test code
* Remove unnecessary cache logic.
During the execution of the test, the actual CPU consumption was close to 18 cores.
When the CPU limit is set to 6 cores, the following errors are often encountered.
```shell
2023/11/13 15:40:45 2023/11/13 15:39:56 Test fail: Outputs are not matching.
Test case: sql/randgen-topn/6_date_1.sql
Statement: #55 -  SELECT `col_varchar_1_key` - `col_double` AS field1, ADDTIME( 'l', `col_char_255` ) AS field2 FROM `table1000_int_autoinc` WHERE SUBTIME( ( FROM_UNIXTIME( 'hmpfzuuqajlvefkkbuhcxrpigdpfdstrrhanfbfvufhkdrpalxsuzsdsiqpucziftkqrwcmduexqzeqzixqczvwlcziytxzmsmmxfmwckuxpmldzdqosjfjtzstttgyicbqthjmmlrbpkhobcldwsbaysxmhtyodzdonjbhmgwjjzqisiqnbbbfxrfblzcyefeivbgrkqvfdnvf', ( …
```

feat(tidb): optimize copr test ci

---

prow-jobs/pingcap-tidb-latest-postsubmits.yaml

Skip report context of some unstable test ci in mergeci.
* integration-jdbc-test
* integration-nodejs-test
After the relevant issues are fixed, the status reporting will be enabled.

fix(tidb/mergeci):  unstable test context will skip report

---

pipelines/PingCAP-QE/tidb-test/release-6.0/ghpr_mysql_test.groovy
pipelines/PingCAP-QE/tidb-test/release-6.1/ghpr_mysql_test.groovy
pipelines/PingCAP-QE/tidb-test/release-6.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.3/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.4/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-6.6/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-7.0/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-7.1/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-7.2/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-7.3/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-7.4/ghpr_mysql_test.groovy
pipelines/pingcap/tidb/release-7.5/ghpr_mysql_test.groovy

Build tidb-server which not enable race in mysql-test pipelines.
Comparison of test time before and after starting the race.
* race  about 30 minutes
* without abount 12 minutes
Now, due to the presence of cache binary logic in pipelines, even though the build command is enabled race `WITH_RACE=1 make server`, it is actually using a tidb-server without race enabled for testing.

feat: build tidb server without race

---

jenkins/jobs/cd/build_common.groovy
jenkins/jobs/cd/devbuild.groovy
jenkins/pipelines/cd/atom-jobs/build-common.groovy
jenkins/pipelines/cd/dev-build.groovy

Why:
- fips need special env var and image
How:
- add option to support build with env var
- support customized product image
- support pass builder image

feat: support env and product dockerfile

---

jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy

fix: remove params from pipeline

---

pipelines/pingcap/tidb/latest/periodics_integration_test.groovy

Currently, the following errors may occur during the checkout stage. In fact, submodule code will not be used in the current pipeline, so here another checkout lib function is used.
```shell
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/pingcap/tidb.git
at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1241)
at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
at …
```

fix: fix checkout submoudle in fail

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy

- fix tikv with given builder image
- remove script coupling with old tikv builder image

fix: using builder image ignore source

---

jenkins/pipelines/cd/tidb-operator.groovy

ref https://github.com/pingcap/tidb-operator/pull/5420.
They have been deprecated for some time, and no need to release them in the previous release-* versions.

remove tk-ctl and debug image

---

jenkins/pipelines/cd/tidb-operator.groovy

remove `tidb-cluster` and `tidb-backup` Helm chart as they have been deprecated for a long time.
ref https://github.com/pingcap/tidb-operator/pull/5422

remove tidb-cluster and tidb-backup Helm chart for TiDB Operator CD

---

pipelines/pingcap/tiflow/release-7.2/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.3/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_mysql_test.groovy
pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/release-7.4/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.4/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.4/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.4/pull_engine_integration_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_mysql_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_engine_integration_test.groovy

The current pipeline will encounter an error of not being able to download the dependency binary for hotfix branches, so we specify the corresponding release branch here.

fix(tiflow): download correct dependency binary on hotfix-branch pr

---

prow-jobs/pingcap-tidb-latest-presubmits.yaml

remove wip from ci context on `pull-lightning-integration-test`

chore: remove wip from ci context

---

jenkins/jobs/cd/devbuild.groovy
jenkins/pipelines/cd/dev-build.groovy

- support ng-monitoring and tidb-dashboard as params for devbuild
- avoid simple failing because of param
- detail implementation will be in another PR

feat(devbuild): support `ng-monitoring` and `tidb-dashboard` as component param

---

jenkins/pipelines/cd/dev-build.groovy

fix: groovy param typo

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.5/ghpr_check2.groovy

ignore error if tar logs fail.

fix: ignore error if tar logs fail

---

prow-jobs/pingcap-tidb-latest-postsubmits.yaml

merged-e2e-test is unstable recently, @pingyu is working on this. We temporarily disable the status reporting , and will enable it again after testing and fixing stability.

chore: disable merged-e2e-test report

---

jobs/tikv/pd/latest/pull_integration_realcluster_test.groovy
pipelines/tikv/pd/latest/pod-pull_integration_realcluster_test.yaml
pipelines/tikv/pd/latest/pull_integration_realcluster_test.groovy

rely on https://github.com/tikv/pd/pull/7493

pd: support pd real cluster

---

prow-jobs/pingcap-tidb-latest-postsubmits.yaml

merged-sqllogic-test the testing is not very stable. Reporting is temporarily disabled. It will be enabled after the testing is fixed.

chore: disable report 

---

jenkins/jobs/cd/devbuild.groovy
jenkins/pipelines/cd/dev-build.groovy

- support given target image path for some cron jobs to be easier

feat: support target image path

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy

Currently, Bazel will retry three times by default. If the timeout is set to "long", each timeout limit for each attempt is 15 minutes. If there are timeout issues with the case, when it reaches three timeouts, the entire task will be terminated will cause the test logs to not be output to stdout.
So here we will increase the timeout for the entire task by five minutes.
PS: At the same time, it would be better to adjust the bazel timeout (`long` -> `moderate `) for testing.

chore: adjust timeout for tidb ci

---

jobs/pingcap/tidb/latest/canary_ghpr_unit_test.groovy

To optimize ci repo fetch. First, use this task for testing to reduce the bandwidth consumption of fetch.

feat: optimize ci repo fetch

---

jenkins/Dockerfile/release/linux-arm64/enterprise/tidb
jenkins/Dockerfile/release/linux-arm64/tidb

- yum install is very slow because centos has been deprecated.(usually 1 hour)
- use dockerfile from https://github.com/PingCAP-QE/artifacts/blob/main/dockerfiles/bases/tidb-base/release-6.5.Dockerfile
- sync it to dockerhub to avoid any network problem

fix: solve yum install slow for centos 8

---

pipelines/tikv/pd/latest/pull_integration_realcluster_test.groovy

after https://github.com/tikv/pd/pull/7567 merged we can remove `cd` operator

pd_real_cluster: remove cd to specific dir

---

prow-jobs/pingcap-qe-ci-presubmits.yaml

I need to verify such a scenario, where a presumbit is set with two parameters
```shell
always_run: false
optional: false
```
what i want: 
1.  it can be merged normally for PRs that have not triggered this task.
2. it can be block merged for PRs that have not triggered this task and this task failed.

debug: test optional

---

jobs/pingcap/tiproxy/OWNERS
jobs/pingcap/tiproxy/latest/OWNERS
jobs/pingcap/tiproxy/latest/ghpr_build.groovy
jobs/pingcap/tiproxy/latest/ghpr_check.groovy
jobs/pingcap/tiproxy/latest/ghpr_unit_test.groovy
pipelines/pingcap/tiproxy/OWNERS
pipelines/pingcap/tiproxy/cd/OWNERS
pipelines/pingcap/tiproxy/latest/OWNERS
pipelines/pingcap/tiproxy/latest/ghpr_build.groovy
pipelines/pingcap/tiproxy/latest/ghpr_check.groovy
pipelines/pingcap/tiproxy/latest/ghpr_unit_test.groovy
pipelines/pingcap/tiproxy/latest/merged_mysql_test.groovy
pipelines/pingcap/tiproxy/latest/pod-ghpr_build.yaml
pipelines/pingcap/tiproxy/latest/pod-ghpr_check.yaml
pipelines/pingcap/tiproxy/latest/pod-ghpr_unit_test.yaml
pipelines/pingcap/tiproxy/latest/pod-merged_integration_common_test.yaml
pipelines/pingcap/tiproxy/latest/pod-merged_integration_jdbc_test.yaml
pipelines/pingcap/tiproxy/latest/pod-merged_integration_ruby_orm_test.yaml
pipelines/pingcap/tiproxy/latest/pod-merged_mysql_test.yaml
pipelines/pingcap/tiproxy/latest/pod-pull_integration_common_test.yaml
pipelines/pingcap/tiproxy/latest/pod-pull_integration_jdbc_test.yaml
pipelines/pingcap/tiproxy/latest/pod-pull_integration_ruby_orm_test.yaml
pipelines/pingcap/tiproxy/latest/pod-pull_mysql_test.yaml
prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml
prow-jobs/pingcap-tiproxy-latest-presubmits.yaml

- Add more tiproxy jobs:
- build: make
- check: make lint build
- unit_test: make test & upload code coverage
- Move mysql_test from presubmit to postsubmit because it may fail when TiDB PR is not merged
- Update the golang versions of some tests from 1.20 to 1.21
- Add OWNERS files to tiproxy directories

tiproxy: add more tiproxy jobs

---

jenkins/jobs/cd/tiproxy_docker.groovy

Now:
- image will published in repo: `hub.pingcap.net/pingcap/tiproxy/image`
- binaries will published in repo: `hub.pingcap.net/pingcap/tiproxy/package`
- It can be list with the [link](https://internal.do.pingcap.net:30443/dl/oci-files/hub.pingcap.net/pingcap/tiproxy/package?tag=main-release_linux_arm64) for get latest `main`'s linux/arm64 binaries.
- Then download it with url: https://internal.do.pingcap.net:30443/dl/oci-file/hub.pingcap.net/pingcap/tiproxy/package?tag=main-release_linux_arm64&file=tiproxy-v0.1.2-13-gec65e0f-linux-arm64.tar.gz

feat(tiproxy): disable docker build flow

---

jenkins/pipelines/cd/atom-jobs/products/tiflash/master.groovy

Why:
- tiflash build failure on arm
- now, the maxium memory used is 33.4GiB, so we increase the limit to 40GiB

fix: increase tiflash builder limit

---

jenkins/pipelines/cd/tiup/tiup-package-offline-mirror-6.0.0.groovy

Why:
- add tiproxy latest to server tiup offline package since v7.6.0

feat: add tiproxy for v7.6.0 later

---

jenkins/pipelines/ci/tiflash/tiflash-build-common.groovy

Try to build tiflash using clang-17 docker image https://github.com/pingcap/tiflash/pull/8537
But the CI will run into errors like https://ci.pingcap.net/job/tiflash-build-common/33843/console
```
[2023-12-30T15:06:42.887Z] + git log -1 --format=%H
[2023-12-30T15:06:42.887Z] fatal: detected dubious ownership in repository at '/home/jenkins/agent/workspace/tiflash-build-common/tiflash/contrib/tiflash-proxy'
[2023-12-30T15:06:42.887Z] To add an exception for this directory, call:
```
```
23:16:59  fatal: detected dubious ownership in repository at '/home/jenkins/agent/workspace/tiflash-build-common/tiflash'
23:16:59  To add an exception for this directory, call:
23:16:59  
23:16:59  	git config --global --add safe.directory /home/jenkins/agent/workspace/tiflash-build-common/tiflash
23:16:59 …
```

Fix building tiflash using clang-17 docker image

---

scripts/ops/statics-prow-jobs.ts

Run with:
```bash
deno run --allow-net ./scripts/ops/statics-prow-jobs.ts
```
results:
```csv
repo, branch, job_type, job_name, success_count, failure_count, success_rate, avg_timecost_minutes
pingcap/tiflow, master, presubmit, pingcap/tiflow/pull_dm_integration_test, 47, 25, 0.6527777777777778, 35.430851063829785
pingcap/tidb, master, presubmit, pingcap/tidb/ghpr_build, 270, 120, 0.6923076923076923, 32.98759259259259
pingcap/tidb, master, presubmit, pingcap/tidb/pull_integration_ddl_test, 373, 45, 0.8923444976076556, 15.359830205540662
pingcap/tidb, master, presubmit, pingcap/tidb/ghpr_check, 298, 130, 0.6962616822429907, 19.887639821029083
pingcap/tidb, master, presubmit, pingcap/tidb/ghpr_check2, 283, 122, 0.6987654320987654, 27.266902237926974
pingcap/tidb, master, presubmit, …
```

feat(scripts/ops): add script static-prow-jobs.ts

---

jenkins/jobs/cd/build_tidb_dashboard.groovy
jenkins/pipelines/cd/build-tidb-dashboard.groovy
jenkins/pipelines/cd/dev-build.groovy
jenkins/pipelines/cd/publish-tidb-dashboard.groovy

- devbuild trigger tidb-dashboard
- tidb-dashboard suport build environment var

feat: support tidb dashboard for devbuild

---

jobs/tikv/migration/latest/pull_integration_kafka_test.groovy
pipelines/tikv/migration/latest/pod-pull_integration_kafka_test.yaml
pipelines/tikv/migration/latest/pull_integration_kafka_test.groovy
prow-jobs/tikv-migration-latest-presubmits.yaml

Related PR: https://github.com/tikv/migration/pull/382

tikv-migration: support Kafka integration tests

---

jenkins/pipelines/ci/rust-rocksdb/rust_rocksdb_ghpr_test.groovy

The toolchain file name has been changed from `rust-toolchain` to `rust-toolchain.toml`

ci: fix rust tool chain file name for rust-rocksdb

---

jenkins/pipelines/cd/tidb-operator.groovy

- arm binary now use independent arm builder for fips
- we need export GIT_COMMIT every time or it would be overwrited by jenkins

fix: operator git commit

---

jobs/pingcap/tiflow/latest/merged_unit_test.groovy
pipelines/pingcap/tiflow/latest/merged_unit_test.groovy
pipelines/pingcap/tiflow/latest/pod-merged_unit_test.yaml
prow-jobs/kustomization.yaml
prow-jobs/pingcap-tiflow-latest-postsubmits.yaml

* Add tiflow postsubmit jobs.
* Add merged_unit_test to run unit tests and upload code coverage to codecov.io.
* Currently, coverage data is uploaded in tiflow PR, but the reporting data on master is missing, causing codecov bot to indicate a decrease in coverage.

feat(tiflow): add tiflow postsubmit

---

jenkins/pipelines/ci/tikv/tikv_ghpr_coverage.groovy

After this change we still need to wait tikv to update the rust toolchain to a newer version before this script can succeed due to https://github.com/rust-lang/rust/issues/118850

tikv: fix code coverage script

---

pipelines/pingcap/tiproxy/latest/merged_integration_nodejs_test.groovy
pipelines/pingcap/tiproxy/latest/pull_integration_nodejs_test.groovy

The container was wrong:
https://prow.tidb.net/log?job=pingcap/tiproxy/merged_integration_nodejs_test&id=1747866918376706052

tiproxy: fix container for nodejs test

---

pipelines/tikv/migration/latest/pull_integration_kafka_test.groovy
pipelines/tikv/migration/latest/pull_integration_test.groovy

- Collect logs with `-maxdepth 2` to exclude WAL of TiKV & PD and reduce artifact size
- Add collect logs for `pull_integration_test` pipeline.

tikv-migration: collect logs with -maxdepth 2

---

pipelines/tikv/migration/latest/pull_integration_kafka_test.groovy
pipelines/tikv/migration/latest/pull_integration_test.groovy

For tikv-migration CDC pipelines:
- Increase timeout from `40` to `65` minutes 
- Original `40 minues` is not sufficient. See https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Fmigration%2Fpull_integration_kafka_test/detail/pull_integration_kafka_test/28/pipeline/261/.
- Increase timeout of `Test` stage from `25` to `45` minutes

tikv-migration: increase pipeline timeout

---

pipelines/pingcap-inc/enterprise-extensions/latest/pr-verify.groovy

`make bazel_lint` take too long, adjust to run `make bazel_build`

fix(enterprise-plugin): adjust cmds

---

libraries/tipipeline/vars/component.groovy

To ensure the consistency of dependency package versions between tidb and plugin, for tidb branch like release-6.1-20231229-v6.1.7, checkout plugin with branch release-6.1.7

feat: checkout enterprise-plugin with branch release-x.y.z

---

libraries/tipipeline/vars/component.groovy

Fix get pr diff files not incomplete.  The paginated response of github api returns 30 files per page by default.

fix(tiflow): fix get pr diff files not incomplete

---

pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy

revert this pr after https://github.com/pingcap/tiflow/pull/10631 merged.

fix(tiflow): update pull_dm_compatibility_test.groovy

---

scripts/ops/statics-prow-jobs-weekly.py

Add analyse script to get prow job weekly data, run this script weekly will generate two csv files
1. prow_job_stats.csv  details about each pipelines.
2. prow_job_summary_stats.csv sumary about pipelines against repo and job_type.

script: add analyse script to get prow job weekly data

---

jenkins/pipelines/cd/tiup/prometheus-tiup-mirror-update.groovy

- v8.0.0 later will use prometheus version to 2.49.1, keep the same as https://github.com/PingCAP-QE/artifacts/blob/32b627f679746b7d1b521c9d630b99ed27ec6fa8/packages/packages.yaml.tmpl#L229
- tested via rerun https://cd.pingcap.net/blue/organizations/jenkins/prometheus-tiup-mirror-update/detail/prometheus-tiup-mirror-update/275/pipeline

chore: update prometheus version to 2.49.1

---

jenkins/pipelines/ci/tikv/tikv_ghpr_clippy_linux_arm64.groovy

https://github.com/tikv/tikv/pull/16602 is going to remove "cloud-aws", "cloud-gcp", and "cloud-azure".

Remove TiKV useless features

---

jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy
jenkins/pipelines/cd/tiup/prometheus-tiup-mirror-update.groovy

Add the grafana panel for tiproxy.
The tag for TiProxy is different with that of TiDB, so always fetch the latest one.

add grafana panel for tiproxy

---

jenkins/pipelines/cd/atom-jobs/jenkins-image-syncer.groovy

fix(jenkins/pipelines/cd/atom-jobs): avoid useless clonings of CI repo

---

pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_pulsar_test.yaml
pipelines/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy

use custom golang and pulsar docker image to run ticdc pulsar integration tests. relate to https://github.com/pingcap/tiflow/pull/10654.

use custom golang and pulsar docker image to run ticdc pulsar integration tests

---

libraries/tipipeline/vars/component.groovy
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy

When checking out the tidb-test code, it is necessary to determine whether the tidb-test PR has been specified based on the tidb pr title. During batch merge, multiple tidb PRs will be processed simultaneously. At this checkout step, we need to obtain all tidb pr titles to determine if the tidb-test PR has been specified.
Which situation is not allowed?
during batch merge, it is not allowed to specify the tidb-test branch or commit in the pr title for checking out code.

feat: support checkout tidb-test with pr in batch merge

---

jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/cdc_ghpr_kafka_integration_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_compatibility_test.groovy
jenkins/jobs/ci2/pingcap/tiflow/dm_ghpr_integration_test.groovy

* all old cdc pipeline only need trigger in old branch release-4.x or  release-5.[0-2].
* all old dm pipeline need disable because dm merged into tiflow since 5.3, all pipeline from 5.3 is trigger by new pipelines.

fix: disable some old tiflow pipeline trigger

---

pipelines/PingCAP-QE/tidb-test/latest/pull_tiproxy_mysql_test.groovy
pipelines/pingcap/tiproxy/latest/merged_mysql_test.groovy
pipelines/pingcap/tiproxy/latest/pull_mysql_test.groovy

Refer to https://github.com/PingCAP-QE/tidb-test/pull/2315: the `-c` is removed.

fix: remove -c option for tiproxy mysql_test

---

pipelines/pingcap/tidb/latest/ghpr_check2.groovy

This recently added package `tests/realtikvtest/pipelineddmltest` is not tested.
https://github.com/pingcap/tidb/blob/9b6db9d47a0b9dc8fe3c726626ce0428a3d3d491/Makefile#L632-L636

feat(tidb): test pipelineddmltest package

---

pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
pipelines/pingcap/tiflash/latest/pod-pull_unit-test.yaml
pipelines/pingcap/tiflash/latest/pull_unit_test.groovy

When the limit memory is set, the size of tmpfs will be restricted to a certain value. At this time, it was found that some tests failed or the probability of interruption increased. Therefore, for now, we will remove the memory restriction here.

fix: not set the limit memory

---

prow-jobs/pingcap-tiproxy-latest-postsubmits.yaml

The ruby_orm always reports error, which is caused by TiDB. The CI in TiDB ignores ruby_orm, so TiProxy also ignores it.
Errors:
```
Failure:
SchemaDumperTest#test_schema_dumps_index_sort_order [/home/jenkins/agent/workspace/pingcap/tiproxy/merged_integration_ruby_orm_test/tidb-test/activerecord_orm_test/activerecord-orm-test/activerecord/test/cases/schema_dumper_test.rb:195]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: UTF-8
-#    valid: true
-"t.index [\"name\", \"rating\"], name: \"index_companies_on_name_and_rating\", order: :desc"
+"t.index [\"name\", \"rating\"], name: \"index_companies_on_name_and_rating\""
rails test home/jenkins/agent/workspace/pingcap/tiproxy/merged_integration_ruby_orm_test/tidb-test/activerecord_orm_test/activerecord-orm-test/activerecord/test/cases/sche …
```

fix: remove ruby_orm test for tiproxy

---

prow-jobs/pingcap-tidb-latest-presubmits.yaml

The br & lightning pipeline supports triggering based on conditions. If code changes are detected in the corresponding directory, the corresponding test pipeline will be triggered. Block PR merging if the test pipeline execution fails.
It should be noted that because prow does not support configuring these two parameters at the same time (`run_if_changed` and `skip_if_only_changed`), after applying this change. If there are changes in pure document categories for br & lightning, it will also trigger the test pipeline.

feat: br ci support run_if_changed

---

prow-jobs/pingcap-tidb-latest-presubmits.yaml

Reverts PingCAP-QE/ci#2885
We found that even without modifying the br/ directory code, it will still trigger, so we revert first and then investigate the reason before enabling it again.

Revert "feat: br ci support run_if_changed"

---

jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy

Disable trigger on tikv old ut master branch because the new pipeline is ready.

chore: disable trigger on tikv old ut master branch

---

prow-jobs/pingcap-tidb-latest-presubmits.yaml

Reverts PingCAP-QE/ci#2899
We have updated the Prow status reconciler and fixed the bug that triggered all open pull requests after modifying the regex. https://github.com/ti-community-infra/test-infra/pull/47

feat(pingcap/tidb): support run_if_changed for br module

---

pipelines/tikv/tikv/release-6.1/pull_unit_test.groovy
pipelines/tikv/tikv/release-6.5/pull_unit_test.groovy
pipelines/tikv/tikv/release-7.1/pull_unit_test.groovy
pipelines/tikv/tikv/release-7.5/pull_unit_test.groovy
pipelines/tikv/tikv/release-8.1/pull_unit_test.groovy
prow-jobs/kustomization.yaml
prow-jobs/tikv-tikv-release-6.5-presubmits.yaml
prow-jobs/tikv-tikv-release-7.1-presubmits.yaml
prow-jobs/tikv-tikv-release-7.5-presubmits.yaml
prow-jobs/tikv-tikv-release-8.1-presubmits.yaml

Enable trigger for new tikv ut on lts branch. After a period of testing, we will enable status reporting and automatic triggering.

chore: enable trigger for new tikv ut on lts branch

---

pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
pipelines/pingcap/tiflash/latest/pod-pull_unit-test.yaml

revert to use llvm13 image on master tiflash new ut pipeline.

chore(tiflash): revert to use llvm13 image on master

---

jenkins/pipelines/ci/ticdc/dm_ghpr_compatibility_test.groovy

use target branch to downloda tidb binary, only support for qa-release-test trigger

chore(dm): use target branch to downloda tidb binary

---

pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy
pipelines/pingcap/tidb/release-7.1/pull_br_integration_test.groovy
pipelines/pingcap/tidb/release-7.5/pull_br_integration_test.groovy
pipelines/pingcap/tidb/release-8.1/pull_br_integration_test.groovy

Since https://github.com/pingcap/tidb/pull/52734, we need to use failpoint tidb-server for br integration test

fix(br): use failpoint tidb-server instead

---

pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_pulsar_test.yaml

ticdc pulsar integration test failed frequently, but when we run it on local env, it never fail, so this PR increase ticdc pulsar integration test resource.

increase ticdc pulsar integration test resource

---

pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_kafka_test.yaml

ticdc kafka integration test failed frequently, but when we ran it on local env, it never fail, so this PR increase ticdc kafka integration test resource.

increase ticdc kafka integration test resource

---

pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
pipelines/pingcap/tiflash/latest/pull_unit_test.groovy

Retry only after get src code cache from ks3. It takes about 7 minutes to retrieve and decompress the code cache from ks3. We only need to retry when git fetch fails to update due to network.

chore(tiflash): retry only after get src code cache from ks3

---

jenkins/pipelines/cd/atom-jobs/products/tiflash/master.groovy
jenkins/pipelines/cd/dev-build.groovy
jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
jenkins/pipelines/cd/pre-release-community-docker-rocky.groovy
jenkins/pipelines/cd/pre-release-enterprise-docker-rocky.groovy
pipelines/pingcap/tidb/latest/merged_tiflash_test.groovy
pipelines/pingcap/tidb/latest/pull_tiflash_test.groovy

Reverts PingCAP-QE/ci#2958
It broken the dev-builds since of the issue, we must solve it atomic:
```log
[2024-05-10T10:29:43.850Z] + docker build --pull -t 325168c9-8528-454b-9e0f-2041080ee440 . --build-arg 'BASE_IMG='
```

Revert "refactor(jenkins/pipelines,pipelines): use the new dockerfile url location"

---

pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
pipelines/pingcap/docs/latest/merged_update_docs.groovy
prow-jobs/pingcap-docs-cn-postsubmits.yaml
prow-jobs/pingcap-docs-postsubmits.yaml

Update the stable PDF version of TiDB and TiDB Cloud:
- TiDB: the stable PDF version is updated from release-7.5 to release-8.1.
- TiDB Cloud: the stable PDF version will remain at release-7.5 to ensure consistency with the current TiDB Cloud documentation.

docs: bump pdf stable version to release-8.1

---

scripts/pingcap/community/update-prow-owners.ts

skip the repository when the bot has no rights to create refs.

fix(scripts): fix update-prow-owners.ts

---

pipelines/pingcap/docs-tidb-operator/latest/merged_update.groovy

Update the stable PDF version of TiDB Operator from release-1.5 to release-1.6

k8s docs: bump pdf stable version to release-1.6

---

scripts/artifacts/tag-rc2ga-on-repos.sh

feat(scripts/artifacts): add shell function `publish_tiup_from_oci_artifact_repos`

---

pipelines/pingcap/tidb/latest/pull_lightning_integration_test.groovy

try to collect failure log after test timeout

feat: try to collect failure log after test timeout

---

jenkins/pipelines/cd/build-tidb-dashboard.groovy

opt(pingcap/tidb-dashboard): speedup image building fo linux/arm64 target

---

scripts/artifacts/check-images-internal.sh
scripts/artifacts/check-tiup.sh

fix(scripts/artifacts): not override other parts in output file

---

jenkins/pipelines/cd/pre-release-docker-rocky-sync.groovy

fix(jenkins/pipelines/cd): keep same tags with inner repositories  on GCR

---

prow-jobs/ti-community-infra/prow/postsubmits.yaml
prow-jobs/ti-community-infra/prow/presubmits.yaml

fix(ti-community-infra/prow): fix image building jobs

---

OWNERS
OWNERS_ALIASES
jenkins/OWNERS
jenkins/jobs/cd/OWNERS
jenkins/pipelines/cd/OWNERS
jobs/OWNERS
libraries/OWNERS
pipelines/OWNERS
prow-jobs/OWNERS
prow-jobs/ti-community-infra/prow/postsubmits.yaml
prow-jobs/ti-community-infra/prow/presubmits.yaml
scripts/plugins/OWNERS
staging/OWNERS

fix(ti-community-infra/prow): let the heavy job run in other cluster

---

pipelines/pingcap/tidb-tools/latest/pull_verify.groovy

temp comment cross-compile platform darwin. cross-compile on Linux amd64 for the platform GOOS=darwin GOARCH=amd64 will encountered error.

fix: temp comment cross-compile platform darwin

---

pipelines/pingcap/tidb-tools/latest/pull_verify.groovy

feat(pingcap/tidb-tools): add integration tests

---

scripts/ops/statics-repo-code-lines.ts

fix(scripts/opt): update to new deno version

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

add 8.1 tikv cache image build
___
enhancement
___
- Added a new build step for the `release-8.2` branch in the TiKV cache image build process.
- Ensures that the `release-8.2` branch is included in the CI pipeline.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>tikv_ghpr_cache.groovy</strong><dd><code>Add build step for `release-8.2` branch in TiKV cache image</code></dd></summary>
<hr>
jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy
- Added build step for `release-8.2` branch.
</details>
</td>
<td><a href="https://github.com/PingCAP-QE/ci/pull/3010/files#diff-42307aa09c6c78d80cec5458b31dff8753ec68a6d317699ba7cefaf2918a74b8">+1/-0</a>&nbsp; &nbsp; &nbsp; …

feat: add 8.2 tikv cache image build 

---

prow-jobs/pingcap/monitoring/periodics.yaml

___
Enhancement
___
- Added a new periodic job named `periodic-update-pingcap-monitoring-dmr-8.2` for the `release-8.2` branch.
- Updated the `golang` image version from `1.21.6` to `1.21.11` for existing periodic jobs.
- Ensured consistent formatting and indentation across the file.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>periodics.yaml</strong><dd><code>Add periodic job for release-8.2 and update golang image version</code></dd></summary>
<hr>
prow-jobs/pingcap/monitoring/periodics.yaml
<li>Updated <code>golang</code> image version from <code>1.21.6</code> to <code>1.21.11</code>.<br> <li> Added a new …

feat(prow-jobs/pingcap/monitoring): add periodic type job to update file for release-8.2

---

pipelines/tikv/tikv/release-8.2/pull_unit_test.groovy

fix pod yaml path
___
Bug fix
___
- Fixed the path to the pod YAML file in the `pull_unit_test.groovy` script to ensure the correct file is referenced.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pull_unit_test.groovy</strong><dd><code>Fix pod YAML file path in Groovy script.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pipelines/tikv/tikv/release-8.2/pull_unit_test.groovy
- Corrected the path to the pod YAML file.
</details>
</td>
<td><a href="https://github.com/PingCAP-QE/ci/pull/3015/files#diff-36661dd3b075dc1a3e89481456b65422b5417bc8b0db91a0227829249d6f0eda"> …

fix(pingcap/tikv): fix pod yaml path

---

pipelines/pingcap/tidb/latest/pod-pull_sqllogic_test.yaml
pipelines/pingcap/tidb/release-8.2/pod-pull_sqllogic_test.yaml

sqllogic test pod use specify node to avoid the test script from getting stuck
___
enhancement
___
- Added a node selector for `ci-nvme-high-performance` with value `true` in the `latest` pipeline configuration.
- Added a node selector for `ci-nvme-high-performance` with value `true` in the `release-8.2` pipeline configuration.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pod-pull_sqllogic_test.yaml</strong><dd><code>Add node selector for high-performance NVMe in latest pipeline</code></dd></summary>
<hr>
pipelines/pingcap/tidb/latest/pod-pull_sqllogic_test.yaml
<li>Added a node selector for <code>ci-nvme-high-performance</code> with value …

chore: sqllogic test pod use specify node

---

jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy

enhancement
___
- Updated the `builder` container image in the TiFlash sanitizer daily pipeline to `hub.pingcap.net/tiflash/tiflash-llvm-base:amd64-llvm-17.0.6`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>tiflash-sanitizer-daily.groovy</strong><dd><code>Update `builder` container image in TiFlash sanitizer pipeline</code></dd></summary>
<hr>
jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy
<li>Updated the <code>builder</code> container image to <br><code>hub.pingcap.net/tiflash/tiflash-llvm-base:amd64-llvm-17.0.6</code>.<br>
</details>
</td>
<td><a href="https://github.com/PingCAP-QE/ci/pull/3018/files#diff-cf6e0f80b8d57ff16c04804cccb20aa2048f6041 …

Update sanitizer tiflash image

---

prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
prow-jobs/pingcap/docs/docs-postsubmits.yaml

configuration changes
___
- Updated branch patterns in `docs-cn-postsubmits.yaml` and `docs-postsubmits.yaml` to include support for `release-8.2`.
- Removed support for `release-5.0` and `release-6.6` in both files.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>docs-cn-postsubmits.yaml</strong><dd><code>Update branch patterns for docs-cn postsubmits</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
<li>Updated branch patterns for postsubmits.<br> <li> Added support for <code>release-8.2</code>.<br> <li> Removed support for <code>release-5.0</code> …

docs PDF: add release-8.2 and remove archived versions

---

jenkins/pipelines/ci/tiflash/tiflash-sanitizer-daily.groovy

Fix that git considers the directory as not safe, making tiflash sanitizer failed to build
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/1987/pipeline/
```
[2024-07-01T18:48:01.172Z] fatal: detected dubious ownership in repository at '/home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash'
[2024-07-01T18:48:01.172Z] To add an exception for this directory, call:
[2024-07-01T18:48:01.172Z] 
[2024-07-01T18:48:01.172Z] 	git config --global --add safe.directory /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash
```
ref https://github.com/pingcap/tiflash/issues/7193
___
Bug fix, Configuration changes
___
- Added commands to configure Git safe directories to avoid build failures due to dubious ownership detection.
- …

Fix building tiflash-sanitizer

---

pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_mysql_connector_test.yaml
pipelines/pingcap/tiproxy/latest/pod-pull_mysql_connector_test.yaml

After upgrading tidb deps to v1.1.0 in tiproxy, the test `mysql_connector_test` reports:
```
/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20240428083427-66ba419636ce/pkg/types/compare.go:18:2: package cmp is not in GOROOT (/usr/local/go/src/cmp)
note: imported by a module that requires go 1.21
/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20240428083427-66ba419636ce/pkg/util/stmtsummary/v2/stmtsummary.go:20:2: package maps is not in GOROOT (/usr/local/go/src/maps)
note: imported by a module that requires go 1.21
/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20240424052342-0229f4077f0c/internal/locate/region_cache.go:44:2: package slices is not in GOROOT (/usr/local/go/src/slices)
note: imported by a module that requires go 1.21
```
Maybe I should upgrade the golang image.
___ …

fix(deps): update golang image for mysql_connector_test

---

scripts/artifacts/check-tiup.sh

___
Bug fix
___
- Added a command to create `results.yaml` file if it does not exist in `scripts/artifacts/check-tiup.sh`.
- This prevents potential errors when the script attempts to modify a non-existent file.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>check-tiup.sh</strong><dd><code>Ensure `results.yaml` file exists before modification</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
scripts/artifacts/check-tiup.sh
<li>Added a command to create <code>results.yaml</code> file if it does not exist.<br>
</details>
</td>
<td><a href="https://github.com/PingCAP-QE/ci/pull/3023/files#diff-83f2cad14e0bb5b9198ff6572612 …

fix(scripts/artifacts): fix check-tiup.sh

---

scripts/artifacts/check-tiup.sh

___
Bug fix
___
- Added a conditional check in `check_results` function to handle the `tikv` package differently during git_sha verification.
- This change addresses the issue of `tikv` amd64 building hang by allowing more than two unique git_sha values for `tikv`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>check-tiup.sh</strong><dd><code>Add workaround for `tikv` amd64 building hang in check-tiup.sh</code></dd></summary>
<hr>
scripts/artifacts/check-tiup.sh
<li>Added conditional check for <code>tikv</code> package to handle git_sha <br>verification differently.<br> <li> Modified the <code>check_results</code> function …

fix(scripts/artifacts): workaround tikv amd64 building hang problem

---

pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy

archive log if test not successful, eg test timeout
___
enhancement
___
- Modified the post-build action in the `ghpr_mysql_test.groovy` pipeline script to archive logs if the test is unsuccessful instead of only on failure.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ghpr_mysql_test.groovy</strong><dd><code>Archive logs if test is unsuccessful instead of failure</code>&nbsp; &nbsp; </dd></summary>
<hr>
pipelines/pingcap/tidb/latest/ghpr_mysql_test.groovy
<li>Changed the post-build action from <code>failure</code> to <code>unsuccessful</code> for <br>archiving artifacts.<br>
</details>
</td>
<td><a href="https://github.com/PingCAP-QE/ci/pull/3028/files#diff-1 …

chore(tidb): archive log if test not successful

---

prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
prow-jobs/pingcap/docs/docs-postsubmits.yaml

v5.1 and v7.5 PDFs are archived and will no longer trigger new PDF builds.
___
configuration changes
___
- Removed `release-5.1` branch from postsubmits configuration in `docs-cn-postsubmits.yaml` and `docs-postsubmits.yaml`.
- Removed `release-7.6` branch from postsubmits configuration in `docs-cn-postsubmits.yaml` and `docs-postsubmits.yaml`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>docs-cn-postsubmits.yaml</strong><dd><code>Update postsubmits configuration for archived branches</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
<li>Removed branch <code>release-5.1</code> from postsubmits<br> <li> …

docs-pdf: remove v5.1 and v7.5 as they are archived 

---

jenkins/pipelines/cd/dev-build.groovy

build tiflash with rust cache for reducing external traffic downloads
___
enhancement
___
- Added a new string parameter `USE_TIFLASH_RUST_CACHE` with the value 'true' to the build specification in `dev-build.groovy`.
- This change aims to build TiFlash with Rust cache to reduce external traffic downloads.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>dev-build.groovy</strong><dd><code>Add `USE_TIFLASH_RUST_CACHE` parameter to build spec</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
jenkins/pipelines/cd/dev-build.groovy
<li>Added a new string parameter <code>USE_TIFLASH_RUST_CACHE</code> with the value <br>'true' to the build specification.<br> …

feat: build tiflash with rust cache 

---

jenkins/pipelines/cd/nightly/release-all-images-by-branch.groovy
jenkins/pipelines/cd/nightly/tiup-release-tidb-master-nightly.groovy
jenkins/pipelines/cd/tiup/tiup-mirror-update-multi-products.groovy
jenkins/pipelines/cd/tiup/tiup-online-mirror-atom.groovy

bump master nightly version to v8.3.0-alpha.

chore: bump master nightly version to v8.3.0-alpha

---

prow-jobs/pingcap/tidb/latest-presubmits.yaml
prow-jobs/pingcap/tiflash/latest-presubmits.yaml
prow-jobs/pingcap/tiflow/latest-presubmits.yaml
prow-jobs/tikv/pd/latest-presubmits.yaml
prow-jobs/tikv/tikv/latest-presubmits.yaml

feat(pingcap/tiflow,pingcap/pd): support feature branch

---

prow-jobs/pingcap/tidb/latest-presubmits.yaml

Also trigger`BR` integration testing when changes are made to `DDL` module. @BornChanger @Benjamin2037
Fixes #3039

chore(pingcap/tidb): update trigger for CI job `pull-br-integration-test`

---

pipelines/pingcap/tidb/latest/pull_integration_ddl_test.groovy

you can append suffix in pr title to set pd and tikv branch:
"| tikv=feature/xxx pd=master"
default to use master branch bulid binary if not specify in pr title.
Ref https://github.com/PingCAP-QE/ci/issues/3041

feat(pingcap/tidb): intergration support feature branch and ci params in PR title

---

scripts/artifacts/check-images-internal.sh
scripts/artifacts/check-images-internal.ts
scripts/artifacts/check-tiup.ts
scripts/ops/search-lark-user-by-githubid.ts

Also add Deno scripts:
- scripts/artifacts/check-image-internal.ts
- scripts/artifacts/check-tiup.sh
- ops/search-lark-user-by-githubid.ts

fix(scripts/artifacts): fix check-images-internal.sh

---

jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tiflash_multi_branch.groovy

Add support on multibranch build on feature branch of tidb & tiflash.

chore: add support for feature branch build

---

pipelines/pingcap/tiflash/latest/pull_unit_test.groovy
pipelines/pingcap/tiflash/release-6.1/pull_unit_test.groovy
pipelines/pingcap/tiflash/release-6.5/pull_unit_test.groovy
pipelines/pingcap/tiflash/release-7.1/pull_unit_test.groovy
pipelines/pingcap/tiflash/release-7.5/pull_unit_test.groovy
pipelines/pingcap/tiflash/release-8.1/pull_unit_test.groovy
pipelines/pingcap/tiflash/release-8.2/pull_unit_test.groovy

In some PRs with many changes, the tiflash binary compilation time and test execution time may exceed 60 minutes, so increase the timeout limit here.

chore: increate timeout for tiflash ut

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

* add 8.3 tikv cache image build
* remove 8.2 tikv cache image build

feat: add cache image build for 8.3

---

pipelines/pingcap/tiflash/release-8.1/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-8.1/pod-pull_unit-test.yaml

The git version in the original image was too old(v1.8.3), missing some command options, so the git version has been upgraded here(update git to v2.40.3).

fix: update git version to 2.40.3 in image

---

prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
prow-jobs/pingcap/docs/docs-postsubmits.yaml

reason for this PRL: Remove v5.2/v8.0 from the PDF building workflow because v5.2/v8.0 docs have been archived at https://docs-archive.pingcap.com/tidb and will no longer receive new updates.

docs-pdf: remove v5.2 and v8.0 as they are archived

---

pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
pipelines/pingcap/tiflash/latest/pull_unit_test.groovy

For PRs with significant changes, tiflash build binary generally takes 25 minutes. For some test instabilities or environment issues causing pipeline execution failures, repeatedly building the same commit SHA binary of a PR is unnecessary; therefore, adding a build cache is used for acceleration.

feat: cache build in tiflash pipeline

---

pipelines/pingcap/tiflow/latest/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/latest/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy

support downloading dependencies from a specified branch in PR titles.
Related to this PR: https://github.com/pingcap/tiflow/pull/11572

feat(tiflow): support downloading dependencies from a specified branch

---

jobs/tikv/pd/latest/pull_unit_test.groovy
pipelines/tikv/pd/latest/pod-pull_unit_test.yaml
pipelines/tikv/pd/latest/pull_unit_test.groovy
prow-jobs/tikv/pd/latest-presubmits.yaml

Refactor pd ut pipelines, Status reporting is disabled during the test period.

feat: refactor pd ut pipelines

---

jenkins/jobs/ci/tiflash/ghpr_build.groovy
jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy
prow-jobs/pingcap/tiflash/release-8.1-presubmits.yaml
prow-jobs/tikv/tikv/release-8.1-presubmits.yaml

Swtich to use new pipeline trigger by prow in tikv & tiflash branch release-8.1

feat: switch to use new pipeline trigger by prow in branch 8.1

---

pipelines/PingCAP-QE/tidb-test/latest/ghpr_common_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_common_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_jdbc_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_mysql_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_nodejs_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_python_orm_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy

feat: add retry and check binary

---

prow-jobs/ti-community-infra/configs/postsubmits.yaml

ci(ti-community-infra/configs): remove archived repo from sync list

---

libraries/tipipeline/vars/component.groovy

support checkout  not merged pr commit sha.

feat(lib): support checkout to pr commit sha

---

scripts/flow/ga/create_github_release.ts

fix(scripts/flow/ga): fix release note detail list

---

jenkins/jobs/ci/tiflash/ghpr_build.groovy
jenkins/jobs/ci/tiflash/ghpr_integration_test.groovy
jenkins/jobs/ci/tiflash/ghpr_unit_test.groovy
jenkins/jobs/ci/tikv/tikv/ghpr_test.groovy
prow-jobs/pingcap/tiflash/release-7.5-presubmits.yaml
prow-jobs/tikv/tikv/release-7.5-presubmits.yaml
scripts/ops/release-check-version/config.py

Swtich to use new pipeline trigger by prow in tikv & tiflash branch release-7.5

feat: switch to use new pipeline trigger by prow in branch 7.5

---

pipelines/pingcap/tidb/latest/pod-canary-ghpr_unit_test.yaml

fix(canary): fix pod vol

---

jobs/pingcap/aa_folder.groovy

Increase refreash time for lib cache from 1 hour to 1 day.

chore(lib): increase refreash time for lib cache

---

jobs/pingcap/tidb/latest/pull_unit_test_ddlv1.groovy
pipelines/pingcap/tidb/latest/pull_unit_test_ddlv1.groovy
prow-jobs/pingcap/tidb/latest-presubmits.yaml

This pull request introduces a new Jenkins pipeline job for running unit tests on the latest version of the `pingcap/tidb` repository. It includes the creation of the pipeline job, its definition, and updates to the relevant presubmits configuration.
* [`jobs/pingcap/tidb/latest/pull_unit_test_ddlv1.groovy`](diffhunk://#diff-1774a984294d89d34230774eb9ef00228b3ff3aecda9adc1e48adf624c810bb8R1-R38): Added a new pipeline job definition for `pingcap/tidb/pull_unit_test_ddlv1`, including parameters, properties, and SCM configuration.
* [`pipelines/pingcap/tidb/latest/pull_unit_test_ddlv1.groovy`](diffhunk://#diff-5bba6bdccf3d6f4b2c714649e73aa7e35188dda4e40683190e0e2fbb8b4b573cR1-R75): Implemented the pipeline script for the new job, setting up Kubernetes agents, environment variables, and …

feat(tidb): add ddlv1 unit test pipeline

---

pipelines/pingcap/tiflow/latest/pod-ghpr_verify.yaml
pipelines/pingcap/tiflow/latest/pod-merged_unit_test.yaml
pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_kafka_test.yaml
pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_pulsar_test.yaml
pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_storage_test.yaml
pipelines/pingcap/tiflow/latest/pod-pull_cdc_integration_test.yaml
pipelines/pingcap/tiflow/latest/pod-pull_dm_compatibility_test.yaml
pipelines/pingcap/tiflow/latest/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/latest/pod-pull_engine_integration_test.yaml

tiflow master bump go version to 1.23

feat(tiflow): tiflow master bump go version to 1.23

---

pipelines/pingcap/tiflash/release-7.5/pull_integration_test.groovy

user clang-format 15 after v7.4
releate to https://github.com/pingcap/tiflash/pull/7927/files#diff-a847e281c62ad2738f1616a96cd3174ca1fa5eba8134bf6f5d802a425c92c8b2R86-R90

fix: use clang-format 15 after v7.4

---

pipelines/pingcap/tiflash/release-8.1/pull_integration_test.groovy

Related to this PR https://github.com/pingcap/tiflash/pull/7927/files#diff-a847e281c62ad2738f1616a96cd3174ca1fa5eba8134bf6f5d802a425c92c8b2R86-R90
For versions greater than or equal to 7.4 and less than 8.2, use clang-format 15.

fix(tiflash): user clang-format 15 after v7.4

---

pipelines/tikv/pd/latest/ghpr_build.groovy
pipelines/tikv/pd/latest/pull_integration_copr_test.groovy
pipelines/tikv/pd/latest/pull_integration_realcluster_test.groovy
pipelines/tikv/pd/latest/pull_unit_test.groovy
pipelines/tikv/pd/release-6.5-fips/ghpr_build.groovy
pipelines/tikv/pd/release-6.5/ghpr_build.groovy
pipelines/tikv/pd/release-7.1/ghpr_build.groovy
pipelines/tikv/pd/release-7.1/pull_integration_copr_test.groovy
pipelines/tikv/pd/release-8.1/ghpr_build.groovy
pipelines/tikv/pd/release-8.1/pull_integration_copr_test.groovy

display pr info on pipeline run

feat(pd): display pr info on pipeline run

---

prow-jobs/pingcap/tidb/latest-presubmits.yaml

After a period of grayscale testing, we plan to enable this pipeline. This pipeline is set with conditional triggers, and changes to files in the specified directory will trigger it.

feat(tidb): enable ddlv1 ut pipeline

---

pipelines/pingcap/tiflash/release-6.1/pull_integration_test.groovy
pipelines/pingcap/tiflash/release-6.5/pull_integration_test.groovy
pipelines/pingcap/tiflash/release-7.1/pull_integration_test.groovy

for version <= 7.4, need use clang-format 12

chore: to use clang-format 12 for tiflash version less than v7.4

---

prow-jobs/pingcap/tidb/latest-postsubmits.yaml

Temporary disable failed job merged_integration_common_test due to https://github.com/pingcap/tidb/pull/56463, enable status reporting after fixing the test failure issue.

chore: temporary disable failed job

---

jenkins/pipelines/ci/tikv/tikv_ghpr_cache.groovy

Since 8.4, the base image has been switched from centos7 to rocky8, so we no longer use this task for cache image updates on branch master and 8.4.

feat: disable auto refresh cache image for master&8.4

---

jobs/pingcap/tiflash/latest/merged_build.groovy
pipelines/pingcap/tiflash/latest/merged_build.groovy
pipelines/pingcap/tiflash/latest/merged_unit_test.groovy
pipelines/pingcap/tiflash/latest/pod-merged_build.yaml
pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
prow-jobs/pingcap/tiflash/latest-postsubmits.yaml

Gen build cache in merge ci for tiflash.
* update base image from centos7 to rockylinux 8 because centos7 end of life
* update ccache version from 4.5 to 4.10
* Gen build and ut cache in merged pipelines

feat(tiflash): gen build cache in merge ci for tiflash

---

scripts/flow/rc/check-images-internal.ts
scripts/flow/rc/check-tiup.ts

- skip check for tidb-binlog since v8.4.0.
- fix the shell sharbang.

fix(script/flow/rc): fix flow check script

---

pipelines/tikv/pd/latest/pod-ghpr_build.yaml
pipelines/tikv/pd/latest/pod-pull_integration_copr_test.yaml
pipelines/tikv/pd/latest/pod-pull_integration_realcluster_test.yaml
pipelines/tikv/pd/latest/pod-pull_unit_test.yaml

CentOS 7 has reached the end of its life cycle. Starting from version 8.4, we begin using Rocky Linux 8 as the base image.

feat(pd): update base image to use rockylinux 8

---

pipelines/tikv/tikv/latest/pod-pull_unit_test.yaml
pipelines/tikv/tikv/latest/pull_unit_test.groovy
pipelines/tikv/tikv/release-8.4/pod-pull_unit_test.yaml
pipelines/tikv/tikv/release-8.4/pull_unit_test.groovy

CentOS 7 has reached the end of its life cycle. Starting from version 8.4, we began using Rocky Linux 8 as the base image.
* The default version of gcc in the new image is 8.5.0
* Temporarily use a docker image to implement the cargo cache, and after switching the base image, try to handle the cargo cache using the PVC

feat(tikv): start use rocky8 as base image since from 8.4

---

pipelines/pingcap/tiflash/latest/merged_build.groovy

fix(tiflash): correct build ccache path

---

pipelines/pingcap/tiflash/release-6.1/pull_integration_test.groovy
pipelines/pingcap/tiflash/release-6.5/pull_integration_test.groovy
pipelines/pingcap/tiflash/release-7.1/pull_integration_test.groovy
pipelines/pingcap/tiflash/release-7.5/pull_integration_test.groovy
pipelines/pingcap/tiflash/release-8.1/pull_integration_test.groovy

Remove clang-format-12, since we do not maintain the llvm@12 image.
For v6.1 ~ v7.1, using clang-format-13
For v7.5 ~ v8.1, using clang-format-15

chore(tiflash): use clang-format in image

---

prow-jobs/tikv/pd/latest-presubmits.yaml
prow-jobs/tikv/pd/release-6.5-presubmits.yaml

Hotfix branch release-6.5-20241101-v6.5.7 need go1.23, change trigger to use correct go version.

feat(pd): adjust trigger for branch  release-6.5-20241101-v6.5.7

---

jobs/pingcap-inc/aa_folder.groovy
jobs/pingcap-qe/aa_folder.groovy
jobs/pingcap/aa_folder.groovy
jobs/tikv/aa_folder.groovy

* Use git shallow clone for lib cache to optimize the issue of incomplete library downloads caused by network quality.
* Disable the autorefresh lib for folder pingcap

feat(lib): use git shallow clone for lib cache

---

prow-jobs/pingcap/tidb-engine-ext/latest-presubmits.yaml
prow-jobs/pingcap/tidb-engine-ext/release-6.1-latest-presubmits.yaml

Directly setting the CARGO_HOME variable will result in losing the default config and env configurations，so just creat link for git and registry of cargo cache.

fix(tidb-engine-ext): link git and registry cargo cache

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy
pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
pipelines/pingcap/tiflash/release-8.5/pull_integration_test.groovy

update the build script path.
Ref https://github.com/PingCAP-QE/ci/pull/3216

chore(tiflash): update CI/CD pipelines

---

prow-jobs/pingcap/tidb-engine-ext/latest-presubmits.yaml
prow-jobs/pingcap/tidb-engine-ext/release-6.1-latest-presubmits.yaml

Mount the necessary cargo home cache directory to reduce cache size.

feat(tidb-engine-ext): Mount the necessary cargo home cache directory

---

scripts/plugins/monitor-s3-object-size.ts

Add s3 object monitor clean script, The default S3 upload limit is 5GB, and some code caches may exceed this limit, causing the upload to fail.
* just monitor
```
deno run --allow-net --allow-env monitor-s3-object-size.ts \
--path="path" \
--threshold-mb=500 \
--feishu-webhook="xxxx"
```
* monitor and clean
```shell
deno run --allow-net --allow-env monitor-s3-object-size.ts \
--path="path" \
--threshold-mb=500 \
--feishu-webhook="xxxx" \
--cleanup
```

feat(script): add s3 object monitor clean script

---

pipelines/pingcap/docs/latest/merged_update_docs.groovy

As the default version for new TiDB Dedicated clusters has been updated to v8.1.0, this PR updates the cloud documentation branch to release-8.1 for PDF generation.

docs: change the cloud doc branch to release-8.1 for PDF output

---

prow-jobs/pingcap/tidb/release-8.5-presubmits.yaml

remove wip for test pull-integration-e2e-test on 8.5

chore: remove wip for test pull-integration-e2e-test on 8.5

---

pipelines/tikv/pd/release-8.1/pull_integration_copr_test.groovy
prow-jobs/tikv/tikv/release-7.5-presubmits.yaml

add supports for release feature branches and hotfix branches, keep it same with TiDB's CI jobs.

opt(tikv/pd): fix the pull_integration_copr_test job for [v7.4 ~ v8.4]

---

pipelines/pingcap/tiflow/latest/periodics_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/latest/pod-periodics_cdc_integration_kafka_test.yaml
prow-jobs/pingcap/tiflow/latest-periodics.yaml

* Add feishu notify for periodics cdc test pipeline
* Check Kafka availability in the pod readinessProbe.

chore(tiflow): add feishu notify

---

prow-jobs/kustomization.yaml
prow-jobs/pingcap/community/postsubmits.yaml
prow-jobs/pingcap/community/presubmits.yaml
prow-jobs/tikv/community/presubmits.yaml

This pull request includes updates to the `prow-jobs` configuration files to add new presubmit jobs and refine existing configurations. The most important changes include adding new presubmit job configurations for `pingcap/community` and `tikv/community`, and refining branch specifications for postsubmit jobs.
Some times the community maintainers contribute wrong format team membership json files, It will make the bot(ti-chi-bot) can not work to sync the OWNERS files for the controlled repositories. I made the pull request to add basic json verify jobs for membership json files to block wrong changes on format.
* [`prow-jobs/pingcap/community/presubmits.yaml`](diffhunk://#diff-201e72a2e194854030a794a5b8bbf9cbf0464c4ea4dfc225871c70eb822a4f23R1-R25): Added a new presubmit job `pull-verify` …

feat(tikv,pingcap): add lint job for community repos

---

pipelines/pingcap/tidb/latest/pod-merged_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_ddl_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_lightning_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_python_orm_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_mysql_client_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_tiflash_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_common_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_integration_common_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_integration_copr_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_integration_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_integration_jdbc_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_integration_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_integration_python_orm_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_sqllogic_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_tiflash_test.yaml

Update to use rocky8 image in merge ci pipelines.

chore(tidb): update to use rocky8 image

---

pipelines/pingcap/tidb/latest/pod-merged_sqllogic_test.yaml
pipelines/pingcap/tidb/latest/pod-pull_sqllogic_test.yaml

After adjusting the CentOS 7 image to Rocky 8, in order to reduce the image size, we did not include the test files in the image but prepare them during the pod init phase.

fix(tidb): prepare sqllogic test data in pod init

---

prow-jobs/pingcap-qe/ee-apps/presubmits.yaml

This pull request includes a small change to the `prow-jobs/pingcap-qe/ee-apps/presubmits.yaml` file. The change updates the image reference for the `secure-merge-check` container to remove the platform-specific suffix.
* [`prow-jobs/pingcap-qe/ee-apps/presubmits.yaml`](diffhunk://#diff-db56dc8ed1c82668a58b1ec5ccc1354f07976cbf913f080448232d3c5c497f99L13-R13): Updated the `image` field for the `secure-merge-check` container to use a more general image reference.

chore(deps): bump tag image for security scan task

---

pipelines/PingCAP-QE/tidb-test/latest/ghpr_integration_mysql_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/ghpr_mysql_test.groovy
pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_build.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_common_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_common_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_jdbc_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_mysql_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_integration_python_orm_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-ghpr_mysql_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_common_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_jdbc_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_mysql_test.yaml
pipelines/PingCAP-QE/tidb-test/latest/pod-pull_tiproxy_ruby_orm_test.yaml

Adjust image from centos7 to rocky8 because centos7 end of life.

feat(tidb-test):  adjust image from centos7 to rocky8

---

pipelines/pingcap/tiflow/latest/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-8.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_dm_compatibility_test.groovy

Reverts PingCAP-QE/ci#3269. The issue of encountering a 403 error when downloading from Kingsoft Cloud has been resolved.

Revert "fix(tiflow): temp bypass qiniuyun block download"

---

OWNERS
jobs/OWNERS

wrong introduce security team as reviewers in top OWNERS file.

chore: fix OWNERS

---

pipelines/pingcap/tiflow/latest/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-7.1/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-7.5/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-7.6/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-8.0/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-8.1/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-8.2/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-8.3/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-8.4/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-8.5/pod-pull_dm_integration_test.yaml

Use tini as init process in image to avoid zombie process after test kill some process.

fix(tiflow/dm): use tini image to avoid zombie process

---

prow-jobs/pingcap/tiflow/latest-presubmits.yaml
prow-jobs/pingcap/tiflow/release-5.3-presubmits.yaml
prow-jobs/pingcap/tiflow/release-5.4-presubmits.yaml
prow-jobs/pingcap/tiflow/release-6.0-presubmits.yaml
prow-jobs/pingcap/tiflow/release-6.1-presubmits.yaml
prow-jobs/pingcap/tiflow/release-6.2-presubmits.yaml
prow-jobs/pingcap/tiflow/release-6.5-20241101-v6.5.7-presubmits.yaml
prow-jobs/pingcap/tiflow/release-6.5-fips-presubmits.yaml
prow-jobs/pingcap/tiflow/release-6.5-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.1-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.1.0-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.2-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.3-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.4-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.5-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.6-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.0-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.1-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.2-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.3-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.4-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.5-centos-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.5-presubmits.yaml

To reduce the memory cost of triggering commands, keep the trigger command consistent with the context.
Taking pull-cdc-integration-kafka-test as an example. Context of this pipeline is `pull-cdc-integration-kafka-test` 
* The current trigger command is `/test cdc-integration-kafka-test`
* The adjusted trigger command is `/test pull-cdc-integration-kafka-test`
For `jenkins-ticdc/verify`, because this pipeline includes unit tests and build for multiple components (CDC and other components),  so we update this context to `pull-verify`
* The context will change from `jenkins-ticdc/verify` to `pull-verify`
* The trigger command will change from `/test verify` to `/test pull-verify`

chore(tiflow): keep the trigger command and context consistent

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy
pipelines/pingcap/tidb/latest/merged_unit_test.groovy
pipelines/pingcap/tidb/release-7.1/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-7.2/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-7.3/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-7.4/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-7.5/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-7.6/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-8.0/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-8.1/ghpr_unit_test.groovy
pipelines/pingcap/tidb/release-8.2/pull_unit_test.groovy
pipelines/pingcap/tidb/release-8.3/pull_unit_test.groovy
pipelines/pingcap/tidb/release-8.4/pull_unit_test.groovy
pipelines/pingcap/tidb/release-8.5/pull_unit_test.groovy

This pull request includes several changes to the unit test pipelines for different branches of the `pingcap/tidb` repository. The main focus is on adding a new stage for testing enterprise extensions. 
* Added a new stage named 'Test Enterprise Extensions' in multiple pipeline files to ensure that private submodules are tested. This stage includes steps to run tests and upload coverage data. [[1]](diffhunk://#diff-b56f73beeb61b056a6dd2b10e709f4e2c3fb1ce386038e2cba0e9fcaf75bf469R104-R131) [[2]](diffhunk://#diff-09bf784057b556598a5c45e45288e856c35774a5992096173ee90f949cefff4aL55-R122) [[3]](diffhunk://#diff-d07b38910eb3c884055beb55a4a6bf94a63c9a6906ef2fd7f9fa4a0bff783d55R104-R131) [[4]](diffhunk://#diff-fbb8d1f563c1585d02c3bc01ada595ccaec77a4632da766aa08d9f34f4c92a44R100-R127) …

fix(tidb): add unit test step for enterprise extensions

---

prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
prow-jobs/pingcap/docs/docs-postsubmits.yaml
prow-jobs/pingcap/docs/docs-tidb-operator-postsubmits.yaml

This PR stops the PDF builds of the following versions of docs as they have been archived. 
- TiDB v5.3
- TiDB v8.2
- TiDB Operator v1.2

docs-pdf-building: remove v5.3 and v8.2 as they are archived

---

pipelines/pingcap/tidb/release-6.5-20241101-v6.5.7/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.5-fips/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.5-with-kv-timeout-feature/ghpr_check.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_check.groovy

An error will be encountered when executing make bazel_prepare.
```shell
make bazel_prepare
./tools/check/check-bazel-prepare.sh
make[1]: Entering directory `/home/jenkins/agent/workspace/pingcap/tidb/release-6.5/ghpr_check/tidb'
bazel run //:gazelle
FATAL: corrupt installation: file '/home/jenkins/.cache/bazel/_bazel_jenkins/install/a09dbb90c658248f08f9aa0eba11997d/A-server.jar' is missing or modified.  Please remove '/home/jenkins/.cache/bazel/_bazel_jenkins/install/a09dbb90c658248f08f9aa0eba11997d' and try again.
make[1]: *** [bazel_prepare] Error 36
```
To fix the error, we need to delete this directory first.
Related issue  https://github.com/bazelbuild/bazel/issues/14355

fix(pingcap/tidb): fix bazel error

---

prow-jobs/pingcap/tidb/latest-periodics.yaml

Add an daily pipeline for some long tidb unit test cases.
Related PR https://github.com/pingcap/tidb/pull/58492.

feat(tidb): add long unit test daily pipeline

---

pipelines/pingcap/tiflow/latest/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy

Change the CI of pull_dm_integration_test and pull_engine_integration_test that are not covered by previous PR https://github.com/PingCAP-QE/ci/pull/3315.
Related retest:
- [pull_engine_integration_test](https://do.pingcap.net/jenkins/job/pingcap/job/tiflow/job/pull_engine_integration_test/3336/)
- [pull_dm_integration_test](https://do.pingcap.net/jenkins/job/pingcap/job/tiflow/job/pull_dm_integration_test/3934/)

Change tiflow CI to build sync_diff_inspector from source

---

pipelines/pingcap/docs-cn/latest/merged_update_docs_cn.groovy
pipelines/pingcap/docs-cn/latest/pod-merged_update_docs_cn.yaml
pipelines/pingcap/docs-tidb-operator/latest/merged_update.groovy
pipelines/pingcap/docs-tidb-operator/latest/pod-merged_update.yaml
pipelines/pingcap/docs/latest/merged_update_docs.groovy
pipelines/pingcap/docs/latest/pod-merged_update_docs.yaml

- Upgrade the Docker image to `hub.pingcap.net/jenkins/docs-cn-checker:v1.0.0`, which includes rclone integration
- Migrate storage from Qiniu Cloud to Tencent Cloud, implementing rclone for remote storage uploads to ensure S3 compatibility
- Relocate the TiDB Cloud PDF building process from the upload step to the build step
- Extend the docs pipeline timeout to accommodate the additional time required for building multiple PDFs

docs: migrate from Qiniu Cloud to Tencent Cloud

---

jenkins/pipelines/cd/atom-jobs/build-common.groovy

This pull request includes a small change to the `jenkins/pipelines/cd/atom-jobs/build-common.groovy` file. The change modifies the condition for using GCC 8 on Linux systems by checking for the existence of the file `/opt/rh/devtoolset-8/enable` instead of an empty `BUILDER_IMG` variable.
Changes in `jenkins/pipelines/cd/atom-jobs/build-common.groovy`:
* Modified the condition to check for the existence of the file `/opt/rh/devtoolset-8/enable` to enable GCC 8 on Linux systems.

fix(cd): fix build-comon for tikv when given builder image

---

libraries/tipipeline/vars/component.groovy

For the hotfix branch(example release-8.5-20250114-v8.5.0), we need to checkout the corresponding minimum version of the tidb-test code (release-8.5.0).

fix(tidb): checkout to minor version of tidb-test for hotfix

---

prow-jobs/pingcap/tidb/latest-postsubmits.yaml

Copr-test is broken after PR https://github.com/pingcap/tidb/pull/58261, temporarily skip report until the issue https://github.com/pingcap/tidb/issues/58509  fixed.

chore(tidb): temporarily skip until the test is fixed

---

pipelines/pingcap/tiflash/latest/pod-merged_build.yaml
pipelines/pingcap/tiflash/latest/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-6.1/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-6.5/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-7.1/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-7.5/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-8.1/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-8.2/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-8.3/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-8.4/pod-pull_build.yaml
pipelines/pingcap/tiflash/release-8.5/pod-merged_build.yaml
pipelines/pingcap/tiflash/release-8.5/pod-pull_build.yaml

The current memory limit is 32G, and during the tiflash compilation process, there are instances of OOM occurring on the master branch code.  Maybe recent changes of tiflash have led to a need for more memory.

chore(tiflash): increase memory limit to avoid build oom

---

pipelines/pingcap/tiflash/latest/pull_integration_test.groovy

Compilation is time-consuming, so we put the license check first to avoid wasting time on recompilation.

chore(tiflash): run license check before build

---

prow-jobs/pingcap/tidb/release-8.5-presubmits.yaml

Enable condition trigger for br integration test pipepline on lts branch release-8.5，PRs that modify relevant files need to pass this test before they can be merged.

feat(br): enable condition trigger for br test on 8.5

---

prow-jobs/pingcap/tidb/release-8.1-presubmits.yaml

Enable condition trigger for br integration test pipepline on lts branch release-8.1，PRs that modify relevant files need to pass this test before they can be merged.

feat(br): enable condition trigger of br test on 8.1

---

pipelines/pingcap/tiflow/release-8.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-8.1/pull_engine_integration_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_engine_integration_test.groovy

1. Default to pulling images from the corresponding release branch (like release-8.1)
2. Support specifying the tag of the TiDB image in the PR title of the hotfix branch.

feat(tiflow): use correct tidb cluster branch on hotfix

---

prow-jobs/pingcap/tidb/release-8.1-presubmits.yaml

Reverts PingCAP-QE/ci#3332
Some br tests have failed; automatic triggering will be enabled after the tests are fixed.
test link:
1. https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Frelease-8.1%2Fpull_br_integration_test/detail/pull_br_integration_test/29/pipeline/241

Revert "feat(br): enable condition trigger of br test on 8.1"

---

prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml

Close #3345
This pull request includes several updates to the `prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml` file. The changes primarily focus on updating branch patterns and adding new presubmit job configurations.
Branch pattern updates:
* Updated the branch patterns in the `brancher` section to be more specific, replacing the previous patterns with `^release-6[.][1-9].*Close #3345
and `^release-[78][.].*Close #3345
.
Presubmit job configurations:
* Added the `skip_if_only_changed` field to the existing presubmit job configuration for `idc-jenkins-ci-binlog/build`.
* Introduced a new presubmit job named `pull-check` with detailed specifications, including container settings, environment variables, resource limits, and node affinity requirements.

refactor(pingcap/tidb-binlog): refactor check job to prow style

---

prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml

refactor(pingcap/tidb-binlog): refactor integration-test job to prow style

---

jenkins/pipelines/cd/dev-build.groovy

This pull request includes significant changes to the `jenkins/pipelines/cd/dev-build.groovy` file to improve the mapping and retrieval of Docker image URLs and Dockerfile URLs. The most important changes include the introduction of a new mapping for Docker image repositories, updates to the Dockerfile URL retrieval logic, and adjustments to the image naming conventions.
Improvements to Docker image and Dockerfile mappings:
* [`jenkins/pipelines/cd/dev-build.groovy`](diffhunk://#diff-883dea4e305e8d8dffff92a73f812d069fd76eaf118e96b9efd1bdc219de9fe6L1-R35): Introduced `DockerImgRepoMapping` to map products to their respective Docker image repositories. This replaces the previous `DockerMapping` and expands the coverage to include more products.
* …

fix(cd): update docker image repo and dockerfiles for devbuild job

---

pipelines/pingcap/tidb/latest/ghpr_unit_test.groovy

run the UT of pkg/extension/enterprise/... when changes are made on `pkg/extension` path.
Close #3376

feat(pingcap/tidb): update UT job for master branch to cover enterprise extension

---

pipelines/pingcap/tiflow/latest/pod-pull_syncdiff_integration_test.yaml
pipelines/pingcap/tiflow/latest/pull_engine_integration_test.groovy
pipelines/pingcap/tiflow/latest/pull_syncdiff_integration_test.groovy

Related tiflow changes: https://github.com/pingcap/tiflow/pull/12060

Add new CI for tiflow to enable integration tests of sync_diff_inspector

---

jobs/pingcap/tiflow/latest/pull_syncdiff_integration_test.groovy
prow-jobs/pingcap/tiflow/latest-presubmits.yaml

Ref https://github.com/PingCAP-QE/ci/pull/3387
Add trigger for new pipeline of sync_diff_inspector. Enable the condition trigger and remove the WIP  after passing the test.

feat(tiflow): add trigger for new sync_diff pipeline

---

jobs/pingcap/ticdc/aa_folder.groovy
jobs/pingcap/ticdc/latest/pull_cdc_mysql_integration_heavy.groovy
jobs/pingcap/ticdc/latest/pull_cdc_mysql_integration_light.groovy
pipelines/pingcap/ticdc/latest/pod-pull_cdc_mysql_integration_heavy.yaml
pipelines/pingcap/ticdc/latest/pod-pull_cdc_mysql_integration_light.yaml
pipelines/pingcap/ticdc/latest/pull_cdc_mysql_integration_heavy.groovy
pipelines/pingcap/ticdc/latest/pull_cdc_mysql_integration_light.groovy
prow-jobs/pingcap/ticdc/latest-presubmits.yaml

Add two MySQL test integration testing pipelines for ticdc, related to another PR https://github.com/pingcap/ticdc/pull/1025
* pull_cdc_mysql_integration_light
* pull_cdc_mysql_integration_heavy
To make better use of resources, the tests are divided into light(4 core) and heavy(12 core) based on CPU consumption.
The naming of the pipeline should be concise and clear: cdc_${test_type}_integration_heavy, the value of test_type is mysql, kafka, or other test types.

feat(ticdc): new ticdc add mysql it pipeline

---

pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-6.1/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-6.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-6.1/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-6.5/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-6.5/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-6.5/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-6.5/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1.0/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_engine_integration_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_mysql_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-7.5/pull_engine_integration_test.groovy
pipelines/pingcap/tiflow/release-8.1/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_mysql_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_dm_integration_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_engine_integration_test.groovy

Download exact version content for tiflow hotfix branch integration tests.
Over time, the release branch will be continuously updated, and for the hotfix branch (from the tag), using non-fixed artifacts in integration testing may lead to test failures due to incompatible changes in dependency components(tidb & tikv & pd & tiflash). Therefore, we handle hotfixes separately in the pipeline; when a hotfix branch is detected, we download and test the dependencies for that tag version.
1. current PR will support for those lts hotfix branch:  6.1 & 6.5 & 7. 1 & 7.5 & 8.5
2. Support for 8.1 is in this PR: https://github.com/PingCAP-QE/ci/pull/3380

feat(tiflow): download exact version content for tiflow hotfix

---

scripts/flow/ga/create_github_release.ts

This pull request includes an update to the `scripts/flow/ga/create_github_release.ts` file to exclude the `tidb-tools` repository from releases starting from version 9.0.0. This change ensures that the `tidb-tools` repository, which has migrated its code to the `tiflow` repository, is no longer included in the release process.
* [`scripts/flow/ga/create_github_release.ts`](diffhunk://#diff-c5760f7bc08ebe7f0db7f1eee0626e0844179cd9e4def16db9c809f45d5e4e89R111-R116): Added logic to filter out the `tidb-tools` repository for versions 9.0.0 and above.

chore(scripts/flow/ga): do not create github version tag on tidb-tools repo for since v9.0.0

---

pipelines/pingcap/tiflash/latest/pull_unit_test.groovy

Previously bench_dbms is not compiled at all, and it has been broken for a while.
Now we fixed it in https://github.com/pingcap/tiflash/pull/9948 and would like to check it in CI as well.
See replay: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflash%2Fpull_unit_test/detail/pull_unit_test/3428/pipeline/177/

feat(tiflash): compile bench_dbms in PR pipelines

---

scripts/flow/build/versioning-strategy.md
scripts/flow/build/versioning-strategy.test.ts
scripts/flow/build/versioning-strategy.ts

you can run it by one method of them:
- run with file params:
```bash
deno run --allow-read --allow-write scripts/flow/build/versioning-strategy.ts --git_version_file release_version.txt --contain_branches_file branches.txt
```
- run with literal params:
```bash
deno run --allow-write scripts/flow/build/versioning-strategy.ts --git_version=v9.0.0-beta.0-2-g12235 --contain_branches=release-9.0
```

feat(scripts/flow/build): add versioning strategy script

---

prow-jobs/pingcap/tiflow/latest-presubmits.yaml

pull-syncdiff-integration-test has been tested and passed, and there are plans to remove the wip/ label and enable conditional triggering.
After that, the new release branch also needs to configure this pipeline.

feat(tiflow): synfdiff it remove wip and enable condition trigger

---

prow-jobs/pingcap/monitoring/periodics.yaml

It should be merged after the branch `release-9.0-beta.1` be created.

feat(prow-jobs): add perioldic job for monitoring repo to support v9.x

---

pipelines/pingcap/tiflow/release-9.0-beta/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-9.0-beta/pull_cdc_integration_mysql_test.groovy
pipelines/pingcap/tiflow/release-9.0-beta/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/release-9.0-beta/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-9.0-beta/pull_dm_compatibility_test.groovy
pipelines/pingcap/tiflow/release-9.0-beta/pull_dm_integration_test.groovy

Remove unnecessary version check for sync_diff_inspector in multiple CDC integration test pipelines for the release-9.0-beta.M branch.

chore(tiflow): remove sync_diff_inspector version check in CDC test pipelines

---

pipelines/pingcap/tidb/release-6.1/periodics_br_integration_test.groovy
pipelines/pingcap/tidb/release-6.5/periodics_br_integration_test.groovy
pipelines/pingcap/tidb/release-7.1/periodics_br_integration_test.groovy
pipelines/pingcap/tidb/release-7.5/periodics_br_integration_test.groovy
pipelines/pingcap/tidb/release-8.1/periodics_br_integration_test.groovy

Eliminate CODECOV_TOKEN environment variable and timeout options from the "Test" stage in periodic BR integration test pipelines across multiple release branches (6.1, 6.5, 7.1, 7.5, and 8.1) for cleaner configuration.

refactor(br): remove CODECOV_TOKEN and timeout options on test stages of periodics jobs

---

prow-jobs/pingcap/ticdc/latest-presubmits.yaml

These two test pipelines have passed testing and can now enable conditional triggers, requiring tests to be run before merging the PR.
Refactor the latest-presubmits.yaml to introduce a reusable skip_if_only_changed pattern and update the trigger expressions for the MySQL integration jobs to allow for 'all' tests. Additionally, set the optional flag to false for both integration jobs.

chore(ticdc): update presubmit job configurations to modify triggers

---

pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_cdc_integration_kafka_test.yaml
pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_cdc_integration_mysql_test.yaml
pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_cdc_integration_pulsar_test.yaml
pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_cdc_integration_storage_test.yaml
pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_dm_compatibility_test.yaml
pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_dm_integration_test.yaml
pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_engine_integration_test.yaml
pipelines/pingcap/tiflow/release-9.0-beta/pod-pull_verify.yaml

-  Changed golang container images from centos7 to rocky8 across multiple test configurations.
- Adjusted CPU and memory requests for golang and added new report containers with specified resources in various test YAML files.
- Introduced init containers for MySQL configuration in DM compatibility and integration tests.

chore(tiflow): update container images and resource requests for integration tests

---

pipelines/pingcap/tiflash/latest/merged_build.groovy
pipelines/pingcap/tiflash/release-9.0-beta/merged_build.groovy

- Implemented logic to upload proxy cache only if the commit hash is valid and the refresh is enabled.
- Added checks to skip upload if the cache already exists or if the proxy library is not found.
- Updated messages to provide clear feedback on the upload process.

feat(pipelines): Add proxy cache upload logic on master merged-build pipeline

---

jobs/pingcap/ticdc/latest/pull_cdc_kafka_integration_light.groovy
jobs/pingcap/ticdc/latest/pull_cdc_pulsar_integration_light.groovy
jobs/pingcap/ticdc/latest/pull_cdc_storage_integration_light.groovy
pipelines/pingcap/ticdc/latest/pod-pull_cdc_kafka_integration_light.yaml
pipelines/pingcap/ticdc/latest/pod-pull_cdc_pulsar_integration_light.yaml
pipelines/pingcap/ticdc/latest/pod-pull_cdc_storage_integration_light.yaml
pipelines/pingcap/ticdc/latest/pull_cdc_kafka_integration_light.groovy
pipelines/pingcap/ticdc/latest/pull_cdc_mysql_integration_heavy.groovy
pipelines/pingcap/ticdc/latest/pull_cdc_pulsar_integration_light.groovy
pipelines/pingcap/ticdc/latest/pull_cdc_storage_integration_light.groovy
prow-jobs/pingcap/ticdc/latest-presubmits.yaml

Add the following three integration test pipeline configurations. Note that it is currently in the WIP testing phase.\
* pull-cdc-pulsar-integration-light
* pull-cdc-kafka-integration-light
* pull-cdc-storage-integration-light
Initially configure the light mode pipeline, and later distribute the tests with high load to the heavy pipeline based on actual testing conditions.

feat(ticdc): ticdc add new integration pipelines

---

pipelines/pingcap/ticdc/latest/pod-pull_cdc_kafka_integration_light.yaml

In the monitoring of Kafka Light Pipelines, the CPU throttling metric for net-tool is consistently around 60%. Therefore, it is necessary to increase the CPU allocation for net-tool. This PR increases net-tool’s CPU from 100m to 300m.

feat(ticdc): add net-tool cpu from 100m to 300m for kafka light pipelines

---

scripts/flow/ga/create-patch-release-branches.ts
scripts/flow/ga/create_github_release.ts

The script now creates branch names like "release-9.0-beta.1" for beta versions, while maintaining the existing format for regular releases.

feat(scripts/flow/ga): support beta release branch naming

---

prow-jobs/pingcap-qe/ci/periodics.yaml

This pull request includes changes to the `prow-jobs/pingcap-qe/ci/periodics.yaml` file to modify the git remote configuration commands.
Changes in git remote configuration:
* Updated the command to add a new git remote instead of setting the URL for an existing remote. This change ensures that the remote is added correctly if it doesn't already exist. [[1]](diffhunk://#diff-627e88a7426360b8626ef9a0002f3558221924cb7e816f08afa52255839473d7L110-R110) [[2]](diffhunk://#diff-627e88a7426360b8626ef9a0002f3558221924cb7e816f08afa52255839473d7L211-R211)

fix(prow-jobs/pingcap-qe/ci): fix git remote setup in periodic jobs

---

prow-jobs/pingcap-qe/ci/periodics.yaml

Use Alpine-based Google Cloud CLI image for smaller footprint and replace pixi dependency management with uv. Install github-cli directly through apk instead of using pixi global install.
I will use gcloud cli to implement cache for git clones.

refactor(prow-jobs/pingcap-qe/ci): switch from Ubuntu/pixi to Alpine/uv for crawl jobs

---

pipelines/pingcap/ticdc/latest/pod-pull_cdc_storage_integration_light.yaml

In the monitoring of Storage Light Pipelines, the CPU throttling metric for net-tool is consistently around 56%. Therefore, it is necessary to increase the CPU allocation for net-tool. The CPU usage of Golang doesn’t reach 6 cores, so the CPU resources can be reduced a bit. This PR increases net-tool’s CPU from 100m to 400m, and decreases golang's CPU from 6 to 4.

feat(ticdc): modify golang and net-tool cpu for kafka light pipelines

---

pipelines/pingcap/ticdc/latest/pod-pull_cdc_kafka_integration_light.yaml
pipelines/pingcap/ticdc/latest/pod-pull_cdc_mysql_integration_heavy.yaml
pipelines/pingcap/ticdc/latest/pod-pull_cdc_mysql_integration_light.yaml
pipelines/pingcap/ticdc/latest/pod-pull_cdc_pulsar_integration_light.yaml
pipelines/pingcap/ticdc/latest/pod-pull_cdc_storage_integration_light.yaml

After lots of tests, setting the CPU limits of `golang` and `net-tool` to 6 and 600m respectively provides good performance in CPU throttling monitoring, without occupying too much resources.

feat(ticdc): modify golang and net-tool cpu for mysql, kafka, pulsar and storage

---

prow-jobs/pingcap/ticdc/latest-presubmits.yaml

This PR finalizes the setup for the `pull-cdc-kafka-integration-light`, `pull-cdc-pulsar-integration-light` and `pull-cdc-storage-integration-light`, but remains the `optional` flag in `pull-cdc-kafka-integration-light` and `pull-cdc-pulsar-integration-light` due to some unstable test cases.

feat(ticdc): modify kafka, pulsar and storage prow-jobs

---

prow-jobs/pingcap-qe/ci/periodics.yaml

- Add more organizations to crawl (pingcap, tidbcloud, PingCAP-QE) Extend commit crawling period from 10 to 11 years
- Increase job timeout from 12h to 23h30m
- Adjust CPU/memory resource allocations for better efficiency Add error handling for PR merge failures

chore(prow-jobs/pingcap-qe/ci): expand GitHub data collection scope and adjust resources

---

prow-jobs/pingcap/tidb-engine-ext/OWNERS
prow-jobs/pingcap/tidb-engine-ext/latest-presubmits.yaml

do a full clone in job `pull-unit-test`.

chore(prow-jobs/pingcap/tidb-engine-ext): update latest-presubmits.yaml

---

prow-jobs/pingcap-qe/ci/periodics.yaml

These jobs will now be executed by self-hosted GitHub Action runners instead of being managed by Prow.

chore(prow-jobs/pingcap-qe/ci): move periodic jobs to prow_ignored action

---

pipelines/pingcap/tiflash/latest/merged_build.groovy
pipelines/pingcap/tiflash/latest/pod-merged_build.yaml
pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
pipelines/pingcap/tiflash/latest/pod-pull_build.yaml
pipelines/pingcap/tiflash/latest/pod-pull_unit-test.yaml
pipelines/pingcap/tiflash/latest/pull_unit_test.groovy

This PR makes CI in https://github.com/pingcap/tiflash/pull/10081 compile:
1. Use -v2 image ([source](https://github.com/pingcap/tiflash/pull/10096)), which now supports dev tools used by CI, and protobuf-compiler required by TiFlash libclara
2. Mount libclara-cache directory
3. Utilize libclara-cache in PR build, and build libclara-cache after PR is merged.
A working CI to compile with libclara is: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflash%2Fpull_unit_test/detail/pull_unit_test/4044/pipeline
However due to libclara PR is not merged, the cache is not available yet.

chore (tiflash): Libclara support (1)

---

pipelines/pingcap/tiflash/latest/merged_build.groovy
pipelines/pingcap/tiflash/latest/merged_unit_test.groovy
pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
pipelines/pingcap/tiflash/latest/pull_unit_test.groovy

It turns out that cxxbridge is generating symbolic links:
```
❯ ls -la /Users/breezewish/Work/tiflash-cse/cmake-build-Debug/libs/libclara-cmake/cxxbridge/clara_fts/src
total 0
drwxr-xr-x  9 breezewish  staff  288  4 10 01:08 .
drwxr-xr-x  3 breezewish  staff   96  4 10 01:08 ..
lrwxr-xr-x  1 breezewish  staff  106  4 10 01:08 brute_searcher.rs.cc -> ../../../release/build/clara_fts-8ffc5909ded41509/out/cxxbridge/sources/clara_fts/src/brute_searcher.rs.cc
lrwxr-xr-x  1 breezewish  staff  105  4 10 01:08 brute_searcher.rs.h -> ../../../release/build/clara_fts-8ffc5909ded41509/out/cxxbridge/include/clara_fts/src/brute_searcher.rs.h
lrwxr-xr-x  1 breezewish  staff  104  4 10 01:08 index_reader.rs.cc -> ../../../release/build/clara_fts-8ffc5909ded41509/out/cxxbridge/sources/clara_fts/src/index_ …
```

fix(tiflash): Fix libclara build cache issue

---

scripts/ops/clean-cherry-pick-branches.ts

Safely removes merged cherry-pick branches by
checking for open PRs before deletion. Works across multiple repos (tidb, tiflash, tiflow, tikv, pd) using the GitHub API.
Usage:
```bash
deno run --allow-net scripts/ops/clean-cherry-pick-branches.ts -token <github token>
```

feat(scripts/ops): add cherry-pick branch cleanup script

---

pipelines/pingcap/tiflash/latest/merged_build.groovy
pipelines/pingcap/tiflash/latest/merged_unit_test.groovy
pipelines/pingcap/tiflash/latest/pull_integration_test.groovy
pipelines/pingcap/tiflash/latest/pull_unit_test.groovy

For update private git submodules

opt(pingcap/tiflash): add git.setSshKey before prow.checkoutRefs in TiFlash pipelines

---

prow-jobs/pingcap-inc/tici/presubmits.yaml

Remove manual protobuf installation as it's included in the TiKV builder image.
The image also contains CMake v3 tool.

feat(pingcap-inc/tici): update Rust build image to TiKV builder

---

pipelines/pingcap/tidb/latest/periodics_tidb_next_gen_smoke_test.groovy

update smoke test command to use --without-monitor flag

fix(tidb/next-gen): update smoke test command to use --without-monitor flag

---

prow-jobs/pingcap/tiflow/latest-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.1-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.2-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.3-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.4-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.5-presubmits.yaml
prow-jobs/pingcap/tiflow/release-7.6-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.0-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.1-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.2-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.3-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.4-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.5-centos-presubmits.yaml
prow-jobs/pingcap/tiflow/release-8.5-presubmits.yaml
prow-jobs/pingcap/tiflow/release-9.0-beta-presubmits.yaml

The tiflow `engine` module is deprecated and in unmaintained state.

fix(pingcap/tiflow): remove engine integration tests from presubmits jobs

---

prow-jobs/pingcap/tidb/latest-periodics.yaml

Update the name of the smoke test job to use the full path 'pingcap/tidb/periodics_tidb_next_gen_smoke_test' for better clarity

fix(tidb): rename smoke test job to include full path 

---

pipelines/pingcap/tidb/latest/pull_next_gen_real_tikv_test.groovy

* Add GIT_CREDENTIALS_ID to the pipeline configuration for improved authentication. 
* Remove timeout option from the Test stage for better flexibility and avoid groovy errors.

feat(pingcap/tidb): add Git credentials ID for next gen real tikv test pipeline

---

pipelines/pingcap/tidb/latest/pull_next_gen_real_tikv_test.groovy
prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

- Removed commented-out artifact fetching code from the test script.
- Simplified the list of test scripts to run by removing unnecessary entries.
- Updated the branch filter in the presubmit configuration to match the master branch instead of the feature branch.

refactor(pingcap/tidb): clean up next-gen real tikv test script and update branch filter in presubmit config

---

pipelines/pingcap/tiflash/latest/pod-merged_build.yaml
pipelines/pingcap/tiflash/latest/pod-merged_unit_test.yaml
pipelines/pingcap/tiflash/latest/pod-pull_build.yaml
pipelines/pingcap/tiflash/latest/pod-pull_unit-test.yaml

Avoid caching old images on some nodes in the cluster.

chore(pingcap/tiflash): set imagePullPolicy to Always for Tiflash pod configurations

---

pipelines/pingcap/tidb/latest/periodics_tidb_next_gen_smoke_test.groovy

Changed the TARGET_BRANCH_TIDB variable from "feature/next-gen-tidb" to "master" to align with the current branch strategy.
* The previous feature development branch has been deleted, and future development will be based on the Master branch.

chore(pingcap/tidb): update TARGET_BRANCH_TIDB to master in smoke test pipeline

---

prow-jobs/pingcap-inc/tici/presubmits.yaml

Introduced a new presubmit job named `pull-e2e-test` that includes an init container for preparing test assets and a main container for executing end-to-end tests. The job utilizes a cache volume for asset storage and specifies resource limits for the containers.

feat(tici): add pull-e2e-test job to presubmit configuration

---

prow-jobs/pingcap-inc/tici/presubmits.yaml

* update image to find mc and minio in path
* add job timeout 45mins

chore(tici): update e2e job image and set timeout to 45 minutes in presubmit configuration

---

prow-jobs/pingcap-inc/tici/presubmits.yaml
prow-jobs/pingcap/community/presubmits.yaml
prow-jobs/pingcap/tidb-binlog/latest-presubmits.yaml
prow-jobs/pingcap/tidb/latest-postsubmits.yaml
prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml
prow-jobs/pingcap/tidb/latest-presubmits.yaml
prow-jobs/pingcap/tiflash/latest-presubmits.yaml
prow-jobs/tikv/community/presubmits.yaml
prow-jobs/tikv/copr-test/latest-presubmits.yaml
prow-jobs/tikv/raft-engine/presubmits.yaml
prow-jobs/tikv/tikv/latest-presubmits.yaml

This pull request makes changes to the `skip_if_only_changed` configuration across multiple Prow job configuration files. The primary update adds `.gitignore` files to the list of file types that, when modified, will not trigger specific CI jobs. Additionally, the changes introduce YAML anchors and references to reduce redundancy in some configurations.
* Added `.gitignore` to the `skip_if_only_changed` regex pattern in multiple files, including `prow-jobs/pingcap-inc/tici/presubmits.yaml`, `prow-jobs/pingcap/community/presubmits.yaml`, and others. This ensures that changes to `.gitignore` files do not trigger unnecessary CI jobs. [[1]](diffhunk://#diff-3c1db7bcdc72f49245c498a5dbe018a2355b56a3bbf4672768743c419486c3aeL7-R7) [[2]](diffhunk://#diff-201e72a2e194854030a794a5b8bbf9cbf0464c4ea4df …

opt(prow-jobs): skip triggering CI jobs for changes on git ignore file

---

prow-jobs/tikv/raft-engine/presubmits.yaml

Raft engine CI fails https://github.com/tikv/raft-engine/actions/runs/15057664903/job/42326808634?pr=379
TiKV already uses 1.85+

Update rustc version

---

scripts/pingcap/community/prow-owners-updater.ts
scripts/pingcap/community/update-prow-owners.ts

…
The key `alias` is incorrect, the correct key is `aliases`. This commit fixes the key to `aliases`.

fix(scripts/pingcap/community): use correct key for aliases in OWNERS file

---

prow-jobs/pingcap/tidb/latest-postsubmits.yaml

Close  https://github.com/PingCAP-QE/ci/issues/3516
Updates the latest-postsubmits.yaml file to include the `skip_if_only_changed` condition for several postsubmit jobs, enhancing the job configuration for better handling of changes.

chore(pingcap/tidb): add skip_if_only_changed condition to postsubmit jobs

---

prow-jobs/kustomization.yaml
prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml

This commit introduces a new presubmit job configuration for the `tidb-operator` in the `latest-presubmits.yaml` file. The configuration includes job specifications, resource requests, and decoration settings, enhancing the CI pipeline for the `tidb-operator` repository.

chore(pingcap/tidb-operator): add new e2e presubmit on branch feature/v2

---

scripts/artifacts/gethash.py

This commit introduces a new script, `gethash.py`, which allows users to retrieve git commit hashes based on repository names, tags, branches, or pull requests using the GitHub API. The script supports both tag-based and branch-based versioning, enhancing the devbuild pipeline's ability to resolve specific commit hashes for building versions.

feat(scripts/artifacts): add gethash.py for retrieving git hashes from GitHub API

---

prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml

This commit modifies the `latest-presubmits.yaml` file to change the dind-daemon container's image to `docker:28.1-dind`, updates the command to `dockerd-entrypoint.sh`, and adjusts the environment variable settings. Additionally, it changes the mount path for the Docker socket from `/run/user/1001` to `/var/run`, streamlining the configuration for better compatibility.

chore(pingcap/tidb-operator): update dind-daemon configuration in laest-presubmits.yaml

---

pipelines/pingcap/tidb/latest/pull_vector_search_test.groovy

This commit refactors the `pull_vector_search_test.groovy` file to enhance the setup process by reorganizing the caching mechanism for binaries and test assets. The changes include moving the cache steps to improve efficiency and adding a matrix for test scripts, allowing for better management of test execution. Additionally, the download commands for test assets have been updated to suppress output for cleaner logs.

chore(pingcap/tidb): refactor vector search test for parallel test

---

jenkins/pipelines/cd/dev-build.groovy

Rename the GCR image of newarch ticdc to ticdc due to convenient to run tests.
This commit updates the GcrDockerImgRepoMapping in the dev-build.groovy file to include a new entry for the ticdc-newarch image, enhancing the Docker image configuration for the build process.

chore(jenkins/pipelines/devbuild): Rename the GCR image of newarch ticdc to ticdc.

---

prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml

* Use the Docker CLI image to avoid the need to install Docker ce cli.
* This commit changes the e2e-runner image from golang:1.23-bullseye to docker:28.1-cli and modifies the command to use /bin/sh instead of /bin/bash. The script now installs Go 1.23 using apk instead of apt-get, and enhances the logic for waiting on the Docker daemon to be responsive, improving reliability during the CI process.

refactor(pipelines/pingcap/tidb-operator): update e2e-runner image

---

prow-jobs/pingcap/tiflash/latest-postsubmits.yaml
prow-jobs/pingcap/tiflash/latest-presubmits-next-gen.yaml

This commit modifies the branch patterns in both `latest-postsubmits.yaml` and `latest-presubmits-next-gen.yaml` to include the `master` branch alongside the `feature/next-gen` branches. This change ensures that the CI pipelines correctly handle builds and tests for the latest developments in both the master and next-gen feature branches.

chore(pipelines/pingcap/tiflash): tiflash next-gen pipeline support master branch

---

jobs/pingcap/tidb/latest/pull_integration_realcluster_test_next_gen.groovy
prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

This pull request updates the naming convention for a specific integration test job in both the Jenkins job DSL script and the Prow presubmit configuration to ensure consistency and alignment with naming standards.
* [`jobs/pingcap/tidb/latest/pull_integration_realcluster_test_next_gen.groovy`](diffhunk://#diff-0b2218849b61adf414df00b459719558317f2473f12cf3f9d8bbcdac03a7c2aeL4-R4): Renamed the `jobName` variable from `pull_integration_real_cluster_next_gen` to `pull_integration_realcluster_test_next_gen` to reflect the updated naming convention.
* [`prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml`](diffhunk://#diff-6d136e7cf0b5751935f337e8b7065f23f4f547f7f85072637dbab6476832439eL32-R32): Updated the `name` field in the presubmit configuration to match the new job name, ensuring …

fix(jobs,prow-jobs): rename job to pull_integration_realcluster_test_next_gen

---

pipelines/pingcap/tidb/latest/pull_build_next_gen/pipeline.groovy

fix(pipelines): add keyspace-name flag to tidb-server startup command for build-next-gen job

---

jobs/pingcap/tidb/latest/pull_mysql_client_test_next_gen.groovy
pipelines/pingcap/tidb/latest/pull_mysql_client_test_next_gen/pipeline.groovy
pipelines/pingcap/tidb/latest/pull_mysql_client_test_next_gen/pod.yaml
prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml
prow-jobs/pingcap/tidb/latest-presubmits.yaml

- Add new pipeline and pod template for MySQL client test
- Register job in latest-presubmits-next-gen.yaml
- Clean up unused fields in presubmit configs
Close #3583

feat(pingcap/tidb): add CI job for MySQL client test next-gen

---

jobs/pingcap/tidb/latest/pull_integration_ddl_test_next_gen.groovy
pipelines/pingcap/tidb/latest/pull_integration_ddl_test_next_gen/pipeline.groovy
pipelines/pingcap/tidb/latest/pull_integration_ddl_test_next_gen/pod.yaml
prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

- Introduce pipeline and pod configuration for `pull_integration_ddl_test_next_gen`
- Register the job in `latest-presubmits-next-gen.yaml`
- Define stages for debugging, checkout, preparation, and testing
This commit enhances the CI/CD process for the TiDB project by adding a dedicated job for integration DDL tests, ensuring better testing coverage for next-gen features.
Close #3582

feat(pingcap/tidb): add new CI job for integration DDL tests next-gen

---

jobs/pingcap/tidb/latest/pull_br_integration_test_next_gen.groovy
pipelines/pingcap/tidb/latest/pull_br_integration_test_next_gen/pipeline.groovy
pipelines/pingcap/tidb/latest/pull_br_integration_test_next_gen/pod.yaml
prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

- Introduced a new Jenkins pipeline job for the `pull_br_integration_test_next_gen`, including its configuration in the job DSL and Prow presubmits.
- Created associated pipeline and pod specifications to facilitate the integration testing process.
- Implemented caching and resource management for Kubernetes pods to optimize performance.
This addition enhances the CI/CD capabilities for the TiDB project, ensuring robust testing for the BR integration.
Close #3581

feat(pingcap/tidb): add new integration test job for BR next-gen

---

prow-jobs/tikv/pd/release-6.1-presubmits.yaml
prow-jobs/tikv/pd/release-6.5-fips-presubmits.yaml
prow-jobs/tikv/pd/release-6.5-presubmits.yaml
prow-jobs/tikv/pd/release-7.1-presubmits.yaml
prow-jobs/tikv/pd/release-7.5-presubmits.yaml
prow-jobs/tikv/pd/release-8.1-presubmits.yaml
prow-jobs/tikv/pd/release-8.5-presubmits.yaml

- Add Kubernetes-based build jobs for all PD release branches.
- Define shared global settings for resource requests, affinity, and file change skipping.
- Update images and build commands per release.
- Remove old Jenkins job definitions.

refactor(tikv/pd): migrate presubmit `build` jobs from Jenkins to Kubernetes

---

jobs/pingcap/tidb/latest/merged_tiflash_integration_test.groovy
pipelines/pingcap/tidb/latest/merged_tiflash_integration_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_tiflash_integration_test.yaml
prow-jobs/pingcap/tidb/latest-postsubmits.yaml

Relate to https://github.com/PingCAP-QE/ci/issues/3601
Currently, it is necessary to observe the stability for two weeks before enabling status reporting and removing the WIP label.

feat(tidb): add merged TiFlash integration test job

---

prow-jobs/pingcap/monitoring/periodics.yaml

This PR updates the base reference in the monitoring periodic job from `release-9.0-beta.1` to `release-9.0-beta.2` to align with the latest beta branch.

fix(monitoring): update base_ref to release-9.0-beta.2

---

pipelines/pingcap/tidb/latest/merged_tiflash_integration_test.groovy

Modified the TiFlash integration test script to remove pull request title references when fetching artifacts for TikV, PD, and TiFlash components, ensuring a more streamlined artifact retrieval process.

fix(pipelines/pingcap/tidb): update artifact fetching logic in TiFlash integration test

---

pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-7.1/pull_cdc_integration_test.groovy
pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_mysql_test.groovy
pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/release-8.1/pull_cdc_integration_storage_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_kafka_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_mysql_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_pulsar_test.groovy
pipelines/pingcap/tiflow/release-8.5/pull_cdc_integration_storage_test.groovy

Updated the binary download script references in multiple integration test files to use the specific release version (release-7.1, release-8.1, release-8.5) instead of the base reference. This change ensures that the correct binaries are downloaded for the respective release branches.
This is to ensure that there are no errors when executing downloads for the hotfix branch; in fact, the hotfix branch will download dependencies with precise tags.

fix(pipelines/tiflow): update binary download script references to specific release versions on hotfix branch

---

jenkins/pipelines/cd/multibranch/build_pd_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tidb_multi_branch.groovy
jenkins/pipelines/cd/multibranch/build_tikv_multi_branch.groovy

Close https://github.com/PingCAP-QE/ci/issues/3625
Modified the tar command in build scripts for PD, TiDB, and TikV to package only the 'bin/' directory instead of all files, improving the efficiency of artifact creation. Reduce size by not packaging the source code.

chore(pipelines/cd): update tar command to include only 'bin/' directory for artifact packaging

---

pipelines/pingcap/tidb/latest/pull_build_next_gen/pipeline.groovy

from test-ks to SYSTEM in test run

fix(pipelines/pingcap/tidb/pull_build_next_gen): change keyspace name in test run

---

prow-jobs/pingcap-inc/tici/presubmits.yaml

To avoid task timeout(45 mins) failures caused by excessively long compilation times, we need to increase some request resources.
Updated CPU and memory resource limits for the 'check' and 'ci-run-test' jobs in presubmits.yaml to enhance performance during CI runs. CPU limit changed from 2 to 6 and memory limit from 8Gi to 12Gi.

chore(prow-jobs/pingcap-inc/tici): increase resource limits for tici presubmit jobs

---

prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

This pull request updates the `context` fields in the `latest-presubmits-next-gen.yaml` file to reflect non-blocking statuses for various presubmit jobs. Additionally, it removes commented-out lines and ensures proper configuration for `skip_if_only_changed` and `run_if_changed` fields.
* **Context field updates**:
- Changed `context` values to indicate non-blocking statuses for the following jobs:
- `pull-build-next-gen` → `non-block-pull-build-next-gen`
- `pull-check-next-gen` → `non-block-pull-check-next-gen`
- `pull-unit-test-next-gen` → `non-block-pull-unit-test-next-gen`
- `pull-unit-test-ddlv1-next-gen` → `non-block-pull-unit-test-ddlv1-next-gen`
- `pull-mysql-client-test-next-gen` → `non-block-pull-mysql-client-test-next-gen`
* **Configuration fixes**:
- Removed commented-out …

feature(prow-jobs/pingcap/tidb): enable auto run for pull_build_next_gen job

---

prow-jobs/pingcap/docs/docs-cn-postsubmits.yaml
prow-jobs/pingcap/docs/docs-postsubmits.yaml

This PR stops the PDF builds of the following versions of docs as they have been archived.
- TiDB v8.3
- TiDB v8.4

docs-pdf: remove v8.3 and v8.4 as they are archived

---

pipelines/pingcap/tidb/release-8.5/pull_integration_br_test.groovy

Also archive logs when aborted.
get the log to address the test timeout issue.

chores(pingcap/tidb/release-8.5): update pull_integration_br_test.groovy

---

prow-jobs/pingcap-inc/tici/presubmits.yaml

Relate to https://github.com/PingCAP-QE/artifacts/pull/656.

chore(prow-jobs/pingcap-inc/tici): update container images to v2025.7.13-2-gdf06f11

---

prow-jobs/pingcap/monitoring/periodics.yaml

This pull request updates the `prow-jobs/pingcap/monitoring/periodics.yaml` file to use a more recent version of the Go programming language and updates a branch name in the environment configuration. These changes ensure the periodic jobs are using the latest stable tools and correct target branches.
* Updated the Go image from `golang:1.23.2` to `golang:1.23.11` in three different periodic job configurations to ensure compatibility with the latest patches and improvements. [[1]](diffhunk://#diff-42023fd3a034e5c540da3b9f7b6982f48acb7ee3545326f91f6abfb65cd92d4dL17-R17) [[2]](diffhunk://#diff-42023fd3a034e5c540da3b9f7b6982f48acb7ee3545326f91f6abfb65cd92d4dL136-R136)
* Updated the Go image from `golang:1.23` to `golang:1.23.11` in another periodic job configuration.
* Changed the `TARGET` …

fix(prow-jobs): update TARGET to release-9.0-beta.2 in monitoring periodics

---

pipelines/pingcap-qe/tidb-test/latest/pull_integration_jdbc_test_next_gen/pipeline.groovy
pipelines/pingcap-qe/tidb-test/latest/pull_mysql_test_next_gen/pipeline.groovy

This pull request includes updates to the pipeline configuration for testing in the `tidb-test` project. The changes focus on improving caching, modifying test configurations, and cleaning up the pipeline scripts.
* Updated the cache key in the `pull_integration_jdbc_test_next_gen` pipeline to use a workspace-specific key format (`ws/${BUILD_TAG}/tidb-test`) for better cache management. (`[pipelines/pingcap-qe/tidb-test/latest/pull_integration_jdbc_test_next_gen/pipeline.groovyL137-R137](diffhunk://#diff-eea030b5a2abb8b2e5e3a1be2362ce7712fc41dd2b252430b51432f9d9663366L137-R137)`)
* Modified the `STORE` axis in the `pull_mysql_test_next_gen` pipeline to temporarily exclude `tikv` from the list of values. (`[pipelines/pingcap-qe/tidb-test/latest/pull_mysql_test_next_gen/pipeline.groovyL88-R8 …

fix(pipelines/pingcap-qe/tidb-test): fix pipelines

---

pipelines/pingcap/tidb/latest/merged_common_test.groovy
pipelines/pingcap/tidb/latest/merged_e2e_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_br_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_common_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_copr_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_jdbc_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_lightning_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_mysql_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_nodejs_test.groovy
pipelines/pingcap/tidb/latest/merged_integration_python_orm_test.groovy
pipelines/pingcap/tidb/latest/pod-merged_e2e_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_common_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_copr_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_jdbc_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_mysql_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_nodejs_test.yaml
pipelines/pingcap/tidb/latest/pod-merged_integration_python_orm_test.yaml
scripts/artifacts/download_pingcap_oci_artifact.sh

This pull request updates multiple CI pipeline scripts to streamline the process of downloading and preparing binaries, replacing the older artifact download script with a new OCI-based script. Additionally, minor enhancements were made to the new script for better logging and clarity.
* Replaced the `download_pingcap_artifact.sh` script with `download_pingcap_oci_artifact.sh` across multiple pipeline scripts, improving the binary download process. This includes changes to the following files:
- `merged_e2e_test.groovy`
- `merged_integration_common_test.groovy`
- `merged_integration_copr_test.groovy`
- `merged_integration_jdbc_test.groovy`
- `merged_integration_mysql_test.groovy`
- `merged_integration_nodejs_test.groovy`
- `merged_integration_python_orm_test.groovy`
* Introduced a `bin` …

refactor(pingcap/tidb): use oci download script in post-submit jobs

---

pipelines/pingcap/tidb/latest/pull_integration_ddl_test_next_gen/pipeline.groovy
pipelines/pingcap/tidb/latest/pull_integration_realcluster_test_next_gen/pipeline.groovy
pipelines/pingcap/tidb/latest/pull_mysql_test_next_gen/pipeline.groovy
prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

This pull request focuses on restructuring and optimizing the CI/CD pipelines for integration and MySQL tests, as well as making small configuration adjustments. The most significant changes include removing unnecessary debug stages, improving caching and artifact handling, and ensuring better script reliability.
* Removed the `Debug info` stage from the `pull_integration_ddl_test_next_gen` pipeline, which included commands for printing environment variables, debugging commands, and network checks. This simplifies the pipeline by removing redundant steps. (`pipelines/pingcap/tidb/latest/pull_integration_ddl_test_next_gen/pipeline.groovy`, [pipelines/pingcap/tidb/latest/pull_integration_ddl_test_next_gen/pipeline.groovyL32-L48](diffhunk://#diff-30290e50879c98b2b0d4bd9095242cb7de09be03866928 …

feature(pingcap/tidb): enable job `pull_integration_ddl_test_next_gen` job

---

prow-jobs/pingcap-inc/tici/presubmits.yaml

Run unit tests in the `pull-verify` job of TiCI

chore(prow-jobs/pingcap-inc/tici): Run ut for tici

---

prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

The `integrationtest` make task running inside the `check_next_gen` job seems unnecessary (running tests/integrationtest/run-tests.sh), as it is covered by `pull_integration_realcluster_test_next-gen`.

fix(pingcap/tidb): remove pull_check_next_gen presubmit job configuration

---

pipelines/pingcap/tidb/latest/pull_integration_realcluster_test_next_gen/pipeline.groovy

This pull request makes a small adjustment to the test pipeline by removing one of the test scripts from the integration test suite. The change streamlines the set of tests that are executed in the pipeline.
- Removed the execution of the `bazel_brietest` test script from the integration test values in `pipeline.groovy`.

chore(pingcap/tidb): update job `pull_integration_realcluster_test_next_gen`

---

prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

This pull request makes a small change to the presubmit job configuration for `pingcap/tidb` in `prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml`. The change comments out the `skip_if_only_changed` field for the `pull_unit_test_next_gen` job, which means this job will now always run regardless of which files are changed.

chore(pingcap/tidb): disable auto trigger `pull_unit_test_next_gen` job

---

prow-jobs/pingcap/tidb/latest-presubmits.yaml

- Changed the `always_run` property to `true` for the `pull-error-log-review` job, ensuring it runs on every trigger.
- Added `skip_report: true` to prevent reporting on this job, streamlining the CI process.
Enable automatic triggering. To verify the effectiveness of the matching rules, please note that this task currently has status reporting turned off, so task cost failures will not be reflected on the PR GitHub page and will not affect PR merging.

feat(pipelines/tidb): update pull-error-log-review job configuration of tidb

---

jobs/pingcap/tidb/latest/periodics_integration_test.groovy

Reduce log retention period for integration tests from 30 to 7 days, avoid generating too many archives that take up disk space.

chore(pipelines/tidb): reduce log retention period for integration tests from 30 to 7 days

---

scripts/flow/build/versioning-strategy.md
scripts/flow/build/versioning-strategy.test.ts
scripts/flow/build/versioning-strategy.ts

This pull request adds support for feature branch prerelease versioning in the build versioning strategy. Now, if a commit is on a feature branch, the computed version and tag will reflect the feature name, improving clarity and traceability for feature branch builds. The changes are documented, tested, and implemented in the core logic.
**Feature branch versioning support:**
* Updated `versioning-strategy.md` to document the new feature branch prerelease versioning scheme in the mapping table.
* Added logic to `versioning-strategy.ts` to detect feature branches and generate version/tag strings using the feature name, e.g., `v9.0.0-feature.fts`.
**Test coverage:**
* Added new test cases in `versioning-strategy.test.ts` for feature branch beta and alpha prerelease scenarios to ensure …

feat(scripts/flow/build): add feature branch prerelease support to versioning strategy

---

scripts/pingcap/community/prow-owners-updater.ts

This pull request improves the robustness of the `getFileContent` method in `prow-owners-updater.ts` by adding error handling for missing files. Now, if a requested file does not exist, the method returns `undefined` instead of throwing an error.
Error handling improvements:
* Updated `getFileContent` in `scripts/pingcap/community/prow-owners-updater.ts` to catch `RequestError` exceptions with a 404 status and return `undefined` for missing files, ensuring smoother handling of absent files. [[1]](diffhunk://#diff-2ed7e110944d601280252ef0eff96a4f51e0a68610b0799b65db910f8380e31fR154) [[2]](diffhunk://#diff-2ed7e110944d601280252ef0eff96a4f51e0a68610b0799b65db910f8380e31fR163-R168)

fix(scripts/pingcap/community): handle 404 error in getFileContent and return undefined

---

prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

It succeed in master and `release-nextgen-20250815` branches.

feat(pingcap/tidb): enable auto trigger for `pull-mysql-client-test-next-gen` job

---

prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

fix(pingcap/tidb): make `pull-integration-realcluster-test-next-gen` job as required

---

prow-jobs/pingcap-qe/ci/presubmits.yaml

Relate to https://github.com/PingCAP-QE/ci/pull/3708.
* Update to [v20240614-fd27fb709](https://hub.docker.com/layers/ticommunityinfra/checkconfig/v20240614-fd27fb709/images/sha256-4e5633eac93a446580b541883f90a6df934d496d9d02c25e87d5d02bb9e49058)

feat: update ci prow presubmit check image

---

prow-jobs/pingcap/ticdc/latest-presubmits.yaml
prow-jobs/pingcap/tidb/latest-presubmits.yaml
prow-jobs/pingcap/tiflash/latest-presubmits.yaml
prow-jobs/pingcap/tiflow/latest-presubmits.yaml
prow-jobs/tikv/pd/latest-presubmits.yaml
prow-jobs/tikv/tikv/latest-presubmits.yaml

Added a conditional check in multiple presubmit job configurations to skip the error log review process if the JOB_TYPE is set to "batch". This change applies to the following job configurations: ticdc, tidb, tiflash, tiflow, pd, and tikv.
All PRs entering the batch merge have passed all required checks (including error log review check), so the modifications here will not cause any issues. It can ensure the normal merging of batch jobs without blocking.

feat(presubmits): skip error log review for batch jobs

---

prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml

Reverts PingCAP-QE/ci#3746.
Prow tide and sinker have been upgraded.

Revert "Remove dind-daemon initContainer configuration"

---

pipelines/pingcap/tidb/release-6.1/ghpr_check2.groovy
pipelines/pingcap/tidb/release-6.5/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.1/ghpr_check2.groovy
pipelines/pingcap/tidb/release-7.5/ghpr_check2.groovy

Updated the timeout setting from 30 minutes to 65 minutes in the `ghpr_check2.groovy` files across multiple release branches to allow for longer job execution times.

chore(pingcap/tidb): increase timeout for CI jobs in release branches

---

pipelines/pingcap/tidb/latest/pull_br_integration_test.groovy

The pass rate of the tidb BR integration test (pull_br_integration_test) is relatively low, and a large number of builds fail due to timeout. 
Analysis of Jenkins logs reveals the following:
1. The test is forcibly terminated by the SIGTERM signal during execution (exit code 143).
2. The current timeout configuration is insufficient: total timeout is 60 minutes, and the timeout for a single test group is 45 minutes.
Adjust the timeout configuration as follows:
1. Total timeout: increased from 60 minutes to 90 minutes.
2. Test group timeout: increased from 45 minutes to 60 minutes.

fix: increase tidb br integration test timeout duration

---

prow-jobs/pingcap/tidb-operator/latest-presubmits.yaml

Restore operator pull-e2e configuration after https://github.com/PingCAP-QE/ee-ops/pull/1653.

revert: Revert "Remove dind-daemon initContainer configuration

---

prow-jobs/pingcap/tidb/latest-presubmits-next-gen.yaml

Now the job is passed:
Also refactor presubmits to use jenkins_job anchor

feat(prow-jobs/pingcap/tidb): enable auto trigger and set as required for `pull-unit-test-next-gen` job
